### ISSUE TITLE
dużo spamu na poradni

### ISSUE THREAD

**Issue by AgnieszkaZdanowicz** [watchdogpolska/poradnia#1015]
@rwakulszowa podobno można Cię pomęczyć w temacie :) Ostatnio na poradnię wpada więcej spamu niż dotychczas - po kilka wiadomości dziennie (kiedyś to było kilka w miesiącu). To ogólnie niedużo, ale zaburza nam to statystyki mówiące o tym, ile próśb o porady wpłynęło. Czy miałbyś pomysł, jak walczyć z tym spamem?

**Comment by rwakulszowa** [comment]
Jasne, postaram się rzucić okiem, na ile jestem w stanie.

Zakładam, że możemy spróbować rozwiązać 2 kwestie:
1. konfiguracja poczty w taki sposób, by bardziej aktywnie odfiltrowywała śmieci
2. uwzględnienie spamu w logice liczącej statystyki

@ad-m - zakładam, że mogę potrzebować jakichś dodatkowych uprawnień żeby przyjrzeć się sprawie. Czy w ramach watchdogpolska/feder#940 pojawiły się jakieś rozwiązania? Zakładam, że problem jest dość podobny.

**Comment by AgnieszkaZdanowicz** [comment]
Spam na fedrowaniu jest inny niż na poradni, o ile mogę stwierdzić - ale oceniam tylko te maile, które zaciągają się z serwera do narzędzi, a może jakieś spamy są jeszcze blokowane na innym poziomie.
Na fedrowaniu jest spam masowy i najczęściej od fundacji, które masowo wysyłają prośby o wsparcie jakiegoś celu. A na poradnię spływają różne spamy w stylu "kup Pan najlepszą klimatyzację na świecie" etc. Nie wiem, czy ta uwaga ma jakieś znaczenie, ale stwierdziłam, że się podzielę mimo wszystko.

**Comment by ad-m** [comment]
Dotąd filtrowanie na poziomie serwera pocztowego było całkowicie wyłączone. W tym zakresie wspomóc może @mrbojko, jeżeli się zdecydujemy na taki krok. Serwer pocztowy zapewnia Zenbox.

Ja nie chciałbym, aby biznes dostawał wiadomość do skrzynki technicznej, aby weryfikować spam. Zatem prawdopodobnie wciąż potrzebowaliśmy pobierać spam do ewentualnej weryfikacji, ale go od razu flagować.

Naprawienie statystyk wymaga pierw flagowania wiadomości przez BI. @AgnieszkaZdanowicz statystyki robisz przez BI, tak? Jeżeli BI to oznacza Metabase, a to oznacza dopracowanie SQL-ki.

**Comment by ad-m** [comment]
Paula zwróciła uwagę na przypadek, gdy ktoś wysyła szeroko korespondencje, a następnie osoby odpowiadają do wszystkich, aby przestać wysyłać takie wiadomości do nich:

> Otrzymaliśmy do wiadomości: https://porady.siecobywatelska.pl/sprawy/sprawa-13191/
> 
> I teraz dostajemy wiadomości od innych osób, które piszą do tego pana, żeby je wypisać z listy adresatów wiadomości:
> https://porady.siecobywatelska.pl/sprawy/sprawa-13193/
> https://porady.siecobywatelska.pl/sprawy/sprawa-13194/
> https://porady.siecobywatelska.pl/sprawy/sprawa-13195/
> https://porady.siecobywatelska.pl/sprawy/sprawa-13196/
> https://porady.siecobywatelska.pl/sprawy/sprawa-13201/

Możliwe, że powinniśmy przestać przyjmować w Poradni wiadomości, jeżeli nie jesteśmy wymienieni w polu "Do".

**Comment by AgnieszkaZdanowicz** [comment]
@ad-m bardzo dobry pomysł, bo taki problem pojawia się co jakiś czas

**Comment by AgnieszkaZdanowicz** [comment]
założyłam nowy issuse #1067 

Jeśli spam nie liczy się do statystyk, to moim zdaniem nie ma go tak dużo, żebyśmy nie mogli go kasować ręcznie - zwłaszcza, że teraz to jest dużo prostsze. Byłabym za zamknięciem tego wątku.
