### ISSUE TITLE
wygodniejsze usuwanie spraw z poradni

### ISSUE THREAD

**Issue by AgnieszkaZdanowicz** [watchdogpolska/poradnia#1028]
W tej chwili usuwanie spraw z poradni jest bardzo niewygodne, bo robi się to przez panel admina, gdzie widać wszystkie sprawy, ale nawet nie wiem, w jakiej kolejności są ułożone. Czasem też na poradni jest kilka spraw o tym samym tytule, bo ludzie nie trzymają wątku i nie potrafię dojść, którą z tych spraw chcę skasować. Przydałby się wygodniejszy mechanizm do kasowania spraw.

**Comment by AgnieszkaZdanowicz** [comment]
@ad-m zastanawiam się jeszcze nad 2 sprawami

1. czy jak ja kasuje sprawy poprzez przycisk "usuń", to one są też kasowane z serwera? Bo tutaj pewnie jest tak, jak na fedrowaniu, że maile są ściągane do narzędzia z serwera i są przechowywane w tych dwóch miejsach?

2. czy dałoby się tak zaczarować w kodzie, że sprawy, w których nikt nic nie pisał od 6 lat, kasowałyby się automatycznie? W naszej polityce ochrony danych jest napisane, że dane związane z poradą trzymamy przez 6 lat i potem kasujemy. Akurat teraz mija 6 lat od wprowadzenia poradni i zastanawiam się, czy musimy ręcznie te wiadomości najstarsze kasować, czy da się to zautomatyzować.

**Comment by ad-m** [comment]
1/ Wymaga weryfikacja kwestia kasowania kasowania załączników (i oryginałów wiadomości) w takiej sytuacji. 

W Poradni także przechowujemy oryginał wiadomości (ikonka koła ratunkowego).

2/ To osobne zagadnienie. Do zrobienia.

**Comment by ad-m** [comment]
2/ Gdzie jest polityka, która mówi o 6 latach? Czy możemy to zrealizować manualnie i kasować raz w roku lub raz na pół roku? Boje się, że @mrbojko zignoruje powiadomienia o tym, że  to cykliczne zadanie się nie wykonuje (tak jak ignoruje wiele cyklicznych zadań w Zabbixie, które święcą się od roku i dłużej np. JudgementBot)  i będziemy mieli problem prawny.

**Comment by mrbojko** [comment]
> (tak jak ignoruje wiele cyklicznych zadań w Zabbixie, które święcą się od roku i dłużej np. JudgementBot)
@ad-m wybacz mi moją ignorancję, ale w Zabbiksie widzę następujące ostrzeżenia:
![obraz](https://user-images.githubusercontent.com/47541542/147793795-ecd7c129-24ea-4587-b6eb-a04af0b6b71c.png)

Zapewne źle interpretuję te komunikaty - który z nich jest JudgementBot'em?

**Comment by ad-m** [comment]
Ten:

![image](https://user-images.githubusercontent.com/3618479/147796342-4565c65b-782a-411e-ab96-65b8b696d08a.png)

Skonfigurowane w tym miejscu https://github.com/watchdogpolska/infra/blob/3d2cb30d9f7f81cd68747f04fbe691f347686a5f/ansible/vars/instance/porady/vars.yml#L60 .

**Comment by AgnieszkaZdanowicz** [comment]
@ad-m 6 lat jest zapisane w Rejestrze Czynności Przetwarzania, który mamy obowiązek prowadzić, ale on jest na potrzeby wewnętrzne i staram się go nie udostępniać za szeroko.

**Comment by ad-m** [comment]
6 lat od? Czy możemy wykonać to wykonywać manualnie? Jakie chcemy tolerować opóźnienie w kasowaniu spraw?

**Comment by AgnieszkaZdanowicz** [comment]
Przez okres 6 lat od udzielenia porady lub przesłania projektu pisma.

Możemy oczywiście manualnie, tylko trzeba o tym pamiętać, dlatego spytałam o magię automatyzacji. Ale jak się nie da, to będziemy sami kasować - tylko trzeba wejść po kolei w każdą sprawę i ją skasować, co zabiera chwilę czasu. Najchętniej raz w miesiącu, żeby opóźnienie wynosiło maksymalnie miesiąc

**Comment by ad-m** [comment]
Ja nie mam problemu w tym, żeby jakoś udostępnić operacje usuwania i nie chciałbym, abyście klikali samemu w usuwanie starych spraw (BTW. to wpłynie na statystyki), ale monitorowania, że to się faktycznie dzieje, bo ma to znaczenie prawne. 

Raz na pół roku / kwartał zrobić zagadnienie na GH, aby ktoś wykonał zbiorcze usuwanie i udokumentował to, że faktycznie zostało to wykonane zapewni, że nie będziemy mieli problemów.

**Comment by mrbojko** [comment]
@AgnieszkaZdanowicz rozumiem obawy Adama, że proces w pełni automatyczny może się w pewnym momencie "wysypać", a my nie zwrócimy na to uwagi. Wydaje mi się, że gdyby poradnia prezentowała sprawy kwalifikujące się "do skasowania", przy okazji delikatnie narzucając się wysyłając maila do kogośtam@siecobywatelska.pl to byłaby wystarczająca pomoc? Czy się mylę? Takie rozwiązanie z jednej strony ułatwia życie człowiekowi, z drugiej to człowiek, a nie system podejmuje decyzję o skasowaniu danych. I przy odpowiedniej upierdliwości (raz na miesiąc przypomnienie) człowieku odpowiedzialnemu wejdzie to na tyle w krew, że też będzie pamiętał :-). I wydaje mi się, że o to pytał @ad-m - nie żeby zostawić was zupełnie bez narzędzi, a zostawić wam w ręku decyzję - mam rację Adamie?

**Comment by mrbojko** [comment]
@ad-m 
> Raz na pół roku / kwartał zrobić zagadnienie na GH, aby ktoś wykonał zbiorcze usuwanie i udokumentował to, że faktycznie zostało to wykonane zapewni, że nie będziemy mieli problemów.
A nie można wprowadzić narzędzia w Poradni, które zapewni logowanie operacji usuwania danych? Wyprowadzanie czynności obsługowych leżących po stronie użytkownika aplikacji na GH chyba nie jest dobrym pomysłem.

**Comment by AgnieszkaZdanowicz** [comment]
@mrbojko czyli, że raz w miesiącu poradnia mogłaby wysyłać maila o treści "na poradni jest X spraw starszych niż 6 lat - skasuj je"? To by ułatwiło pamiętanie o temacie

**Comment by mrbojko** [comment]
> @mrbojko czyli, że raz w miesiącu poradnia mogłaby wysyłać maila o treści "na poradni jest X spraw starszych niż 6 lat - skasuj je"? To by ułatwiło pamiętanie o temacie

Wręcz widziałbym to jako "na poradni jest X spraw starszych niż 6 lat - przejdź do strony usuwania" z linkiem do właściwego narzędzia które na tacy poda wszystkie sprawy z kwadracikiem do zaznaczenia, które pozwoli hurtem odptaszkować i usunąć wiadomości.

**Comment by AgnieszkaZdanowicz** [comment]
@mrbojko wow, to by było super :)

**Comment by ad-m** [comment]
> Jak po pół roku nagle nie dostaniesz takiego maila

Skąd będzie o tym wiedziała? Widzę, że Agnieszka ma już w kalendarzu regularne i działające check-listy, więc skoro check-lista w Zabbixie nie działa (sam pokazałeś jaka tam choinka) to proponuje, aby dodać wpis "zapewnić archiwalnych usuniecie spraw na Poradni", obok "przygotować rachunki i poprosić o faktury" i "rozpisać pensje", bo to nie jest pytanie "czy trzeba usunąć", ale nadzorować skuteczne usunięcie. Monitorowanie trzeba centralizować, aby działało.

Taka forma nadzoru jest oczywiście realna, jeżeli możemy usuwać coś z opóźnieniem miesięcznym / kwartalnym / rocznym, co próbuje ustalić od początku rozważań w tym zakresie. Jeżeli mielibyśmy coś usuwać tygodniowo / codziennie / częściej to oczywiście nie zrobiłbym tego Agnieszce.

Kolejnym krokiem jest zapewnienie przystępnego i odpornego na błędy mechanizmu do usuwania takich spraw. Jestem w stanie sobie wyobrazić różne mechanizmy:
* początkowo myślałem o poleceniu konsoli, aby zrobić to minimalnym nakładem pracy (inicjowanym przez Agnieszkę otwarciem zgłoszenia na GH, aby ona nadzorowała wykonanie tego), 
* wyobrażam sobie także dostosowanie w tym zakresie https://porady.siecobywatelska.pl/admin/cases/case/ (można dodawać filtrowanie według "archiwalna sprawa" i niezbędne kolumny do oceny).

**Comment by mrbojko** [comment]
> > Jak po pół roku nagle nie dostaniesz takiego maila
> 
> Skąd będzie o tym wiedziała? Widzę, że Agnieszka ma już w kalendarzu regularne i działające check-listy, więc skoro check-lista w Zabbixie nie działa (sam pokazałeś jaka tam choinka) 
Choinka w Zabbiksie wynika z tego, że zapisy tam są dla mnie kompletnie nieczytelne. Moja wina, jestem na niego za głupi. I ta choinka również pokazuje, że pomysł centralizacji nie jest fortunny, bo jak widzisz nie działa. To, że coś jest wygodnym i zrozumiałym rozwiązaniem dla ciebie nie znaczy, że jest wygodne i zrozumiałe dla innych. 

W Zabbiksie jest sporo fałszywych i niepotrzebnych alarmów przez co uległem znieczuleniu. Podobnie jak ze znakami drogowymi, jak jest ich za dużo zaczynasz je ignorować i już nie pamiętasz czy ograniczenie było do 60 czy może 70. W moim przypadku nie wiedziałem (i cały czas nie wiem dokładnie co muszę dodać), że muszę sobie dokonfigurować Zabbix, żeby widzieć więcej ostrzeżeń w panelu "problems".


>to proponuje, aby dodać wpis "zapewnić archiwalnych usuniecie spraw na Poradni", obok "przygotować rachunki i poprosić o faktury" i "rozpisać pensje", bo to nie jest pytanie "czy trzeba usunąć", ale nadzorować skuteczne usunięcie. Monitorowanie trzeba centralizować, aby działało.
> 
> Taka forma nadzoru jest oczywiście realna, jeżeli możemy usuwać coś z opóźnieniem miesięcznym / kwartalnym / rocznym, co próbuje ustalić od początku rozważań w tym zakresie. Jeżeli mielibyśmy coś usuwać tygodniowo / codziennie / częściej to oczywiście nie zrobiłbym tego Agnieszce.
> 
> Kolejnym krokiem jest zapewnienie przystępnego i odpornego na błędy mechanizmu do usuwania takich spraw. Jestem w stanie sobie wyobrazić różne mechanizmy:
> 
>     * początkowo myślałem o poleceniu konsoli, aby zrobić to minimalnym nakładem pracy (inicjowanym przez Agnieszkę otwarciem zgłoszenia na GH, aby ona nadzorowała wykonanie tego),

Drogi Adamie. Polecenie w konsoli może ci się wydawać prosty i eleganckim rozwiązaniem, ale przypominam, że większość aplikacji w dzisiejszych czasach obsługiwana jest jednak inaczej. Co więcej raczej polecenie z konsoli nie zapewnia kryteriów przystępności i odporności na błędy.

>     * wyobrażam sobie także dostosowanie w tym zakresie https://porady.siecobywatelska.pl/admin/cases/case/ (można dodawać filtrowanie według "archiwalna sprawa" i niezbędne kolumny do oceny).
Wydaje mi się, że lepiej byłoby zaprojektować oddzielny ekran, przez co nie będziesz mnożył kolumn, a dodatkowo masz gwarancję, że użytkownik zapuszczający się w rejon "porządkowanie" czy jakkolwiek zostanie ten ekran nazwany, nie zrobi czegoś przez pomyłkę. Mechanizm porządkowania spraw na poradni to mechanizm którego brakuje i nie warto robić protezy "na szybko" tylko z rozmysłem zaprojektować coś "przystępnego i odpornego na błędy", nawet kosztem większej pracy teraz. 

I jeszcze raz powtórzę - wynoszenie ważnych czynności obsługowych poza aplikację (np. przypominania) sprawia, że aplikacja staje się mniej przenośna, bo zaczynasz ją obudowywać niepotrzebnym ekosystemem przypomnień z dziwnych miejsc (zadania google). To ty uważasz coś za wygodne rozwiązanie wcale nie musi być rozwiązaniem wygodnym dla zwykłych ludzi (co pokazuje Zabbix).

**Comment by ad-m** [comment]
> W Zabbiksie jest sporo fałszywych i niepotrzebnych alarmów przez co uległem znieczuleniu. Podobnie jak ze znakami drogowymi, jak jest ich za dużo zaczynasz je ignorować i już nie pamiętasz czy ograniczenie było do 60 czy może 70.

Najwidoczniej osoby, które odpowiadały za monitorowanie środowiska nie dostosowały na bieżąco monitoringu do zmiany wymagań i priorytetów Stowarzyszenia. Dostrzegam słabą kondycje Zabbix, nawet pisałem w watchdogpolska/infra#410 o informacje na ten temat, ale od lipca 2021 nie dostałem odpowiedzi, aby móc się zastanowić nad czymś skutecznym. W takiej sytuacji nie mam przekonania, że środowisko Stowarzyszenia jest monitorowane przez IT na bieżąco.

> Wydaje mi się, że lepiej byłoby zaprojektować oddzielny ekran, przez co nie będziesz mnożył kolumn, a dodatkowo masz gwarancję, że użytkownik zapuszczający się w rejon "porządkowanie" czy jakkolwiek zostanie ten ekran nazwany, nie zrobi czegoś przez pomyłkę.

Mnożenie ekranów to wzrost kosztów utrzymania i rozwoju aplikacji. Dlatego warto projektować rozwiązania w sposób elatyczny, a nie dla każdego specyficznego przypadku użycia osobne moduły. 

> Mechanizm porządkowania spraw na poradni to mechanizm którego brakuje i nie warto robić protezy "na szybko" tylko z rozmysłem zaprojektować coś "przystępnego i odpornego na błędy", nawet kosztem większej pracy teraz.

Mam świadomość, że większość rozwiązań w Stowarzyszeniu ma taką właściwość. W przypadku pierwszego wariantu przyjąłem, że to minimalny rozwiązanie, które zajmie kilka minut, a pozwoli zwalidować rozwiązanie nim stworzymy bardziej skomplikowany interfejs użytkownika. W przypadku drugiego wydaje mi się to optymalne i dość trwałe rozwiązanie, a jednocześnie przystępne pod względem nakładów i kosztów. Masz czytelną koncepcje i widzisz realną możliwość wykonania takich rozwiązań – pozostawiam Ci to.

**Comment by AgnieszkaZdanowicz** [comment]
To jest aktualne. Najbardziej podobał mi się pomysł Marcina:

_Wydaje mi się, że gdyby poradnia prezentowała sprawy kwalifikujące się "do skasowania", przy okazji delikatnie narzucając się wysyłając maila do kogoś[tam@siecobywatelska.pl](mailto:tam@siecobywatelska.pl) to byłaby wystarczająca pomoc.

Wręcz widziałbym to jako "na poradni jest X spraw starszych niż 6 lat - przejdź do strony usuwania" z linkiem do właściwego narzędzia które na tacy poda wszystkie sprawy z kwadracikiem do zaznaczenia, które pozwoli hurtem odptaszkować i usunąć wiadomości._

Chodzi o sprawy, w których od ponad 6 lat nikt nie napisał żadnej wiadomości.

**Comment by PiotrIw** [comment]
Podsumuję pomysły powyżej i dodam swoje:
1) raz na miesiąc/kwartał (?) mail do osób  z odpowiedniej grupy z informacją o ilosci spraw w których nie było żadnego działania od 6 lat, jednocześnie takie sprawy są ocznaczane markerem archiwum i domyślnie przestają się wyświetlać w widokach i tabelach poradni, można je zobaczyć dopiero po wyłączeniu tego filtra lub w osobnym widoku
2) ta sama grupa osób by mogła by mieć wyświetlany w menu poradni alarm/znacznik że są takie sprawy do skasowania z linkiem do ich kasowania
3) jeśli mówimy o sprawach niedotykanych od 6 lat to trzeba je odklikiwać do skasowania? czy może lepiej żeby akcja działała w trybie "skasuj wszystkie za wyjątkiem zaznaczonych"?

Majle na zenboxie można kasować bez potwierdzenia automatycznie w pkt1, bo i tak mamy ich kopię na poradni 

Pytanie czy w ogóle przechowywać je tam tak długo?
@mrbojko  - teraz najstarsze maile na zenboxie są z sierpnia 2020, co daje zajętośc skrzynki 77% (btw. gdzie są starsze?) czy wysyłane też siedzą na emaillabs czy są tylko tamtendy transferowane?

@AgnieszkaZdanowicz , @mrbojko , @KarolaJ, Wasze zdanie? widok do kasowania zaproponuję jak ustalimy mechanizm.

**Comment by AgnieszkaZdanowicz** [comment]
@PiotrIw punkty 1 i 2 jak najbardziej ok. Punkt 3 - chyba lepsza jest opcja "skasuj wszystkie za wyjątkiem zaznaczonych".

Co do zenboxa, to właśnie nie mam pojęcia, jak to działa i potrzebna rzeczywiście odpowiedź @mrbojko

**Comment by KarolaJ** [comment]
Zgadzam się z Agnieszką.
