### ISSUE TITLE
zmiana statusu sprawy z "przypisana" na "wolna"

### ISSUE THREAD

**Issue by AgnieszkaZdanowicz** [watchdogpolska/poradnia#1035]
Kiedy przypiszę do sprawy prawnika, który ma prawo kontaktować się bezpośrednio z klientem, wtedy sprawa uzyskuje status "przypisana". Kiedy jednak taki prawnik przestaje zajmować się sprawą i mu ją zabieram, to sprawa nadal ma status "przypisana". Mogę ją ręcznie zmienić na "wolna", ale po wysłaniu wiadomości w wątku wraca do statusu "przypisana". Zależałoby mi, żeby status zmieniał się na "wolna", kiedy w sprawie nie ma żadnego prawnika albo jest przypisana taka osoba, która nie może pisać bezpośrednio do klienta.

**Comment by ad-m** [comment]
> Mogę ją ręcznie zmienić na "wolna", ale po wysłaniu wiadomości w wątku wraca do statusu "przypisana". 

Widzę tu dwa zagadnienia:
* automatyczne aktualizowanie stanu sprawy po odebraniu uprawnień prawnikowi
* zmiana stanu sprawy po przesłaniu wiadomości

W przypadku pierwszego mam pomysł, ale drugie próbowałem odtworzyć w https://porady.siecobywatelska.pl/sprawy/sprawa-13197/ i nie jestem w stanie tego odtworzyć.

**Comment by AgnieszkaZdanowicz** [comment]
@ad-m no ja, szczerze mówiąc, też nie mogę odtworzyć tego błędu. Sorry, coś mi się musiało uroić. Tak więc tylko pierwszy punkt jest aktualny.

**Comment by ad-m** [comment]
Czy pierwszy punkt jest dalej aktualny? Mam wrażenie, że zmiana w tym zakresie została wdrożona.

**Comment by AgnieszkaZdanowicz** [comment]
Punkt pierwszy załatwiony i pięknie działa.

Jak robiłam test nowych statusów, to sobie je klikałam i zauważyłam, że jest tak, że jak przypisałam "wsparcie ++" i potem chce zmienić na "wsparcie" to nie mogę. Czy to się da jakoś łatwo zmienić, żeby jednak przez permissiongroup dało się zmieniać uprawnienia z szerszych (wsparcie++) na węższe (wsparcie)? Jeśli to dużo roboty, to spoko, rzadko się zdarza, żeby komuś zmniejszać uprawnienia, chyba tylko przy przypisaniu przez pomyłkę moglibyśmy chcieć je zmieniać. Chodzi mi tylko o to, żebyśmy były świadome, jak to działa.

**Comment by ad-m** [comment]
Permission group obecnie wyłącznie przypisuje uprawnienia. Zaraz zmienię, aby przed przypisaniem usuwał.

**Comment by AgnieszkaZdanowicz** [comment]
działa, zamykam
