### ISSUE TITLE
usunięcie permission group

### ISSUE THREAD

**Issue by AgnieszkaZdanowicz** [watchdogpolska/poradnia#1036]
@ad-m chciałam zrobić porządek w grupach uprawnień i skasować jedno z nich, którego dawno nie używaliśmy, ale kiedyś jednak tak. I jak chcesz je skasować, to system mi napisał, że skasuje też obiekty od nich zależne i boję się tego określenia:

![Zrzut ekranu 2021-12-17 o 06 45 15](https://user-images.githubusercontent.com/36925935/146495425-f549feca-451d-4638-ada7-e160b8f50920.png)
e

On mi nie skasuje żadnych spraw z poradni, prawda? Tylko pewnie odpisze prawników w sprawach, w których używałam tego uprawnienia? Wolę się upewnić :)

**Comment by ad-m** [comment]
Na poziomie sprawy nie ma grup uprawnień, a wyłącznie indywidualne uprawnienia. Dlatego możesz zawsze wejść i dodać indywidualne uprawnienia, bo nie dzieje się to poprzez grupy.

"Permission Group" to logiczna grupa określająca jakie uprawnienia będą przypisane w przypadku jej wykorzystania, ale na poziomie sprawy są przypisywane już bezpośrednio uprawnienia i nie ma śladu jaka logiczna grupa została wykorzystana. To taki szablon uprawnień innymi słowy.

> On mi nie skasuje żadnych spraw z poradni, prawda? 

Nie.

> Tylko pewnie odpisze prawników w sprawach, w których używałam tego uprawnienia? Wolę się upewnić :)

Nie, te obiekty zależne to są opcje zaznaczone w "Uprawnienia", czyli łącznik pomiędzy grupą uprawnień, a konkretnymi uprawnieniami . Jeżeli nie chcesz mieć obiektów zależnych to odznacz wszystko w polu "Uprawnienia", chociaż to praktycznego sensu nie ma, skoro to się "odznaczy", gdy skasujesz grupę uprawnień.

**Comment by ad-m** [comment]
Ja przyjmuje, że w tym miejscu nie ma potrzeby przeprowadzania żadnych prac programistycznych.
