### ISSUE TITLE
przeszukiwanie spraw po klientach dla nie-adminów

### ISSUE THREAD

**Issue by AgnieszkaZdanowicz** [watchdogpolska/poradnia#1037]
To mi się wydaje trudne. Admini widzą wszystkie sprawy i dlatego mogą je dowolnie przeszukiwać i filtrować. Nie-admini widzą tylko swoje sprawy i mają mocno ograniczone przeszukiwanie i filtrowanie. Z tego, co rozumiem, nie mogą np. przeszukiwać po klientach. Z punktu widzenia działania systemu, rozumiem czemu tak jest - bo widzą tylko określone sprawy i określonych klientów, a wyszukiwanie dotyczy wszystkich. Czy jednak dałoby się tak zrobić, żeby nie-admini mogli wyszukiwać tylko swoje sprawy i w ramach tego wyfiltrować wszystkie przypisane im sprawy danego klienta? Bartosz, który niedawno przestał być adminem, zgłosił mi, że ten brak możliwości wyszukania spraw klientów, bardzo utrudnia mu pracę.

**Comment by ad-m** [comment]
Tutaj są trzy zagadnienia:

* prawo do wyświetlenia danej sprawy, co jest ograniczone uprawnieniem `can_view` w danej sprawie,
* możliwość filtrowania, która jest ograniczona dla członków zespołu,
* widoczność (wybór) innych osób niż członkowie zespołu (trzeba widzieć, aby móc kogoś zaznaczyć jako opcja wyboru), co jest obecnie ograniczone poprzez globalne uprawnienie `users.can_view_other`. 

Odnosząc powyższe na sytuacje Bartosza:

* Bartosz może widzieć sprawę, bo mu nadajesz uprawnienia do sprawy
* Bartosz może filtrować według klienta (sprawdziłem to przed chwilą wrzucając na chwile dodatkowe konto do zespołu), jednak nie może wybrać nikogo innego niż klient,
* Bartosz nie może widzieć (wybrać) innych osób niż członkowie zespołu jak opcja filtrowania.

Na bazie obecnych rozwiązań wystarczające jest przydzielenie zatem Bartoszowi uprawnienia `users.can_view_other`, aby mógł na https://porady.siecobywatelska.pl/uzytkownik/ wybrać sobie użytkowników, a także w wykazie spraw wybrać filtrowanie według tego użytkownika. Bartosz w ten sposób nie uzyskuje dostępu do wszystkich spraw klientów, ale – co było modelowane jako informacja wrażliwa – uzyskuje pośrednią informacje o wszystkich osobach, które się zwracały do Stowarzyszenia, a także osobowych danych identyfikacyjnych.

Daj znać czy to rozwiązanie jest dla Ciebie satysfakcjonujące.

**Comment by AgnieszkaZdanowicz** [comment]
No właśnie moim zdaniem nie-admin, jak Bartosz, nie powinien widzieć wszystkich klientów, a wyłącznie "swoich" - dlatego napisałam, że wydaje mi się to trudne do rozwiązania

**Comment by ad-m** [comment]
OK, teraz rozumiem oczekiwania. Będzie wykonane.

**Comment by AgnieszkaZdanowicz** [comment]
Czy to już wprowadzone i mogę zamknąć?

**Comment by ad-m** [comment]
Według mojej wiedzy to zostało wprowadzone, ale optymalnie, gdyby p. B. Wilk się wypowiedział.

**Comment by AgnieszkaZdanowicz** [comment]
Spytałam Bartosza, czekam na odpowiedź

**Comment by AgnieszkaZdanowicz** [comment]
Bartosz potwierdził, że działa, więc dziękuję i zamykam
