### ISSUE TITLE
Pasek adresu na Androidzie blady

### ISSUE THREAD

**Issue by ad-m** [watchdogpolska/poradnia#104]
![screenshot_2015-07-21-18-08-34](https://cloud.githubusercontent.com/assets/3618479/8805846/b8e4a488-2fd3-11e5-94bf-ef868059fd13.png)

Jeżeli można zmienić kolor - zmieńmy. Lans.

**Comment by mik-laj** [comment]
`<meta name="theme-color" content="#D82727">`

**Comment by mik-laj** [comment]
https://github.com/watchdogpolska/poradnia/commit/f2f5ae22a5d32a043d05801be1f835e9004b43df Need test

**Comment by ad-m** [comment]
![screenshot_2015-07-21-22-25-40](https://cloud.githubusercontent.com/assets/3618479/8811643/82d14c9c-2ff7-11e5-9273-a9f9f3e1d0fa.png)
