### ISSUE TITLE
odrzucanie wiadomości, kiedy adres poradni jest w polu "do wiadomości"

### ISSUE THREAD

**Issue by AgnieszkaZdanowicz** [watchdogpolska/poradnia#1067]
Paula zwróciła uwagę na przypadek, gdy ktoś wysyła szeroko korespondencje, a następnie osoby odpowiadają do wszystkich, aby przestać wysyłać takie wiadomości do nich:

Otrzymaliśmy do wiadomości: https://porady.siecobywatelska.pl/sprawy/sprawa-13191/

I teraz dostajemy wiadomości od innych osób, które piszą do tego pana, żeby je wypisać z listy adresatów wiadomości:
https://porady.siecobywatelska.pl/sprawy/sprawa-13193/
https://porady.siecobywatelska.pl/sprawy/sprawa-13194/
https://porady.siecobywatelska.pl/sprawy/sprawa-13195/
https://porady.siecobywatelska.pl/sprawy/sprawa-13196/
https://porady.siecobywatelska.pl/sprawy/sprawa-13201/

Możliwe, że powinniśmy przestać przyjmować w Poradni wiadomości, jeżeli nie jesteśmy wymienieni w polu "Do". Ustaliliśmy 29.12 dodatkowo, że w takiej sytuacji powinna wysyłać się z systemu automatyczna odpowiedź, że wiadomość nie dotarła i jak ma dotrzeć, to muszą wpisać adres w polu "do"

**Comment by ad-m** [comment]
@AgnieszkaZdanowicz czy możesz potwierdzić, że Twoje potrzeby zostały zaspokojone?

**Comment by AgnieszkaZdanowicz** [comment]
@ad-m jest ok, dzięki wielkie! zamykam
