### ISSUE TITLE
wydarzenia widoczne dla klientów

### ISSUE THREAD

**Issue by AgnieszkaZdanowicz** [watchdogpolska/poradnia#1069]
Okazało się, że klienci nie widzą wydarzeń - nie wiedzą, że zaznaczyliśmy termin albo że ściągnęły się informacje z ewokandy. Ustaliliśmy, że chcemy, żeby klienci widzieli wydarzenia z poradni. Tylko najpierw @ad-m musi udostępnić w BI @AgnieszkaZdanowicz spis dotychczasowych wydarzeń, żeby AZ sprawdziła, czy nie wpisywaliśmy jakichś wydarzeń, których lepiej, żeby klienci nie widzieli :)

**Comment by ad-m** [comment]
@AgnieszkaZdanowicz proszę zestawienie: https://bi.siecobywatelska.pl/question/40?created_on=2021-12-01~2021-12-31

Uprzejmie proszę o potwierdzenie gotowości do publikacji wydarzeń.

**Comment by AgnieszkaZdanowicz** [comment]
Chciałam pobrać tę bazę, bo byłoby mi łatwiej przejrzeć, ale za długo się pobiera i wywala błąd 504. Oj... teraz to w ogóle bi przestało działać

**Comment by ad-m** [comment]
@mrbojko zatrzymałem small-eod v2 (za chwile przeciez uruchamiamy na DO) i zrestartowałem Metabase (w logach było o braku pamięci).

@AgnieszkaZdanowicz wybierz mniejszy okres.

**Comment by AgnieszkaZdanowicz** [comment]
@ad-m nawet jak wybieram mniejszy okres (np. tydzień), to mi nie pobiera tej bazy, a przez BI nie widzę całych nazw wydarzeń

**Comment by ad-m** [comment]
To ci w nowym roku prześlę to w jakiś inny sposób.

**Comment by AgnieszkaZdanowicz** [comment]
ok!

**Comment by ad-m** [comment]
@AgnieszkaZdanowicz , odkryłem błąd, który sprawiał, że odpowiedź była masywna (i nieprawidłowa). Teraz już powinno być dobrze, więc użyj Metabase.

**Comment by ad-m** [comment]
@AgnieszkaZdanowicz czy są problemy?

**Comment by AgnieszkaZdanowicz** [comment]
Adam, jedynym problemem jest brak czasu. Przepraszam, pamiętam o sprawie, postaram się nią zająć, jak najszybciej. Wiem, że to o tyle pilne, że zaraz zaczynasz pracę, o ile jeszcze nie zacząłeś.

**Comment by AgnieszkaZdanowicz** [comment]
@ad-m przejrzałam wszystkie nazwy wydarzeń i edytowałam te wątpliwe. Można udostępniać klientom. Dzięki!

**Comment by AgnieszkaZdanowicz** [comment]
to jest aktualne, że klienci nie widzą wydarzeń. @mrbojko możesz mi pomóc technicznie? bo chciałam tu zadać pytanie Karolinie i ją oznaczyć, ale github mi jej nie wyszukuje... A w innych sprawach wyszukiwał. Z czego to może wynikać? Nick Karoliny to @KarolaJ

**Comment by PiotrIw** [comment]
@AgnieszkaZdanowicz  @KarolaJ - czy klienci mają widzieć wszystkie wydarzenia czy tylko te, które zostaną oznakowane jako np. Wewnętrzne - tak/nie?

**Comment by AgnieszkaZdanowicz** [comment]
Ja chciałam, żeby klienci widzieli wydarzenia, bo pomyślałam, że tedy byliby spokojniejsi, wiedząc, że mamy zaznaczony termin w ich sprawie i o nim pamiętamy. Ale nie wiem, czy teraz nie ma jakichś wewnętrznych terminów właśnie, więc Karolina musi zdecydować.

**Comment by KarolaJ** [comment]
Tak, ja poproszę, aby takie dodatkowe oznakowanie było (która umożliwia
pokazywanie Klientom tylko wybrane terminy), bo ustawiam czasem terminy,
aby np. zmotywować Zespół, albo otrzymać jakieś info od Szymona O.

Pozdrawiam
Karolina Jankowska

*Sieć Obywatelska Watchdog Polska*



*Nie lekceważ prawa do jawności!*

*Przekaż 1,5% podatku:siecobywatelska.pl/1-5-procent
<http://siecobywatelska.pl/1-5-procent>*

ul. Ursynowska 22/2 | 02-605 Warszawa
KRS: 0000181348
tel: +48 22 844 73 55 <+48228447355>
www.siecobywatelska.pl | www.sprawdzamyjakjest.pl
www.watchdogportal.pl | www.informacjapubliczna.org



pon., 17 kwi 2023 o 06:41 AgnieszkaZdanowicz ***@***.***>
napisał(a):

**Comment by KarolaJ** [comment]
@PiotrIw Tak, ja poproszę, aby takie dodatkowe oznakowanie było (która umożliwia pokazywanie Klientom tylko wybrane terminy), bo ustawiam czasem terminy, aby np. zmotywować Zespół, albo otrzymać jakieś info od Szymona O.

**Comment by PiotrIw** [comment]
@KarolaJ @AgnieszkaZdanowicz - zrobię, tylko wybierzcie jeszcze opcję domyslną:
A - wszystkie wydarzenia domyslnie widoczne dla klientów a ukrywamy tylko te, które zaznaczymy jako "wewnętrzne"
B - wszystkie wydarzenia domyslnie ukryte dla klientów a pokazujemy tylko te, które zaznaczymy jako "zewnętrzne"

**Comment by KarolaJ** [comment]
@PiotrIw @AgnieszkaZdanowicz proponuję:

B - wszystkie wydarzenia domyslnie ukryte dla klientów a pokazujemy tylko te, które zaznaczymy jako "zewnętrzne"

**Comment by AgnieszkaZdanowicz** [comment]
zgadzam się z Karoliną

**Comment by PiotrIw** [comment]
@AgnieszkaZdanowicz @KarolaJ OK, zrobię w następnej paczce zmian, a znacznik nazwę "Publiczne (widoczne dla klientów)", domyślnie wyłączony. A może wolicie inną nazwę?

**Comment by AgnieszkaZdanowicz** [comment]
dla mnie nazwa ok :)

**Comment by KarolaJ** [comment]
@PiotrIw @AgnieszkaZdanowicz  dla mnie też ok

**Comment by PiotrIw** [comment]
zaimplementowane w wersji 1.1.10
