### ISSUE TITLE
Tłumaczenie SOO

### ISSUE THREAD

**Issue by ad-m** [watchdogpolska/poradnia#107]
Po spotkaniu zapisałem "Tłumaczenie SOO". Trochę zbyt lakonicznie. Nie wiem o co chodzi :worried:

**Comment by ad-m** [comment]
@KatarzynaBatko ?

**Comment by KatarzynaBatko** [comment]
może to były opisy po angielsku, a może jakieś inne czynności? Proponuję olać, chyba to nie była duża sprawa. Jak wyjdzie w praniu to poprwimy. Zbliżajmy się do uznania, że już używamy. Co znam zostało technicznie? Bo wizerunkowo to widzę, że pierwsza strna, menu boczne i regulamin oraz formuły. A coś jeszcze?

**Comment by ad-m** [comment]
Technicznie nic.

**Comment by ad-m** [comment]
Już wiem! To był błąd 500 dla aplikacji.

**Comment by ad-m** [comment]
Fix in 953b77e9cc9042dac67cd79e7c625d158cceeebd
