### ISSUE TITLE
łączenie spraw na poradni

### ISSUE THREAD

**Issue by AgnieszkaZdanowicz** [watchdogpolska/poradnia#1070]
Nie tak rzadko zdarza się, że klienci nie piszą na adres danej sprawy, tylko kolejne pisma w wątku wysyłają na ogólny adres porady@ Wtedy my ręcznie wykopiowujemy treść tych wiadomości, ściągamy załączniki i wrzucamy do właściwego wątku. Chcielibyśmy, żeby wątki dało się łączyć - zostawałby wtedy wątek wcześniej założony, a ten nowszy by się zamykał

**Comment by AgnieszkaZdanowicz** [comment]
Udało się połączyć pierwszą sprawę :) tylko jeszcze nie dzieje tak, żeby ta nowsza sprawa się zamykała automatycznie. Bo jakbyśmy ją kasowali, to wtedy też połączenie zniknie prawda?

**Comment by ad-m** [comment]
Nie istnieje żadne połączenie pomiędzy takimi sprawami, oprócz tekstowej notatki na ten temat. Tylko rzeczy są przenoszone ze sprawami, a stara sprawa jest zamykana.

**Comment by AgnieszkaZdanowicz** [comment]
Ale stara sprawa się nie zamyka - przynajmniej tak wygląda, jak teraz przetestowałam na Twoich testowych wątkach #13289 i #13290

**Comment by ad-m** [comment]
Och, zagadkowe. Mam nawet test, który powinien to sprawdzać. Do naprawienia.

**Comment by ad-m** [comment]
@AgnieszkaZdanowicz czy możesz potwierdzić, że Twoje potrzeby zostały zaspokojone?

**Comment by AgnieszkaZdanowicz** [comment]
@ad-m wygląda, że tak. Dziękuję i zamykam wątek.
