### ISSUE TITLE
zapisywanie ustawień wiadomości w momencie wysyłania

### ISSUE THREAD

**Issue by AgnieszkaZdanowicz** [watchdogpolska/poradnia#1071]
Chodzi o to, że w tej chwili, jak usuwamy prawnika z zespołu, to wysłane przez niego wcześniej wiadomości wyświetlają się jak wysłane przez klienta i trudno się zorientować w takiej sprawie. Dlatego wiadomość powinna zapamiętywać na zawsze, że została wysłana przez osobę, która w danym momencie była w zespole (sorry za sformułowanie, nie wiem, jak to lepiej wyjaśnić), niezależnie od dalszych losów tej osoby.

**Comment by ad-m** [comment]
@AgnieszkaZdanowicz czy możesz potwierdzić, że Twoje potrzeby zostały zaspokojone?

**Comment by AgnieszkaZdanowicz** [comment]
@ad-m jest ok, zamykam
