### ISSUE TITLE
wyróżnienie wiadomości wysyłanych przez opcję "napisz do zespołu"

### ISSUE THREAD

**Issue by AgnieszkaZdanowicz** [watchdogpolska/poradnia#1072]
Mamy prośbę o wyróżnienie wiadomości wysyłanych przez opcję "napisz do zespołu" poprzez oznaczenie ich innym kolorem niż czerwony. Może niebieski byłby ładny? :)

**Comment by ad-m** [comment]
W #1082 wprowadziłem zablokowanie wysyłki listów wysłanych poprzez "Napisz do zespołu", aby uniknąć przypadkowemu wycieku wewnętrznej korespondencji.

**Comment by ad-m** [comment]
W #1083 wprowadziłem zmianę koloru wewnętrznych notatek na niebieskie.

**Comment by AgnieszkaZdanowicz** [comment]
działa :) a czy to da się zastosować do przeszłych wiadomości czy może działać tylko o tych, które dopiero wyślemy?

**Comment by ad-m** [comment]
Niestety, okazało się była w kodzie myśl, aby wiadomości do zespołu były oznaczane "do zespołu", ale to nie funkcjonowało poprawnie, więc to naprawiłem, ale nie mam danych (na tym polegał wszak błąd), aby to naprawić wstecz.

**Comment by AgnieszkaZdanowicz** [comment]
Jednak otwieram, bo Marcin i Martyna coś napisali do zespołu i pojawiło się na czerwono i przy ich wiadomościach nadal jest opcja "wyślij", więc postanowiłam dopytać - czy na niebiesko powinny się wyświetlać mi tylko moje wiadomości, które wysłałam do zespołu? Bo myślałam, że wszystkie, niezależnie kto wysłał, będą niebieskie.  Chyba za słabo przetesowałam - ale u mnie nie wyświetlało się "wyślij"

**Comment by AgnieszkaZdanowicz** [comment]
Hm.. a w innej sprawie poprawnie się wyświetliło na niebiesko i nie ma opcji "wyślij" - to jak Ty napisałeś tutaj: https://porady.siecobywatelska.pl/sprawy/sprawa-13035/#letter-60410

Zastanawiam się, czy to ma znaczenie, czy ktoś pisze przez poradnię a przez maila?

**Comment by ad-m** [comment]
> Zastanawiam się, czy to ma znaczenie, czy ktoś pisze przez poradnię a przez maila?

Przez e-mail jest pisany e-mail do klienta / projekt e-maila do klienta (w zależności od uprawnień). Przez poradnie może być pisany e-mail lub notatka.

**Comment by AgnieszkaZdanowicz** [comment]
tutaj Marcin mi napisał, że wiadomość z 9:53 napisał jako "napisz do zespołu", a jest na czerwono i ma opcję wyślij: https://porady.siecobywatelska.pl/sprawy/sprawa-13259/

**Comment by ad-m** [comment]
Spróbuje złapać Marcina jak to robi, bo u mnie działa (jak widać).

**Comment by AgnieszkaZdanowicz** [comment]
widziałam właśnie!

**Comment by AgnieszkaZdanowicz** [comment]
Marcin naprawiony, ale dziś jeszcze Martyna pisała na czerwono: https://porady.siecobywatelska.pl/sprawy/sprawa-12988/#letter-60454

**Comment by AgnieszkaZdanowicz** [comment]
To jak Martyna napisała na niebiesko, to zamykam i będę obserwować, czy wszystko działa jak należy. I zauważyłam, że jeszcze przycisk "napisz do zespołu" jest na niebiesko - świetny pomysł, dzięki!
