### ISSUE TITLE
nowe statusy spraw (te z filtrowania)

### ISSUE THREAD

**Issue by AgnieszkaZdanowicz** [watchdogpolska/poradnia#1074]
W tej chwili mamy: 

wolna - kiedy żadna z przypisanych osób nie ma opcji bezpośredniego pisania do klienta
przypisana - kiedy choć jedna z przypisanych osób ma opcję bezpośredniego pisania do klienta
zamknięta - jak sprawa jest oznaczona jako zamknięta

Chodzi o modyfikację w taki sposób:

wolna - kiedy do sprawy nie jest przypisany nikt z zespołu poradni
do moderowania - kiedy żadna z przypisanych osób nie ma opcji bezpośredniego pisania do klienta
przypisana - kiedy choć jedna z przypisanych osób ma opcję bezpośredniego pisania do klienta
zamknięta - jak sprawa jest oznaczona jako zamknięta

A po tej zmianie mam prośbę o automatyczne odświeżenie statusów spraw, żeby wszystkie podzieliły się zgodnie z tymi nowymi zasadami

**Comment by ad-m** [comment]
Zostanie to wykonane zgodnie z wskazaniami, z zastrzeżeniem, że zamiast "przypisanych osób" to "przypisanych aktualnych członków zespołu".

**Comment by ad-m** [comment]
Status odświeżę niedługo po tym, gdy upewnimy się, że spełnia to nasze oczekiwania. Zmiana została przygotowana i zaraz wdrażam.

**Comment by AgnieszkaZdanowicz** [comment]
To klikamy z Paulą i testujemy. Na razie pierwsze co zauważyłyśmy, to że jak się wchodzi w wykaz spraw, to automatycznie widać wolne + przypisane, a po dodaniu nowego statusu fajnie, gdyby też "moderowane" były widoczne domyślnie

**Comment by ad-m** [comment]
> To klikamy z Paulą i testujemy. Na razie pierwsze co zauważyłyśmy, to że jak się wchodzi w wykaz spraw, to automatycznie widać wolne + przypisane, a po dodaniu nowego statusu fajnie, gdyby też "moderowane" były widoczne domyślnie

To też zauważyłem po wdrożeniu. Już naprawiłem. Dodatkowo odwróciłem ikony, aby stara ikona była dla starego statusu.

**Comment by KarolaJ** [comment]
Dla mnie wszystko jasne i bez zastrzeżeń.

**Comment by AgnieszkaZdanowicz** [comment]
@ad-m statusy działają jak trzeba - poprosimy jeszcze o zaktualizowanie przeszłym spraw do aktualnej listy statusów

**Comment by AgnieszkaZdanowicz** [comment]
@ad-m to jeszcze jeden aspekt mi przyszedł do głowy - bo można zaznaczyć, żeby poradnia: Powiadamiała o pismach w wolnych sprawach. Po zmianie to będzie dotyczyło spraw, które nie są przypisane, a w nich raczej nie będą pojawiały się nowe pisma. Czy można zmienić, żeby system powiadamiał o pismach w wolnych i moderowanych sprawach?

**Comment by ad-m** [comment]
> @ad-m statusy działają jak trzeba - poprosimy jeszcze o zaktualizowanie przeszłym spraw do aktualnej listy statusów

Wykonano.

> @ad-m to jeszcze jeden aspekt mi przyszedł do głowy - bo można zaznaczyć, żeby poradnia: Powiadamiała o pismach w wolnych sprawach. Po zmianie to będzie dotyczyło spraw, które nie są przypisane, a w nich raczej nie będą pojawiały się nowe pisma. Czy można zmienić, żeby system powiadamiał o pismach w wolnych i moderowanych sprawach?

Tak. Zaraz zrobię PR. Świetnie, że to wyłapałaś!

**Comment by ad-m** [comment]
Sprawdziłem dokładniej. Opis tego "Powiadamiała o pismach w wolnych sprawach" nie jest poprawny, ale już to działa tak jak chcesz – jeżeli nie ma prawnika (osoby z uprawnieniami do zatwierdzania pism) to pisze także do wyznaczonych osób. Nie do końca można w tym zakresie wykorzystywać status, bo trzeba także brać pod uwagę sprawy zamknięte.

**Comment by AgnieszkaZdanowicz** [comment]
To dobrze, że już działa. Wczoraj zrobiłam test na swojej testowej sprawie i zadziałało. To zamykam wątek.
