### ISSUE TITLE
Paula loguje się z prywatnego maila i widzi sprawy służbowe?

### ISSUE THREAD

**Issue by AgnieszkaZdanowicz** [watchdogpolska/poradnia#1081]
@ad-m testując nowe zmiany na poradni Paula zauważyła, że może zalogować się zprzez swojego prywatnego maila (nie będę go tu podawać, żeby cały świat się o nim nie dowiedział - można sprawdzić go w bebechach poradni, gdzie Paula ma 2 konta) do poradni i w tej sposób loguje się na konto służbowe, czyli na użytkownika Paula K... (team). A w systemie jej prywatny adres jest oznaczony, że wcale nie jest w zespole. Paula też nie dostaje żadnych powiadomień na swojego prywatnego maila, tylko na służbowego wszystko. Podobno kiedyś raz dostała powiadomienie na prywatnego maila, ale zakładamy, że ktoś musiał przypisać złego użytkownika do sprawy. W zespole jest konto Pauli z podpiętym adresem służbowym. I nie potrafimy dojść, jak to możliwe.

**Comment by ad-m** [comment]
Paula loguje się z wykorzystaniem prywatnego adresu e-mail, ale loguje się na służbowe konto. Dziwnym trafem udało się jej powiązać do służbowego konta powiązać dodatkowy adres e-mail (zobacz https://porady.siecobywatelska.pl/admin/account/emailaddress/21/change/ ). Nie mam pewności co się wydarzyło, prawdopodobnie kliknęła w link aktywacyjny na prywatny adres e-mail po zalogowaniu na służbowe konto.

**Comment by AgnieszkaZdanowicz** [comment]
Spryciara :) dzięki za wyjaśnienie!
