### ISSUE TITLE
.login-form dla formularza logowania, aby go zwęzić

### ISSUE THREAD

**Issue by ad-m** [watchdogpolska/poradnia#109]

**Comment by ad-m** [comment]
Podobnie log-out?

**Comment by ad-m** [comment]
Podobnie password change.

**Comment by ad-m** [comment]
659298c 
Wylogowanie nie. Jednak zmiana hasła tak. Nadać style dla zmiany hasła? Jakie, jak?

**Comment by mik-laj** [comment]
https://github.com/watchdogpolska/poradnia/commit/8f53640f478b450b1b4c0c574e3fa30fd91aac1c
