### ISSUE TITLE
Eksportowanie porad przez panel administracyjny 

### ISSUE THREAD

**Issue by ad-m** [watchdogpolska/poradnia#1095]
@AgnieszkaZdanowicz czy wykorzystujesz eksportowanie porad z Poradni.

Chciałbym to usunąć z Poradni, aby ograniczyć zakres projektu. A może przenieść do BI?

**Comment by AgnieszkaZdanowicz** [comment]
Ja nawet nie wiedziałam, że jest coś takiego, więc nie wykorzystuje

**Comment by ad-m** [comment]
To jest opcja "Import" i "Export" na https://porady.siecobywatelska.pl/admin/advicer/area/ , https://porady.siecobywatelska.pl/admin/advicer/personkind/ , https://porady.siecobywatelska.pl/admin/advicer/institutionkind/ , https://porady.siecobywatelska.pl/admin/advicer/issue/ . Chciałaś pewnie kiedyś to sobie szybko edytować w Excelu, ale teraz - ze względu na stare dane – takie zbiorcze edycje mogłyby być niebezpieczne.

**Comment by AgnieszkaZdanowicz** [comment]
Tak, to usuńmy tę opcję
