### ISSUE TITLE
Ograniczenie mechanizmów edycji treści

### ISSUE THREAD

**Issue by ad-m** [watchdogpolska/poradnia#1096]
Mamy mechanizm do edycji bloków treści np.:

![image](https://user-images.githubusercontent.com/3618479/147799757-3c1b8d97-61af-4fd5-acbb-a9ee2b9c7c8a.png)

Mamy także mechanizm do edycji stron np.:

![image](https://user-images.githubusercontent.com/3618479/147799786-0a628039-3bf2-42b1-a4cc-e1cfda131594.png)

Czy możemy zastąpić ten drugi mechanizm tym pierwszym? Dla użytkownika rezultat będzie ten sam, a biblioteka, której używamy do edycji stron nie jest wspierana, a przez to rodzi pewne problemy. Poza tym warto weryfikować i ograniczać zakres projektu.

**Comment by ad-m** [comment]
Zagadnienie do dyskusji z @AgnieszkaZdanowicz .

**Comment by AgnieszkaZdanowicz** [comment]
Wydaje mi się, że możemy zastąpić jedno drugim, skoro i tak pozostanie opcja edycji
