### ISSUE TITLE
Uwierzytelnianie z użyciem konta Google

### ISSUE THREAD

**Issue by ad-m** [watchdogpolska/poradnia#1103]
@AgnieszkaZdanowicz czy możemy poczynić działania wobec polityki prywatności celem umożliwienia wprowadzenia uwierzytelniania kontem Google do Poradni? Szczerze mówiąc przez długi czas myślałem, że jest, ale dopiero od ostatniego intensywnego wykorzystania do SKW uświadomiłem sobie to, Paula także to dostrzegła jako potrzebę.

**Comment by AgnieszkaZdanowicz** [comment]
Ale to będzie dotyczyło tylko członków zespołu, tak? Jak dla mnie możemy uwierzytelniać przez Google, to nawet mocniej zagwarantuje, że wszyscy z zespołu logują się przez konta służbowe

**Comment by ad-m** [comment]
Ja miałem na myśli wszystkich fakultatywnie, a możemy dodatkowo wprowadzić, że członkowie zespołu obowiązkowo.

**Comment by AgnieszkaZdanowicz** [comment]
ok :)

**Comment by tobiasz-gleba** [comment]
postaram się to ogarnąć

**Comment by AgnieszkaZdanowicz** [comment]
@PiotrIw potrzebuję Twojej oceny, czy to wpływa jakoś na bezpieczeństwo dostępu do poradni? 

Wycofuję się z obowiązkowego logowania z użyciem konta Google przez członków i członkinie zespołu poradni. W zespole mamy też zewnętrznych radców prawnych, od których nie wymagamy, żeby zakładali sobie maila w domenie @siecobywatelska.pl

**Comment by PiotrIw** [comment]
@AgnieszkaZdanowicz umozliwienie logowania kontem google nie zwiększa istotnie bezpieczeństwa jeśli mamy wymuszone silne hasła i https. Zastosowanie 2FA (logowanie z okresowym potwierdzaniem tożsamości inna metodą - np SMS) - to by zwiększyło bezpieczeństwo.
Na fedrowaniu logowanie kontem google  jest zaimplementowane i nikt z tego nie korzysta z tego co widzę..
Zamykamy?

**Comment by AgnieszkaZdanowicz** [comment]
@PiotrIw dzięki, to zamykam :)

PS. ja na fedrowanie się loguję tylko za pomocą konta google
