### ISSUE TITLE
Wygląd zmodernizowanych uprawnień poprawić

### ISSUE THREAD

**Issue by ad-m** [watchdogpolska/poradnia#111]
Kolor w części: ![zaznaczenie_359](https://cloud.githubusercontent.com/assets/3618479/8816918/00e16eb6-302d-11e5-805c-857eff250824.png)

Przycisk zaawansowane w części:
![zaznaczenie_358](https://cloud.githubusercontent.com/assets/3618479/8816919/06bd1baa-302d-11e5-9386-9326f31909f2.png)
Alternatywnie można przycisk wstaić do panel-heading z wyrównaniem do prawej.

**Comment by ad-m** [comment]
Powiązane z #99

**Comment by ad-m** [comment]
![zaznaczenie_362](https://cloud.githubusercontent.com/assets/3618479/8894940/d6f0ac94-33c8-11e5-947b-9f8c6c0c7400.png)

**Comment by mik-laj** [comment]
Nikt tego publicznie nie zobaczy, więc innym razem.
