### ISSUE TITLE
"Przepływ pracy" i "Ostatnia aktualizacja"

### ISSUE THREAD

**Issue by KarolaJ** [watchdogpolska/poradnia#1113]
Adamie,

mam pytanie w sprawie tabeli "Przepływ pracy", która wyświetla się w lewym górny rogu danej porady na Poradni. Jest tam wers "Ostatnia aktualizacja". W sprawie #12506 wyświetliła się dziś ostatnia aktualizacja wykonana przez Paulę, natomiast Paula jest na urlopie i napisała, że nie wchodziła od rana na Poradnię. Czy owa "Ostatnia aktualizacja" dotyczy każdej aktualizacji zrobionej przez kogokolwiek? Jeżeli tak, to dlaczego widnieje tam zawsze imię i nazwisko członk_a/_ini zespołu, która tej aktualizacji nie dokonała?

Pozdrawiam,
Karolina J.

**Comment by ad-m** [comment]
Ostatnia aktualizacja dotyczy metadanych sprawy np. tytułu sprawy. Myślę, że to błąd, bo data aktualizacji jest automatycznie aktualizowana (np. podczas aktualizacji stanu sprawy w związku z nowym listem), a osoba aktualizacji jest obsługiwana bardziej wprost i obecnie dzieje się tylko podczas edycji samej sprawy np. zmiany jej tytułu. Muszę przemyśleć jak to zbiorczo naprawić.

**Comment by KarolaJ** [comment]
Dziękuję za informację.

**Comment by AgnieszkaZdanowicz** [comment]
To jeśli to tak działa, że data dotyczy tego, kto ostatnio napisał list, a osoba dotyczy tylko osoby, która zmieniła coś w metadanych (np. w tytule sprawy), to wyświetlanie tych danych nie ma chyba za bardzo sensu. @KarolaJ lepiej by było, gdyby tam pojawiało się, kto i kiedy cokolwiek zmienił w sprawie (w tym napisał lub zaakceptował list), prawda?

**Comment by KarolaJ** [comment]
@AgnieszkaZdanowicz zgadza się.

**Comment by AgnieszkaZdanowicz** [comment]
@PiotrIw aktualne

**Comment by PiotrIw** [comment]
@AgnieszkaZdanowicz @KarolaJ  - może lepiej gdyby to pokazywało historię (a nie tylko ostatnią zmianę) aktywności w sprawie?

**Comment by KarolaJ** [comment]
Tak, to jest dobry pomysł. Może przecież być sytuacja, gdy będziemy chcieli prześledzić kompletną pracę nad sprawą.

**Comment by AgnieszkaZdanowicz** [comment]
Tak, dostęp do pełnej historii mógłby być przydatny - byle tylko te wszystkie dane nie wyświetlały się na głównej stronie sprawy, tylko prowadził do nich jakiś link.

**Comment by PiotrIw** [comment]
@AgnieszkaZdanowicz @KarolaJ - przy okazji zmiany edycji Wydarzeń i dodawania linku do kasowania wiadomości zbudowałem mechanizm logujący aktywności użytkowników, można je oglądać w panelu administracyjnym Administracja/logi
teraz można już dodawać kolejne wydarzenia do logowania i zrobić np podgląd wydarzen związanych tylko z daną sprawą/listem/poradą

**Comment by AgnieszkaZdanowicz** [comment]
@PiotrIw w tej chwili w logach widać tylko to, co ktoś zrobił w panelu admina, prawda? A na czym ma polegać dodawanie kolejnych wydarzeń do logowania?

**Comment by PiotrIw** [comment]
@AgnieszkaZdanowicz kolejne zdarzenia do logowania dodaje się w kodzie aplikacji. Można to zrobić jako konfigurowalne z admina, jednak w obecnej architekturze aplikacji to byłby ogrom pracy chyba niezupełnie potrzebnej. W wersji 1.1.9 logowane są:
- wszystkie operacje wykonane w adminie
- dodanie i edycja wydarzenia
- dodanie i edycja listu w widokach aplikacji (nie loguje listów przysyłanych na skrzynkę i dodawanych przez webhooka)

To co jeszcze wg mnie można dodać to:
- listy z webhooka
- dodanie i edycja sprawy
- dodanie i edycja porady

@AgnieszkaZdanowicz @KarolaJ Czy jest coś jeszcze co warto dodać do logowania?

**Comment by AgnieszkaZdanowicz** [comment]
@PiotrIw a co to jest webhook? :)

**Comment by KarolaJ** [comment]
@PiotrIw @AgnieszkaZdanowicz ja uważam, że warto dodać wszystkie 3 proponowane przez @PiotrIw logi.

**Comment by AgnieszkaZdanowicz** [comment]
Dzięki za wyjaśnienie :) To w takim razie zgadzam się z Karoliną i też jestem za dodaniem wszystkich 3 akcji

**Comment by PiotrIw** [comment]
zaimplementowane v1.1.21
