### ISSUE TITLE
logowanie adresem e-mail

### ISSUE THREAD

**Issue by KatarzynaBatko** [watchdogpolska/poradnia#112]
Na pierwszej stronie nadal nie mogę zalogować się długim adresem

**Comment by ad-m** [comment]
Nie została wgrana aktualizacja z zgłoszenia #106 . Teraz to zrobiłem, choć wygląda ona - miejscami - nie najlepiej z powodu zgłoszeń #111 #109.

**Comment by ad-m** [comment]
W najbliższej aktualizacji będzie to dostępne. Przyjdzie e-mail.
