### ISSUE TITLE
klienci nie dostają załączników do maili?

### ISSUE THREAD

**Issue by AgnieszkaZdanowicz** [watchdogpolska/poradnia#1130]
@ad-m już druga osoba napisała, że musi się zalogować, żeby pobrać skargę bezpośrednio z poradni. Dotąd klienci dostawali skargi w formie załącznika do maila - czy coś się zmieniło?

W tych sprawach to było zgłaszane:

https://porady.siecobywatelska.pl/sprawy/sprawa-13331/#letter-60968

https://porady.siecobywatelska.pl/sprawy/sprawa-13055/

**Comment by ad-m** [comment]
Szanowna Agnieszko,

Nawet w zacytowanej wiadomości jest wskazane:

> Załączniki pisma: skarga_45581.odt

Załączniki klient otrzymał, ale z jakiegoś względu je ignoruje. Zmiany były w dwóch kwestiach:

* wymaganie logowania do pobrania załączników – https://github.com/watchdogpolska/poradnia/pull/1056 (to możnaby ułatwić, aby zamiast logowania link miał zaszyty token dostępowy, byle tylko zaniechać linkowania bezpośrednio do plików, bo to sprawi problem, gdy przeniesiemy pliki i też nie jest optymalne pod względem bezpieczeństwa, ale dodatkowa praca)
* w wersji sformatowanej wiadomości link do załacznika w treści zawiera nazwę pliku, zamiast enigmatycznego adresu URL: https://porady.siecobywatelska.pl/listy/sprawa-13331/list-60968/zalacznik/46598 – https://github.com/watchdogpolska/poradnia/pull/1126

Z poważaniem
Adam Dobrawy

**Comment by AgnieszkaZdanowicz** [comment]
@ad-m ale to znaczy, że jest taka zmiana, że dotąd załączniki można było pobrać bezpośrednio z maila, a teraz trzeba się zalogować? Ja dotąd, jak klikałam w link w wiadomości, to mi się pobierały załączniki, ale ja jestem praktycznie cały czas zalogowana na poradni i mogłam nie wpaść na to, że to jest wymagane. Dopytuję, żeby wiedzieć, co odpowiadać klientom.

**Comment by ad-m** [comment]
Tak, do pobrania załączników jest obecnie wymagane zalogowanie, a dotąd nie było.

**Comment by ad-m** [comment]
@AgnieszkaZdanowicz dla usunięcia wątpliwości, każdy klient – nieważne czy pisał z nami e-mailowo, czy przez stronę ma u nas konto. Jeżeli pisał e-mailowo to przy pierwszym kontakcie nowe konto zostało utworzone dla niego i dane logowane przesłane, więc potrzebuje przypomnieć hasło.

Jeżeli to będzie przytłaczać użytkowników to dodam do linków pobierania jednorazowy token, aby wykrywać, że to oni i nie wymagać logowania. Jednakże może to też zachęci, aby korzystać z Poradni, z akt sprawy itd.

**Comment by AgnieszkaZdanowicz** [comment]
Ja obawiam się, że to może być problem dla ludzi, ale może bez potrzeby się martwię. To zamykam wątek - gdyby pojawiało się dużo pytań w tym temacie i ludzie by zgłaszali, że to dla nich problem, to wrócę do tematu
