### ISSUE TITLE
Łączenie spraw

### ISSUE THREAD

**Issue by KarolaJ** [watchdogpolska/poradnia#1132]
Adamie,

czy w sprawie #13222 możemy usunąć wiadomość: https://porady.siecobywatelska.pl/sprawy/sprawa-13222/#letter-61052

Połączyłam tutaj dwie sprawy i nie wiedziałam, że przy połączeniu ta wiadomość będzie istniała dla "Wszyscy". Klient zobaczył, a wolałabym, aby nie miał do tego dostępu.

Pozdrawiam,

Karolina

**Comment by KarolaJ** [comment]
Chodzi mi przede wszystkim o załącznik z tej wiadomości.

**Comment by ad-m** [comment]
Usunięto wiadomość (wraz z załącznikami).

**Comment by KarolaJ** [comment]
Dziękuję.
