### ISSUE TITLE
znikanie oznaczenia "projekt" pisma po wysłaniu kolejnej wiadomości w wątku

### ISSUE THREAD

**Issue by AgnieszkaZdanowicz** [watchdogpolska/poradnia#1134]
W tej chwili działa to tak, że jak wyślemy wiadomość poprzez przycisk "zapisz do przejrzenia", to pojawia się oznaczenie "projekt" - dzięki temu opiekunka poradni wie, że w danej sprawie czeka pismo do sprawdzenia. Jednak zdarza się tak, że "projekt" wisi jakiś czas, a w międzyczasie prawnik wyśle jakąś wiadomość bezpośrednio do klienta - to powoduje, że oznaczenie "projekt" znika, chociaż nadal chcemy, żeby projekt był zatwierdzony prze opiekunkę. Czy można zrobić tak, że oznaczenie "projekt" znika tylko wtedy, kiedy projekt zostanie wysłany do klienta?

Sytuacja powiązana to taka, że czasem prawnicy nie poprawiają starego projektu, tylko tworzą nowy - piszę o tym, żeby się upewnić, że system wtedy uznaje za właściwy "projekt" ten, który został zapisany później?

**Comment by ad-m** [comment]
Dobrze opisałaś zmianę stanu pola "Ma projekt":

- jeżeli jest wysyłany list – projekt – sprawa uzyskuje status "Ma projekt"
- jeżeli jest wysyłany projekt / wysyłany inny list do klienta – sprawa traci status "Ma projekt".

> Czy można zrobić tak, że oznaczenie "projekt" znika tylko wtedy, kiedy projekt zostanie wysłany do klienta?

Każdy projekt, czy dowolny projekt?

> Sytuacja powiązana to taka, że czasem prawnicy nie poprawiają starego projektu, tylko tworzą nowy - piszę o tym, żeby się upewnić, że system wtedy uznaje za właściwy "projekt" ten, który został zapisany później?

System obecnie nie uznaje żadnego projektu za "właściwy", wystarczy wysłać dowolny projekt. Patrz algorytm powyżej.

**Comment by AgnieszkaZdanowicz** [comment]
Chodzi o to, żeby tylko sytuacja wysłania jakiegokolwiek projektu w sprawie powodowała usunięcie statusu "projekt" (albo oczywiście, żeby można było to zrobić ręcznie)
