### ISSUE TITLE
Powtarzające się wydarzenia

### ISSUE THREAD

**Issue by KarolaJ** [watchdogpolska/poradnia#1135]
Szanowni,

w sprawie https://porady.siecobywatelska.pl/sprawy/sprawa-11115/#letter-61134 jedno i to samo wydarzenie powtórzyło się wielokrotnie. Jest to sytuacja występująca w dość wielu sprawach. Czy możemy coś na to poradzić?

Pozdrawiam

Karolina

**Comment by ad-m** [comment]
Szanowna KarolaJ, 

To jest zdecydowanie stan niepożądany i zdecydowanie powinniśmy sobie z tym być w stanie poradzić.

Z poważaniem,

**Comment by ad-m** [comment]
Poprawka przygotowana, wdrożona i nowe wydarzenia takiego rodzaju nie powinny już występować.

**Comment by KarolaJ** [comment]
Szanowny Adamie,

super, dziękuję.
