### ISSUE TITLE
dodanie kolumny do Rejestru Porad + pola wyszukiwania

### ISSUE THREAD

**Issue by AgnieszkaZdanowicz** [watchdogpolska/poradnia#1137]
@ad-m czy mógłbyś dodać do Rejestru Porad (do tabeli) dodać kolumnę zawierającą treść pola "komentarz"? Wiem, że wtedy to się nie zmieści na jednej stronie, ale bardzo nam zależy.

I czy to możliwe, żeby wprowadzić pole, które umożliwi w Rejestrze Porad przeszukiwanie po treści wpisanej do "komentarza", który wpisujemy, rejestrując poradę?

![Zrzut ekranu 2022-02-9 o 14 13 49](https://user-images.githubusercontent.com/36925935/153208356-5c3be22a-b2ef-40a0-b0dc-87eef6aad7e0.png)
?

**Comment by ad-m** [comment]
1/ A komentarz chcecie mieć stale widoczny, czy może wymagać np. najechania na jakimś element, aby pojawiła się chmurka? Poszukuje jak to zorganizować, aby to było czytelna tabela po dodaniu tych dancyh.

2/ Przeszukiwanie - nie ma problemu.

**Comment by AgnieszkaZdanowicz** [comment]
Ad1. Wolałybyśmy stały. Zmieniliśmy sposób rejestrowania porad - dotąd w polu "przedmiot" był stosowany dłuższy opis sprawy, ale teraz wpisujemy tylko określone słowa, które nie zawsze mogą pokazać, o co dokładnie w sprawie chodziło. I potem, jak chcemy wrócić do jakiejś sprawy, a nie pamiętamy tytułu ani klienta, to jest nam trudno. Dlatego postanowiliśmy bardziej korzystać z pola "komentarz". "Przedmiot" będzie ujednolicony i będzie nam dawał dane statystyczne bardziej, a w komentarz każdy będzie wpisywał taki tekst, który potem pozwoli mu zidentyfikować konkretną sprawę. Dlatego lepiej, gdyby treść pola "komentarz" była od razu widoczna w tabeli, bo będziemy po niej przeszukiwać.

**Comment by ad-m** [comment]
@AgnieszkaZdanowicz to może co drugi wiersz będzie zawierał na całą szerokość pole "Komentarz" i jakoś wizualnie to kolejne porady?

**Comment by AgnieszkaZdanowicz** [comment]
Moim zdaniem to się wydaje ok rozwiązanie!

**Comment by AgnieszkaZdanowicz** [comment]
@ad-m wygląda super, dzięki wielkie!
