### ISSUE TITLE
Brak informacji o zgłoszonej poradzie

### ISSUE THREAD

**Issue by KarolaJ** [watchdogpolska/poradnia#1139]
Adamie,

wczoraj o 21:16 Pani napisała za pośrednictwem e-maila na Poradnię. Niestety brak informacji na Poradni o tej sprawie. Czy wiesz dlaczego?

Pani pisała z e-maila: @wp.pl

**Comment by AgnieszkaZdanowicz** [comment]
@KarolaJ najlepiej nie podawać na githubie adresów email klientów, bo nasze wiadomości są widoczne dla każdego.

@ad-m podbijam problem. Kolejna osoba zgłosiła, że wysłała wczoraj wiadomość o 16, i jeszcze dziś ok. 10.35. Jak pierwszej osobie zaproponowaliśmy, żeby wysłała wiadomość przez formularz, to doszła do nas. Może blokują się maile, które są wysyłane jako pierwsze w wątku i z maila, a nie przez formularz? 

@KarolaJ a czy maile w innych sprawach spływają, czy czujesz, że ogólnie jest mniej wiadomości od klientów na poradni teraz?

**Comment by ad-m** [comment]
@mrbojko uprzejmie proszę o weryfikacje z perspektywy logów pocztowych (Emaillabs -> GSuite / Postfix), bo w aplikacji zmian nie było. Ostatnio były dziwne powiadomienia odnośnie phishingu wokół poradni w GSuite, co warto wyjaśnić.

**Comment by KarolaJ** [comment]
@AgnieszkaZdanowicz chyba rzeczywiście od wtorku jest trochę mniej porad spływających na poradnię.

**Comment by ad-m** [comment]
@mrbojko uprzejmie proszę o weryfikacje z perspektywy logów pocztowych (imap-to-webhook), stanu skrzynki (Zenbox), bo w aplikacji zmian nie było. Wierzę także, że powyższe uczucia można zweryfikować  z wykorzystaniem Metabase (albo jakimś istniejącym wykresem, ad-hoc query na tabeli `letters_letter`).

**Comment by KarolaJ** [comment]
Dostałam info od Pauli, że w kolejnej sprawie pojawił się ten sam problem. Klient pisał 14 i 17 lutego. Sprawa nie spłynęła na poradnię, teraz jest załatwiana e-mailowo.

**Comment by mrbojko** [comment]
> @mrbojko uprzejmie proszę o weryfikacje z perspektywy logów pocztowych (Emaillabs -> GSuite / Postfix), bo w aplikacji zmian nie było. Ostatnio były dziwne powiadomienia odnośnie phishingu wokół poradni w GSuite, co warto wyjaśnić.

@ad-m nie bardzo rozumiem co mam sprawdać w Emailabs skoro to poczta przychodząca. W skrzynce odbiorczej main na Zenbox jest 50 nieprzetworzonych maili, w skrzynce Error jest praktycznie sam spam (i kilka maili ewidentnie nie będących spamem). Natomiast w skrzynce Sucess ostatni mail jest z soboty 12.02.2022, więc tak jakby maile z tej skrzynki przestały być odbierane przez imap-to-webhook.

**Comment by ad-m** [comment]
> @ad-m nie bardzo rozumiem co mam sprawdać w Emailabs skoro to poczta przychodząca.

Początkowo zgłoszenie dotyczyło braku powiadomienia. Brak powiadomienia przyjąłem, że jest związane z dostarczeniem takiego powiadomienia do nas, a za to odpowiada Emaillabs.

Dziękuje za sprawdzenie imap-to-webhook. Zatem zrestartuje go i trzeba będzię się przyjrzeć gdzie jest problem z timeoutem, że się zacina.

**Comment by ad-m** [comment]
Dodatkowo dane z netstat z tego kontenera przed restartem:
```
# netstat -tu
Active Internet connections (w/o servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State      
tcp       25      0 27412be59599:49542      gateway.ext.watch:https CLOSE_WAIT 
tcp        1      0 27412be59599:43644      249.195.120.34.bc:https CLOSE_WAIT 
tcp        0      0 27412be59599:38212      151.101.14.132:http     TIME_WAIT  
tcp       37      0 27412be59599:54500      imap.zenbox.pl:imap2    CLOSE_WAIT 
```

Jak również po restarcie w trakcie przetwarzania zaległości:
```
# netstat -tu
Active Internet connections (w/o servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State      
tcp        0      0 27412be59599:55880      gateway.ext.watch:https ESTABLISHED
tcp        0      0 27412be59599:53602      imap.zenbox.pl:imap2    TIME_WAIT  
tcp        0      0 27412be59599:40954      249.195.120.34.bc:https ESTABLISHED
```

Logi są dostepne na hoście helper po wykonaniu ```docker logs --tail 100 --follow imap-to-webhook-porady```

Mam wrażenie, że TCP dla IMAP się zawiesza.

**Comment by mrbojko** [comment]
> Mam wrażenie, że TCP dla IMAP się zawiesza.

W kontenerze?

**Comment by ad-m** [comment]
Uprzejmie proszę o weryfikacje problemu.

**Comment by AgnieszkaZdanowicz** [comment]
Brakujące maile spłynęły na raz. W tej chwili nikt nie zgłasza, żeby coś wysłał, a u nas by nie było widać. Tak więc dziękuję za pomoc i zamykam wątek.
