### ISSUE TITLE
Wygląd formularzy - który świat piękniejszy?

### ISSUE THREAD

**Issue by ad-m** [watchdogpolska/poradnia#114]
![poradnia_-_2015-07-25_12 51 19](https://cloud.githubusercontent.com/assets/3618479/8889116/fd02abd8-32cb-11e5-9173-e24406c76f43.png)
vs.
![poradnia_-_2015-07-25_12 53 33](https://cloud.githubusercontent.com/assets/3618479/8889121/3175e0e2-32cc-11e5-9f26-37dfb35f6a56.png)

**Comment by KatarzynaBatko** [comment]
Mi się bardziej podoba na tym szarym tle. Zwłaszcza, że właśnie miałam napisac, że nie za bardzo mi pasuje guzik zgłoś sprawę na szarej belce. To wygląda na pozostałość po jakimś przypadkowym wyglądzie.

**Comment by mik-laj** [comment]
Dodałem, ale trzeba sprawdzić, czy wszystko funkcjonuje porpawnie.

**Comment by ad-m** [comment]
![poradnia_-_2015-07-27_10 54 35](https://cloud.githubusercontent.com/assets/3618479/8902019/e8466ada-344d-11e5-97e9-f29adc35c3fc.png)

nie

**Comment by ad-m** [comment]
Formularz nowej sprawy wymaga pracy dalej.

**Comment by AgnieszkaZdanowicz** [comment]
mi się wydaje, że jest ok, zamykam
