### ISSUE TITLE
Dostęp do sprawy

### ISSUE THREAD

**Issue by KarolaJ** [watchdogpolska/poradnia#1140]
Adamie,

Adam M. ma dostęp do tej sprawy wyłącznie od wątku z dnia 18 października 2021: https://porady.siecobywatelska.pl/sprawy/sprawa-12426/#letter-62105

Czy możesz ustawić tak, aby widział wszystkie wcześniejsze załączniki i wiadomości, przed datą 18 października i od początku wątku sprawy?

Dziękuję,

Karolina

**Comment by KarolaJ** [comment]
Adamie D.,

sprawa rozwiązana. Dostęp jest. 

Pozdrawiam,

Karolina

**Comment by ad-m** [comment]
W Poradni dostęp jest do całej sprawy, a nie tylko do części po nadaniu uprawnień. Nie zdążyłem odpisać, ale mocno zdziwiło mnie, że ktoś uzyskał częściowy dostęp.

Jedyna różnica w ramach sprawy po nadaniu do niej dostępu, która może objawić się dodatkowo to dostęp do korespondencji dla członków zespołu, co zależy od statusu użytkownika, a nie uprawnień do sprawy.
