### ISSUE TITLE
Problem z doręczeniem wiadomości (PORADNIA)

### ISSUE THREAD

**Issue by KarolaJ** [watchdogpolska/poradnia#1146]
Cześć,

w sprawie #13584 odezwała się Klientka, że nie otrzymała od Nas w ogóle wiadomości, która została do niej przesłana 14 marca. Klientka twierdzi, że problem jest prawdopodobnie po naszej stronie. Bardzo proszę o sprawdzenie, czy rzeczywiście jest coś nie tak z systemem wysyłki na Poradni, czy to jednak było jakieś niedopatrzenie Klientki.

https://porady.siecobywatelska.pl/sprawy/sprawa-13584/#letter-62680

Dziękuję,

Karolina

**Comment by AgnieszkaZdanowicz** [comment]
Pani napisała, że nasza wiadomość wpadła do ogłoszeń, ale ostatecznie ją znalazła
