### ISSUE TITLE
PILNA SPRAWA

### ISSUE THREAD

**Issue by KarolaJ** [watchdogpolska/poradnia#1148]
Dzisiaj od rana na Poradni pojawiło się ponad 100 spraw, z czego w większości widnieje osoba zaangażowana jako: https://porady.siecobywatelska.pl/uzytkownik/sprawa-______porady_siecobywatelska_pl-4/

Sprawcą całego zamieszania jest prawdopodobnie ta wiadomość: https://porady.siecobywatelska.pl/sprawy/sprawa-13682/

Czy można jednorazowo je usunąć to generalnie wygląda to wszystko jak SPAM?

Dziękuję,

Karolina

**Comment by ad-m** [comment]
Posprzątane. Wiadomość od `porady@siecobywatelska.pl` do `porady@siecobywatelska.pl` spowodowała nieskończoną pętle. Powinniśmy zabezpieczyć to.

**Comment by KarolaJ** [comment]
Super, dzięki Adamie. A jak to można zabezpieczyć? Czy zajmiesz się tym, czy rozmawiać o tym z kimś innym? 

Karolina

**Comment by ad-m** [comment]
Zrobiłem zagadnienie w #1149. Potrzebujemy programistę do tego...

**Comment by KarolaJ** [comment]
Dzięki Adamie, przekazałam info dalej.
