### ISSUE TITLE
BRAK WIADOMOŚCI W PORADZIE STWORZONEJ PRZEZ SYSTEM PORADNI

### ISSUE THREAD

**Issue by KarolaJ** [watchdogpolska/poradnia#1150]
Szanowni,

mamy kłopot na poradni. Sprawa #13722 wygląda następujco: Klient wysłał wiadomość, ale jej treść się nie pokazała. Wysłał treść pierwotnego maila jako odpowiedź w sprawie, ale też niczego nie pokazało. Dopiero jak stworzył nową oddzielną sprawę, to mail przeszedł. Klient tworzył sprawę przez system poradnictwa, nie przez maila. Tutaj link do obecnej sprawy:

https://porady.siecobywatelska.pl/sprawy/sprawa-13723/

**Comment by ad-m** [comment]
Szanowna Karolino,

Sprawdziłem, nie widzę w żaden sposób, abyśmy otrzymali od tej osoby wiadomości e-mailowe (sprawdziłem skrzynkę w Zenbox). Ostatnie dostarczone wiadomości od tej osoby są z czerwca 2021 roku. Wiadomość nie została oznaczona jako spam, ani w inny sposób odrzucona (np. brak Poradni w jawnych adresatach wiadomości).

Uprzejmie proszę, aby użytkownik przekazał oryginał wiadomości (z nagłówkami) na mój adres e-mailowy to będę mógł prowadzić śledztwo dalej czy to po naszej stronie pojawił się problem.

Z poważaniem,

**Comment by KarolaJ** [comment]
Szanowny Adamie,

dziękuję za informacje. Poleciłam Szymonowi D., aby poprosił Klienta o przesłanie e-maila na Twój adres.

Pozostaję w kontakcie życząc Tobie dobrego dnia,

Karolina

**Comment by KarolaJ** [comment]
Szanowny Adamie,

Klient odpowiedział w taki sposób: "Witam, Panie Szymonie, ja chyba wiem. Chodziło o to, że jeden z załączników miał opis dłuższy niż 100 znaków. Skróciłem opis i wtedy przeszło"

Tutaj link do wiadomości: https://porady.siecobywatelska.pl/sprawy/sprawa-13723/#letter-63741
