### ISSUE TITLE
MNIEJSZA ILOŚĆ WIADOMOŚCI NA PORADNI

### ISSUE THREAD

**Issue by KarolaJ** [watchdogpolska/poradnia#1157]
Szanowni,

na poradni w tym miesiącu odnotowuję mniejszą ilość zarejestrowanych porad niż zwykle. Wobec powyższego, uprzejmie proszę o sprawdzenie i informację, czy nie ma miejsca jakiś brak przepustowości, co już raz się zadziało na poradni w trakcie mojej działalności. 

Dziękuję,

Karolina

**Comment by KarolaJ** [comment]
Dzień dobry,

ponawiam pytanie. Nadal ilość wpływających na poradnię spraw jest mniejsza niż zwykle.

Dziękuję,

Karolina

**Comment by ad-m** [comment]
W przypadku importowania przez e-mail nie widzę problemu. Także patrząc na problem statystycznie nie widzę odchyleń:

![image](https://user-images.githubusercontent.com/3618479/166308801-6df08b5c-3e96-4b58-8c13-1dac9fec92f6.png)

https://bi.siecobywatelska.pl/question/42?created_at=past30days

Możesz jakoś to sprecyzować lub uwiarygodnić, bo trudno mi szukać po omacku przyczyny czegoś czego nawet nie obserwuje.

**Comment by KarolaJ** [comment]
Adamie,

nie mam nadal dostępu do statystyk, ale podejrzewam, że te które mi przesłałeś dotyczą wszystkich e-maili/wiadomości, które spływają na Poradnie, czyli także tych, które spływają w sprawach już wcześniej zarejestrowanych. Ostatnio (od okresu świat Wielkanocnych) zauważyłam, że na poradni jest rejestrowanych mniej spraw nowych. Poinformowałam o tym Agnieszkę Z., która również potwierdziła taki stan rzeczy sprawdzając statystyki. Ponieważ ten stan jest nadal kontynuowany to napisałam o problemie na GitHub, aby sprawdzić, czy rzeczywiście spraw jest mniej, czy może coś się "zapchało" w systemie. Pamiętam, że już raz był taki problem i potem coś zrobiłeś i nagle jednego dnia wpłynęło na poradnię wiele nowych - zaległych - spraw. Czy możesz proszę sprawdzić, czy teraz też ma coś takiego miejsce? W razie dalszych pytań, pozostaję w kontakcie. Karolina

**Comment by ad-m** [comment]
> Czy możesz proszę sprawdzić, czy teraz też ma coś takiego miejsce?

Zweryfikowałem to wcześniej. Wówczas problem dotyczył wszystkich wiadomości e-mailowych, a na wykresie widać, że wiadomości e-mailowe działają.

**Comment by KarolaJ** [comment]
Do zamknięcia.
