### ISSUE TITLE
Punktacja na poradni

### ISSUE THREAD

**Issue by KarolaJ** [watchdogpolska/poradnia#1159]
Dzień dobry,

w wielu sprawach, gdy Klient, bądź ja podaję swoje zdania w punktach, to każdy kolejny punkt po wysłaniu już wiadomości do Zespołu (albo do wszystkich, gdy pisze to Klient), wyświetla się jako punkt numer 1. Tutaj przykład: https://porady.siecobywatelska.pl/sprawy/sprawa-13783/ - moja ostatnia wiadomość do Zespołu. 

Czy można to jakoś naprawić, tak aby wyświetlały się punkty np. od 1 do 7, a nie siedem jedynek?

Mam również informację od Szymona D., że przycisk enter nie działa. Szymon D. robi akapity z odstępami, a po wysłaniu wiadomości już ich nie ma, nie są widoczne. Czy tutaj można również jakoś zadziałać?

Dziękuję,

Karolina

**Comment by AgnieszkaZdanowicz** [comment]
ja nie widzę w tym akurat wątku na poradni, żeby było siedem jedynek, ale może chodziło o to, co wyświetla się w mailu w programie pocztowym? w każdym razie pytanie do @PiotrIw - czy nowy edytor tekstu rozwiąże ten problem?

**Comment by PiotrIw** [comment]
poprawione w wersji 1.1.5
