### ISSUE TITLE
PILNA SPRAWA #13850

### ISSUE THREAD

**Issue by KarolaJ** [watchdogpolska/poradnia#1160]
Dzień dobry,

dzisiaj od rana na moim e-mailu jest ponad 995 e-maili, głównie informacja z poradni o sprawie #13850 z 15 maja. To prawdopodobnie to samo, co ostatnio się zadziało w związku ze sprawą #1148. Poproszę o pomoc. Czy mam komuś zgłosić Adamie, że potrzebujesz wsparcia programisty w tej kwestii? 

Dziękuję, 

Karolina

**Comment by KarolaJ** [comment]
Dzień dobry,

przypominam o problemie. Dzisiaj po raz kolejny na mojej skrzynce około 100 e-maili. Tym razem prawdopodobnie związanych ze sprawą #13876. Za każdym razem w adresie e-mailowym znajduje się słowo: "_zemlyanov_". Na początku tygodnia ten sam bałagan zrobiła sprawa #13857, a w weekend #13850. Nie usunęłam ich z poradni, abyście mieli możliwość sprawdzenia. 

Proszę o wsparcie. 

Dziękuję,

Karolina

**Comment by ad-m** [comment]
Dodałem filtr na Zenbox na wiadomości od "Postmaster". Wierzę, że to pomoże.

**Comment by KarolaJ** [comment]
Szanowny Adamie,

jesteś the best! Dziękuję.

Karolina
