### ISSUE TITLE
#13850

### ISSUE THREAD

**Issue by KarolaJ** [watchdogpolska/poradnia#1162]
Dzień dobry,

proszę o usunięcie sprawy #13850. Nie mogę tego zrobić samodzielnie, bo coś się tnie, gdy próbuję.

Dziękuję,

Karolina

**Comment by mrbojko** [comment]
Sprawa usunięta. 
Dla potomności: przyczyną błędów 404 i 504 było ustawienie wartości timeout na gunicorn. Na potrzeby tego usunięcia zmieniłem ręcznie wartość timeout na 300 sekund, wystarczyło około 200.

**Comment by KarolaJ** [comment]
Dzięki!
