### ISSUE TITLE
PILNE! BRAK POWIADOMIEŃ Z PORADNI

### ISSUE THREAD

**Issue by KarolaJ** [watchdogpolska/poradnia#1163]
Dzień dobry,

wczoraj i dzisiaj rano członkowie Zespołu poradni zaczęli mi zgłaszać, że nie przychodzą im powiadomienia o sprawach. Mi również przestały dochodzić. Bardzo proszę o pilną pomoc w tej sprawie, aby nie umknęła nam żadna sprawa i termin. Proszę o sprawdzenie dlaczego nie dochodzą wiadomości informujące o nowej sprawie, akceptacji sprawy i wysłaniu wiadomości. 

Dziękuję,

Karolina

**Comment by KarolaJ** [comment]
Adam, 

czy to oznacza, że Klienci nie otrzymywali żadnych e-maili? Czy jesteś w stanie sprawdzić od kiedy? 

I czy tutaj ja mam coś autoryzować:
https://porady.siecobywatelska.pl/sprawy/sprawa-13978/

Dziękuję,

Karolina

**Comment by AgnieszkaZdanowicz** [comment]
tu znowu nie jestem w stanie ocenić, czy to jest jakiś błąd systemy, któremu warto się przyjrzeć, czy jednorazowy problem i sprawę można zamknąć. @mrbojko i @PiotrIw zostawiam Wam do oceny

**Comment by PiotrIw** [comment]
błąd prawdopodobnie chwilowy - nie występuje obecnie
