### ISSUE TITLE
Obraz wyróżniający dla strony poradni

### ISSUE THREAD

**Issue by JoannaGucman** [watchdogpolska/poradnia#1169]
Czy da się wgrać/zaszyć w stronie obraz wyróżniający, żeby po włożeniu gdzieś linka wyskakiwało rozszerzenie z obrazkiem?

**Comment by mrbojko** [comment]
![obraz](https://user-images.githubusercontent.com/47541542/185024934-ecac0f1d-900e-41f5-ada2-aa7b52401c2a.png)
