### ISSUE TITLE
prośba o sprawdzenie, czy dochodzą maile na skrzynkę porady@

### ISSUE THREAD

**Issue by AgnieszkaZdanowicz** [watchdogpolska/poradnia#1177]
@mrbojko, czy możesz spojrzeć na serwer, czy nam się znowu coś nie zapchało? Klient zgłosił, że maile na porady@siecobywatelska.pl nie dochodzą. Widzę, że w niektórych sprawach klienci do nas piszą i te wiadomości dochodzą, ale może to od tych, którzy piszą po zalogowaniu się do poradni, a nie przez maila? Zrobiłam test, wysłałam na poradnię maila ok. 11:00 i nie ma go na poradni ani nie dostałam potwierdzenia założenia sprawy.

**Comment by mrbojko** [comment]
@AgnieszkaZdanowicz faktycznie maile nie dochodziły. Przyczyną było wyczerpanie miejsca na dysku wirtualnej maszyny app-prod. Zwiększyłem rozmiar dysku, po restarcie obsługa maili ruszyła jak dawniej. Problem można uznać za rozwiązany.

**Comment by AgnieszkaZdanowicz** [comment]
@mrbojko dzięki, to zamykam

**Comment by AgnieszkaZdanowicz** [comment]
@mrbojko klient znowu zgłasza ten sam problem - spojrzysz?

**Comment by mrbojko** [comment]
@AgnieszkaZdanowicz przepchałem, tym razem helper, wywaliły się wszystkie kontenery, to wymaga dodatkowego śledztwa, nie zamykaj na razie wątku...

**Comment by AgnieszkaZdanowicz** [comment]
@mrbojko ok, dzięki!

**Comment by AgnieszkaZdanowicz** [comment]
@mrbojko dostaliśmy zgłoszenie, że skrzynka porady@ odbija maile:

<html>
<body>
<br class="Apple-interchange-newline">

Nie dostarczono w całości
--
Podczas próby dostarczenia wiadomości na adres porady@siecobywatelska.pl wystąpił tymczasowy problem. Gmail będzie próbował wysyłać wiadomość jeszcze przez pewien czas (23 godz.), a następnie zarzuci próby.


</body>
</html>

**Comment by AgnieszkaZdanowicz** [comment]
tutaj nie wiem, czy zamykać - co jakiś czas jednak coś tam się blokuje. To już pozostawiam Wam, @mrbojko i @PiotrIw do oceny, czy to do zamknięcia, bo problem rozwiązany
