### ISSUE TITLE
Zrobiłam regulamin ale nie wiem co dalej

### ISSUE THREAD

**Issue by KatarzynaBatko** [watchdogpolska/poradnia#118]
https://github.com/watchdogpolska/poradnia/wiki/Regulamin-poradnictwa

**Comment by ad-m** [comment]
Wprowadze go i nakram z tego film.

**Comment by ad-m** [comment]
nagram*

**Comment by ad-m** [comment]
https://youtu.be/mJwsxzRxBxs

**Comment by ad-m** [comment]
https://youtu.be/7pCeEWB-L9U
