### ISSUE TITLE
Poradnia - rejestrowanie porad/tagowanie

### ISSUE THREAD

**Issue by KarolaJ** [watchdogpolska/poradnia#1187]
Dzień dobry,

w sprawie #14794 na Poradni nie ma możliwości edytowania porady - Dane Metrykalne. W chwili, gdy klikamy na poradę - wyświetla się strona: Page Not found. Uprzejmie proszę o informację dlaczego tak się dzieje, i wsparcie techniczne poprzez ustawienie możliwości edytowania porady, dodania TAGÓW do sprawy.

Dziękuję,

Karolina

**Comment by PiotrIw** [comment]
Ta porada ma zmieniony znacznik "Widoczne" na 0 więc nie jest pokazywana. Zmieniłem na 1 więc już można jąoglądać/edytować. Mylący jest komunikat "Page not found". Nie ma historii aktywności więc nie wiadomo kto i kiedy zmienił :(

@AgnieszkaZdanowicz @KarolaJ Zmienić komunikat dla ukrytych porad na np. "Porada ukryta"? zamiast "Page not found"?

**Comment by AgnieszkaZdanowicz** [comment]
hm... a jak się w ogóle ukrywa porady? To było zmienione w panelu administracyjnym, tak?
