### ISSUE TITLE
Czy przy rejestracji i wysłaniu nowej sprawy nie powinna pojawić sie formuła o zgodzie 

### ISSUE THREAD

**Issue by KatarzynaBatko** [watchdogpolska/poradnia#119]
na przetwarzanie i polityce prywatanosci?

**Comment by ad-m** [comment]
Mamy jeszcze zgloszenie przes sam e-mail....

**Comment by KatarzynaBatko** [comment]
Ale generalnie sądzisz, że powinniśmy? Bo moze nie musimy i wtedy nie ma o czym rozmawiać. Ale jesli musimy, to na e--mail może trzeba coś wymyślić

**Comment by ad-m** [comment]
Myślę, że zrobimy to na stronie (przy nowej sprawie przez usera, przez
Zespół (będą pytać) i przy rejestracji). Przy e-mailach GIODO nie pyta o
zgodę, a też ma system...

Wysłano z urządzenia mobilnego.
25 lip 2015 22:11 "KatarzynaBatko" <notifications@github.com> napisał(a):

**Comment by ad-m** [comment]
Uzgodniona treść zgody:
> Akceptuję Politykę Prywatności i wyrażam zgodę na przetwarzanie moich danych osobowych w rozumieniu ustawy o ochronie danych osobowych z 29 sierpnia 1997 r. przez Sieć Obywatelską Watchdog Polska z siedzibą w Warszawie, ul. Ursynowska 22/2 w celu świadczenia określonego Regulaminem Poradnictwa.
