### ISSUE TITLE
Pasek z boku

### ISSUE THREAD

**Issue by KatarzynaBatko** [watchdogpolska/poradnia#120]
To może poprawmy lekko, dajmy wyraz poradnia i zastanawiam się czy nowa sprawa powinna pojawiać się pod wyrazem archiwum. Może tak:

Poradnia Sieci Obywatelskiej Watchdog Polska

Zgłoszenia:
- nowa sprawa
- regulamin poradnictwa

Dopiero po zalogowaniu:

Archiwmum:
- wykaz spraw 
itp.

**Comment by ad-m** [comment]
A może tylko zamiast "Archiwum" wpiszemy "Sprawy"?

**Comment by KatarzynaBatko** [comment]
Pewnie
