### ISSUE TITLE
Jak wymusić czytanie regulaminu? 

### ISSUE THREAD

**Issue by KatarzynaBatko** [watchdogpolska/poradnia#121]
Bo tam jest wiele rzeczy, które wyjaśniają. Nie warto chyba dawać konieczności akceptaccji, ale może zachęcić. Albo może w mailu potwierdzającym dodać te fragmenty - co sądzicie?

Standardowy termin odpowiedzi wynosi do 10 dni. Otrzymujemy bardzo wiele zapytań i nasz system organizacji pracy wymaga współpracy i zrozumienia ze strony użytkowników/użytkowniczek. Dlatego prosimy o nieprzesyłanie dodatkowych maili na znane Państwu osobiste maile prawników, niezgłaszanie pytań przez komunikatory i niedzwonienie w sprawie przyspieszenia prac, o ile to nie jest bezwzględnie konieczne. Każda taka interwencja odrywa prawników i prawniczki od pracy na rzecz innych osób i utrudnia dotrzymywanie terminów. 

Prosimy też o jak najwcześniejsze informowanie o otrzymywanej z sądu korespondencji i nieczekanie do ostatniego momentu. W przypadku zgłoszenia konieczności złożenia odwołania, wniosku o ponowne rozpatrzenie sprawy, skargi lub skargi kasacyjnej na dzień przed upływem terminu, nie będziemy w stanie Państwu pomóc.

**Comment by ad-m** [comment]
Myślę, że można w wiadomościach dodać najistotniejsze oraz nad formularzem dodawania sprawy. Już pracuje nad dodaniem edycji komunikatu nad formularzem dodawania sprawy.

**Comment by KatarzynaBatko** [comment]
ok. to czekam

**Comment by ad-m** [comment]
Na https://github.com/watchdogpolska/poradnia/blob/master/poradnia/cases/templates/cases/email/case_registered.txt są już raz zapisane najistotniejsze rzeczy. Myślisz, że należy to rozwinąć o to co powyżej?

**Comment by KatarzynaBatko** [comment]
nie, niech będzie tak
odsyla do regulaminu
