### ISSUE TITLE
umożliwienie przeszukiwania treści spraw (wiadomości przychodzących i wychodzących)

### ISSUE THREAD

**Issue by AgnieszkaZdanowicz** [watchdogpolska/poradnia#1219]
@PiotrIw miałam zrobić nowe issue na temat, który poruszyliśmy na spotkaniu. Chodzi o wprowadzenie przeszukiwania treści wiadomości przychodzących i wychodzących na poradni. Bo tytuły ludzie różne wpisują, a czasem pamiętamy, że ktoś napisał coś specyficznego w jakiejś wiadomości (ja tak na gmailu często szukam), ale w tej chwili nie ma opcji przeszukiwania po tych treściach. To by nam bardzo ułatwiło pracę.

**Comment by PiotrIw** [comment]
@AgnieszkaZdanowicz  
Przeszukiwanie jednoczesne spraw i korespondencji to bardzij skomplikowany temat (też do zrobienia) jak mówiłem na spotkaniu. Na szybko (2-3dni) mogę zrobić tabelę korespondencji z opcją wyszukiwania w treści maila, a w osobnych kolumnach w tytule sprawy, tytule porady i komentarzu porady lub generalny search we wszystkich kolumnach (muszę sprawdzić czy jest i czy działa w bootstrap 3). Ostrzegam że taka tabela może być dość powolna przy ok 60 tys maili w bazie :)
Pomoże?

**Comment by AgnieszkaZdanowicz** [comment]
@PiotrIw to spróbujmy tak, jak proponujesz :) Chyba najważniejsze, żeby przeszukiwało w treści maila i żeby z tego maila dało się przejść do konkretnej sprawy. Tylko zastanawiam się, jak to będzie działało dla osób, które widzą tylko sprawy, które mają przypisane. Czy one będą miały dostęp tylko do tych maili ze spraw, które mają przypisane? Tak powinno być, bo specjalnie, ze względu na ochronę danych klientów poradni, tylko niektóre osoby mają dostęp do wszystkiego. Większość jednak widzi tylko przypisane sprawy.

**Comment by PiotrIw** [comment]
@AgnieszkaZdanowicz 
OK, robię. Dzięki że zaznaczyłaś o widoczności spraw. Zrobię z mailami tak samo :)
