### ISSUE TITLE
dodatkowe komunikaty, kolor pól

### ISSUE THREAD

**Issue by KatarzynaBatko** [watchdogpolska/poradnia#123]
ten komunikat przyszedł do mnie na zielonym polu, inny (w innym miejscu) na różowym. Proponuję ujednolicić, ale nie na zielony. Nie pasuje. Albo róż albo najleiej szary, z czerwonymi literkami.

Konto user-11 utworzone! Hasło otrzymasz na adres e-mail. Zaloguj się, aby uzyskać dostęp do archiwum.

**Comment by ad-m** [comment]
Bledy sa czerwone, sukces zielony, informacje niebieskie.

**Comment by KatarzynaBatko** [comment]
a, ok. choć ten zielony niezbyt pasuje etstetycznie. Ale nie będę się czepiać skoro jest w tym logika.

**Comment by ad-m** [comment]
Ja na kolorach się nie znam. @mik-laj też podobno nie. @Krzysiu ?
