### ISSUE TITLE
Wydarzenia na poradni

### ISSUE THREAD

**Issue by KarolaJ** [watchdogpolska/poradnia#1244]
@PiotrIw w tej sprawie: https://porady.siecobywatelska.pl/sprawy/sprawa-15227/#event-1939 , pomimo że jakiś czas temu ustawiłam termin na "false" to nadal mi system przypomina o terminie. Można coś z tym zrobić? Tak się dzieje w innych sprawach też. 

Karolina

**Comment by PiotrIw** [comment]
@KarolaJ w wersji 1.1.8 dodałem na wydarzeniu flagę Zakończone, jeśli jest odznaczona to przypomnienia nie przychodzą

**Comment by KarolaJ** [comment]
@PiotrIw  super. Dziękuję
