### ISSUE TITLE
Poprawki w poradach. 

### ISSUE THREAD

**Issue by KarolaJ** [watchdogpolska/poradnia#1249]
Członkowie Zespołu zgłaszają problemy na poradni: nie zapisują się wprowadzone przez nich zmiany we wiadomościach do Klientów. Szymon D. miał taki problem np. przed chwilą w sprawie 15315, wcześniej Piotr R. w sprawie 14088. 

Karolina

**Comment by KarolaJ** [comment]
@PiotrIw  mi teraz w tej sprawie https://porady.siecobywatelska.pl/sprawy/sprawa-15329/ też nie wprowadziły się poprawki w wiadomości do Zespołu (niebieskiej).

**Comment by PiotrIw** [comment]
@KarolaJ w wersji 1.1.9 (na produkcji), dodałem edytor HTML z formatowaniem, który obsługuje wiadomości napisane w HTML
