### ISSUE TITLE
Uzupełnić opis sekcji edycyjnych

### ISSUE THREAD

**Issue by ad-m** [watchdogpolska/poradnia#125]
https://github.com/watchdogpolska/poradnia/wiki/Sekcje-edycyjne

**Comment by AgnieszkaZdanowicz** [comment]
nie chce mnie chyba wpuścić do tego linka, więc nie potrafię dojść, o co tu chodzi. @ad-m czy to aktualne?

**Comment by ad-m** [comment]
Treść przeniesiona na https://poradnia.readthedocs.io/modules/tinycontent.html#zdefiniowane-sekcje i tam wykonana.
