### ISSUE TITLE
Edycja wiadomości z historii sprawy - kopia z historii maili

### ISSUE THREAD

**Issue by PiotrIw** [watchdogpolska/poradnia#1262]
Pracując nad edytorem wiadomości istniejących w sprawie (ikona i link edytuj pod każdą wiadomością w lewym panelu sprawy) zweryfikowałem cały mechanizm, który za tym stoi:

Po aktualizacji (dotyczy sprawa zarejestrowana na portalu, mail przychodzący, wychodzący lub komunikat do zespołu) treść wiadomości jest aktualizowana w bazie i informacja o aktualizacji jest wysyłana mailem wyłącznie do osób zaangażowanych z zespołu SO.

Taka edycja ma sens jedynie w przypadku komunikatów do zespołu w przypadku każdej innej kategorii wyłącznie wprowadza zamieszanie:

    w przypadku edycji maili przychodzących (sic!) i spraw zarejestrowanych na portalu przez klienta, my widzimy zmienioną treść ale klient nic o tym nie wie, rzeczywisty mail pozostaje bez zmiany, eml (plik źródłowy maila ) w bazie też bez zmiany (no bo jak odbiorca miałby zmieniać treść maila odebranego ????)
    w przypadku maili wychodzących podobnie, tj zespół dostaje informację o zmianie pisma ale taka zmiana nie jest wysyłana do klienta w postaci stosownego aktualizującego maila, więc wydaje nam się że coś poprawiliśmy (np błąd w mailu wychodzącym) ale ta poprawka pozostaje wyłącznie w naszej szufladce....

Nie wiem jak często taka edycja jest wykorzystywana, jednak zanim ją uporządkuję proponuję wyłączyć możliwość edycji na stałe (bo jak moglibyśmy edytować coś co z definicji nie jest edytowalne) w :

    sprawach zarejestrowana na portalu przez klienta (tu można się zastanowić czy dać możliwość edycji klientowi, jak jednak bym optował żeby dopisywał kolejny komunikat z aktualizacją informacji - będziemy mieć wówczas historię zmian)
    mailach przychodzących

Wyłączyć edycję czasowo dopóki nie poprawię mechanizmu wysyłania maili aktualizacyjnych w:

    mailach wychodzących (tu nie można zmieniać treści maila który już został wysłany lecz wysłać maila z aktualizacją i aktualizowanym poniżej)

Link edycji pozostawiłbym jedynie w komunikatach do zespołu bo tu ma sens i działa zgodnie z logiką.

**Comment by PiotrIw** [comment]
... Jak została wysłana do Klienta to też warto, aby "Edytuj" było, bo czasem my sami dla siebie chcemy dodać jakąś notatkę w tej wysłanej już wiadomości. I tutaj pytanie, czy wtedy taką aktualizację w wysłanej już wiadomości Klient otrzymuje, czy nie? Z tego co napisałeś to rozumiem, że nie....

Nie dostaje
Notatkę do wysłanej proponuję zapisywać w wiadomości do zespołu z linkiem w treści jn:
image.png

A w wysłanych bym wyłączył mozliwość edycji i kasowania bo klient już dostał a jak zmienimy lub usuniemy ze sprawy to się pojawią rozbieżności w stanowiskach naszym i klienta, poprawki bym proponował wysyłać jako nowe wiadomości (łatwo teraz skopiować) lub zamiast Edytuj zmieniłbym link na "Zrób korektę" który by generował nową wiadomość ze starą w cytacie pod spodem. Podobnie jak robi "przekaż dalej" w skrzynkach mailowych.

**Comment by PiotrIw** [comment]
Ok, tak zróbmy.

Pozdrawiam
Karolina Jankowska

**Comment by PiotrIw** [comment]
.. jako nowe wiadomości (łatwo teraz skopiować)  - nic nie trzeba robić

czy

.. zamiast Edytuj zmieniłbym link na "Zrób korektę" który by generował nową wiadomość ze starą w cytacie pod spodem - to zupełnie nowy formularz, view i obsługa, testy, czyli tak 3-5 dni pracy maks

? Pozdrawiam
P

**Comment by PiotrIw** [comment]
Ja bym wołała na "Zrób korektę" , ale ze względu na dużą ilość Twojej pracy przy takim rozwiązaniu, tutaj decyzję zostawiam Agnieszce Z. 

Pozdrawiam
Karolina Jankowska

**Comment by AgnieszkaZdanowicz** [comment]
pogadałam z Piotrkiem i Szymonem, że nie robią żadnych zmian na wysłanych poradach, ewentualnie w razie błędu wysyłają po prostu kolejną wiadomość z wyjaśnieniem. A notatki robimy w opcji "napisz do zespołu". I widzę, że już w ogóle opcja edycji wysłanych wiadomości jest skasowana. Więc zamykam wątek.
