### ISSUE TITLE
Terminy na poradni

### ISSUE THREAD

**Issue by KarolaJ** [watchdogpolska/poradnia#1269]
W tej sprawie: https://porady.siecobywatelska.pl/sprawy/sprawa-15239/#event-1945 , nadal mi przychodzi e-mial o terminie, pomimo, że wcześniej oznaczyłam "Termin - nie" i że termin został ukończony/nie ma więcej przypomnień. 

Proszę o sprawdzenie.

**Comment by AgnieszkaZdanowicz** [comment]
Potwierdzam, ja właśnie dostałam przypomnienia w sprawie testowej: https://porady.siecobywatelska.pl/sprawy/sprawa-8646/#event-1953

**Comment by PiotrIw** [comment]
@AgnieszkaZdanowicz @KarolaJ - zróbcie mi, proszę forward tych maili z powiadomieniami ze spraw "sprawa-15239/#event-1945" oraz "sprawa-8646/#event-1953"

**Comment by AgnieszkaZdanowicz** [comment]
@PiotrIw zrobione w sprawie 8646

**Comment by PiotrIw** [comment]
@KarolaJ @AgnieszkaZdanowicz - sprawdziłem wszystkie scenariusze i działają poprawnie. Dodałem dodatkowe logi, prosze o info jak przyjdą powiadomienia pomimo ustawinie znacznika "Wykonane - tak"
