### ISSUE TITLE
Kolorystyka spraw na poradni

### ISSUE THREAD

**Issue by KarolaJ** [watchdogpolska/poradnia#1270]
@PiotrI jak wchodzę na niektóre sprawy to mają inną kolorystykę niż standardowo, np. tutaj: https://porady.siecobywatelska.pl/sprawy/sprawa-15371/#letter-78027

Czy Tobie też tak to się wyświetla? Napisy na ostry niebieski? Czy to jest jakiś błąd?

Karolina

**Comment by piotri** [comment]
@PiotrIw  ;)

**Comment by KarolaJ** [comment]
@PiotrIw aaaa, ok :)

**Comment by PiotrIw** [comment]
efekt "wstrzykiwania" styli z maili pisanych w outlooku MS. Porawione w wersji 1.1.13, dodany sanitizer html
