### ISSUE TITLE
Involved staff/osoba przypisana

### ISSUE THREAD

**Issue by KarolaJ** [watchdogpolska/poradnia#1271]
Cześć,

w "Wykazie spraw" była możliwość wyszukania spraw tylko jednej osoby przypisanej do sprawy. Teraz w tabelce "Involved staff" nie ma możliwości poniżej wpisania imienia albo nazwiska jednego członka Zespołu, aby wyświetliły się sprawy tylko tej osoby. Nie ma też takiej możliwości w ramce "Szukaj". @PiotrI możesz proszę wprowadzić taką możliwość? Jest to bardzo ważne dla mojej pracy jako koordynatorki. Najlepiej też, aby wysuwała się lista członków Zespołu, tak jak było poprzednio - ułatwia to sprawdzenie wykazu osób.

**Comment by PiotrIw** [comment]
zaimplementowane w wersji 1.1.12
@KarolaJ - ze względu nastrukturę danych to jest filtr obok tabeli ale działa jak potrzebujesz :)

**Comment by KarolaJ** [comment]
@PiotrIw super, bardzo dziękuję :)
