### ISSUE TITLE
Rejestr porad/Tabela porad

### ISSUE THREAD

**Issue by KarolaJ** [watchdogpolska/poradnia#1272]
@PiotrIw obecnie w Tabeli porad nie wyskakują ustawione hasła do tabelek: ""Problemy z zakresu prawa do informacji", "Zakresy tematyczne zapytania", "Rodzaj osoby, która się zgłasza o poradę", "Rodzaj podmiotu zobowiązanego", "Gmina" - czy możemy je proszę dodać? Nie pamiętamy wszystkich ustawionych haseł, a po nich się szuka, więc to ułatwi pracę na poradni. Czy tam, gdzie jest obecnie w "Tabeli porad" miejsce na wpisanie czegoś "...", to czy może się dodatkowo też lista haseł wyświetlać? 

@AgnieszkaZ czy to ok dla Ciebie?

Karolina

**Comment by PiotrIw** [comment]
zaimplementowane w v1.1.12
@KarolaJ - w nagłówkach kolumn może być albo opcja wybowu albo wyszukiwanie po wpisywaniu znaków (wyszukuje podobne). Dodałem filtry wyboru za wyjątkiem jednostki terytorialnej , bo tam by była lista ok 900 pozycji, więc lepiej wpisywać część nazwy, i sprawdać co się wybrało w tabeli
