### ISSUE TITLE
Link do polityki prywatności na poradni

### ISSUE THREAD

**Issue by Roksana90** [watchdogpolska/poradnia#1297]
![image](https://github.com/watchdogpolska/poradnia/assets/16541446/0a07fc4f-1a27-4c46-b16b-66ca86e11ecd)
Hej, zauważyłam, a Karolina się ze mną zgadza, że w tym miejscu https://porady.siecobywatelska.pl/konta/signup/, gdzie zaznaczamy Akceptację Polityki Prywatności mogłaby by być ona podlinkowana: https://siecobywatelska.pl/polityka-prywatnosci/

**Comment by PiotrIw** [comment]
zaimplementowane v1.1.21

**Comment by Roksana90** [comment]
dzięki!
