### ISSUE TITLE
Wiadomości wysyłane do "Wszystkich" po naciśnięciu do "Zespołu". 

### ISSUE THREAD

**Issue by KarolaJ** [watchdogpolska/poradnia#1299]
@PiotrIw ,

w dwóch sprawach członek Zespołu poradni Szymon D. po napisaniu wiadomości nacisnąć "Do Zespołu", a wiadomość została wysłana do wszystkich, przez co widzi ją również Klient. To te dwie wiadomości, każda w innej sprawie:

https://porady.siecobywatelska.pl/sprawy/sprawa-15444/#letter-78776

https://porady.siecobywatelska.pl/sprawy/sprawa-14060/#letter-78798

Czy możesz pilnie coś poradzić, aby się tak nie działo, bo to dość niebezpieczne dla Nas. 

Pozdrawiam,

Karolina

**Comment by PiotrIw** [comment]
@KarolaJ - prześledziłem teama
Wszystkie trzy wiadomości mają podobną historię (w załączniku). Otóż nie powstały w wyniku wpisania tekstu w formularzu poradni i naciśnięciu prycisku "Napis do Zespołu" lecz w wyniku odpisania na maila z powiadomieniem z poradni (jeden screen z zenboxa poniżej). Obecnie poradnia nie ma logiki różnicującej przychodzące maile w sprawie i traktuje je tak samo, powiadamiając wszystkich, również klienta. Funkcjonalność przyjmowania mail ograniczonych tylko do zespołu trzeba/można dodać.
![image](https://github.com/watchdogpolska/poradnia/assets/36678620/e7410cc1-532b-4287-bc07-9055f982593f)

**Comment by KarolaJ** [comment]
@PiotrIw rozumiem, wszystko jasne. Skonsultuję sprawę z Szymonem.

**Comment by KarolaJ** [comment]
@PiotrIw tak, rozmawiałam z Szymonem D. i okazało się, że jednak musiał odpisać bezpośrednio z e-maila, a nie wciskając przycick "Napisz do Zespołu". Dzięki za prześledzenie sprawy.
