### ISSUE TITLE
dodanie adresu w nagłówku do Nowej sprawy. Poproszę o poprawke jednego zdania

### ISSUE THREAD

**Issue by KatarzynaBatko** [watchdogpolska/poradnia#130]
Witamy w elektronicznym systemie poradnictwa Sieci Obywatelskiej Watchdog Polska. Tu możesz opisać swój problem lub wysłać e-mail na adres: porady@siecobywatelska.pl.

**Comment by ad-m** [comment]
Wdrożone na produkcji.
