### ISSUE TITLE
prośba o sprawdzenie/usunięcie zakładki "klucze" w polu edycji użytkownika

### ISSUE THREAD

**Issue by AgnieszkaZdanowicz** [watchdogpolska/poradnia#1307]
@PiotrIw czy Ty jesteś w stanie sprawdzić, co się robi w zakładce "klucze"?

Ona się pojawia, kiedy po zalogowaniu klika się w nazwę swojego użytkownika i tam jest kilka przycisków, w tym "klucze":

![image](https://github.com/watchdogpolska/poradnia/assets/36925935/11e64a38-5e41-44e6-9c4f-23c76e4fe0d3)

Nikt z nas nigdy z niej nie korzystał i najchętniej byśmy ją usunęli, chyba że on robi jakąś magię. Jedyne co znalazłam na github, to klucze związane z kalendarzem, ale nie wiem, jak by to miało działać.

**Comment by PiotrIw** [comment]
@AgnieszkaZdanowicz klucze służa do dostępu dla uprawnionych użytkowników przez API. Opis:
https://github.com/watchdogpolska/poradnia/blob/master/docs/modules/keys.rst
Rozwiazanie bezpieczne ale niewykorzystywane, bo chyba nie ma żadnej aplikacji, która by korzystała z poradni. Może zaktualizuję link do helpu i lepiej opisze przycisk np. "Klucze API" ?

**Comment by AgnieszkaZdanowicz** [comment]
@PiotrIw a możesz mi napisać, jak to może być przez nas w praktyce wykorzystywane? Bo kojarzy mi się, że z API mogłoby korzystać bi.siecobywatelska.pl? Wiesz, że my mamy takie narzędzie?

**Comment by PiotrIw** [comment]
wyłączyłem w adminie edycję i dodawanie oraz ukryłem wartość klucza dla nie właściciela - dobre praktyki bezpieczeństwa

**Comment by PiotrIw** [comment]
zaimplementowane v1.1.17
do poprawienia błędny link na klawiszu "?Pomoc"

**Comment by PiotrIw** [comment]
poprawione v1.1.18
