### ISSUE TITLE
prośba o zmiany w wykazie użytkowników

### ISSUE THREAD

**Issue by AgnieszkaZdanowicz** [watchdogpolska/poradnia#1308]
@PiotrIw Od razu uprzedzę, że to jest trudne do wyjaśnienia i pewnie będą potrzebne jakieś pytania z Twojej strony :)

Chodzi o widok Wykazu użytkowników, ale zarówno po zalogowaniu osoby będącej superużytkownikiem, jak i zwykłym użytkownikiem będącym członkiem zespołu (ci, którzy w panelu zarządzania mają zaklikane "w zespole").

Zacznijmy od  **superużytkownika.**

W tej chwili superużytkonicy widzą takie kolumny:

![image](https://github.com/watchdogpolska/poradnia/assets/36925935/85f78594-4643-49c8-89d5-db5a0eee2f77)

I te nagłówki są nieaktualne, bo zmieniliśmy statusy spraw w pewnym momencie (teraz są wolne, moderowane, przypisane, zamknięte), a nie zaktualizowaliśmy tej tabeli.

Co jest do zrobienia:

- usunięcie kolumny "wolne", bo wolne sprawy to te, które nie są przypisane do nikogo, więc tam zawsze wartość będzie "0"
- widoczne powinny być kolumny: moderowane, przypisane, zamknięte. 
                  - W tej chwili kolumna "aktywne" liczy tylko sprawy "przypisane" - więc wystarczy jej zmienić nazwę na "przypisane"
                  - kolumna zamknięte jest ok
                  - trzeba dodać kolumnę "moderowane", bo to jest nowy status i nigdzie się nie zlicza chyba 

A teraz **zwykli użytkownicy**, którzy mają status "w zespole" (bo inni zwykli użytkownicy w ogóle nie widzą wykazu użytkowników w swoim menu i to jest ok)

Zwykli użytkownicy będący w zespole widzą w wykazie użytkowników tylko inne osoby z zespołu i to jest ok, natomiast przy tych osobach z zespołu widzą tylko licznik ich spraw jako klientów:

![image](https://github.com/watchdogpolska/poradnia/assets/36925935/9c0884b9-f561-478f-8695-27ce2265af90)

A chcielibyśmy, żeby widzieli te wszystkie kolumny, które widzą superużytkownicy - ale nadal tylko dotyczące innych członków zespołu.

I pytanie dodatkowe co do zwykłych użytkowników - czy jesteś w stanie stwierdzić, czemu oni widzą jedną osobę spoza członków zespołu? Dane tej osoby mogę Ci podesłać mailem, gdybyś nie mógł namierzyć, o kogo mi chodzi.

**Comment by PiotrIw** [comment]
zaimplementowane v1.1.21

**Comment by AgnieszkaZdanowicz** [comment]
@PiotrIw czy my nie rozmawialiśmy o wprowadzeniu opcji wyszukiwania użytkowników i sortowania? Mogliśmy rozmawiać i uznać, że to jednak za dużo roboty, ale niestety nie robiłam notatek, więc mam tylko takie przebłyski. Wolę się upewnić, stąd pytanie :) I jeszcze mówiłeś coś o takim rozwiązaniu, żeby dało się skasować w miarę łatwo i masowo użytkowników "spamowych", którzy nie mają nawet jednej sprawy zarejestrowanej. Czy na to trzeba założyć nowy issue?

**Comment by PiotrIw** [comment]
Filtr do kasowania użytkowników ze SPAMu jest w adminie. Jak projektowałem tabelę użytkowników to doszedłem użytkowników do wniosku że ona nie będzie bardziej użyteczna niż to co jest tylko inna i zaniechałem - tam jest niezbyt wiele danych do prezentacji. Zakładka ze wszystkimi uzytkownikami ma w ogóle mały sens, bo nawet po skasowaniu spamu to będzie lista pond 2000 użytkowników z pojedynczymi sprawami, a wyszukiwanie/filtrowanie ich po nazwie nic nie daje. Lepiej odfiltrowac sprawy użytkownika w tabeli spraw :) Dlatego tylko poprawiłem to co zgodnie z pierwotnym issue.
