### ISSUE TITLE
link w menu "panel administracyjny"

### ISSUE THREAD

**Issue by AgnieszkaZdanowicz** [watchdogpolska/poradnia#1309]
@PiotrIw zastanawiam się, czy byłaby możliwość, żeby osoby, które nie mają statusu "superużytkownika", nie widziały w menu przycisku "panel administracyjny"? Bo i tak jak go klikną, to mają informację, że "Nie masz uprawnień do oglądania ani edycji niczego"

![image](https://github.com/watchdogpolska/poradnia/assets/36925935/4fea8496-6090-49f0-a8fc-a6a767ef3dc2)

**Comment by PiotrIw** [comment]
zaimplementowane v1.1.17
