### ISSUE TITLE
nie działa automatyczna informacja po przesłąniu na porady

### ISSUE THREAD

**Issue by KatarzynaBatko** [watchdogpolska/poradnia#131]
Wygląda na to, że nie działa mailowe zgłaszanie porad. Nie wiem czy ja czegoś nie zepsułam, poniewaz nie zauważylam aliasu i dodałam głupio ten adres do maili, ale potem się zorientowałam w błędzie i wykasowałam. Nie sądzę, żeby to wpłynęło, ale pisze Ci na wszelki wypadek. 

Wydaje mi się, że dawno nie sprawdzaliśmy zgłaszania przez maila po prostu.

**Comment by ad-m** [comment]
Wdrożone na produkcji.
