### ISSUE TITLE
prośba o zmianę w menu "rejestr porad" i "tabela porad" na "rejestr tagów" i "tabela tagów"

### ISSUE THREAD

**Issue by AgnieszkaZdanowicz** [watchdogpolska/poradnia#1310]
@PiotrIw mamy prośbę o zmianę w menu "rejestr porad" i "tabela porad" na "rejestr tagów" i "tabela tagów". Bo te porady to jest dawny pomysł i realnie powstały z tego właśnie tagi. Tak o nich mówimy i dla nowych osób na poradni to bardzo mylące.

![image](https://github.com/watchdogpolska/poradnia/assets/36925935/7dbe7da0-67f6-42ce-adce-0cfd3240ef5d)

**Comment by PiotrIw** [comment]
zaimplementowane v1.1.17
