### ISSUE TITLE
prośba o usunięcie opcji "powiadom użytkownika" przy zamykaniu sprawy

### ISSUE THREAD

**Issue by AgnieszkaZdanowicz** [watchdogpolska/poradnia#1311]
@PiotrIw mamy taki mechanizm (zresztą wprowadzony na moją prośbę kilka lat temu - przyznaję, że to nie wypaliło), że jak zamykamy sprawę, to wtedy widoczne jest okienko "powiadom użytkownika"

![image](https://github.com/watchdogpolska/poradnia/assets/36925935/104d3dc0-eafa-44b0-9f37-4d83d2346eaa)

Jak zaznaczymy to pole, to klient dostaje wiadomość o treści: _Dziękujemy za skorzystanie z poradni. Twoja sprawa została zamknięta na tym etapie. Jeśli pojawią się w niej nowe pisma lub pytania, możesz do nas napisać, odpowiadając na tego maila, co automatycznie otworzy sprawę i pozwoli nam kontynuować temat. Sieć obywatelska - Watchdog Polska wspiera ludzi z całej Polski. Sprawne udzielanie pomocy w oparciu o fachową wiedzę to dla nas wyzwanie zarówno organizacyjne, jak i finansowe. Dlatego potrzebujemy Twojego wsparcia. Zachęcamy do przekazania nam darowizny, byśmy mogli razem tworzyć standardy jawnego życia publicznego!_ 

Doszliśmy do wniosku, że to wprowadza więcej zamieszania, niż pomaga i nie korzystamy z tej opcji w ogóle. Dlatego mielibyśmy prośbę o usunięcie tego pola.

**Comment by AgnieszkaZdanowicz** [comment]
przepraszam, nie zdążyliśmy o tym porozmawiać na spotkaniu, ale mamy to w planie zapisane - temat musi powisieć jeszcze do stycznia

**Comment by AgnieszkaZdanowicz** [comment]
@PiotrIw pogadaliśmy, że jednak nie potrzebujemy możliwości wysyłania ankiety przy konkretnej sprawie - do ankiety będziemy chcieli podejść zupełnie inaczej, ale to będę opiszę we właściwym wątku. Tak więc tutaj ten ekran przy zamykaniu sprawy można zupełnie usunąć

**Comment by PiotrIw** [comment]
Zaimplementowane v1.1.24

![image](https://github.com/watchdogpolska/poradnia/assets/36678620/79753269-27c7-4534-a665-535cfdd9b270)
