### ISSUE TITLE
zmiana nazwy pola "Zarejestrowana porada" na "Sprawa otagowana" na karcie Wykaz spraw (pole do filtrowania)

### ISSUE THREAD

**Issue by AgnieszkaZdanowicz** [watchdogpolska/poradnia#1312]
@PiotrIw mamy prośbę o zmianę nazwy pola na karcie "wykaz spraw" - tam na samej górze są pola do filtrowania spraw.  Chodzi o zmianę nazwy pola "Zarejestrowana porada" na "Sprawa otagowana"

![image](https://github.com/watchdogpolska/poradnia/assets/36925935/a939e588-bde4-461b-926b-1277c3ab8265)

**Comment by PiotrIw** [comment]
zaimplementowane v1.1.17
