### ISSUE TITLE
filtrowanie po statusie na karcie "korespondencja" nie działa - prośba o usunięcie

### ISSUE THREAD

**Issue by AgnieszkaZdanowicz** [watchdogpolska/poradnia#1313]
@PiotrIw jak się wejdzie w menu w "korespondencja", to na górze jest pole do filtrowania po statusie sprawy - ale ono nic nie daje. My i tak nie korzystamy z tej opcji, więc można skasować to pole do filtrowania.

![image](https://github.com/watchdogpolska/poradnia/assets/36925935/02650c99-92f6-4d24-ab9c-7cbaf447f95c)

**Comment by PiotrIw** [comment]
Czy ten widok (Rejest orespondencji) jest używany? Jest jeszcze "bela korespondencji", która umożliwia filtrowanie, sortowanie i wyszukiwanie listów. Może usunąć widok (Rejest orespondencji) , a nie tylko filtr?

**Comment by AgnieszkaZdanowicz** [comment]
@PiotrIw aktualnie nikt z nas rzeczywiście nie korzysta z rejestru korespondencji. Ale pamiętam, że Karolina mówiła, że ona korzystała, więc zakładam, że mogą być potencjalnie nawet w przyszłości osoby, którym ten widok będzie odpowiadał. Dlatego może lepiej go nie usuwać tak zupełnie?
