### ISSUE TITLE
grupy uprawnień przypisywane użytkownikom poradni - czy może się gdzieś wyświetlać informacja o tym?

### ISSUE THREAD

**Issue by AgnieszkaZdanowicz** [watchdogpolska/poradnia#1314]
@PiotrIw , żeby nie musieć za każdym razem przypisywać po kolei wszystkich uprawnień w każdej sprawie zrobiliśmy sobie grupy uprawnień:

![image](https://github.com/watchdogpolska/poradnia/assets/36925935/9becb532-762f-4e51-abb9-632a21383e63)

Natomiast, jak już przypiszemy grupę uprawnień, to potem nazwa przyznanej grupy nigdzie się nie wyświetla i jak chcemy zweryfikować, czy dobrą grupę uprawnień przyznaliśmy, musimy patrzeć po kolei na uprawnienia. Jak się kliknie w ikonkę ołówka przy imieniu i nazwisku użytkownika, to wtedy pojawią się nadane mu uprawnienia - ale nie ma tam nazwy grupy uprawnień, tylko konkretne uprawnienia. Więc trzeba wiedzieć, jakie uprawnienia są powiązane z jaką grupą. Czy się możliwe, żebyś dodał gdzieś na tym ekranie informację, jaka grupa uprawnień została nadana danemu użytkownikowi? :

![image](https://github.com/watchdogpolska/poradnia/assets/36925935/82c85a02-dade-4669-93ae-0a40be39adc0)

**Comment by PiotrIw** [comment]
Niestety Grupy uprawnień są "wirtualne" tj, po wybraniu grupy, użytkownikowi zostają przypisane poszczególne uprawnienia z grupy a nie grupa. Można je potem usuwać pojedynczo, na skutek czego mogą się zdarzyć sytuacje że użytkownik ma tylko część uprawnień z grupy którą dostał.... 
Proponuję:
- obok nazwy użytkownika w zaangazowanych dodam ikonę po najechaniu na ktorą wyświetlą się uprawnienia użytkownika
- Obok listy wyboru grupy lub przycisku przyznaj dodam ikonę po najechaniu na którą wyświetlą się nazwy grup wraz z uprawnieniami w ramach grupy
@AgnieszkaZdanowicz - czy to pomoże?

**Comment by PiotrIw** [comment]
zaimplementowane v1.1.17

**Comment by AgnieszkaZdanowicz** [comment]
@PiotrIw otwieram wątek, bo przetestowaliśmy i mamy prośbę. Jak nadajemy uprawnienie, to wybieramy je z listy rozwijanej w dół. I potem jak wracamy myszką na pole "przyznaj", to przejeżdżamy przez obszar "uprawnienia w grupach" przez co pojawia się lista uprawnień i nie możemy kliknąć w "przyznaj", bo lista uprawnień je zasłania :) Chyba po prostu pole "uprawnienia w grupach" jest dosyć szerokie i nawet nie chcąc, łatwo jest rozwinąć te uprawnienia. Czy da się zrobić tak, żeby trzeba było kliknąć w napis "uprawnienia w grupach", żeby one się pokazywały i potem kliknąć drugi raz, żeby się zamknęło? Takie rozwiązanie mi przyszło do głowy, ale Twoje pomysły są zawsze lepsze, więc nie upieram się przy tym pomyśle. Jednak zależy nam, żeby to działało tę odrobinę inaczej niż w tej chwili

**Comment by PiotrIw** [comment]
zaimplementowane v1.1.17

**Comment by PiotrIw** [comment]
Nieuwzględniony ostatni komentarz

**Comment by PiotrIw** [comment]
@AgnieszkaZdanowicz - kliknięcie i przytrzymanie lewego klawisza na ikonę tarczy i jej opis (w "Przyznaj uprawnienia") wyświetla uprawnienia w grupach. W tym samym czasie można używać kółka myszy do przewijania wewnątrz uprawnień w grupach. Po zwolneniu lewego klawisza myszy, help uprawnień znika. - Tak będzie OK?

**Comment by AgnieszkaZdanowicz** [comment]
@PiotrIw myślę, że tak będzie ok :)

**Comment by PiotrIw** [comment]
@AgnieszkaZdanowicz wrzucę to na szybko dziś wieczorem, żeby przywrócić sprawne przyznawanie uprawnień - teraz mozna nadać uprawnienia, trzeba tylko "objechać" kursorem obszar "pomocy" i najechać na przycisk "Przyznaj" od góry

**Comment by PiotrIw** [comment]
poprawione v1.1.18
