### ISSUE TITLE
kalendarz na poradni - kolory wydarzeń

### ISSUE THREAD

**Issue by AgnieszkaZdanowicz** [watchdogpolska/poradnia#1316]
@PiotrIw mam problem z rozgryzieniem kalendarza wydarzeń (https://porady.siecobywatelska.pl/wydarzenia/2023-12). Bo mamy tam wydarzenia z czerwonym/różowym tłem, szarym tłem i bez tła. Wydaje mi się, że tła oznaczają:

- czerwone tło mają wydarzenia, które na karcie tworzenia wydarzenia mają zaznaczone pole “termin”, czyli teoretycznie ważniejsze wydarzenia,
- bez tła są wydarzenia, które nie mają na karcie tworzenia wydarzenia zaznaczonego pola "termin" oraz informacje o rozprawach
- szare tło nie mam pojęcia, co znaczy - teraz mi przyszło do głowy, że one znaczą to samo, co czerwone tło, tylko jest na zmianę czerwone i szare, żeby się nie zlewało - to możliwe?

![image](https://github.com/watchdogpolska/poradnia/assets/36925935/1bf52696-aeba-47f7-aa1f-980f1b3ea444)

Czy możesz też sprawdzić, czy jak odznaczymy pole "termin" na karcie tworzenia wydarzenia, to to oznacza, że nie dostaniemy powiadomienia mailowego, czy to wpływa tylko na kolor tła wydarzenia w kalendarzu?

![image](https://github.com/watchdogpolska/poradnia/assets/36925935/f97c8a8d-22eb-424a-8504-e07dfd5b9e00)

**Comment by AgnieszkaZdanowicz** [comment]
@PiotrIw super, zrezygnujmy z czerwonego tła. Kolor tekstu możemy zmienić na czarny. Propozycja z ikonami mi się podoba. Tylko jeszcze się zastanawialiśmy, czy jak wydarzenie jest zakończone, to czy nadal powinno być widoczne na kalendarzu. Ale w sumie może dobrze jest mieć taki spis wszystkich wydarzeń na kalendarzu - zwłaszcza, że będą ikony, które pozwolą od razu zobaczyć, które wydarzenie jest zakończone. Więc zróbmy tak, jak zaproponowałeś :)

**Comment by PiotrIw** [comment]
zaimplementowane v1.1.17
waga szalkow ato ikona sprawy sądowej
