### ISSUE TITLE
prośba o zmianę wyświetlanych nazw - dane metrykalne na karcie konkretnej sprawy

### ISSUE THREAD

**Issue by AgnieszkaZdanowicz** [watchdogpolska/poradnia#1351]
@PiotrIw mamy prośbę o zmianę poniższych nazw:

-  "dane metrykalne" na "dane statystyczne" (bo takie określenie na ekranie po kliknięciu w "utwórz nową poradę" i to będzie jednolite)
- "porada" na "TAGI"
- "utwórz nową poradę" na "Otaguj sprawę"

![image](https://github.com/watchdogpolska/poradnia/assets/36925935/25b0e1a2-a685-49b6-b7bb-945bb64b3617)

**Comment by PiotrIw** [comment]
zaimplementowane v1.1.17
