### ISSUE TITLE
dodawanie i usuwanie załączników do listów

### ISSUE THREAD

**Issue by AgnieszkaZdanowicz** [watchdogpolska/poradnia#1352]
@PiotrIw mamy problem z usuwaniem załączników, jak np. coś dodamy przez przypadek (przy pisaniu listu - jeszcze przed wysłaniem go). Teraz jest tak, że żeby usunąć załącznik, trzeba znowu wybrać "wybierz plik" i kliknąć esc albo można odświeżyć stronę, bo wpisana treść jest zapamiętywana, a załączniki nie. Wiem, że to nie jest bardzo trudne, ale mało intuicyjne. Zwłaszcza, że jest napis "usuń", który w sumie nic nie robi?
Może da się to jakoś lepiej rozwiązać?

![image](https://github.com/watchdogpolska/poradnia/assets/36925935/07e65ccd-31cb-4ea4-89ed-c75c429cdd71)

I przy okazji - czy bardzo czasochłonne byłoby wprowadzenie opcji "drag and drop" przy dodawaniu załączników? Bo teraz można dodać tylko jeden na raz.

**Comment by PiotrIw** [comment]
zaimplementowane v1.1.21

**Comment by AgnieszkaZdanowicz** [comment]
@PiotrIw przegadaliśmy wprowadzone rozwiązanie i mamy pytanie, czy jednak byłaby opcja, żeby można było dodawać załączniki też osobno, "po kolei"? I też kasować pojedyncze załączniki? Bo jedna osoba zgłosiła, że ona dodaje załączniki z różnych folderów, więc nie ma jak ich dodać wszystkich jednocześnie i myślimy, że klienci też mogą tak działać.

A druga sprawa - czy można przetłumaczyć pola, które są po angielsku? To z myślą o klientach :)

![image](https://github.com/watchdogpolska/poradnia/assets/36925935/721a5409-9395-4dbf-a776-a84e0e1bfec9)

**Comment by PiotrIw** [comment]
@AgnieszkaZdanowicz Dodam tłumaczenia, pomyślę jak zrobić równocześnie dodawanie hurtem i pojedynczo.

**Comment by PiotrIw** [comment]
zaimplementowane v1.1.22 - ponownie wybrane lub upuszczone pliki dodaja się do listy (nie mona doda tego samego pliku wielokrotnie - nie jest dodawany do listy), mozna w ten sposób dodawac pliki z różnych folderów, działa również wybór wielu plików z jednego folderu z klawiszami ctrl lub shift
