### ISSUE TITLE
sprawy sądowe na poradni

### ISSUE THREAD

**Issue by AgnieszkaZdanowicz** [watchdogpolska/poradnia#1353]
@PiotrIw jak jesteśmy w konkretnej sprawie na poradni, to mamy w prawej kolumnie zakładkę "sprawa sądowa", gdzie możemy wpisać dane sprawy sądowej powiązanej ze sprawą z poradni:

![image](https://github.com/watchdogpolska/poradnia/assets/36925935/a66e57f5-f78b-4f46-a7a0-a78c568575ff)

Jej działanie jest dla nas trochę zagadką, chociaż widzimy duży potencjał w jej wykorzystaniu :) Tu jest kilka wątków:

1) brakuje nam miejsca, gdzie mielibyśmy spisane wszystkie sprawy sądowe oznaczone na poradni. Potrzebowalibyśmy może nowej zakładki w menu, która prowadziłaby do tabeli spraw sądowych i w tej tabeli byłyby takie informacje: link do sprawy z poradni + nazwa klienta + sąd + sygnatura sądowa + link do CBOSA/SAOS (te informacje są widoczne, jak się zarejestruje sprawę sądową)

![image](https://github.com/watchdogpolska/poradnia/assets/36925935/e383256c-ebeb-4ad4-b6f7-b02a1c937c43)

2) teraz coś, czego nie jestem pewna (tutaj o tym Adam pisał: Monitorowanie spraw sądowych #423)  - wydaje mi się, że mamy bota, który przegląda co jakiś czas e-wokandy sądów (wskazane w #423) i szuka po sygnaturach sądowych, czy jest już wyznaczone posiedzenie - jeśli tak, to ściąga te dane na poradnię i tworzy z nich wydarzenie. A nawet widzę, że wrzuca wynik posiedzenia:

![image](https://github.com/watchdogpolska/poradnia/assets/36925935/d2ecec3d-f669-4658-9edd-07a720f5484c)

W związku z tym, że nie mamy zebranych spraw sądowych, to trudno mi jest znaleźć więcej przykładów, żeby sobie jakoś odtworzyć ten proces. Co chciałabym wiedzieć: jak często ten bot przegląda e-wokandy, czy robi to rzeczywiście dla wszystkich spraw sądowych zaznaczonych na poradni i czy wrzuca dane na poradnię już jak jest wyznaczone posiedzenie czy dopiero jak jest już wynik tego posiedzenia? Te dane z karty wydarzenia związanego ze sprawą sądową też są dla nas bardzo ciekawe (najważniejsze są: data + wynik + skład sędziowski + typ). Gdyby dało się też te dane wrzucić do tabeli ze sprawami, to byłoby super.

**Comment by PiotrIw** [comment]
zaimplementowane v1.1.21

**Comment by AgnieszkaZdanowicz** [comment]
@PiotrIw widzę, że jest zakładka "tabela wydarzeń", ale nie widzę w niej żadnych rekordów

<img width="814" alt="Zrzut ekranu 2023-12-19 o 21 29 18" src="https://github.com/watchdogpolska/poradnia/assets/36925935/e15a0d93-2b04-436f-890f-b4780a961585">

czy ja coś źle robię? :)

**Comment by PiotrIw** [comment]
@AgnieszkaZdanowicz  - Były zmiany frontendu, trzeba odświerzyć dane przeglądarki. W zależności od przeglądarki:
Firefox:  shift+kliknąć w kółeczko odświerzania strony
Chrome: ctrl+kliknąć w kółeczko odświerzania strony

**Comment by PiotrIw** [comment]
:)
