### ISSUE TITLE
prośba o zmianę pola przy tagowaniu z "czy pomogliśmy" na "czy udzieliliśmy porady"

### ISSUE THREAD

**Issue by AgnieszkaZdanowicz** [watchdogpolska/poradnia#1401]
@PiotrIw mamy prośbę o zmiany nazwy pola, bo aktualna powoduje problemy z interpretacją i mamy rozjazd przy tagowaniu.

To pole jest widoczne, kiedy otagowujemy sprawę:

![image](https://github.com/watchdogpolska/poradnia/assets/36925935/4f5c2122-2711-4210-8607-74e978f0d9bf)

I potem w rejestrze i tabeli możemy po nim przeszukiwać, więc tutaj też trzeba by zmienić tę nazwę:

![image](https://github.com/watchdogpolska/poradnia/assets/36925935/ee8e528a-e272-4bfb-920f-44320bbcbf98)

![image](https://github.com/watchdogpolska/poradnia/assets/36925935/903681ae-57d4-427e-af1b-ae49a4f4f0e5)

**Comment by PiotrIw** [comment]
Zaimplementowane v1.1.26
