### ISSUE TITLE
Stopki dla zespołu poradni

### ISSUE THREAD

**Issue by JoannaGucman** [watchdogpolska/poradnia#1419]
W nawiązaniu do naszej korespondencji prośba o wdrożenie synchronizowanych stopek dla zespołu poradni.

Treść:
**Wspieraj działanie poradni prawnej Watchdoga!
Przekaż 1,5% podatku - KRS 0000181348**
Więcej informacji na stronie: www.siecobywatelska.pl/1-5-procent

Sieć Obywatelska Watchdog Polska
ul. Ursynowska 22/2 | 02-605 Warszawa
tel: +48 22 844 73 55

KRS: 0000181348
NIP: 526 284 28 72

**Comment by PiotrIw** [comment]
@JoannaGucman: która opcja lepsza:
1 - jeśli użytkownik z zespołu zdefiniuje własną to będzie miał własną, a jeśli nie to Imię i Nazwisko i standardową dla zespołu
2 - użytkownik definiuje własną (jeśli nie zdefiniuje to z automatu wpisuje się tam Imie i Nazwisko) a pod własną zawsze dolącza się standardowa dla zespołu

**Comment by PiotrIw** [comment]
Zaimplementowane v1.1.26

**Comment by JoannaGucman** [comment]
Dziękuję

śr., 21 lut 2024, 19:41 użytkownik Piotr ***@***.***> napisał:
