### ISSUE TITLE
Podszywanie się poradni pod użytkownika

### ISSUE THREAD

**Issue by szymond** [watchdogpolska/poradnia#1420]
Moim zdaniem skoro poradnia wysyła maila-powiadomienie, to wpisanym jako nadawca tego maila powinna być poradnia (a nie osoba, która wyzwoliła zdarzenie). Tj. jak dodam sprawę do poradni, nie powinien do mnie przychodzić mail "ode mnie", tylko z poradni.

Zdaję sobie sprawę, że skoro tak to działa od lat, to pewnie nikt w tym niczego złego nie dostrzega. Niemniej jednak, być może m.in. z takiego powodu maile z poradni trafiają na gmailu do spamu. 

![image](https://github.com/watchdogpolska/poradnia/assets/432837/3caad098-3e55-41f2-9320-618ad43ec71b)

**Comment by PiotrIw** [comment]
@szymond Czy wcześniej takie maile też trafiały do spamu, czy zaczęło się to dopiero parę tygodni temu? Prześlij mi proszę tego maila na watchdogowej poczcie abym mógł zajrzeć w szczegóły.

**Comment by szymond** [comment]
Nie wiem/nie pamiętam jak było przed paroma tygodniami. Zauważona wiadomość w spamie odebrana była w styczniu. Jak podasz maila, to mogę na niego ją przekazać. Aczkolwiek wcale się nie odnosisz do wskazanego problemu.

**Comment by PiotrIw** [comment]
@szymond Podawanie w etykiecie adresu mailowego np nazwy użytkownika wspólnej skrzynki mailowej lub serwisu nie jest podszywaniem się pod nikogo. Dostajesz prawdopodobnie maile od Githuba zaadresowane w stylu 
"szymond <notifications@github.com>" ?
Github w ten sposób nie podszywa się pod nikogo tylko informuje w jaki użytkownik zainicjował akcję, której powiadomienie dotyczy.  Podobnie poradnia - w sprawie może pisać wielu zaangażowanych, a etykieta adresu mailowego informuje kto dokonał wpisu, gdyby autor zapomniał się podpisac ;).
Adres mailowy tak skonstruowany jest jak najbardziej poprawny i spełnia wszystkie standardy.

**Comment by szymond** [comment]
Moim zdaniem nie powinno się tłumaczyć, że jest dobrze, w sytuacji gdy jest źle :) 

Masz rację, że dostaję takie maile (aczkolwiek github uznał, że nie potrzeba mnie powiadamiać o czynnościach, które sam czynię). Natomiast nie przypominam sobie sytuacji, żeby gmail sugerował mi, że ktoś się pod kogoś może podszywać. Być może dzieje się tak, bo nagłówki maili od githuba komunikują, że chodzi o listę mailingową, a nie zwykłego maila.
