### ISSUE TITLE
PILNE - problem z dochodzeniem maili na poradnię?

### ISSUE THREAD

**Issue by AgnieszkaZdanowicz** [watchdogpolska/poradnia#1440]
@PiotrIw @mrbojko czy możecie sprawdzić (nie wiem, który z Was ma taką możliwość), czy maile poprawnie spływają na poradnię? Bo wiem co najmniej o dwóch przypadkach z wczoraj, kiedy wiadomość nie dotarła. Kiedyś już tak było, że wpływały tylko wiadomości wysłane bezpośrednio z poradni, a te wysłane na adres mailowy ogólny lub adres konkretnych spraw nie docierały, bo coś tam się zacięło na serwerze. Niestety nie mogę znaleźć tamtego wątku na githubie.

**Comment by AgnieszkaZdanowicz** [comment]
@mrbojko wielkie dzięki, spłynęło sporo wiadomości, więc widać od razu, że zadziałało :)

**Comment by PiotrIw** [comment]
@mrbojko 👍 , tam jest sentry. W logach widać że aplikacja stanęła 24/03 w południe, ale nie ma żadnego błędu z tym związanego....
```2024-03-04T11:59:45.408643527Z Waiting 60 seconds
2024-03-04T12:00:45.467943582Z Resume after delay
2024-03-12T08:22:06.509562678Z Configuration:  {'imap': {'hostname': 'imap.zenbox.pl', 'username': .......}, 'webhook': 'https://porady.siecobywatelska.pl/listy/webhook............, 'sentry_dsn': 'https://...........}
2024-03-12T08:22:06.706273659Z Connected to mail server
2024-03-12T08:22:06.735475254Z Logged in
20```
@AgnieszkaZdanowicz - imap-to-webhook to jest kolejny temat do aktualizacji bibliotek i rewiizji kodu

**Comment by PiotrIw** [comment]
@AgnieszkaZdanowicz - na szbko napiszę skrypt, który o np 3 rano będzie sprawdzał datę ostatniego logowania do zenboxa i resetował serwis jeśli jest inna niż dzisiejsza
