### ISSUE TITLE
Brak informacji dla nadawcy że maile z adresem poradni w kopii nie są przyjmowane

### ISSUE THREAD

**Issue by PiotrIw** [watchdogpolska/poradnia#1446]
*** Please remember not to include application or user sensitive data ***
*** Proszę pamiętać o nieumieszczaniu wrażliwych danych aplikacji i użytkowników ***
@AgnieszkaZdanowicz  ten problem nadal występuje i to może być przyczyna reklamacji od klientów, którzy wysyłają takie maile na poradnię a nie wiedzą że poradnia nie przyjmuje kopii.
Wymagana modyfikacja kodu imap-to-webhook, tak aby używając emaillabs generował dla takiego maila stosowną odpowiedź

**Comment by AgnieszkaZdanowicz** [comment]
@PiotrIw ale nie było nigdy takiego komunikatu czy coś się popsuło? Bo wydawało mi się, że był albo może tylko miał być :) Ja w każdym razie o tym pamiętam i jak ktoś zgłasza problem, bo zwracam na to uwagę.

**Comment by PiotrIw** [comment]
@AgnieszkaZdanowicz  - jest komunikat i działa poprawnie. Zamykam - mój błąd w testach webhooka ;)
