### ISSUE TITLE
Przebudować strukturę pola "status" dla sprawy

### ISSUE THREAD

**Issue by ad-m** [watchdogpolska/poradnia#157]
Pole "status" powinno być dynamicznie generowane na podstawie dwóch nowych pól:
- posiada prawnika,
- aktywna.

**Comment by ad-m** [comment]
Brak szczegółowego uzasadnienia. :-1:

**Comment by AgnieszkaZdanowicz** [comment]
mi się wydaje, że to działa dobrze - to zamykam
