### ISSUE TITLE
E-mail powiadamiający o zamknięciu sprawy

### ISSUE THREAD

**Issue by ad-m** [watchdogpolska/poradnia#168]
Kochasz nas. Jesteśmy super. A może chcesz się dopisać do newslettera? Mamy Facebooka tu, tu i tu itd.

Link do newslettera z automatycznym wypełnieniem pola e-mail.

**Comment by ad-m** [comment]
Przygotowane przez @rwakulszowa  w #208

**Comment by ad-m** [comment]
> Bardzo mnie cieszą te poprawki :) zobaczymy, jak ludzie zareagują na maila zwrotnego o zamknięciu sprawy.
> 
> pozdrawiam,
> 
> Agnieszka
> 
> Agnieszka Zdanowicz
> 
-----

> 
> No i mam odpowiedź na to, jak ludzie zareagują na maila z informacją o zamknięciu sprawy. Otóż wczoraj zamknęłam wiele spraw - w tym również takich, w których nie udzieliliśmy porad, tylko informowaliśmy, że daną sprawą się nie możemy zająć, bo nie dotyczy dostępu do informacji. I dostałam dwie wiadomości zwrotne, że przecież tej danej osoby nie pomogliśmy, to po co taki mail. I mają rację. Stąd moje pytanie - czy nie dało by się zrobić dwóch opcji na zamykanie spraw - jednej, że jest wysyłana automatycznie odpowiedź, a drugiej, że zamykamy bez wysyłania wiadomości. Bo w tej chwili te sprawy mi wiszą i nie mogę ich zamknąć, bo znowu pójdzie mail. A wykasowywać tak zupełnie też nie chcę.
> 
> pozdrawiam

**Comment by rwakulszowa** [comment]
Powinno wystarczyć dodanie nowego parametru `notify` do `CaseForm.save` i `CaseCloseForm.save` https://github.com/watchdogpolska/poradnia/blob/master/poradnia/cases/forms.py#L84
Rozumiem, że konieczne będzie dodanie pola 'checkbox' do wyboru czy potwierdzenie ma zostać wysłane czy nie. O ile dla `CaseCloseForm` nie będzie to problemem, to w przypadku `CaseForm` jest to bardziej skomplikowane, ponieważ ten widok w większości przypadków służy do innych celów niż zamykanie spraw.
Myślę że optymalnym rozwiązaniem byłoby pozostawienie `CaseForm` bez zmian i domyślne niewysyłanie powiadomień, gdyż ten widok służy bardziej do administracyjnych rzeczy. Przy okazji rozwiązuje to problem omyłkowego zamknięcia już zamkniętej sprawy, co obecnie skutkuje kolejnym wysłaniem powiadomienia.

**Comment by ad-m** [comment]
:+1:
W pełni się z Tobą zgadzam, także w zakresie wyłączenia powiadomień w ```CaseForm```. Przygotujesz poprawkę?

**Comment by ad-m** [comment]
https://github.com/rwakulszowa/poradnia/pull/2
