### ISSUE TITLE
Uprawnienie do zamykania sprawy

### ISSUE THREAD

**Issue by ad-m** [watchdogpolska/poradnia#169]
Dodać do "wsparcie+" uprawnienie do zamykania sprawy.

**Comment by ad-m** [comment]
Szanowny @rwakulszowa,

Proponuje wprowadzić rozwiązane powyższego issues. Obecnie możliwe jest zamykanie sprawy przez osobę o uprawnieniach `can_change_case`, ale może ona także dokonywać innych zmian statusu sprawy. Odbywa się ono przez edycje sprawy i zmianę ```CaseUpdateView```, a powinna móc tylko zmienić ``status`` na ``closed``.

Możemy to rozwiązać na kilka sposób. Moglibyśmy zmodyfikować formularz, dodać w nim odpowiednią walidacje i blokować nadmierne edycje i dopuścić do widoku zmiany całej sprawy, ale myślę, że lepiej stworzyć nowy widok, który będzie zajmował się tylko tym, aby ustawić status na zamknięty.

Aby wykonać nowy widok należy:
- [ ] dodać testy dla widoku,
- [ ] stworzyć nowe uprawnienie "zamykanie sprawy" w cases.models.Case.Meta (por. dokumentacja django-guardian) i wygenerować migracje dla nich,
- [ ] stworzyć nową klasę widoku - przykład https://github.com/watchdogpolska/feder/blob/ae565514d4f05557c8dd4fa590d01b74d46094ef/feder/questionaries/views.py#L133-L151 albo bez ActionView (z mojej biblioteki django-atom),
- [ ] dodać url w urlpatterns,
- [ ] dodać przycisk zamykania spraw w template ```CaseDetailView```.

W issues "wsparcie+" to jest element danych aplikacji. W systemie istnieją uprawnienia, a następnie grupy uprawnień do sprawy. Dzięki czemu mamy możliwość elastycznego przypisania uprawnień, ale możemy też po prostu dodać zestaw. Są zestawy uprawnień (```cases.models.PermissionGroup```) takie jak "obserwator" (nie może pisać, ale widzi sprawę), "wsparcie" (może napisać projekt do klienta) i "wsparcie+" (może napisać pismo do klienta).

**Comment by rwakulszowa** [comment]
Dodałem parę zmian związanych z tym problemem: https://github.com/watchdogpolska/poradnia/compare/master...rwakulszowa:feature/case_close#diff-13e98137bddbbd408e721247a0a0b6f9R5

Oczywiście kod nie jest jeszcze kompletny, póki co brakuje tłumaczeń i paru drobnych kwestii, jednak chciałbym zapytać czy zaproponowane przeze mnie rozwiązanie jest akceptowalne. 
Zdecydowałem się oprzeć CaseCloseView na CaseUpdateView, podobnie z CaseCloseForm, głównie ze względu na podobną logikę i zasadę działania obu czynności.
Formularz oparty jest na UpdateView z wykluczonymi polami edycji, przez co cała logika aktualizowania bazy danych i wysyłania powiadomień jest taka sama jak w CaseForm.

**Comment by ad-m** [comment]
@rwakulszowa , tak, po lekturze kodu bardzo mi się podoba, zwłaszcza odejście od ActionView.

Odnośnie tłumaczeń stosuje:
```bash
function manage.py () 
{ 
    if [ -f "manage.py" ]; then
        manage="manage.py";
    else
        if [ -f "../manage.py" ]; then
            manage="../manage.py";
        else
            if [ -f "../../manage.py" ]; then
                manage="../../manage.py";
            fi;
        fi;
    fi;
    echo "manage.py path: $manage";
    python "$manage" "$@"
}
function l10n () 
{ 
    ../manage.py makemessages -l pl && poedit locale/pl/LC_MESSAGES/django.po && ../manage.py compilemessages -l pl
}
```
Wywoływane w katalogu aplikacji django (nie mylić z projektem) np. ```cases```.
