### ISSUE TITLE
Powiadomienie o wydarzeniu w kalendarzu

### ISSUE THREAD

**Issue by ad-m** [watchdogpolska/poradnia#173]

**Comment by ad-m** [comment]
Szanowny @ppkt, 

to wydaje się też dobre na początek pracy z Poradnią. Mamy coś takiego jak ```events.models.Event```, które przechowuje informacje o wydarzeniach w sprawach, a także ```events.models.Alarm```, które przechowuje informacje o wywołaniu alarmu z wydarzenia. Obiekt ```events.models.Event``` jest widoczny tylko dla członków zespołu.

Należy:
 
- [ ]  w profliu użytkownika konfiguracje czy powiadamiać o zbliżających się (domyślne ```True```) wydarzeniach widoczne tylko dla członków zespołu, a jeżeli nie skomplikuje to nadmiernie to także czas np. z listy wyboru z jakim wyprzedzeniem powiadamiać,
- [ ] przygotować procedurę, która będzie tworzyła obiekt ```events.models.Alarm``` i powiadamiała użytkowników ```is_staff=True```, którzy w opcjach profilu wybrali, że chcą powiadomienia o wydarzeniach,
- [ ] przygotować polecenie ```manage.py```, które będzie mogło być wywoływane cyklicznie z shella za pomocą linuxowego crona i wywoływało procedurę z punktu powyższego.

Zwracam uwagę, że nie mamy obecnie aplikacyjnego crona np. celery i nie wydaje się to celowe.

**Comment by ad-m** [comment]
Szanowny @ppkt ,

Czy potrzebujesz jakieś dodatkowego objaśnienia dla tego issues?

Z wyrazami szacunku,

**Comment by ppkt** [comment]
@ad-m dłubię sobie to, mam w sumie jedno pytanie odnośnie samej implementacji. Użytkownik ma możliwość wyboru czasu powiadomienia - jakie opcje powinien mieć? Fajnie jest to rozwiązane w Google Calendar
![screenshot from 2016-07-22 22-04-10](https://cloud.githubusercontent.com/assets/477174/17069711/5d1ff8f4-5058-11e6-8698-a6448301bb7f.png)
Ale zastanawiam się czy potrzeba aż tak rozbudowanych opcji, może wystarczy dropdown menu z listą opcji (1 godz. / 12 godz. / 1 dzień / 3 dni / tydzień) albo input z liczbą dni?

**Comment by ad-m** [comment]
Myślę, że wybór opcji 1/3/7 dni to maksimum co jest dla nas potrzebne.

**Comment by ppkt** [comment]
@ad-m szybkie pytanie - o wydarzeniach mają być informowani tylko użytkownicy zaangażowani w sprawę czy wszyscy członkowie z zespołu?

**Comment by ad-m** [comment]
@ppkt, nie można ufać odpowiedziom e-mailowym GitHuba. Nie dotarła jak tutaj udzieliłem odpowiedzi. :-1: 

Członkowie zespołu (1) zaangażowani (2) w sprawę, bo wydarzenia są dla organizacji pracy zespołu (1), a dostęp do sprawy jest ściśle ograniczony (2).

W zwykłych systemach zgłoszeń (osTicket itd.) sprawy są widoczne dla dość wielu osób, co najmniej dla danego departamentu. W tym systemie mamy sprawy czasem wrażliwe, gdy np. ktoś jest narażony na represje lub odpowiedzialność karną, więc np. wolontariusze-prawnicy widzą tylko te sprawy, które im przydzielono, a wąskie zaufane grono widzi wszystko i rozdziela zadania przydzielając dostęp dla wolontariuszy.

**Comment by ad-m** [comment]
@ppkt , dziękuje za zaangażowanie i chęć wsparcia Stowarzyszenia. :+1:

**Comment by ppkt** [comment]
@ad-m nie ma sprawy, dzięki za wyjaśnienie - wieczorem wrzucę PR do code review :)

**Comment by ad-m** [comment]
Wykonane dzięki @ppkt  w ramach #346.
