### ISSUE TITLE
djmail - simple and nonobstructive django email middleware

### ISSUE THREAD

**Issue by ad-m** [watchdogpolska/poradnia#187]
http://bameda.github.io/djmail/

**Comment by ad-m** [comment]
Porzucone API:
- User.notify
- User.send_template_email
- template_mail.send_tpl_email
- User._get_notify_template_name
- User._get_email_name

**Comment by ad-m** [comment]
- [ ] Case.send_notification

**Comment by ad-m** [comment]
- [ ] Letter.send_notification

**Comment by ad-m** [comment]
- [ ] Letter.get_users

**Comment by ad-m** [comment]
- [ ] Letter.is_done
- [ ] Case.get_users_with_perms -> Case.get_users (+params)

**Comment by ad-m** [comment]
```python
# Create MagicMailBuilder instance
mails = template_mail.MagicMailBuilder()

# Create a native email object.
# NOTE: The method name represents a email name.
email = mails.some_email("to@example.com", {"template": "context"})
email.send()
```

**Comment by ad-m** [comment]
- [ ] AbstractRecord.send_notification

**Comment by ad-m** [comment]
Tu celem jest uporządkowanie i uproszczenie kodu dla powiadomień.

**Comment by AgnieszkaZdanowicz** [comment]
@ad-m czy to aktualne?

**Comment by AgnieszkaZdanowicz** [comment]
nie wiem, czy tu jest coś do zrobienia czy można zamykać. @mrbojko @PiotrIw pozostawiam Wam do oceny.
