### ISSUE TITLE
Wykrywanie delty w tekstach

### ISSUE THREAD

**Issue by ad-m** [watchdogpolska/poradnia#189]
https://github.com/paulgb/simplediff

Wprowadzić jako element powiadomień.

**Comment by ad-m** [comment]
Blocked by #187

**Comment by AgnieszkaZdanowicz** [comment]
@ad-m czy to aktualne?

**Comment by ad-m** [comment]
Aktualne, ale myślę, że nie warto praktycznego rozwoju, skoro nie doskwiera to ludziom.
