### ISSUE TITLE
Rozszerzenie wykrywania ID sprawy w e-mailach 

### ISSUE THREAD

**Issue by ad-m** [watchdogpolska/poradnia#200]
Wiadomość następująca została nieprawidłowo zidentyfikowana. 
````
Return-path: <SRS0=OLHwAW=NS=gmail.com=[[CENZURA___1]]@porady.siecobywatelska.pl>
Envelope-to: sprawa-639@porady.siecobywatelska.pl
Delivery-date: Mon, 18 Jan 2016 15:31:15 +0100
Received: from mail-wm0-f53.google.com ([74.125.82.53])
    by s50.hekko.net.pl with esmtps (TLSv1:RC4-SHA:128)
    (Exim 4.86)
    (envelope-from <[[CENZURA___1]]@gmail.com>)
    id 1aLApt-0001Qw-5m
    for sprawa-639@porady.siecobywatelska.pl; Mon, 18 Jan 2016 15:31:15 +0100
Received: by mail-wm0-f53.google.com with SMTP id 123so54686333wmz.0
        for <sprawa-639@porady.siecobywatelska.pl>; Mon, 18 Jan 2016 06:31:12 -0800 (PST)
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
        d=gmail.com; s=20120113;
        h=mime-version:sender:in-reply-to:references:date:message-id:subject
         :from:to:cc:content-type;
        bh=LbP/fPx6ZsmQjMYGpsXWdWVAgdqLqsEWwM+sRSgHoOA=;
        b=Sn0OFXgg27Y/hj1XBcRxO9uqbWZRX4szxAkdulBpZSJ16j0Qt/M1QTCaOeQqi4Blhx
         5gyXlCTUL22y0capWMXGdj+1uh+XYhWOgQm/M6rwmS1AKJg/Cg0haDF+GUL10p/Fa9m/
         ekxs9wG2zWPodA2gBnly6chKaYGcU6SoUknDIoEXBOtPpuxIoJqP9wcG1VgWdsZ0mLRQ
         s+4MKkW8Gq0tyCcLqjWbetmu39lBZVxhqf8xxKfHhYuxm25nZL7Q8qQ07Vq5CSzdeFU9
         zsVyrVJS9ctcor98LOHLQ4JyEPeXRszAHu4PdNXbwM39AENhg9PuvG+S1aDpUd4jZDBN
         ZHhA==
X-Google-DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
        d=1e100.net; s=20130820;
        h=x-gm-message-state:mime-version:sender:in-reply-to:references:date
         :message-id:subject:from:to:cc:content-type;
        bh=LbP/fPx6ZsmQjMYGpsXWdWVAgdqLqsEWwM+sRSgHoOA=;
        b=GUU0JkLxeml9YdL/81Dn8fo3r29ThQOeyMJ6yR1OYqZcuOptMxoXQIprejq7WUPMk9
         oTaElkjzGcUMI1UbI4ir/2MlVUgnySIQRVdpzByZfV9HO1bewUHPpITjv3ZMRSyjQTm1
         5sUNGzThPpoiBZlzP8JUtHY2psDuRoMlcZdnIetxtQAgcNrYBunlpujRkE1aknbu0ic9
         P/3p2yloRAQ7vqPYWpfX4GFcqTEd9u5tjEov0yhr5kVQUaP7dCMY+gLmXkR5bWkR6Vi5
         V2j8OLVR7cmBfn5PN8AM6BkCB+9sxNX6StMgR22BVmlPNwGlZTnkrOHhwqmHI1vqKNsG
         o9Qg==
X-Gm-Message-State: AG10YORTnMYxOPX07fA6oWnGUUfXun0cm3k8g1z6L8PAUklzrt9NvF+4W0Z2o1THAc7wPaRU+ooR6TJxOJaMeQ==
MIME-Version: 1.0
X-Received: by 10.28.89.195 with SMTP id n186mr14064388wmb.49.1453127471205;
 Mon, 18 Jan 2016 06:31:11 -0800 (PST)
Sender: [[CENZURA___1]]@gmail.com
Received: by 10.194.44.193 with HTTP; Mon, 18 Jan 2016 06:31:10 -0800 (PST)
In-Reply-To: <CADA-hANw2VYyHyc7H4iVN3vG0NxCpmQmbZ2i7TrdR6xQG025Wg@mail.gmail.com>
References: <CADA-hAPfhNTPZDekQc=QASQ7RqP3x43UGA_GiCNoPxuMxDWZ9Q@mail.gmail.com>
    <CAM-EUyU_4eewg3aPMtvuQfRECDQqFTzf1aM==xkvaZ_N3t35WQ@mail.gmail.com>
    <CADA-hAPauTGKLp__h+LxiWYHwSdGKHFWoHVUsRAyaAVswOQ+OQ@mail.gmail.com>
    <CADToESei37f2qgM8foncE8bDn1-1AtNf-DFrhPkw-XDFCkHbwg@mail.gmail.com>
    <CADA-hANsoa2ACD_9P=-HPchXP5=LcdZTEu97oQZ3+YUYyP-DKg@mail.gmail.com>
    <CADToESdsJC4JM+7NOEs96FjnirVO65m=7i9MNPAAb7VSjNKzTQ@mail.gmail.com>
    <CADA-hAMyucMtW=H_1dPZrxAvH=_Y4AOKCJNiB+2z4VpqP2JX6w@mail.gmail.com>
    <CADA-hANfd0eG1rOE=8V055KGWMTSmApuso5f2FeLBgFHvhzZhw@mail.gmail.com>
    <CADA-hAOf5+9FKjXswtddLdBjVbR35RhQzeZFRw9sGwx1egURLA@mail.gmail.com>
    <CADA-hAOvFNt3kBFhmOdOoKE3Br7uKBReaAMw9R-2sNwpkVQUkQ@mail.gmail.com>
    <CADA-hAPzVQJM3JQaDcHP7pYspiLRtxwSuJuyEYDxA8K8f8CLRw@mail.gmail.com>
    <CADToEScBHdroDuvmZO8haL9YJZqKJPyvxQ4pzK2wLC_zB7R13A@mail.gmail.com>
    <CADA-hAPHHf67UgjUq3feKnLhbKfVvo4kX5EGEcpy9PFhcKb3ug@mail.gmail.com>
    <CADToESfZAreYxOMTUZfjuVmf61EuKZd5hoFxM918Ec_Xpsq8ug@mail.gmail.com>
    <CADA-hAMRorz1js+F+FRcnar0w_AV0u+vd5CYoFteR4TQBQW1Cw@mail.gmail.com>
    <CADA-hAN7=SswKDv7-vOpgxUEzSY5UCnyupp4Z+8rgfgkS9CSQA@mail.gmail.com>
    <CADA-hAMDtnG2zcrKhsLR5b481Om2pFs+5Y01U3Nk8OYqExhkXg@mail.gmail.com>
    <CADA-hAO269QbsKwsoz_ZLOujjgtKX7G2rzuW4jg_t2wViNiKKQ@mail.gmail.com>
    <CADA-hAMQGveuUQecfY6RC8ZhjUO5pWFvMVeC_FdSO3CB4KVbCA@mail.gmail.com>
    <CADA-hAMdKtO8DffDSXzh9wfMLnN4QA17gr+nM0Wa5S6djYvBzA@mail.gmail.com>
    <CADA-hAMrV6CwQjJnU9HaibQAtdFBKwW_fi=zgJMLm1sSNRfeBQ@mail.gmail.com>
    <CADA-hANw2VYyHyc7H4iVN3vG0NxCpmQmbZ2i7TrdR6xQG025Wg@mail.gmail.com>
Date: Mon, 18 Jan 2016 15:31:10 +0100
X-Google-Sender-Auth: AI--1s9Gft81_B4rgIjb4BJIXiQ
Message-ID: <CADA-hAMtV7STFy3+z04tVj3MYPooqpdzqpQ4cv-c9tLDZzfjKQ@mail.gmail.com>
Subject: Re: Szymon Osowski - sprawa Stowarzyszenia "Ruska Bursa"
From: [[CENZURA___3]] <[[CENZURA___2]]@gmail.com>
To: =?UTF-8?Q?Szymon_Osowski_Sie=C4=87_Obywatelska_Watchdog_Polska?= <[[CENZURA___5]]@siecobywatelska.pl>
Cc: sprawa-639@porady.siecobywatelska.pl, 
    =?UTF-8?B?UGF1bGEgS8WCdWNpxYRza2E=?= <[[CENZURA___4]]@siecobywatelska.pl>
Content-Type: multipart/mixed; boundary=001a114128a2bd14ab05299c9a07
X-HEKKO: 74.125.82.53:
```

**Comment by ad-m** [comment]
Szanowny @rwakulszowa ,

Czy miałbyś ochotę przygotować poprawkę dla niniejszego issues?

Obecnie korespondencje prowadzimy z wykorzystaniem WWW, ale można odpowiedzieć także na dowolny e-mail w sprawie, bo każda sprawa ma swój własny e-mail w postaci ```sprawa-XX@porady.siecobywatelska.pl```. 

Realizowane jest to w funkcji https://github.com/watchdogpolska/poradnia/blob/master/poradnia/letters/models.py#L126, która wywołuje ```Case.objects.by_msg(message).get()```, aby otrzymać numer sprawy z wiadomości. Aby otrzymać adres wiadomości wykorzystywany jest atrybut ```django_mailbox.models.Message.to_addresses```. Niestety, w skutek tego funkcja ```Case.by_msg``` bada tylko pierwszy adres z pola "To:", a nie są brane pod uwagę takie pola jak "CC:". Z względów technicznych pole "BCC:" w ogóle nie może być brane pod uwagę. 

Proponuje wykorzystać pole "Envelope-to", które jest przypisywane już przez nasz serwer, zamiast pierwszego adresu z pola "To:" wyparsowanego przez django-mailbox. Przejrzałem wszystkie dotychczas zgromadzone w systemie wiadomości. Wszystkie mają ten nagłówek i poprawne wartości.

```python
import email
from letters.models import Letter

for e in Letter.objects.filter(eml__isnull=False).filter(message__isnull=False).all():
    msg = email.message_from_file(e.eml)
    print e.case_id, msg['Envelope-to']
    e.eml.close()
```

**Comment by rwakulszowa** [comment]
Czy jest jakiś prosty sposób wywołania tej funkcji? https://github.com/watchdogpolska/poradnia/blob/master/poradnia/letters/models.py#L126
Wygląda na to, że zwykłe założenie nowej sprawy bez logowania nie wywołuje funkcji mail_process. Wynika to z ustawień środowiska testowego, czy po prostu ta funkcja wywoływana jest w innych warunkach? Czy jest jakiś prosty sposób na ominięcie tego problemu?

Druga sprawa to brak szablonu case/email/case_many.txt - póki co nie pojawia się błąd, ponieważ skrypt nigdy nie zwraca MultipleObjectsReturned.

**Comment by ad-m** [comment]
Szanowny,

Założenie zwykłej sprawy z wykorzystaniem formularza nie wykorzystuje funkcji ```poradnia.letters.models.mail_process```, która jest wywoływana w przypadku odbioru wiadomości przez ```django-mailbox``` z wykorzystaniem tradycyjnej poczty elektronicznej. Wykorzystywany jest w tym zakresie mechanizm sygnałów ( https://django-mailbox.readthedocs.org/en/latest/topics/signal.html  https://docs.djangoproject.com/en/1.9/topics/signals/ ). Zobacz również na sposób wzbudzenia sygnału w https://github.com/coddingtonbear/django-mailbox/blob/master/django_mailbox/models.py#L263 . 

Dziś opracuje podstawowy TestCase dla przetwarzania wiadomości na podstawie pliku ```eml```.

**Comment by rwakulszowa** [comment]
Mam pytanie odnośnie pól wiadomości. 
W załączonym do testów pliku, w nagłówku "Envelope-To" jest tylko jeden adres. Poza nim jest też nagłówek "Cc", w którym znajdują sie pozostałe adresy. Czy poprawnym rozwiązaniem problemu nie jest iteracja po zbiorze adresów "Cc" i "To" (to wcześniejszym usunięciu ewentualnych duplikatów)?

```
ipdb> message.get_email_object().keys()
['Return-path', 'Envelope-to', 'Delivery-date', 'Received', 'Received', 'DKIM-Signature', 'X-Google-DKIM-Signature', 'X-Gm-Message-State', 'MIME-Version', 'X-Received', 'Sender', 'Received', 'In-Reply-To', 'References', 'Date', 'X-Google-Sender-Auth', 'Message-ID', 'Subject', 'From', 'To', 'Cc', 'Content-Type', 'X-HEKKO']
ipdb> message.getmessage.get_email_object()['Cc']
'sprawa-639@porady.siecobywatelska.pl, \n =?UTF-8?B?UGF1bGEgS8WCdWNpxYRza2E=?= <[[CENZURA___4]]@siecobywatelska.pl>'
ipdb> message.getmessage.get_email_object()['Envelope-To']
'sprawa-639@porady.siecobywatelska.pl'
ipdb> message.get_email_object()['To']
'=?UTF-8?Q?Szymon_Osowski_Sie=C4=87_Obywatelska_Watchdog_Polska?=\n <[[CENZURA___5]]@siecobywatelska.pl>'
```

Pozostaje jeszcze sprawa szablonu. Jeśli się nie mylę, po poprawieniu błędu funkcja `Case.by_msg` będzie w niektórych przypadkach zwracać wyjątek `Case.MultipleObjectsReturned`. Funkcja `mail_process` w takim wypadku wysyła szablon `case/email/case_many.txt`, jednak póki co ten szablon nie istnieje. Czy zapodział się pod jakąś inną nazwą, czy po prostu nie został dodany?
https://github.com/watchdogpolska/poradnia/blob/master/poradnia/letters/models.py#L150

**Comment by ad-m** [comment]
Szanowny,

W przypadku, gdy ktoś umieści adres Poradni w polu ```UCC``` nie będziemy mieli adresu Poradni nigdzie poza polem ```Envelope-to```, które jest dopisywane do nagłówków przez nasz serwer pocztowy. W przypadku G^Maila jest dopisywany nagłówek ```Delivered-to````. Nie jest to więc standard, ale w przypadku wykorzystywanego serwera pocztowego - jak sprawdziłem - jest prawidłowe. Myślę, że z tego względu warto rozważyć, aby np. wprowadzić jakąs formę konfiguracji pod różne serwery np. callback, który zwróci listę adresów e-mail. 

Typowa sesja SMTP wygląda następująco:
```
220 serwer ESMTP Exim 4.43 Wed, 12 Jan 2005 23:14:13 +0100
helo serwer.email.com
250 uzytkownik.internet.com Hello uzytkownik at uzytkownik.internet.com [1.1.1.1]
mail from: <nadawca@example.org>
250 OK
rcpt to: <odbiorca@example.org>
250 Accepted
data
354 Enter message, ending with "." on a line by itself
Date: 03 Jan 07 21:21:21
From: nadawca@example.org
To: odbiorca@example.org
Subject: temat wiadomosci

tresc wiadomosci
.
250 OK id=1Coql6-0003Qi-MP
quit
221 serwer.email.com closing connection
```
Jak widzisz w tym przykładnie dwukrotnie są przesyłane dane adresata. Pełne i wyczerpujące dane są zawarte przy poleceniu ```rcpt to```, które przy odbieraniu wiadomości są zapisywane przez nasz serwer pocztowy do pola "Envelope-to". Dzięki temu możliwe są wiadomości takie jak:
![zaznaczenie_453](https://cloud.githubusercontent.com/assets/3618479/14365680/4172acf6-fd0f-11e5-847f-929b1ea886dd.png)
Oczywiście nie mam adresu e-mail "cbosa-648@googlegroups.com", a mimo to skutecznie wrzucono mi wiadomośc do skrzynki.

Zobacz także na https://www.fastmail.com/help/receive/emailnottome.html .

**Comment by rwakulszowa** [comment]
Dodałem zmiany, test działa poprawnie. Myślę, że przed wykonaniem PR trzeba będzie jeszcze podjąć jedną decyzję. Pole Envelope-To zawiera adresata w formie stringa, dlatego usunąłem pętlę for. Czy mamy gwarancję, że pole Envelope-To zawsze będzie zawierać tylko jeden numer sprawy? Jeżeli możliwe jest, że znajdą się tam dwa adresy, trzeba będzie dodać proste parsowanie i konwertować string na listę adresów. Jeśli natomiat pole zawsze będzie zawierać jeden adres, można usunąć obsługę `Case.MultipleObjectsReturned` w https://github.com/watchdogpolska/poradnia/blob/master/poradnia/letters/models.py#L126

**Comment by ad-m** [comment]
Nie mogę znaleźć żadnej dokumentacji dla ```Envelope-to```, co nam nie daje gwarancji przyszłego działania, lecz przeanalizowałem wszystkie wiadomości, które dotąd otrzymaliśmy.
```
$ grep 'Envelope-to' * >> emaile.txt
2053
$ ls -1 | wc -l 
2054
$ egrep -v -e 'Envelope-to: (sprawa-[0-9]+@porady.siecobywatelska.pl|noreply@porady.siecobywatelska.pl|[pP]orady@siecobywatelska.pl)$' emaile.txt | wc -l
0
$ # Bez flagi "-v" i bez "wc -l" znajduje pożądane wyniki.
```
Daje to nam podstawy, aby założyć, że nie wystąpi przypadek ```Case.MultipleObjectsReturned```.
