### ISSUE TITLE
Nieprawidłowe nazwy użytkowników w wiadomościach e-mail

### ISSUE THREAD

**Issue by ad-m** [watchdogpolska/poradnia#204]
Problem: W przypadku automatycznej rejestracji za pośrednictwem adresu e-mail użytkownik dostaje automatyczne powiadomienie o nadanej nazwie użytkownika. Niestety, nazwa ta jest podczas zapisu do bazy danych obcinana. W skutek tego inna nazwa użytkownika (dłuższa) jest przesyłana za pośrednictwem wiadomości, a inna jest zapisywana w bazie danych. 

Rozwiązanie: ujednolicić.

**Comment by ad-m** [comment]
Szanowny @rwakulszowa ,

Czy maiłbyś ochotę naprawić ten issues? 

Problem znajduje się w poradnia.users.models.CustomUserManager.{email_to_unique_username,register_email}. Napisałem na gałęzi issue-204 test, który pozwala na potwierdzenie występowania usterki.

Z poważaniem,

**Comment by ad-m** [comment]
https://github.com/watchdogpolska/poradnia/tree/issue-204

**Comment by rwakulszowa** [comment]
Jasne, zajmę się tym.

**Comment by ad-m** [comment]
Close by PR #211
