### ISSUE TITLE
Statystyki

### ISSUE THREAD

**Issue by ad-m** [watchdogpolska/poradnia#206]
- [ ]  liczba spraw, które wpłynęły w rozbiciu miesięcznym i tygodniowym,
- [ ]  średni czas pierwszej reakcji w sprawie w rozbiciu miesięcznym i ogólnym,
- [ ]  liczba spraw bez odpowiedzi,
- [x]  średni czas przypisania sprawy (możliwe w ogóle?),

**Comment by ad-m** [comment]
Hej,

Zaszła potrzeba przygotowania statystyk przedstawiających działanie aplikacji. Należy w tym celu przygotować wykresy obrazujące gromadzone dane. Myślę, że warto na stałe rozbudować o to aplikacje.

Nie mam szczególnych preferencji co do rozwiązania, o ile będzie to wydajne. Dane miesięczne i tygodniowe nie muszą być w czasie rzeczywistym aktualizowane. Możesz wykorzystać dowolne biblioteki służące do wykresów itd., bo dotąd aplikacja nie ma żadnyc rozwiązań, które można by ponownie wykorzystać. W zakresie django zwracam uwagę na listy "awesome-django", które agregują interesujące biblioteki.

Liczba spraw, które wpłynęły w rozbiciu miesięcznym i tygodniowym tzn. liczba spraw (``cases.models.Cases``) według pola ``created_on``.

Średni czas pierwszej reakcji w sprawie w rozbiciu miesięcznym i ogólnym - każda sprawa ma przypisane ``records.Record`` (rekord). Specyficznego rodzaju rekord to ``letters.Letter`` (list), który ma różne statuty. Pismo, które klient otrzymał ma ``status==Letter.STATUS.done``. Moment akceptacji jest rejestrowany w polu ``accept``. Interesuje nas zatem różnica pomiędzy utworzeniem sprawy dla listu, a pierwszym accept, który ```status==Letter.STATUS.done``` (ukończone pismo) i pochodzi od zespołu (``created_by__is_staff=True``).

Liczba spraw bez odpowiedzi może być obliczona na podstawie zdenormalizowanego pola (możliwego do wyliczenia także na podstawie ``letters.Letters``, ale odstąpiłem ze względu na wydajność) w ``cases.models.Case.last_send``. Pole powinno mieć wartość Null, jeżeli brak jest opdowiedzi. Przenalizuj ``cases.models.Case.update_counters``, które jest wywoływane przy tworzeniu listów i odwołuje się do ``letters.models.LetterQuerySet``.

Na początek proponuje, abyś wymyślił w jaki sposób pobierzesz dane z bazy. Wolałbym wykorzystać w tym celu ORM, ale jeżeli kod będzie miał testy to natywny SQL też jest spoko. 

Testowe dane możesz wygenerować przez ``python poradnia/manage.py loadtestdata users.User:10 cases.Case:25 letters.Letter:25``, a żywe laboratorium uruchomić przez ``python poradnia/manage.py shell``.

Istotna będzie dla Ciebie dokumentacja Django odnośnie agregowania ( https://docs.djangoproject.com/en/1.9/topics/db/aggregation/ ).

Zwracam uwagę na:
```python
from django.db.models import IntegerField, Func, F
from cases.models import Case
Case.objects.annotate(week=Func(F('created_on'), function='week', output_field=CharField())).all().query
```
Wywołuje on kod:
```sql
SELECT `cases_case`.`id`, `cases_case`.`name`, `cases_case`.`status`, `cases_case`.`status_changed`, `cases_case`.`client_id`, `cases_case`.`letter_count`, `cases_case`.`last_send`, `cases_case`.`last_action`, `cases_case`.`last_received`, `cases_case`.`deadline_id`, `cases_case`.`created_by_id`, `cases_case`.`created_on`, `cases_case`.`modified_by_id`, `cases_case`.`modified_on`, `cases_case`.`handled`, `cases_case`.`has_project`, week(`cases_case`.`created_on`) AS `week` FROM `cases_case` ORDER BY `cases_case`.`last_send` ASC
```

**Comment by ad-m** [comment]
1. 
```python
Case.objects.annotate(month=Func(F('created_on'), function='month', output_field=IntegerField())).annotate(year=Func(F('created_on'), function='year', output_field=IntegerField())).values('month','year').annotate(count=Count(F('id'))).values('month','year','count').order_by(F('year'), F('month')).query
```
````sql
SELECT month(`cases_case`.`created_on`) AS `month`, year(`cases_case`.`created_on`) AS `year`, COUNT(`cases_case`.`id`) AS `count` FROM `cases_case` GROUP BY month(`cases_case`.`created_on`), year(`cases_case`.`created_on`) ORDER BY year(`cases_case`.`created_on`) ASC, month(`cases_case`.`created_on`) ASC
````
Może trochę straszne to sosrtowanie, ale to konsekwencja ograniczeń ORM Django. Nie mamy nawet 5 tysięcy rekordów, więc szybko nie będzie to problematyczne zapytanie, jeżeli będzie jakikolwiek cache.

**Comment by rwakulszowa** [comment]
Dodałem trochę nowych funkcjonalności, uporządkowałem kod, dodałem część testów.
https://github.com/watchdogpolska/poradnia/compare/master...rwakulszowa:feature/stats
Jeszcze brakuje paru z zaplanowanych na ten moment rzeczy (tłumaczenia, dodatkowe pola - średnia itp., testy api, widok tygodniowy, format kodu d3 jeszcze trochę ulegnie zmianie), ale całość przypomina mniej więcej efekt końcowy.
Mam prośbę o pobieżny przegląd kodu i uwagi jeśli coś jest nie tak. Oczywiście nic pilnego, w najbliższych dniach i tak nie będę miał za bardzo czasu.

Z ważniejszych spraw:
- zapytania do bazy danych nie działają poprawnie w SQLite (funkcja month), więc dodałem dekorator do warunkowego pomijania testów; w MySQL jest ok
- w django-braces `SuperUserRequired` jest bug powodujący pętlę przekierowań, stąd obejście `raise_unless_authenticated` w pliku utils. Zastanawiam się czy da się zbudować url z parametrem next w jakiś ładniejszy sposób
- klasa GapFiller ma za zadanie wypełnić luki w ciągach dat - jeśli np. żadna sprawa nie powstała w marcu 2016, klasa wstawia w tablicę danych odpowiedni obiekt z licznikiem ustawionym na 0, podczas gdy samo zapytanie do bazy danych nie zwróciłoby żadnego pola (byłyby tylko dane z lutego i kwietnia). Klasa jest dość dobrze przetestowana, więc wszystko powinno działać ok
- każdy z widoków API poza zapytaniem do bazy przetwarza jeszcze dane w pythonie. Jest to jednak operacja na danych już pogrupowanych, więc nie powinno to mieć wyraźnego wpływu na czas działania aplikacji
- w `StatsCaseReactionApiView` konieczne było dodanie obliczania pola `time_delta` dla każdego obiektu już w pythonie. Jest to spowodowane prawdopodobnym błędem Django - odejmowanie dwóch dat daje błędne wyniki (godziny są minutami a minuty dodają się do sekund), niezałeżnie od zastosowanego `output_field`

Myślę, że najważniejsze funkcjonalności działają poprawnie, więc niedługo powinno być możliwe wdrożenie funkcjonalności. Jeśli chodzi o ewentualne osadzanie wykresów na stronie, jest to możliwe w zasadzie w dowolnym miejscu. Generowane obrazy to SVG, które bardzo dobrze skalują się do dowolnych rozmiarów. Jeśli zajdzie potrzeba, ten sam kod można wykorzystać także w innych projektach watchdogpolska - wymagane zmiany w kodzie powinny być minimalne.

**Comment by ad-m** [comment]
@mik-laj , w wolnej chwili spójrz na kwestie front-endowe, proszę.

Bliżej się temu kodowi przyjrzę w środku weekendu. Jednak dziwi mnie sposób w jaki pomijasz testy. Wydaje mi się, że do tego zostało stworzone ```unittest.skipIf``` ( https://docs.python.org/2/library/unittest.html#unittest.skipIf ). Ponadto odwoływanie się bezpośrednio do zmiennej środowiskowej, zamiast do konfiguracji (```DATABASE_URL```) jest - w mojej ocenie słabe. Najlepiej jednaj moim zdaniem odwołać się do ```django.db.connection.vendor```, które przyjmie wartość np. ```postgresql```,```sqlite```,```mysql```. Tak rozwiązuje się te zagadnienie w core django ( https://github.com/django/django/blob/ecb59cc6579402b68ddfd4499bf30edacf5963be/tests/postgres_tests/__init__.py#L7 , https://github.com/django/django/blob/ecb59cc6579402b68ddfd4499bf30edacf5963be/tests/backends/test_mysql.py#L10 , https://github.com/django/django/blob/ecb59cc6579402b68ddfd4499bf30edacf5963be/tests/backends/tests.py#L49 , https://github.com/django/django/blob/ecb59cc6579402b68ddfd4499bf30edacf5963be/tests/backends/tests.py#L107).

**Comment by rwakulszowa** [comment]
Rzeczywiście, jeśli istnieje funkcja zwracająca typ bazy danych, jest to dużo lepsze rozwiązanie niż sprawdzanie zmiennej. Co do dekoratora, zrobiłem to w taki sposób ze względu na fakt, iż używany on będzie dla bardzo dużej ilości testów, zawsze w takiej samej postaci - uznałem, że lepiej zrobić własny dekorator niż w kółko powtarzać ten sam kod w `skipIf`. Oczywiście mogę to zmienić.

**Comment by AgnieszkaZdanowicz** [comment]
hm... czy to jest to, co mamy na BI?

**Comment by ad-m** [comment]
Nie, to było widoczne na https://porady.siecobywatelska.pl/statystyki/ .
