### ISSUE TITLE
Gdy znawa załącznika jest za długa post dodaje się błędnie

### ISSUE THREAD

**Issue by farmazon3000** [watchdogpolska/poradnia#210]
Korzystam z http://porady.siecobywatelska.pl.

Chciałem zgłosić nową sprawę i dodałem treść oraz załącznik, kliknąłem "Zgłoś sprawę" i nie dostałem informacji że coś poszło nie tak, jednak sprawa nie dodała się poprawnie:
http://porady.siecobywatelska.pl/sprawy/sprawa-804/
nie ma ani załącznika ani treści.

Gdy potem spróbowałem zrobić to inaczej dostałem informację że nazwa załącznika jest za długa (101 znaków) co pewnie spowodowało ten problem.

BTW. sprawę o numerze 804 można usunąć z bazy danych.

**Comment by ad-m** [comment]
Dziękuje za zgłoszenie. 

Co znaczy "zrobić to inaczej"?

**Comment by farmazon3000** [comment]
najpierw napiałem post i gdy juz sie stworzyl probowalem dodac zalacznik
