### ISSUE TITLE
Jak zrobić link między jednym zgłoszeniem a drugim?

### ISSUE THREAD

**Issue by farmazon3000** [watchdogpolska/poradnia#212]
Jak zrobić link między jednym zgłoszeniem a drugim?

**Comment by ad-m** [comment]
Napisać #numer. Nie tworzą się linki.

**Comment by farmazon3000** [comment]
No właśnie widzę że się nie tworzą a szkoda bo byłoby wygonie.

**Comment by ad-m** [comment]
W drobnej ilości spraw, a dostrzegam, że zwiększyłoby to istotnie złożoność, bo musimy uwzględnić kontrolę uprawnień na poziomie każdego issues dla każdego użytkownika, aby wyświetlić linki wtedy i tylko wtedy, gdy ktoś ma link do danej sprawy. Myślę, że nie jest to dość częsta sytuacja, a uwzględniam ograniczenia zasobów programistycznych.

**Comment by farmazon3000** [comment]
rozumiem, dzieki, faktycznie na 15 zgloszonych spraw to pierwszy link ktory chcialem zrobic :)

**Comment by ad-m** [comment]
Uwzględnij jeszcze, że musi być przypisana ta sama osoba do obsługi (administracja widzi wszystkie sprawy i je rozdziela, czasem zatwierdza pismo, a wsparcie przygotowuje pismo w konkretnej sprawie), a prawdopodobieństwo jeszcze bardziej spada, że pojawi się link :-)
