### ISSUE TITLE
Niezgodność wersji Django i django-Filter

### ISSUE THREAD

**Issue by mik-laj** [watchdogpolska/poradnia#217]
Dzień dobry,

Domyślnie instaluje mi się projekt z Django 1.7 i django-filter w wersji 0.12.0, a django-filter w tej wersji wymaga Django conajmniej 1.8. 

Z wyrazami szacunku

**Comment by ad-m** [comment]
W jaki sposób instalujesz projekt, że tylko django 1.7 instaluje Ci się? Mnie się instaluje dj 1.9.

**Comment by ad-m** [comment]
Wobec braku informacji zwrotnej - zamykam.

**Comment by mik-laj** [comment]
Teraz zrobiłem od nowa projekt i mam `1.9.5`
