### ISSUE TITLE
Usuwanie oznaczenia projektu

### ISSUE THREAD

**Issue by ad-m** [watchdogpolska/poradnia#219]
Szanowny,

W aplikacji występują projekty pism. Są to pisma widoczne dla zespołu, ale przy ich dodawaniu zmieniony jest atrybut sprawy ```has_project``` na True w ramach ```AddLetterForm```, aby potem wyświetlać informacje o takim projekcie na wykazie spraw. Taka "wersja robocza" z programu pocztowego.

Zachodzi potrzeba dodania funkcjonalności usuwania tej flagi. Sytuacja analogiczna ```CaseCloseView``` z tym, że teraz ```case.has_project = False``` będzie ustawione. 

Czy miałbyś ochotę przygotować odpowiednią poprawkę?

Z poważaniem,

**Comment by rwakulszowa** [comment]
Nie jestem pewien czy dobrze rozumiem - chodzi o ustawienie flagi case.has_project na false za każdym razem, gdy sprawa zmienia status na close? W takim razie potrzebne będzie wprowadzenie zmian w CaseCloseView i CaseUpdateView. Czy są jeszcze jakieś sytuacje, które trzeba wziąć pod uwagę? Z tego co wiem, gdzieś w kodzie obsługiwane jest ponowne otwarcie uprzednio zamkniętych spraw. Czy tam też trzeba jakoś obsłużyć tę flagę?

**Comment by ad-m** [comment]
Szanowny,

```has_project``` ma być niezależne od zamykania spraw. Przywołałem jako przykład, bo ma taki sam mechanizm działania.

Należy stworzyć nowy widok, który ustawi ```has_project=False``` np. nazwany ```CaseRemoveProjectView```, w taki sam sposób jak ```CaseCloseView``` ustawia ```status = Case.STATUS.closed```.

Obecnie ```has_project=False``` jest ustawiane, gdy jest wysyłany (akceptowany) nowy projekt do sprawy, ale jest to niewystarczające. Trzeba wprowadzić mechanizm usuwania oznaczenia ```has_project```, które nie będzie wymagało wysłania pisma.

Z poważaniem,

**Comment by rwakulszowa** [comment]
Ok, rozumiem.
Interesuje nas tylko sytuacja w jedną stronę, tj. True -> False, czy także zmiana w drugą stronę, np. przy omyłkowej edycji? W takiej sytuacji pewnie wygodniej byłoby dodać rozwijaną listę z polami True/False. Ewentualnie jest jeszcze opcja dodania tego pola do CaseUpdateView.
Tak czy inaczej, poprawka nie powinna zająć zbyt wiele czasu, postaram się tym zająć w najbliższym tygodniu.

**Comment by ad-m** [comment]
Słuszna myśl, aby po prostu zmienić CaseUpdateView, a raczej w odpowiednim
formularzu :-)

W dniu sobota, 2 kwietnia 2016 rwa <notifications@github.com> napisał(a):

> Ok, rozumiem.
> Interesuje nas tylko sytuacja w jedną stronę, tj. True -> False, czy także
> zmiana w drugą stronę, np. przy omyłkowej edycji? W takiej sytuacji pewnie
> wygodniej byłoby dodać rozwijaną listę z polami True/False. Ewentualnie
> jest jeszcze opcja dodania tego pola do CaseUpdateView.
> Tak czy inaczej, poprawka nie powinna zająć zbyt wiele czasu, postaram się
> tym zająć w najbliższym tygodniu.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/watchdogpolska/poradnia/issues/219#issuecomment-204741822>
>


-- 
Wysłano z Gmaila na komórki

**Comment by rwakulszowa** [comment]
#223 Merged
