### ISSUE TITLE
KeyError: 'case'

### ISSUE THREAD

**Issue by ad-m** [watchdogpolska/poradnia#225]
//sentry.jawne.info.pl/sentry.jawne.info.pl/watchdogpolska/poradnia/group/852/

```
KeyError: 'case'
(2 additional frame(s) were not displayed)
...
  File "events/forms.py", line 15, in __init__
    self.case = kwargs.pop('case')
```

**Comment by ad-m** [comment]
http://porady.siecobywatelska.pl/wydarzenia/wydarzenie-47
![zaznaczenie_450](https://cloud.githubusercontent.com/assets/3618479/14363408/63a0c57a-fd04-11e5-9bac-cbe180ac4e3f.png)

**Comment by rwakulszowa** [comment]
Wygląda na to, że dodanie metody
```
def get_form_kwargs(self, *args, **kwargs):
        kwargs = super(EventUpdateView, self).get_form_kwargs(*args, **kwargs)
        kwargs['case'] = self.object.case
        return kwargs
```
do `EventUpdateView` rozwiązuje problem.

**Comment by ad-m** [comment]
Szanowny,

Jeżeli w tytule commita napiszesz " - close #225" to automatycznie będą się zamykać odpowiednie issues po zmergowaniu commita. Zachęcam ( https://github.com/tiimgreen/github-cheat-sheet#closing-issues-via-commit-messages ).

Dla mnie kod wygląda OK. Zgłosiłem, bo dostałem powiadomienie o usterce (Sentry FTW!), zajmowałem się czymś innym, ale w tym momencie chciałem napisać o mojej wiedzy użytkownikowi, któremu objawił się problem. Dziś planowałem się tym zająć. Już nie muszę :smile_cat:  Dziękuje.
