### ISSUE TITLE
UserDetailView i sprawna kontrola uprawnień

### ISSUE THREAD

**Issue by ad-m** [watchdogpolska/poradnia#227]
W widoku obecnie dla użytkowników wyświetlamy 404, gdy nie mają uprawnień. 

Należy wprowadzić:

- dla niezalogowanych - przekierowanie do 404,
- dla zalogowanych uprawnionych - wyświetlanie,
- dla zalogowanych nieuprawnionych - brak uprawnień (uwaga na pętle przekierowań),
- dla zalogowanych nieuprawnionych oglądających siebie - wyświetlanie,

Można by także wprowadzić templatetag służy do linkowania profilu użytkownika z uwzględnieniem w/w logiki.

**Comment by rwakulszowa** [comment]
Przy okazji feature/stats częściowo zająłem się problemem pętli przekierowań. Myślę, że podobne rozwiązanie można tutaj wykorzystać.
Tam akurat niezalogowany użytkownik jest przekierowywany do okna logowania.

-----Wiadomość oryginalna-----
Od: "Adam Dobrawy" <notifications@github.com>
Wysłano: ‎2016-‎04-‎08 13:39
Do: "watchdogpolska/poradnia" <poradnia@noreply.github.com>
Temat: [watchdogpolska/poradnia] UserDetailView i sprawna kontrola uprawnień (#227)

W widoku obecnie dla użytkowników wyświetlamy 404, gdy nie mają uprawnień. 
Należy wprowadzić:
dla niezalogowanych - przekierowanie do 404, 
dla zalogowanych uprawnionych - wyświetlanie, 
dla zalogowanych nieuprawnionych - brak uprawnień (uwaga na pętle przekierowań), 
dla zalogowanych uprawnionych oglądających siebie - komunikat, 
Można by także wprowadzić templatetag służy do linkowania profilu użytkownika z uwzględnieniem w/w logiki.

**Comment by ad-m** [comment]
@rwakulszowa , pamiętasz o tym? Pracujesz nad tym?

**Comment by rwakulszowa** [comment]
Do końca tygodnia postaram się dopisać kod.

**Comment by ad-m** [comment]
Dziękuje.

**Comment by rwakulszowa** [comment]
Czy na pewno chcemy zawsze zwracać 403 lub 404? I czy faktycznie chcemy dać 404 zamiast 403 dla niezalogowanych?
Jest możliwość przekierowania niezalogowanych użytkowników do strony logowania, natomiast dla zalogowanych zwracanie 403, czy to nie byłoby prostsze?
Swoją drogą, UserListView też wymaga dopracowania, póki co zapytanie do /uzytkownik/ powoduje pętle przekierowań.

**Comment by ad-m** [comment]
Hmm…Pisałem to z założeniem, że nazwa użytkownika stanowi dane sensytywne wobec osób zewnętrznych, ale w sumie to można sprawdzić przy rejestracji, więc było to błędne założenie, a nam upraszcza.

- dla niezalogowanych - przekierowanie do ekranu logowania,
- dla zalogowanych uprawnionych i dla oglądających samych siebie (chodzi o nie tworzenie w bazie danych rekordów redundantnych) - wyświetlanie,
- dla zalogowanych nieuprawnionych - brak uprawnień.

**Comment by ad-m** [comment]
> Czy na pewno chcemy zawsze zwracać 403 lub 404? 
Dziękuje za pytanie. Nie.
> I czy faktycznie chcemy dać 404 zamiast 403 dla niezalogowanych?
Dziękuje za pytanie. Nie.
> Jest możliwość przekierowania niezalogowanych użytkowników do strony logowania, natomiast dla zalogowanych zwracanie 403, czy to nie byłoby wygodniejsze?
Dziękuje za pytanie. Tak.

**Comment by rwakulszowa** [comment]
Jeśli da się lepiej rozwiązać sprawy
- sprawdzania czy użytkownik ogląda sam siebie
- tworzenia urla do `redirect`

to proszę o sugestię.

Pozostaje jeszcze kwestia treści komunikatu przy 403 i poprawka dla `UserListView`
