### ISSUE TITLE
Pytanie o potwierdzenie wylogowania wydaje się niepotrzebne

### ISSUE THREAD

**Issue by tradzik** [watchdogpolska/poradnia#233]
W mojej ocenie pytanie się o to , czy na pewno użytkownik się chce wylogować nie ma większego sensu. Nawet, gdyby użytkownik kliknął to przez przypadek, to nie straci zbyt wiele. Na ogół przyciski do wylogowywania mają działać szybko. Ewentualnie proponuję okno dialogowe z pytaniem "czy na pewno wylogować", a nie aktualne przekierowanie na inną stronę z pytaniem. Jest to mylące. Z góry dziękuję za rozważenie mojego issue'sa :smile:

**Comment by mkutyba** [comment]
Wg mnie miało to być zabezpieczenie przed CSRF. Można zabezpieczyć to inaczej, np. wylogowując przez POST zamiast GET.

**Comment by AgnieszkaZdanowicz** [comment]
To aktualne, chociaż mi to szczególnie nie przeszkadza

**Comment by AgnieszkaZdanowicz** [comment]
To aktualne, chociaż mi to szczególnie nie przeszkadza

**Comment by PiotrIw** [comment]
Można poprawić dodając przycisk "zaloguj/wyloguj" bezposrednio na menu bocznym i trochę js na froncie który ro obsłuży. Wówczas logowanie by było w popup'ie a nie na podstronie tak jak teraz. 
@AgnieszkaZdanowicz - chyba niski prorytet, choć robota też nie za duża?

**Comment by AgnieszkaZdanowicz** [comment]
@PiotrIw ok, to zamykam :)
