### ISSUE TITLE
Filtrowanie po sprawach, w których są projekty zapisane

### ISSUE THREAD

**Issue by ad-m** [watchdogpolska/poradnia#241]
#240 
Modyfikacja ```StaffCaseFilter```

**Comment by rwakulszowa** [comment]
Mowa tu o polu `has_project`?
Wystarczy dodac nowe pole, czy trzeba pozmieniac cos jeszcze? https://github.com/watchdogpolska/poradnia/blob/master/poradnia/cases/filters.py#L35

**Comment by ad-m** [comment]
```StaffCaseFilter.Meta.fields +=['has_project']``` + testy odpowiednio
