### ISSUE TITLE
Statystyki dla wolontariuszy

### ISSUE THREAD

**Issue by ad-m** [watchdogpolska/poradnia#242]
#240

> statystyki dla wolontariuszy (to już trochę jest w wykazie użytkowników) - pojawia się, ile spraw ktoś ma przypisanych, a czy mogłoby się to dzielić na sprawy aktywne i sprawy zamknięte? to by było super, nie musiałabym wchodzić w każdego oddzielnie, tylko od razu bym wszystko widziała

**Comment by rwakulszowa** [comment]
https://github.com/watchdogpolska/poradnia/blob/master/poradnia/users/templates/users/user_filter.html#L45
https://github.com/watchdogpolska/poradnia/blob/master/poradnia/users/models.py#L33
Mozna zwrocic tuple albo slownik i dodac do html.

**Comment by ad-m** [comment]
Dziś rozmawiałem z Agnieszką. Przy okazji wynikło, że pasowałoby, aby widok sprowadzić do tabeli, bo teraz jest lekki chaos i nie spełnia swojej funkcji informacyjnej. Kiedyś był zamysł, aby wykaz choćby zespołu był publiczny, ale Szymon (Prezes) zdecydował odmiennie. 

Należy w tym miejscu uważać, aby Django zbudowało co najmniej dość optymalne zapytanie SQL.

**Comment by rwakulszowa** [comment]
Zacząłem się przyglądać tej sprawie: https://github.com/watchdogpolska/poradnia/compare/master...rwakulszowa:feature/volunteer_stats
Mam pytanie odnośnie działadnia aplikacji - w jaki sposób możliwe jest przypisanie kogoś do sprawy? Z tego co widzę, przy utworzeniu nowej sprawy aplikacja automatycznie przypisuje autora. Czy da się to jakoś zmodyfikować? Czy do sprawy może być przypisanych kilka osób jednocześnie?
Jeśli dobrze rozumiem, sprawa może być przypisana do kogoś, ale nadal mieć status "wolna". Czy w wykazie użytkowników powinienem dodać licznik spraw o statusie "wolna"?

**Comment by rwakulszowa** [comment]
Przy okazji - wydaje mi się, czy filtrowanie spraw po osobie przypisanej nie daje żadnego efektu?

**Comment by ad-m** [comment]
1/ Przypisanie kogoś do sprawy oznacza, że dana osoba ma jakiekolwiek indywidualne uprawnienia do sprawy. Dla nowych spraw dopisanie autora jest realizowane w https://github.com/watchdogpolska/poradnia/blob/master/poradnia/cases/models.py#L323 . Do sprawy może być dopisanych wiele osób. 
Sprawa jest oznaczana jako przypisana, gdy jest przypisany członek zespołu, który może napisać do klienta (niektórzy członkowie nie mogą). Sprawa może być przypisana do kogoś i być wolna, gdy:
- zostanie przypisana do osoby, która jest w zespole i nie może pisać do klienta (poczatkujący wolontariusze),
- zostanie przypisany do niej klient (automatycznie, ale też może się dziać ręcznie).


2/ Sprawdź na nie administratorze (por. #243). Zbadam.

**Comment by rwakulszowa** [comment]
Racja, sprawdzałem tylko dla adminów, a wcześniej nie zaktualizowałem mastera, przez co zmiany jeszcze  nie działają na mojej gałęzi.

Co do 1, czy w takim razie dodać też liczenie wolnych spraw?
Jeśli chodzi o sam wygląd listy użytkowników, rozumiem że powinien jak najbardziej przypominać wykaz spraw?

**Comment by ad-m** [comment]
1/ @rwakulszowa , a jak będzie Tobie wygodniej zaimplementować? Mi trudno przewidzieć na ten moment co się będzie bardziej sprawdzać, chociaż myślę, że - tak jak Agnieszka proponuje - ograniczenie do aktywnych i zamkniętych będzie czytelniejsze.
Tak, zmierzajmy w kierunku tabeli.

**Comment by rwakulszowa** [comment]
Wydaje mi się, że podanie tylko 2 z 3 parametrów jest mało intuicyjne. Poza tym, pewnie przydatne byłoby też podanie sumy wszystkich spraw przypisanych do użytkownika (tak jak do tej pory). Skoro podajemy sumę, sprawy przypisane i sprawy zamknięte, możemy do kompletu dodać sprawy wolne - i tak mamy mnóstwo miejsca po zmianie widoku na typową listę.
