### ISSUE TITLE
Blokada wysyłania pism do zespołu

### ISSUE THREAD

**Issue by ad-m** [watchdogpolska/poradnia#244]
> żeby jak się wybiera opcję "odpowiedz do zespołu", to nie pojawiała się potem adminowi opcja wyślij. To było przydatne, jak nie było projektów, a teraz to jest niebezpieczne, bo często tą opcją piszemy wiadomości, których klienci nie powinni widzieć. Tak więc wiadomość wysłana jako "odpowiedź dla zespołu" powinna być ostateczna i bez opcji modyfikacji czy wysłania do klienta.
> # 240

**Comment by rwakulszowa** [comment]
Zdaje sie, ze konieczna bedzie zmiana tutaj https://github.com/watchdogpolska/poradnia/blob/master/poradnia/letters/forms.py#L143

**Comment by ad-m** [comment]
Mam obawy, że nie ma co dostosywać, ale wobec istotnego zmienienia ```flow``` obsługi dokumentów należy przemyśleć w dalszym ciągu zasady pola ```status```. Już wczesniej miałem taką myśl (por. #157). Zajmę się tym uwzględniając całość aplikacji.

**Comment by ad-m** [comment]
Zmiana jest konieczna w samym modelu, bo dotąd nie mieliśmy pisma o statusie "draft", tylko było "staff", "done", co wynikło z tego, że wcześniej miała być mniejsza ilość przycisków.

**Comment by AgnieszkaZdanowicz** [comment]
radzimy sobie jakoś, więc to nie jest priorytet, ale w zasadzie nadal jest aktualne. Tylko jeśli to byłoby mega trudne do zrobienia, to chyba nie ma sensu poświęcać temu bardzo dużo czasu, bo nie zdarza nam się wysyłać do klientów pism, które powinny trafić tylko do zespołu

**Comment by AgnieszkaZdanowicz** [comment]
o tym dziś rozmawialiśmy, żeby usunąć opcję "wyślij" przy wiadomościach wysyłanych z opcji "napisz do zespołu"
