### ISSUE TITLE
Literówka w "Odpowiedź wszystkim"

### ISSUE THREAD

**Issue by ad-m** [watchdogpolska/poradnia#245]
> czy można poprawić literówkę z przycisku "Odpowiedź wszystkim"? powinno być "odpowiedz"
#240

**Comment by rwakulszowa** [comment]
https://github.com/watchdogpolska/poradnia/blob/master/poradnia/letters/locale/pl/LC_MESSAGES/django.po#L69

**Comment by ad-m** [comment]
+ przebudowanie pliku *.mo.
