### ISSUE TITLE
Autootwieranie spraw

### ISSUE THREAD

**Issue by ad-m** [watchdogpolska/poradnia#247]
> Karol,
> 
> robiłam sobie test na poradni, żeby zobaczyć, jak działa to wysyłanie maili z i bez powiadomień. Zamknęłam ją, nie dostałam żadnego powiadomienia, chociaż zaznaczyłam, że ma być, po czym jak napisałam na przypisany do sprawy adres, to ona się nie otworzyła automatycznie.
> 
> Sprawdź to proszę - to akurat jest pilne.
> 
> Sprawa nr 924
> 
> pozdrawiam,
> 
> Agnieszka

Nie mamy odpowiednich testów. To należy dopisać, skoro już mamy przetwarzanie *.eml w podstawowej wersji.

**Comment by rwakulszowa** [comment]
Jeśli chodzi o wysyłanie powiadomień, to gdzieś w `send_notification` jest odfiltrowywanie członków zespołu z listy adresatów, stąd brak maila.
Można to zmodyfikować tak, by case_close po prostu wysyłało maila do użytkownika w `created_by` - pytanie tylko czy chcemy, żeby tylko ta jedna osoba otrzymywała maila.
Inna możliwość to pozostawienie filtrowania, ale tak, by nie usuwało członków zespołu, jeśli są w polu `created_by`.
Ostatecznie można całkowicie pominąć filtrowanie, ale to pewnie wygeneruje sporo spamu do członków zespołu.

**Comment by ad-m** [comment]
W zgłoszeniu rysują się dwa zagadnienia:
- powiadomienie o zamykaniu sprawy,
- otwieranie spraw po wiadomości e-mailowej.

Zobacz na screen co do aktualnego stanu sprawy:

![test_zamykania_bez_wiadomosci_-_sprawy_-_poradnia_-_2016-04-16_01 26 33](https://cloud.githubusercontent.com/assets/3618479/14577283/501b57e4-0372-11e6-846d-f60688c244e9.png)

W zakresie pierwszego należy wskazać, że nie jest ono wysyłane do aktora danej czynności, natomiast w zakresie drugiego elementu należy wskazać, że pisma zespołu nie wpływają na status sprawy. Kolejny element do rozważenia w #244.

**Comment by ad-m** [comment]
Wygląda mi na załatwione. Sprawy wygląda na to, że poprawnie się reotwierają.
