### ISSUE TITLE
Zweryfikować wydajność i optymalność dołączania załączników do wiadomości e-mail 

### ISSUE THREAD

**Issue by ad-m** [watchdogpolska/poradnia#256]

**Comment by AgnieszkaZdanowicz** [comment]
Dla mnie to jest problem, że można po jednym pliku tylko dodawać

**Comment by AgnieszkaZdanowicz** [comment]
Byłoby fajnie, gdyby dało się dodawać po kilka załączników jednocześnie

**Comment by PiotrIw** [comment]
zaimplementowane v1.1.21
