### ISSUE TITLE
Przygotować apple-app-site-association

### ISSUE THREAD

**Issue by ad-m** [watchdogpolska/poradnia#261]
Mamy wiele odwołań do serwera o https://porady.siecobywatelska.pl/apple-app-site-association . Nie istnieje taki plik. Należy wyjaśnić czym on jest, co ma zawierać i przygotować go, skoro są o niego żądania. Nie mamy żadnych aplikacji mobilnych, a strony przystosowujemy od urządzeń mobilnych.

Z poważaniem,

**Comment by rwakulszowa** [comment]
Jest to plik przekierowujący użytkowników Safari do dedykowanej aplikacji https://developer.apple.com/library/ios/documentation/General/Conceptual/AppSearch/UniversalLinks.html#//apple_ref/doc/uid/TP40016308-CH12-SW1

Niestety nie używam Safari / IPhone / Maca więc nie jestem w stanie przetestować działania, natomiast postaram się stworzyć plik, który (miejmy nadzieję) wypełni lukę, jednocześnie nie wywołując żadnej aplikacji. Niestety nie będę w stanie tego przetestować lokalnie. To rozwiązanie wydaje mi się jednak dość dziwne.
Druga opcja to pozostawienie sytuacji bez zmian - jakby nie patrzeć, obecnie wszystko działa tak jak powinno, czyli nie mamy powiązania z żadną aplikacją. Warto byłoby natomiast przetestować działanie strony na iPhonie + Safari, tj. czy strona otwiera się poprawnie, czy pojawia się jakiś błąd.

Testować strony pod względem kompatybilności ze standardami Apple można tutaj:
https://search.developer.apple.com/appsearch-validation-tool/

**Comment by ad-m** [comment]
Dziękuje za wyjaśnienie. W takiej sytuacji wydaje się, że użytkownicy Safari nie odczuwają dyskomfortu na naszej stronie i nie ma potrzeby przygotowywać nic.
