### ISSUE TITLE
Wykorzystanie Poradni do spraw Stowarzyszenia

### ISSUE THREAD

**Issue by ad-m** [watchdogpolska/poradnia#268]
Obecnie Poradnia jest wykorzystywana do spraw wpływających do Stowarzyszenia (zwykłe poradnictwo), a chcielibyśmy poszerzyć jej wykorzystanie także do spraw, które są przez Stowarzyszenie rozpoczynane ( przykładowo http://siecobywatelska.pl/co-zaskakuje-w-monitoringu-szpitali/ ), bo sposób obiegu dokumentów i monitorowania takich spraw się sprawdza. 

Należy dokonać kilku zmian rozbudowujących system:
- [ ] `cases.Case`: wprowadzić pole określające czy sprawa ma charakter wewnętrzny czy zewnętrzny i wprowadzić możliwość stworzenia spraw bez klienta,
- [ ] `cases.models.mail_process`: .zapewnić, że dla wszystkich wpływających spraw za pomocą  poczty elektronicznej sprawa będzie mieć charakter zewnętrzny i uzupełnić w tym zakresie testy,
- [ ] `cases.filters.StaffCaseFilter`: umożliwić filtrowanie spraw według zewnętrznego / wewnętrznego / dowolnego charakteru, z tym że po wybraniu w menu "Wykaz spraw" przez członka zespołu ma wyświetlać tylko zewnętrzne,
- [ ] `/poradnia/templates/_sidebar.html`: dodać w menu widoczny dla członków zespołu odnośnik do  "Wykaz spraw wewnętrznych",
- [] `/poradnia/cases/templates/cases/case_filter.html`: dodać oznaczenie wewnętrznego charakteru sprawy np. ikona z FontAwesome ( http://fontawesome.io/icons/ ), 
- [] `letters.forms.NewCaseForm`: wprowadzić możliwość utworzenia sprawy wewnętrznej tylko i wylącznie przez członków zespołu,

**Comment by AgnieszkaZdanowicz** [comment]
To jest załatwione przez EOD
