### ISSUE TITLE
Klucze API do danych z kalendarza

### ISSUE THREAD

**Issue by ad-m** [watchdogpolska/poradnia#274]
Mamy kalendarz w ramach aplikacji `events`, który prezentuje wydarzenia. Jest on także w formacie ical, który jest przyjazna np. do wciągnięcia tych wydarzeń do kalendarza Google i ogarniania razem wszystkiego. Realizuje to `events.views.ICalendarView`. 

Stowarzyszenie ma także kalendarz do zarządzania zespołem (urlopy, rozprawy itd.) i w obiegu jest kalendarz wszystkich rozpraw WSA, więc myśle, że cenne jest umożliwienie nałożenia takich kalendarzy w ramahc osobnego narzędzia.

Wydarzenia są przypisane do użytkownika, więc wymagane jest uwierzytelnienie, aby ustalić kogo wydarzenia wyświetlić i zweryfikować tożsamośc w tym zakresie. Nierozważnym byłoby wykorzystywanie do tego celu hasła. Wykorzystywane są do tego klucze API. Realizowane jest to w aplikacji `keys`, która umożliwia dodawać, usuwać, śledzić wykorzystanie kluczy API dla użytkownika.  

W `keys.mixins.KeyAuthMixin` wykorzystany przez `events.views.ICalendarView` jest mixins, który spina to wszystko. Powinien on zapewniać, że poprzez podanie w HTTP nazwy użytkownika i klucza API użytkownik będzie na potrzeby tego konkretnego żądania uwierzytelniony, czyli będzie mógł pobrać dedykowany mu kalendarz.

Okazuje się jednak, że rozwiązanie to sprawia problemy dla użytkowników. Jest mało intuicyjne i praktycznie niewykorzystane. Mam także wątpliwość czy w ogóle działa, bo kod powstał przed tym jak nauczyłem się pisać testy automatyczne :blush: Otrzymałem także w tym zakresie wyrazy wątpliwości, ale nie pogłębiłem tego, a może to wina konfiguracji serwera.

Należy: 
- [ ] w ramach `poradnia/keys/templates/keys/key_detail.html` zapewnić gotowe absolutny adres do `events.views.ICalendarView`, super jakby wziąc przy tym pod uwagę, że mogą się pojawić kolejne widoki w przyszłości, ale zahardkodowanie linku do tego konkretnego widoku będzie też dostateczne,
- [ ] uzupełnić brakujące testy automatyczne co najmniej dla `keys.mixins.KeyAuthMixin`.

**Comment by ad-m** [comment]
API działa, ale jest mało przystępne.

**Comment by AgnieszkaZdanowicz** [comment]
@ad-m ostatnio rozmawialiśmy o łączeniu kalendarza z poradni z kalendarzem google, ale nie wiem, na czym stanęło. Czy, żeby można było wdrożyć takie rozwiązanie, trzeba rozwiązać opisany powyżej problem?

**Comment by ad-m** [comment]
Tak.
