### ISSUE TITLE
Statystyki przyrostu liczby użytkowników

### ISSUE THREAD

**Issue by ad-m** [watchdogpolska/poradnia#276]
Mamy moduł statystyk `stats`. Będziemy śledzić czas rejestracji użytkowników (see #275). Warto rozbudować moduł `stats` o statystyki liczby zarejestrowanych użytkowników w poszczególnych miesiącach.

Przykładowa wizualizacja wykresu:
![zaznaczenie_736](https://cloud.githubusercontent.com/assets/3618479/17231447/38261e10-5522-11e6-8c7a-8ca433fe909e.png)

Myśłę, że - przynajmniej teraz - interesuje nas wartość skumulowana (jak na przykładzie), a nie przyrost w danym miesiącu, chociaż jak nie stanowi to dużego nakładu można przygotować oba wykresy (liczba / miesiąc, rejestracjie/ miesiąc).

**Comment by rwakulszowa** [comment]
Trochę czasu minęło, ale chyba uda mi się znowu znaleźć parę chwil dla Poradni :) Zacząłem od wykresu, sprawa jest dość prosta, przy okazji może posprzątam częściowo kod i testy.

Mam problem z testem tworzącym użytkowników. Nie jestem pewien w którym miejscu, ale testy zdają się automatycznie tworzyć nowego użytkownika, co nieco komplikuje sytuację. [W tym miejscu](https://github.com/rwakulszowa/poradnia/commit/1e9c40fe295bbcc80de228e63530087fb16d36ad#diff-5b3cea91f454bc64c73cd43124bf7530R390) loguję się z wykorzystaniem stworzonego wcześniej użytkownika, ale zwracana odpowiedź sugeruje, że w bazie jest jeden dodatkowy użytkownik stworzony z dzisiejszą datą. Czy da się jakoś wymusić na Django, by nie dodawał nowego użytkownika?

Sytuację pewnie da się jakoś obejść, problem dotyczy tylko testu, ale wolę zapytać czy jest jakiś dobry sposób na rozwiązanie problemu.

**Comment by ad-m** [comment]
@rwakulszowa , na szybko, spójrz czy ``ANONYMOUS_USER_NAME = None`` nie pomoże. Zobacz https://django-guardian.readthedocs.io/en/stable/configuration.html#anonymous-user-name .

**Comment by ad-m** [comment]
@rwakulszowa , po zgłębieniu tego zagadnienia myślę, że najprościej jest napisać odpowiedni dekorator, który wyłączy tworzenie odpowiedniego użytkownika. Ze względu na etap w jakim dzieje sie ta podmiana patchowanie i wbudowane w Django metody okazywały się nieskuteczne, ale może coś przegapiłem.

Proponuje takie rozwiązanie:

```python
from django.test import TestCase, modify_settings, override_settings
from users.models import User

from django.db.models import signals


def disable_anonymous_user(func):
    """Class decorator to disable creating of anonymous User

    It doesn't work for methods etc.
    """
    def func_wrapper(*args, **kwargs):
        signals.post_migrate.disconnect(dispatch_uid="guardian.management.create_anonymous_user")
        return func(*args, **kwargs)
    return func_wrapper


@disable_anonymous_user
class NoAnonymousUserTestCase(TestCase):
    def test_no_user_with_decorator(self):
        self.assertEqual(User.objects.count(), 0)


class LeaveAnonymosUserTestCase(TestCase):
    def test_has_user_without_decorator(self):
        self.assertEqual(User.objects.count(), 1)
```

**Comment by rwakulszowa** [comment]
Ok, pomogło. Dziękuję.

Jeszcze jedno pytanie - pole [created_on](https://github.com/watchdogpolska/poradnia/commit/9031f7889754351f3d74dfcea75f32d438d95611) automatycznie dodaje datę przy tworzeniu użytkownika. Co znajduje się w polu dla użytkowników dodanych przed wspomnianą zmianą w kodzie? `None`?

**Comment by rwakulszowa** [comment]
Wygląda na to, że jednak nie pomogło. Dekorator powoduje, że `TestCase` nie wykonuje się. Skoro wyłączenie tego mechanizmu jest dość skomplikowane, może łatwiej będzie zrobić to [w bardziej toporny sposób](https://github.com/watchdogpolska/poradnia/commit/7d44bcaf4c13685da633b0ddb930f5f543db1aae#diff-5b3cea91f454bc64c73cd43124bf7530R370)?

**Comment by ad-m** [comment]
@rwakulszowa , 
1/ tak, jeżeli tworzysz migracje z polem ``null=True`` i nie ustawisz domyślnej wartości w inny sposób to będzie tam ``None``. Nawet Django nie pozwoli stworzyć migracji z nowym polem, które nie będzie ``null=True`` lub nie ustawisz domyślnej wartości.

Zweryfikowałem to także w rzeczywistości
```
In [1]: from users.models import User

In [2]: User.objects.all()[5]
Out[2]: <User: Katarzyna>

In [3]: User.objects.all()[5].created_on

In [4]: User.objects.all()[5].created_on is None
Out[4]: True
```

2/ myślę, że usuwanie to też opcja, chociaż ja próbowałem jej uniknąć. Poza tym napisałbym to w formie dekoratora metody, bo wtedy łatwiej wykorzystać w innych mijescach i - subiektywnie - będzie czytelniej.
