### ISSUE TITLE
Podpis (sygnaturka) pod odpowiedziami

### ISSUE THREAD

**Issue by ad-m** [watchdogpolska/poradnia#283]
Wykształciła się praktyka u niektórych wolontariuszy podawania w stopce wiadomości np. swojego numeru telefonu. Jest to zachowanie w porządku i myślimy, że nie ma co go zwalczać. Można jednak na nie zareagować, bo obecnie cały podpis trzeba zawsze od nowa wpisywać, albo przeklejać. Myślę, że to strata czasu.

Proponuje:
- rozbudować `Profile`, aby dodać pole na treść synaturki (domyślnej treści wiadomości),
- rozbudować `users.forms.users.ProfileForm`, aby umożliwić edycje nowego pola dla członków zespołu (wyłącznie),
- rozbudować `AddLetterForm`, aby pole wiadomości było domyślnie wypełnione sygnaturką,

**Comment by ppkt** [comment]
@ad-m jeśli ten task jest wolny, chętnie się nim zajmę. Sygnaturka ma być dodawana tylko w klasie 'AddLetterForm' (jak rozumiem, wystarczy ustawic ja w `initial` dla pola `text`)?

**Comment by ad-m** [comment]
@ppkt , tak, wolne. Dziękuje za wsparcie :)

**Comment by jacekll** [comment]
@ppkt @ad-m Czy mogę przejąć ten task?

**Comment by ppkt** [comment]
@jacekll - tak, nie robilem z nim nic jeszcze

**Comment by ad-m** [comment]
Closed by #283. 

@jacekll , obczaj https://help.github.com/articles/closing-issues-using-keywords/ .
