### ISSUE TITLE
Zaktualizować Update django-filter do 0.15.x

### ISSUE THREAD

**Issue by ad-m** [watchdogpolska/poradnia#337]
Szanowni Państwo,

Django-filter złamał w wersji 0.15.x kompatybilność API. Poczynili wiele zmian w API. Natomiast dla naszej aplikacji ma on znaczenie.

Należy zaktualizować django-filter do >=0.15.0, a następnie dokonać odpowiednich zmian w API.

Z poważaniem,

**Comment by ad-m** [comment]
Brak wsparcia dla tłumaczenia nas powstrzymuje (por. alex/django-filter#543).

**Comment by mik-laj** [comment]
Już jest zrobione tłumaczenie z tego co mi wiadomo.

**Comment by AgnieszkaZdanowicz** [comment]
to chyba do zamknięcia?

**Comment by ad-m** [comment]
Tak.
