### ISSUE TITLE
Udokumentować cykliczne polecenia

### ISSUE THREAD

**Issue by ad-m** [watchdogpolska/poradnia#350]
Aby zainstalować aplikacje należy wywoływać ```get_mail``` z django-mailbox (lub inna forma, zob. dokumentacja django-mailbox). Są też powiadomienia o wydarzeniach (#346), które mają osobne polecenie.

Warto to opisać w ```README.rst``` jakoś schludnie.

**Comment by AgnieszkaZdanowicz** [comment]
@ad-m tego nie rozumiem, czy to aktualne czy zamykać?

**Comment by ad-m** [comment]
Tak, dokumentacja w tym zakresie nie została rozwinięta odpowiednio.

**Comment by AgnieszkaZdanowicz** [comment]
nie wiem, czy tu jest coś do zrobienia czy można zamykać. @mrbojko @PiotrIw pozostawiam Wam do oceny.

**Comment by PiotrIw** [comment]
nieaktualne, django-mailbox istnieje w kodzie choć jest nieaktywne - do usunięcia po sprawdzeniu powiązań zletters
