### ISSUE TITLE
Ujednolicić testy automatyczne

### ISSUE THREAD

**Issue by ad-m** [watchdogpolska/poradnia#381]
W ramach #380 dostrzegliśmy konieczność ujednolicenia notacji testów odnoszących się do kontroli uprawnień, co jest stałym elementem w aplikacji. Proponuje wykorzystanie https://github.com/watchdogpolska/feder/blob/master/feder/main/mixins.py#L113 . @rwakulszowa , masz ochotę?

**Comment by rwakulszowa** [comment]
W jaki sposób nadać użytkownikowi `permission` równoznaczne z `superuser`?
Dostęp do modułu udzielany jest na podstawie `SuperuserRequiredMixin`, więc potrzebne jest sprawdzanie tego `permission` w testach.
