### ISSUE TITLE
"Pobierz wszystkie" załączniki

### ISSUE THREAD

**Issue by ad-m** [watchdogpolska/poradnia#42]
Szymon zgłasza, że pragnie, aby można było dla jednej wiadomości pobrać jednorazowo wszystkie załączniki. 

Można użyć https://github.com/allanlei/python-zipstream .

**Comment by ad-m** [comment]
Zgłoszenie jest otwarte, bo chce obserwować jak serwer będzie się zachowywać przy normalnym ruchu nim dołożę mu kompresje danych w którymś momencie. Jest kilka metod podejścia do tego i będę musiał wybrać.Teraz nie jestem w stanie.

Możemy:
 * przy odbiorze dane zapisywać w dwóch miejscach – zapis raz działa spoko, zapis dwukrotny nie powinien być problemem, ale tu drugi zapis będzie z kompresją dodatkowo,
* przy odbiorze zapisywać dane raz i zlecać kompresje do programu, który będzie to stale robić w tle,
* przy każdym pobieraniu kompresować.

Każda metoda ma swoje plusy i wady.

**Comment by AgnieszkaZdanowicz** [comment]
to jest zrobione, zamykam
