### ISSUE TITLE
Szybka wyszukiwarka w Poradni

### ISSUE THREAD

**Issue by ad-m** [watchdogpolska/poradnia#420]
W Poradni w menu nawigacyjnym funkcjonuje wyszukiwarka, która pojawia się w oknie modalnym. Dotąd działała poprzez django-autocomplete-light 2.x. Jednak z powodu problemów z JS przeszedłem na django-autocomplete-light 3.x, które używa biblioteki JS select2 . Opracowałem widok, który renderuje odpowiedni JSON. 

Konieczne jest zrobienie szybkiej wyszukiwarki, co w oknie modalnym będzie szybko odświeżać wyniki podpowiedzi. Można użyć do tego tego select2 samego. 

Jednak JS jest zepsuty. gulp nie dołącza odpowiednich plików JS. Zatem nie włączają się te potrzebne biblioteki.

**Comment by ad-m** [comment]
Porzucam media, bo robi sieczkę, gdy chce użyć select2 samodzielnie. Chce
media wpakować do środka.

Wysłano z urządzenia mobilnego.

17.08.2017 19:47 "Kamil Breguła" <notifications@github.com> napisał(a):

Django autoxomplete wymaga tylko JQuery. Mała szansa jest, że nie ładuje
się JQuery. Wczytujesz media dla formularza? Powinieneś wczytywać je
poniżej kodu jQuery.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/watchdogpolska/poradnia/issues/420#issuecomment-323145252>,
or mute the thread

**Comment by ad-m** [comment]
Moje zmiany są obecnie na branchu "fix-search".

**Comment by ad-m** [comment]
https://github.com/watchdogpolska/poradnia/compare/fix-search

**Comment by mik-laj** [comment]
Jutro się tym zajmę. Dzisiaj już nie dam rady.

**Comment by mik-laj** [comment]
@ad-m zrobiłem coś. Sprawdź, jak to działa.

**Comment by ad-m** [comment]
Wyszukiwarka nie wyszukuje. Pole tekstowe nie jest dostępne.

**Comment by mik-laj** [comment]
Jest już nowa poprawka

**Comment by AgnieszkaZdanowicz** [comment]
@ad-m tu chodzi o wyszukiwarkę w wykazie spraw po polu "przedmiot"? Ono moim zdaniem dobrze działa

**Comment by ad-m** [comment]
Nie, tu chodzi o tą wyszukiwarkę:
![image](https://user-images.githubusercontent.com/3618479/87719652-f9aa9180-c7b3-11ea-84a3-28570644bd0a.png)
