### ISSUE TITLE
Monitorowanie spraw sądowych

### ISSUE THREAD

**Issue by ad-m** [watchdogpolska/poradnia#423]
Chcemy śledzić sprawy, które do nas wpadają. Możemy to zacząć robić za pośrednictwem wokand sądów administracyjnych.

Należy wprowadzić:

- [ ] rejestracje sygnatury sprawy i sądu, gdzie ona się toczy,
- [ ] archiwizowanie wokand (możliwość odpytania o archiwalną wokandę na podstawie sygnatury),
- [ ] powiadomienie w sprawie o zarchiwizowaniu wokandy sprawy zarchiwizowaniej,
- [ ] zarejestrowanie z wokandy NSA brakującej sygnatury,  
- [ ] dostosowanie polityki prywatności

Sprawy toczące się przed Wojewódzkim Sądem Administracyjnym monitorujemy w wokandzie tego sądu i przed Naczelnym Sądem Administracyjnym. Sprawy toczące się w NSA mamy śledzić w CBOSA.

| Nazwa | URL |
| ------------- | ------------- |
| NSA | http://www.nsa.gov.pl/ewokanda/ |
| WSA w Białymstoku | http://www.nsa.gov.pl/ewokanda/wsa/bialystok/ |
| WSA w Bydgoszczy | http://www.nsa.gov.pl/ewokanda/wsa/bydgoszcz/ |
| WSA w Gdańsku | http://www.nsa.gov.pl/ewokanda/wsa/gdansk/ |
| WSA w Gliwicach | http://www.gliwice.wsa.gov.pl/56/49/elektroniczny-terminarz-rozpraw-etr.html |
| WSA w Gorzowie Wielkopolskim | http://www.nsa.gov.pl/ewokanda/wsa/gorzow/ |
| WSA w Kielcach | http://www.nsa.gov.pl/ewokanda/wsa/kielce/ |
| WSA w Krakowie | http://www.nsa.gov.pl/ewokanda/wsa/krakow/ |
| WSA w Krakowie | http://bip.krakow.wsa.gov.pl/71/177/elektroniczny-terminarz-rozpraw-etr.html |
| WSA w Lublinie | http://www.nsa.gov.pl/ewokanda/wsa/lublin/ |
| WSA w Łodzi | http://www.nsa.gov.pl/ewokanda/wsa/lodz/ |
| WSA w Olsztynie | http://www.nsa.gov.pl/ewokanda/wsa/olsztyn/ |
| WSA w Opolu | http://www.nsa.gov.pl/ewokanda/wsa/opole/ |
| WSA w Poznaniu | http://www.nsa.gov.pl/ewokanda/wsa/poznan/ |
| WSA w Rzeszowie | http://www.nsa.gov.pl/ewokanda/wsa/rzeszow/ |
| WSA w Szczecinie | http://www.nsa.gov.pl/ewokanda/wsa/szczecin/ |
| WSA w Warszawie | http://www.nsa.gov.pl/ewokanda/wsa/warszawa/ |
| WSA w Warszawie | http://www.warszawa.wsa.gov.pl/183/elektroniczny-terminarz-rozpraw.html |
| WSA we Wrocławiu | brak |

**Comment by AgnieszkaZdanowicz** [comment]
@ad-m to jest to, co działa już na poradni, prawda? można zamknąć?
