### ISSUE TITLE
Za szerokie pole logowania na urządzeniach mobilnych

### ISSUE THREAD

**Issue by mik-laj** [watchdogpolska/poradnia#431]
![screenshot_2017-09-16-14-09-20-393_com android chrome](https://user-images.githubusercontent.com/12058428/30619151-172d7cec-9d9e-11e7-8dce-e75d8d436559.png)

**Comment by AgnieszkaZdanowicz** [comment]
fakt, nadal nie mieści się na ekranie

**Comment by efefre** [comment]
Zadanie do zamknięcia. Weszło w #903.
