### ISSUE TITLE
Braki w tłumaczeniach

### ISSUE THREAD

**Issue by mik-laj** [watchdogpolska/poradnia#432]
Szanowni,

Są pewne braki w tłumaczeniach, którzy widzą nowo zarejestrowani użytkownicy
![screenshot_2017-09-16-14-09-42-996_com android chrome](https://user-images.githubusercontent.com/12058428/30619161-3a680718-9d9e-11e7-85a1-e3316424390e.png)
![screenshot_2017-09-16-14-10-13-691_com google android gm](https://user-images.githubusercontent.com/12058428/30619165-3e60c224-9d9e-11e7-9722-c52851cf7a9a.png)
![screenshot_2017-09-16-14-13-24-130_com android chrome](https://user-images.githubusercontent.com/12058428/30619175-4dffdd50-9d9e-11e7-941f-98033fbad2b4.png)
![screenshot_2017-09-16-14-17-43-467_com android chrome](https://user-images.githubusercontent.com/12058428/30619184-58adcc9e-9d9e-11e7-9136-a97686d8d1ab.png)

Z wyrazami szacunku

**Comment by kbiernat** [comment]
To ja dorzucę tutaj brak w tłumaczeniu widoczny w widoku sprawy, po najechaniu na osobę, uprawnienia 'Can {add,change,delete} case' nie są tłumaczone.
![tlumaczenia](https://user-images.githubusercontent.com/9462876/34146374-09cc590e-e49a-11e7-9449-7331edff4718.png)

**Comment by Pacu2** [comment]
W jaki sposób zarządzane są tłumaczenia w projekcie? Używacie do tego jakiegoś zewnętrznego narzędzia np. Transifex?

**Comment by ad-m** [comment]
Standardowe rozwiązania specyficzne dla projektu Django. Żadnych dodatkowych narzędzi, oprócz manage.py (do generowania plików językowych), poedit (edycja plików po) i Gita (wersjonowania razem z kodem). Wszystko klasycznie jak na projekt w Django. Jeżeli potrzebujesz większego pokierowania - daj znać.

**Comment by Pacu2** [comment]
@ad-m Istnieje jakiś łatwy sposób, w jaki mogę znaleźć tylko te teksty które nie są przetłumaczone?

**Comment by ad-m** [comment]
Czy masz jakieś doświadczenie z Django? Chce upewnić się jak komunikować.

W większości przypadków (o ile nie we wszystkich) brakujące elementy w tłumaczeniu wynikają z tego, że taki tekst nie został wprowadzony w tej aplikacji specjalnie, a pochodzi z biblioteki. Teksty wprowadzone w tej aplikacji są raczej na bieżąco tłumaczone.

**Comment by AgnieszkaZdanowicz** [comment]
mail o resecie hasła wysyła się po polsku. Ale informacja o braku dostępu rzeczywiście jest po angielsku.

**Comment by efefre** [comment]
> To ja dorzucę tutaj brak w tłumaczeniu widoczny w widoku sprawy, po najechaniu na osobę, uprawnienia 'Can {add,change,delete} case' nie są tłumaczone.
> ![tlumaczenia](https://user-images.githubusercontent.com/9462876/34146374-09cc590e-e49a-11e7-9449-7331edff4718.png)

Nie mogę znaleźć tego miejsca. @AgnieszkaZdanowicz/@kbiernat możecie sprawdzić, czy to jeszcze występuje? A jeżeli tak, to proszę, dajcie znać jak mam dotrzeć do tego miejsca.

**Comment by ad-m** [comment]
Najłatwiej będzie przejść do konkretnej sprawy, a potem `https://localhost:8000/sprawy/sprawa-{id_sprawy}/uprawnienia/`. Ten o to widok: https://github.com/watchdogpolska/poradnia/blob/8bf9c88888d538cf4d1224431355c850d31ef252/poradnia/cases/views/permissions.py#L41 .

**Comment by ad-m** [comment]
Znaczy się to co na screenshocie to jest inne i nie mam do końca pewności co (mam jednak pomysł jak sprawić, aby ten komunikat był czytelny, bo obecnie nie jest wcale), ale źródło jest zgodne z tym co wskazałem:
![image](https://user-images.githubusercontent.com/3618479/95911531-e3f03c80-0da1-11eb-8d7a-0b7be13b59fa.png)

**Comment by ad-m** [comment]
W wykazie spraw tu jeszcze: 
![image](https://user-images.githubusercontent.com/3618479/95911641-084c1900-0da2-11eb-8dc8-02df6d199541.png)

**Comment by ad-m** [comment]
Przy manualnym dodawaniu nowego użytkownika do sprawy https://porady.siecobywatelska.pl/sprawy/sprawa-9763/uprawnienia/ także pole "Users" nie jest przetłumaczone.
