### ISSUE TITLE
Myląca etykieta "Sprawy klienta"

### ISSUE THREAD

**Issue by mik-laj** [watchdogpolska/poradnia#433]
Szanowni

Użytkownik wchodząc swój profil widzi napis "Sprawy klienta". Lepiej, aby pisało "Moje sprawy"
![screenshot_2017-09-16-14-19-49-289_com android chrome](https://user-images.githubusercontent.com/12058428/30619216-89967e96-9d9e-11e7-8511-e66516610523.png)

Z wyrazami szacunku

**Comment by ad-m** [comment]
Tak, na widoku siebie można to opisać inaczej. Ten sam widok służy do oglądania kogoś, jeżeli ma się uprawnienia.

**Comment by ad-m** [comment]
@koszany , co o tym sądzisz? Staram się wybrać podstawowe zadania, aby spokojnie wdrożyć w projekt.

**Comment by koszany** [comment]
Miałam huk w robocie, ale dzisiaj zabieram do tego i pozostałych :)

**Comment by ad-m** [comment]
Świetnie!

**Comment by ad-m** [comment]
Wykonane w #690
