### ISSUE TITLE
Mało przyjazny widok "Sprawy klienta" dla nowego użytkownika

### ISSUE THREAD

**Issue by mik-laj** [watchdogpolska/poradnia#434]
Szanowni,

Widok przedstawiający aktualne sprawy: https://porady.siecobywatelska.pl/sprawy/?status=0&status=1 jest mało przyjazny dla nowego użytkownika, bo ma mało wolnej przestrzeni oraz braku nagłówka.

Proponuje:
 * dodać nagłówek
 * ukryć domyślnie pola filtrów. bo mało użytkowników z tego korzysta. Pokazywać dopiero, gdy ktoś ze chce. Stan ukrycia/pokazywania zapisywać, aby przywrócić po ponownym otwarciu

Z wyrazami szacunku

**Comment by Pacu2** [comment]
Obecnie w/w strona przenosi do strony logowania, prawdopodobnie nieaktualne.

**Comment by ad-m** [comment]
Wydaje mi się, że opis pozostaje aktualny w przypadku nowych użytkowników, jednak już zarejestrowanych. Wskazuje na to także treść zgłoszenia.
