### ISSUE TITLE
Alerty - nieprawidłowy kod

### ISSUE THREAD

**Issue by mik-laj** [watchdogpolska/poradnia#435]
Szanowni

Alerty zawierają zbędną kropkę, która nie przewiduje Bootstrap
![screenshot_2017-09-16-14-11-58-168_com android chrome](https://user-images.githubusercontent.com/12058428/30619382-5f9a2b46-9d9f-11e7-93bd-e77a18b829a2.png)

Z wyrazami szacunku

**Comment by AgnieszkaZdanowicz** [comment]
@ad-m nie wiem, gdzie ta kropka jest. Czy to aktualne?
