### ISSUE TITLE
Brak styli dla przycisku "Zmiany hasła"

### ISSUE THREAD

**Issue by mik-laj** [watchdogpolska/poradnia#436]
![screenshot_2017-09-16-14-11-05-193_com android chrome](https://user-images.githubusercontent.com/12058428/30619398-73c4dd5a-9d9f-11e7-9c06-b0db595e01e6.png)

**Comment by ad-m** [comment]
@koszany, co sądzisz? Django-debug-toolbar wskaże Ci tu dokładnie ścieżkę pliku.

**Comment by koszany** [comment]
Niestety nie jestem w stanie wypushować brancha, dostaję 403. 
Dodałam brancha na forku: https://github.com/koszany/poradnia/tree/issue-change-password-button

**Comment by ad-m** [comment]
@koszany , po prostu PR wystarczy :-)

**Comment by ad-m** [comment]
Dziękuje za zgłoszoną poprawkę. Nie mam uwag i zmiany zostały wcielone (#680). Mam nadzieje, że takie małe zmiany, które na początek planuje pozwolą Ci się zapoznać z projektem i nie odbierzesz ich jako poniżej Twoich umiejętności.

**Comment by westscz** [comment]
@ad-m issue jest chyba do zamknięcia?

**Comment by ad-m** [comment]
Tak.
