### ISSUE TITLE
Schowane przyciski "Nowego lista"

### ISSUE THREAD

**Issue by mik-laj** [watchdogpolska/poradnia#437]
Szanowny

Przycisk nowego listu jest ukryty i osoba może go nie zauważyć, a jest dość ważny. Należy go wyróżnić.

![screenshot_2017-09-16-14-17-09-749_com android chrome](https://user-images.githubusercontent.com/12058428/30619432-a8fc40bc-9d9f-11e7-8809-512eb3b0d630.png)

Z wyrazami szacunku

**Comment by ad-m** [comment]
Duplicate #441 .
