### ISSUE TITLE
Nie jednolity interfejs

### ISSUE THREAD

**Issue by mik-laj** [watchdogpolska/poradnia#438]
Szanowni,

Na widokach:
https://porady.siecobywatelska.pl/uzytkownik/~aktualizuj/
https://porady.siecobywatelska.pl/uzytkownik/~profil/
ale na 
https://porady.siecobywatelska.pl/konta/password/change/
brak jest wella

Z wyrazami szacunku

**Comment by ad-m** [comment]
@koszany , obsłużysz?

**Comment by AgnieszkaZdanowicz** [comment]
tutaj chodzi o to, że brakuje szarego tła?

**Comment by ad-m** [comment]
Tak

**Comment by AgnieszkaZdanowicz** [comment]
Mi to nie przeszkadza, ale może jak ktoś ma słabszy wzrok, to mu trudniej namierzyć w takiej sytuacji pola, do których ma wpisać hasło? Więc aktualne.

**Comment by PiotrIw** [comment]
poprawione w wersji 1.1.5
