### ISSUE TITLE
Brak linku do statystyk

### ISSUE THREAD

**Issue by mik-laj** [watchdogpolska/poradnia#439]
Szanowni

Brakuje na stronie linku do statystyk 
https://porady.siecobywatelska.pl/statystyki/
mimo, że widok nie jest chroniony. Proponuje dorzucić w stopkę.

Z wyrazami szacunku

**Comment by ad-m** [comment]
Trafna uwaga. Chcieliśmy pierw zebrać dane, aby coś już zaprezentować. Teraz myślę, że to poczeka aż to do osobnego modułu i zrobimy poprawną nawigacje w czasie.
