### ISSUE TITLE
Brak dostępu do profili

### ISSUE THREAD

**Issue by mik-laj** [watchdogpolska/poradnia#440]
Szanowni,

Nie mam dostępu do profili osób, które są zaangażowane w moją sprawę. Są linki, ale dostaje komunikaty o braku dostępu. 

W ostateczności interesujące może być tylko ukrycie linków jeśli prowadzą do zablokowanych profili.

Z wyrazami szacunku

**Comment by ad-m** [comment]
Tak, to jest znany problem. Dotąd przyjmowałem, że tak musi być z powodu ograniczenia wydajności. Jednak po ostatnich spostrzeżeniach - dzięki @jacekll - to można łatwo, aczkolwiek pracochłonnie naprawić.

**Comment by AgnieszkaZdanowicz** [comment]
to aktualne, ale w sumie nie wiem, co klient miałby widzieć po kliknięciu w profil osoby radzącej

**Comment by ad-m** [comment]
Myślę raczej, aby ukryć te linki.

**Comment by AgnieszkaZdanowicz** [comment]
aktualne - o ile ma być tak, że klient nadal będzie widział, kto obsługuje jego sprawę, tylko imię i nazwisko osoby obsługującej nie będzie zawierało linka? No chyba, żeby pomyśleć o zrobieniu jakichś bio każdej osoby z poradni i żeby link prowadził do takiego bio? Chciałabym tu spytać Karolinę o zdanie, ale nie mogę jej dodać.

**Comment by PiotrIw** [comment]
@KarolaJ, poproszę o opinię w temacie

**Comment by KarolaJ** [comment]
To jest dobry pomysł @AgnieszkaZdanowicz , tylko pytanie, czy mamy zasoby, aby to na bieżąco aktualizować (np. jak ktoś kończy studia, itd.) lub wprowadzać nowe, gdy zatrudniamy nową osobę na poradni?

**Comment by AgnieszkaZdanowicz** [comment]
Aha, no to rzeczywiście każdy sam musiałby zadbać o aktualne informacje o sobie. To zanim to wprowadzimy, to wszyscy muszą uzupełnić swoje opisy - @KarolaJ powiedziałabyś dziś o tym na spotkaniu zespołu poradni? Mogą to być nawet 2-3 zdania. Ja to zrobiłam na swoim profilu i chciałam dodać zdjęcie, ale mi nie zapisuje. @PiotrIw spojrzysz, czy mechanizm do dodawania zdjęć działa? Czy avatar jest dodawany przez system i to co innego niż zdjęcie? Albo to zdjęcie musi mieć odpowiednią wielkość? Bo widzę, że Szymon ma zdjęcie:

![image](https://user-images.githubusercontent.com/36925935/231432849-d00475cb-2a8b-416d-917f-9790ac75c304.png)


I właśnie zastanawiam się, czy klienci będą mieli taki widok, jak powyżej, tylko bez tych przycisków i z opisem?

**Comment by AgnieszkaZdanowicz** [comment]
@KarolaJ tak, muszą kliknąć w menu nazwę swojego użytkownika i potem wejść w "profil"

**Comment by PiotrIw** [comment]
v1.1.12, dodałem widok user info z ogólnym profilem członków zespołu dla zalogowanych użytkowników zewnętrznych 
Dodawanie awatarów rzeczywiście się zacięło - do poprawienia jeszcze

**Comment by PiotrIw** [comment]
Dodawanie awatarów nie działało od 6 Lat :)
 
Poprawiłem w wersji 1.1.13

**Comment by PiotrIw** [comment]
@KarolaJ - możesz informować zespół żeby uzupełnili profile :)
