### ISSUE TITLE
Widok avatarów wygląda fatalnie

### ISSUE THREAD

**Issue by ad-m** [watchdogpolska/poradnia#45]
![django-avatar_-_2015-07-08_02 59 29](https://cloud.githubusercontent.com/assets/3618479/8560892/6cd8ee2a-251d-11e5-96b5-0aaaa5f8bfc5.png)

Nieczytelnie, chaotycznie. Brakuje przypisu zapisz dla pól wyboru…

**Comment by mik-laj** [comment]
Potrzebuje breadcrumbsów
