### ISSUE TITLE
Wprowadzić django-tables2 do CaseListView

### ISSUE THREAD

**Issue by ad-m** [watchdogpolska/poradnia#452]
Chcemy mieć przyjemne sortowanie i łatwe ukrywanie dodatkowych kolumn dla konkretnego użytkownika, dlatego warto przepisać, aby używać [django-tables2](https://django-tables2.readthedocs.io/en/latest/).

**Comment by rwakulszowa** [comment]
Czy to nadal aktualne? Mogę spróbować się tym zająć.

**Comment by AgnieszkaZdanowicz** [comment]
@ad-m czy to aktualne?

**Comment by ad-m** [comment]
Tak.

**Comment by PiotrIw** [comment]
wdrożone tabele ajax datatables w wersji 1.1.3
