### ISSUE TITLE
Nieprawidłowe uwalnianie spraw

### ISSUE THREAD

**Issue by ad-m** [watchdogpolska/poradnia#479]
W przypadku wykonania następujących kroków:

1. utworzenia sprawy,
2. przypisania prawnika do sprawy (co zmienia status na przypisana)
3. odebrania prawnikowi wszystkich uprawnień z sprawy (odjęcia go z sprawy),

Sprawa zachowuje status przypisana. Sprawa w takim przypadku powinna stać się wolna.

**Comment by ad-m** [comment]
@rwakulszowa sprawa obecnie może mieć status:
- wolna,
- przypisana
- zamknięta.

Sprawa jest wolna zaraz po rejestracji. Po przypisaniu prawnika (osoby, która może pisać do klienta) jej status ulega zmianie na przypisana. Sprawie może zostać ręcznie zmieniony status na zamknięta. Status sprawy z zamknięta na wolna / przypisana (odpowiednio) jest zmieniany, gdy zostanie nadesłane dowolne nowe pismo w sprawie. Status sprawy ma charakter czysto informacyjny i nie blokuje żadnych operacji. 

Nie mam poczucia, aby to było napisane w sposób czysty. Krytyczna jest wydajność, gdyż jest to na liście spraw, która już obecnie prezentuje sporo informacji. Od momentu napisania tego ORM Django mocno rozwinął agregacje. Myślę, że możemy:

- wprowadzić pole do klasy "Case" z ostatnim czasem zamknięcia sprawy,
- wprowadzić metodę w Managerze, który wykona agregacje, która wskaże
- liczbę użytkowników z przypisanymi uprawnieniami do pisania,
  - czas ostatniego listu,
- wprowadzić właściwość na klasie "Case", który obliczy status sprawy, w następujący sposób:
  - jeżeli brak pól wynikających z agregacji - status jest "Nieznany",
  - jeżeli czas zamknięcia jest wyższy niż czas ostatniego listu - status jest zamknięty,
  - jeżeli liczba prawników jest wyższa niż 1 - status jest "Przypisana", w innym przypadku "Wolna".

W takim ujęciu wygląda to nawet na wykonywalne w całości po stronie bazy danych.
   
Zastanawiam się czy czas zamknięcia przechowywać w encji "Case", czy w osobnej encji podobnej do "Letter", ale myślę, że łatwiej i wydajnie przechowywać to razem, a nie potrzebujemy historii.

Co sądzisz? Gdzie widzisz problemy?

**Comment by rwakulszowa** [comment]
Brzmi wykonalnie.

Czas zamknięcia sprawy jak najbardziej może zostać dodany jako pole samej sprawy, bez dodatkowych obiektów.

Pytanie tylko odnośnie statusu `Nieznany` - czy jest to konieczna opcja? Z bazy danych potrzebujemy:
- czas ostatniego zamknięcia (domyślnie `null`)
- czas ostatniego listu (domyślnie `null`)
- liczbę przypisanych osób z uprawnieniami (domyślnie `0`)
O ile dobrze rozumiem, w stanie początkowym, tj. zaraz po utworzeniu sprawy, zarówno czas ostatniego listu jak i czas ostatniego zamknięcia mają (lub mogą mieć?) wartości `null`, a w takim przypadku sprawę uważamy za wolną. W takiej sytuacji brak danych z agregacji (tj. wartości `null`) są równoznaczne ze stanem początkowym, więc status także powinien wrócić do stanu początkowego, tj. wolna.

**Comment by ad-m** [comment]
Opcja "Nieznany" jest konieczna, jeżeli ktoś (programista) pominie wykorzystania managera i nie będzie miał dostępnych danych z agregacji. To powinien być stan, którego unikamy, ale - skoro będzie to wymagało explicit wywołania - nie jesteśmy w stanie wykluczyć takiej sytuacji.

Zaraz po utworzeniu sprawy czas ostatniego listu jest czasem pierwszego listu. Sprawy są zawsze otwierane z jednym listem.

**Comment by ad-m** [comment]
@rwakulszowa , na jakim etapie jest to zagadnienie? Z powodu #749 potrzebujemy poprawki i zastanawiam się czy wprowadzać krótkie rozwiązanie, czy ta zmiana jest na ukończeniu?

**Comment by rwakulszowa** [comment]
@ad-m przez najbliższych parę dni będzie u mnie dość krucho z czasem, więc myślę, że będzie konieczna tymczasowa poprawka.

**Comment by ad-m** [comment]
Już mam zaimplementowaną w ramach #750. Muszę wdrożyć, ale chce pierw zamknąć #755 i #754.

**Comment by rwakulszowa** [comment]
@ad-m Wreszcie znalazłem trochę czasu.
Po przyjrzeniu się sprawie wydaje mi się, że zastąpienie pola `status` logiką może być problematyczne.
Pole jest wykorzystywane w paru miejscach, które będą (chyba) niemożliwe do utrzymania przy pozbyciu się pola `status`, np. w liczeniu spraw z punktu widzenia użytkownika:
https://github.com/watchdogpolska/poradnia/blob/master/poradnia/users/models.py#L36

Jedno rozwiązanie jakie przychodzi mi do głowy to pozostawienie pola `status` i powiązanie go z pokrewnymi polami (`CaseUserObjectPermission` i `last_closed_at`) za pomocą sygnałów, ale de facto już mamy coś w tym stylu.

Może wystarczającym rozwiązaniem byłoby dodanie pola `last_closed_at`, co uprościłoby logikę aktualizacji pola `status` przy `save` na tyle, że błędy byłyby mniej prawdopodobne?

**Comment by ad-m** [comment]
Bardzo trafne spostrzeżenie, że wykorzystujemy te informacje w wykazie użytkowników. Generowanie agregacji także w tamtym ujęciu oznaczałoby znacząco za duże przetwarzanie. Pozostaje zatem napisać test (potwierdziłem manualnie), a następnie uzupełnić kod w zakresie pierwotnego przypadku braku aktualizacji statusu.

**Comment by rwakulszowa** [comment]
@ad-m jeszcze jedno pytanie.

W tym momencie, po dodaniu dowolnej osobie uprawnienia do pisania do klienta w danej sprawie, sprawa zmienia status na `assigned`, niezależnie od jej wcześniejszego statusu. Konkretnie interesuje mnie tu kwestia zamkniętych spraw. Czy zmiana `closed` na `assigned` w takim scenariuszu jest oczekiwanym zachowaniem, czy błędem?
(https://github.com/watchdogpolska/poradnia/blob/master/poradnia/cases/models.py#L343)

**Comment by ad-m** [comment]
W przypadku zamkniętych spraw jest mało prawdopodobne, aby do sprawy ktoś został przypisany, aby kontaktował się z klientem. @AgnieszkaZdanowicz , jaki w Twojej ocenie powinien być stan po przypisaniu prawnika do zamkniętej sprawy?

**Comment by rwakulszowa** [comment]
I jeszcze jedna sprawa - zauważyłem, że metoda `delete` nigdy nie jest wywoływana - https://github.com/watchdogpolska/poradnia/blob/master/poradnia/cases/models.py#L346

Zdaje się, że jest to spowodowane implementacją `remove_perm`, które nie wywołuje tej metody.
Jeśli dobrze rozumiem, rozwiązaniem będzie tutaj podłączenie się do sygnału `post_delete` dla klasy `CaseUserObjectPermission`?

**Comment by ad-m** [comment]
Usunięcie uprawnienia może odbyć się wyłącznie przez edycje uprawnień ( https://github.com/watchdogpolska/poradnia/blob/master/poradnia/cases/views/permissions.py#L101 -> https://github.com/django-guardian/django-guardian/blob/5d49d227f3cc4cb9f2513214f16c14bb15554f32/guardian/forms.py#L139_L140 ) lub usunięcie wszystkich uprawnień ( https://github.com/watchdogpolska/poradnia/blob/master/poradnia/cases/views/permissions.py#L161-L163 ). W obu przypadkach operacje są zbiorcze. W mojej ocenie sygnał ```post_delete``` nie będzie w każdym przypadku generowany, gdyż wyzwalany jest on w przypadku operacji na indywidualnych instancjach, a czasem pracujemy na zbiorze ( https://github.com/watchdogpolska/poradnia/blob/master/poradnia/cases/views/permissions.py#L161-L163 ).  Musimy także obsłużyć operacje, gdy usuwamy jednego z dwóch prawników, bo wówczas sprawa wciąż pozostaje przypisana.

**Comment by AgnieszkaZdanowicz** [comment]
@rwakulszowa @ad-m jeśli sprawa jest zamknięta i zostaje do niej przypisany prawnik, to nadal powinna pozostawać zamknięta. Jak przypisuję kogoś do zamkniętej sprawy to przeważnie po to, żeby np. mógł ją opisać, a nie pisać do klienta.
