### ISSUE TITLE
Domyślny widok sprawy

### ISSUE THREAD

**Issue by kbiernat** [watchdogpolska/poradnia#486]
Zgłoszenie mailowe po upgradzie poradni na Py35:

I zmieniło się jeszcze, że automatycznie widać w widoku sprawy najpierw zakładkę "wydarzenie", a zmienialiśmy to tak, żeby widok domyślny to był list:

**Comment by kbiernat** [comment]
![poradnia_sprawa](https://user-images.githubusercontent.com/9462876/34073236-6b8e485c-e295-11e7-8f7c-3970d59bfc1a.png)

**Comment by ad-m** [comment]
Na tym zdjęciu widać akurat dobrze. To jest pewnie błąd z słownikami, które nie mają określonej kolejności elementów. Trzeba będzie zamienić na OrderedDict,  albo na listę/tuplę jakiś struktur.

**Comment by kbiernat** [comment]
Przekleiłem z maila od requestora

**Comment by ad-m** [comment]
To może przedstawiono stan pożądany. Tu jest błąd: https://github.com/watchdogpolska/poradnia/blob/master/poradnia/cases/views/cases.py#L53 

Co ciekawe, to zachowanie teraz będzie się zmieniać z każdym rebootem workera.
