### ISSUE TITLE
Ponowione powiadomienia odnośnie starych spraw

### ISSUE THREAD

**Issue by kbiernat** [watchdogpolska/poradnia#487]
Po upgradzie na Py35 pojawiły się zgłoszenia, że użytkownicy dostali powiadomienia z jakichś starych spraw, np. #1711, #2026

**Comment by ad-m** [comment]
O czym powiadomienia?

**Comment by kbiernat** [comment]
Wydarzenie "przystąpienie" w sprawie "XXX" upływa o June 21, 2017, midnight.

Zapoznaj się z aktami sprawy pod adresem http://porady.siecobywatelska.pl/sprawy/sprawa-2026/.

Prosimy, używaj adresu sprawa-2026@porady.siecobywatelska.pl do korespondencji w tej sprawie, dzięki temu wymiana korespondencji będzie sprawniejsza. Dziękujemy za współpracę.

**Comment by ad-m** [comment]
Duplicate of #482

**Comment by kbiernat** [comment]
mógłbyś rozwinąć jak to się ma jako duplikat?
Czy wyjątek zgłoszony wcześniej przestał występować na Py3 i dlatego powiadomienia o tamtych sprawach przeszły?

**Comment by ad-m** [comment]
Ten wyjątek występuje dokładnie w tym samym miejscu. Tamta usterka nie była naprawiona. Nie wiem co leży u podstaw tamtej usterki, oprócz tego, że kodowanie, a PY3 sporo zmienia w kodowaniu. Myślę zatem, że problem jest wspólny.

**Comment by ad-m** [comment]
Przebudowałem powiadomienia, więc ta usterka nie ma znaczenia.
