### ISSUE TITLE
Znikające info o projekcie

### ISSUE THREAD

**Issue by kbiernat** [watchdogpolska/poradnia#488]
Przeklejam problem zgłoszony mailowo.
W oryginalnym mailu był drugi screen, z widokiem listy gdzie taga projekt również brakowało. Zanonimizowanie go nie zostawiało żadnych użytecznych informacji.

Chodzi o tą sprawę: https://porady.siecobywatelska.pl/sprawy/sprawa-2598/

W niej jest zapisany projekt do sprawdzenia i wysłania do klienta i sprawa była oznaczona jako projekt. Napisałam coś przed chwilą do klienta i zniknęła informacja o zapisanym projekcie, chociaż on cały czas wisi do wysłania. Zaraz ręcznie zaznaczę, że tu jest projekt, żeby nam nie uciekło, ale teraz wygląda to tak (chodzi mi, że brak info "projekt":
![sprawa-2598-details](https://user-images.githubusercontent.com/9462876/34201408-aea16fac-e574-11e7-9983-3cae26ae6b63.png)

**Comment by ad-m** [comment]
@AgnieszkaZdanowicz jesteś w stanie to odtworzyć?

**Comment by AgnieszkaZdanowicz** [comment]
Teraz już rozumiem.

Krok po kroku jak odtworzyć problem:
- wchodzimy w sprawę jako osoba do niej przypisana
- piszemy pismo do klienta i zapisujemy "zapisz do przejrzenia" - wtedy zapisuje się projekt i widać to w sprawie:  
![image](https://user-images.githubusercontent.com/36925935/67568840-96606700-f72d-11e9-90e3-86586b7cd0ce.png)
i w wykazie spraw:
![image](https://user-images.githubusercontent.com/36925935/67568904-c576d880-f72d-11e9-8ae7-a7d256003587.png)

- potem piszemy w tej samej sprawie kolejną wiadomość i wysyłamy ją za pomocą przycisku "odpowiedz wszystkim"
- po wysłaniu wiadomości znika informacja o zapisanym w sprawie projekcie, chociaż projekt nie został wysłany

Czy to problem? Moim zdaniem nie, tylko rzeczywiście trzeba wiedzieć, że powyższa sytuacja zachodzi i czasem trzeba ręcznie oznaczyć, że sprawa zawiera projekt. Wydaje mi się, że zastosowana logika jest częściej przydatna niż szkodliwa. Ale porozmawiam z zespołem i wrócę do Was z odpowiedzią.
