### ISSUE TITLE
404 po kliknięciu w sprawę w panelu admina

### ISSUE THREAD

**Issue by kbiernat** [watchdogpolska/poradnia#489]
Po kliknięciu w sprawę w panelu admina po chwili ładowania rzuca 404.
Zaobserwowane w sprawie 2598

**Comment by kbiernat** [comment]
[2017-12-20 14:13:17 +0100] [57587] [DEBUG] GET /admin/cases/case/2598/change/
[2017-12-20 14:13:48 +0100] [55985] [CRITICAL] WORKER TIMEOUT (pid:57587)

- worker timeoutuje, co generuje jakiś 50X
- nginx ma error_page 500 502 503 504 /500.html;
- location = /500.html { root /XXX/src/staticfiles/; }
- z racji tego, że src/staticfiles/500.html nie istnieje:
2017/12/20 14:13:49 [error] 1312#1312: *665107 open() "XXX/src/staticfiles/500.html" failed (2: No such file or directory), client: X.X.X.X, server: porady.siecobywatelska.pl, request: "GET /admin/cases/case/2598/change/ HTTP/2.0", upstream: "http://unix:/XXX/gunicorn.sock/admin/cases/case/2598/change/", host: "porady.siecobywatelska.pl"
-> dostajemy 404
Pytanie, co tak obciążającego dzieje się przy ładowaniu sprawy w panelu. Swoją drogą maszyny mają słabą wydajność IO. Dodałem wykresy do zabbixa/grafany

**Comment by ad-m** [comment]
Maszyny mają wydajność IO według potrzeb. Można używać innych rodzajów dysków, jeżeli jest takie zapotrzebowanie.

**Comment by ad-m** [comment]
Myślę, że to timeoutować mogą rekordy powiązane https://github.com/watchdogpolska/poradnia/blob/master/poradnia/cases/admin.py#L19 . Myślę, że tam jest wysyp zapytań związanych z ```RecordInline```.

**Comment by ad-m** [comment]
@koszany , wiesz jak to można naprawić? Jeżeli nie, chętnie wyjaśnię jak debugować takie problemy.

**Comment by AgnieszkaZdanowicz** [comment]
Mnie już bardzo dawno nie wyskakiwał żaden taki błąd na poradni. Można zamknąć?
