### ISSUE TITLE
Przygotować stronę 500.html

### ISSUE THREAD

**Issue by ad-m** [watchdogpolska/poradnia#490]
See #489

**Comment by AgnieszkaZdanowicz** [comment]
@ad-m nie wiem, czy to aktualne, bo dawno mi błędy nie wyskakiwały na poradni i w sumie nie wiem, czy mamy taką stronę

**Comment by ad-m** [comment]
Nie mamy. Wystarczy wejść na porady.siecobywatelska.pl/statystyki/ .
