### ISSUE TITLE
Błąd w zakładce 'Komunikacja'

### ISSUE THREAD

**Issue by HOWARDKNOPFLER** [watchdogpolska/poradnia#500]
Ooops!!! 500
Wygląda na to, że coś poszło nie tak!

Monitorujemy takie błędy automatycznie. Jeżeli błąd się będzie utrzymywać - skontaktuj się z nami. W międzyczasie, spróbuj odświeżyć stronę.

W przypadku potrzeby wsparcia użyj identyfikatora 2c2622edb996439b8950d8f3b93da25a.
Ooops!!! 500
Looks like something went wrong!

We track these errors automatically, but if the problem persists feel free to contact us. In the meantime, try refreshing.

If you need assistance, you may reference this error as 2c2622edb996439b8950d8f3b93da25a.

**Comment by ad-m** [comment]
@HOWARDKNOPFLER sytuacja została rozwiązana (https://github.com/watchdogpolska/infra/commit/17a3e2963e105a89cb02aabdfbb6b931b6f76827 , https://github.com/watchdogpolska/watchdogpolska.duply/commit/c4e3a813af3a3cfdd1e56ec42fc9d58a58bacfb8 ). Spowodowana była przepełnieniem jednego z serwerów. Usterka została wyeliminowana. Zostały podjęte działania zmierzające do trwałego wyeliminowania tego rodzaju problemów w przyszłości.
