### ISSUE TITLE
Po odpowiedzi w danej sprawie...

### ISSUE THREAD

**Issue by HOWARDKNOPFLER** [watchdogpolska/poradnia#501]
Zgłaszam błąd:

Po odpowiedzi w danej sprawie, pojawia się puste pole z okienkiem zamiast historią sprawy. Trzeba odświeżyć sprawę, by było widać, co się napisało.

**Comment by ad-m** [comment]
Proszę o przesłanie screenshotu i podanie adresu pod jakim występuje puste pole z okienkiem.

**Comment by HOWARDKNOPFLER** [comment]
Już jest w porządku, błąd nie występuje.

**Comment by ad-m** [comment]
Serdecznie dziękuje za udzielone informacje.
