### ISSUE TITLE
Zweryfikować funkcjonowanie powiadomień o wydarzeniach

### ISSUE THREAD

**Issue by ad-m** [watchdogpolska/poradnia#504]
- [x] określić kto dostaje – ma dostawać osoba przypisana do sprawy i osoby zarządzające

**Comment by ad-m** [comment]
See #482, #487 .

**Comment by ad-m** [comment]
@AgnieszkaZdanowicz , dostrzegam problem, że niektórzy mogą mieć domyślnie wyłączone powiadomienia np. Michal Z. Zobacz na https://bi.siecobywatelska.pl/question/12 .

**Comment by ad-m** [comment]
Ale to nie jedyny problem.

**Comment by AgnieszkaZdanowicz** [comment]
Nie wydaje mi się, żeby Michał (i nasza wolontariuszka Ewa) mieli tak specjalnie ustawione, ale spytam się Michała, jak przyjdzie. Ja nawet nie wiedziałam, że to można wyłączyć. To może zabrać opcję wyłączania powiadomień?

**Comment by ad-m** [comment]
@AgnieszkaZdanowicz , opcja wyłączania jest związana z określeniem czasu jak szybko coś ma wygasać. Każdy może sobie ustawia czy chce wiedzieć 1,3, 7 dni wcześniej czy wcale o tym, że jakieś wydarzenie w jego sprawie jest. Domyślne ustawienie jest brak powiadomień i może warto je zmienić. Mogę oczywiście wprowadzić jednolicie 1 dzień lub 7 dni. Ile domyślnie? Czy jednolicie? 

Przygotowałem także poprawkę, abyś miała informacje o tym kto dostał powiadomienie.

**Comment by AgnieszkaZdanowicz** [comment]
Domyślnie niech będzie 1 dzień

Agnieszka Zdanowicz

 <http://siecobywatelska.pl/>

Nie wyobrażasz sobie świata bez informacji?

Prosimy, przekaż 1% podatku na działania Sieci. KRS: 0000181348.

*Twój 1% nie jest bez znaczenia❗*

*Sieć Obywatelska Watchdog Polska
*ul. Ursynowska 22/2 | 02-605 Warszawa
KRS: 0000181348*
tel: +48 22 844 73 55 | fax: +48 22 207 24 09
www.siecobywatelska.pl <http://www.siecobywatelska.pl> |
www.watchdogportal.pl <http://www.watchdogportal.pl> |
www.informacjapubliczna.org <http://www.informacjapubliczna.org>*


W dniu 16 kwietnia 2018 10:44 użytkownik Adam Dobrawy <
notifications@github.com> napisał:

**Comment by ad-m** [comment]
Zmiany zostaną wprowadzone dziś wieczorem.
