### ISSUE TITLE
błąd przy zaznaczaniu terminu na poradni

### ISSUE THREAD

**Issue by AgnieszkaZdanowicz** [watchdogpolska/poradnia#506]
Kiedy na poradni w danej sprawie zaznaczam "wydarzenie", uzupełniam pola i potem biorę "zapisz", to wywala mi błąd:

"Ta strona nie działa. Jeśli problem nie ustąpi, skontaktuj się z właścicielem strony.
HTTP ERROR 405"

Termin się zapisuje, ale jednak wyskakujący błąd jest denerwujący. Miałabym prośbę o naprawienie tego.

**Comment by ad-m** [comment]
Naprawione przez #510

**Comment by AgnieszkaZdanowicz** [comment]
Nadal wyskakuje mi błąd:

![image](https://user-images.githubusercontent.com/36925935/36982416-21af6160-2090-11e8-8db0-c9ab4f20a537.png)

**Comment by ad-m** [comment]
Na serwerze w tym momencie wgrane jest oprogramowanie w wersji 915c94901e3babeb0a9511b6776581df9f9c16b8  . Następujące zmiany nie są uwzględnione: https://github.com/watchdogpolska/poradnia/compare/915c94901e3babeb0a9511b6776581df9f9c16b8...master

Wprowadzę do stopki strony informacje o tym jaka wersja jest aktualnie na serwerze.
