### ISSUE TITLE
prośba o zmianę stopki w wiadomościach automatycznie wysyłanych przez poradnię

### ISSUE THREAD

**Issue by AgnieszkaZdanowicz** [watchdogpolska/poradnia#507]
Prosiłabym o ustawienie takiej stopki (ten rysunek na dole to trzeba dostosować rozmiarem):

WESPRZYJ działanie naszej poradni
WEJDŹ na ➡ https://siecobywatelska.pl/1-procent
Przekaż nam swój 1%.
POMÓŻ NAM POMAGAĆ INNYM!

![stopka](https://user-images.githubusercontent.com/36925935/36843551-98ebfc82-1d4f-11e8-8993-7c20fb334e50.png)

**Comment by ad-m** [comment]
Jak bardzo Ci zależy na grafice?

O ile się nie mylę to w poradni nie wspieramy wiadomości HTML z obrazkami. Możliwe, że wysyłamy wyłącznie wiadomości tekstowe.To zatem czyni zmianę stopki większą sprawą.

**Comment by AgnieszkaZdanowicz** [comment]
Nie bardzo mi zależy - wystarczy sam tekst

**Comment by ad-m** [comment]
To dziś wieczorem wprowadzę zmianę, ale spróbuje też wprowadzić grafikę. Grafiki nie gwarantuje.

**Comment by AgnieszkaZdanowicz** [comment]
Ja zrobiłam napis "1%" w wordzie, ale nie mogę tu wkleić tego worda. Wygląda to tak:

![image](https://user-images.githubusercontent.com/36925935/36844818-7d887092-1d54-11e8-99b4-0c6faf6d0836.png)

To wtedy nie będzie to obrazek, tylko znaki tak ułożone. Myślisz, że ta się tam zrobić, żeby się nie rozformatowało? Mam Ci tego worda wysłać mailem?

**Comment by ad-m** [comment]
U mnie wysyłanie plików ```.docx``` działa (odt nie): 
[zarządzanie obiegiem dokumentów SOWP.docx](https://github.com/watchdogpolska/poradnia/files/1771142/zarzadzanie.obiegiem.dokumentow.SOWP.docx)

Proponuje dokument udostępnić przez nextCloud, a tu dać link. Wtedy każdy kto potrzebuje będzie mógł swobodnie pracować np. kbiernat wcześniej się tym zajmie, bo ja dopiero wieczorem.

**Comment by AgnieszkaZdanowicz** [comment]
[1% stopka.docx](https://github.com/watchdogpolska/poradnia/files/1771166/1.stopka.docx)
to próbuję dodać raz jeszcze i chyba się udało

**Comment by ad-m** [comment]
Zupełnie udało się.

01.03.2018 1:41 PM "AgnieszkaZdanowicz" <notifications@github.com>
napisał(a):

**Comment by ad-m** [comment]
Taka grafika to tzw. [ASCII Art](https://en.wikipedia.org/wiki/ASCII_art). Wymaga stałej szerokości znaku oraz wymaga minimalnej szerokości ekranu, co jest trudne do osiągnięcia na ekranach mobilnych. Nie działa poprawnie na urządzeniach mobilnych, gdyż te dodają przejścia do nowej linii, a wtedy wychodzi zupełnie nieczytelne. To w Wordzie działa, bo Ty określiłaś font (zatem szerokość każdego znaku) i Ty określiłaś szerokość strony. W e-mailu tego nie mogę zapewnić.

**Comment by AgnieszkaZdanowicz** [comment]
no trudno. to niech będzie sam ten tekst:

WESPRZYJ działanie naszej poradni
WEJDŹ na ➡ https://siecobywatelska.pl/1-procent
Przekaż nam swój 1%.
POMÓŻ NAM POMAGAĆ INNYM!
