### ISSUE TITLE
events/email/event_updated.txt

### ISSUE THREAD

**Issue by ad-m** [watchdogpolska/poradnia#51]
Request Method: 	POST
Request URL: 	http://localhost:8000/event/event-85/edit
Django Version: 	1.7.1
Exception Type: 	TemplateDoesNotExist
Exception Value: 	

events/email/event_updated.txt

**Comment by ad-m** [comment]
Brakuje treści komunikatów informujących o tym, że wydarzenie uległo zmianie lub w ogóle zostało utworzone.

**Comment by KatarzynaBatko** [comment]
A wydarzenie to co? Napisz mi ze dwa słowa przykłąduu o co może chodzić. dznx

**Comment by ad-m** [comment]
Wydarzenie - jak ustaliliśmy na ostatnim spotkaniu - to zdarzenie, które określa jakieś zdarzenie, które ma nastąpić w przyszłości. Docelowo o tym będzie powiadomienie na e-mail. Terminy spraw sądowych, terminy pism dla wolontariuszy.

Ustaliliśmy, że klient tego nie widzi, więc z swojego konta tego nie widzisz. Masz tylko konto klienta.

**Comment by ad-m** [comment]
Zdjęcie widoku w aktach.

Wysłano z urządzenia mobilnego.
13 lip 2015 12:08 AM "KatarzynaBatko" <notifications@github.com> napisał(a):

**Comment by ad-m** [comment]
#47 related
