### ISSUE TITLE
prośba o zmianę widoku domyślnego w sprawie

### ISSUE THREAD

**Issue by AgnieszkaZdanowicz** [watchdogpolska/poradnia#514]
Znowu jako domyślny widok po wejściu w sprawę na poradni wyświetla się "wydarzenie" zamiast "list":

![image](https://user-images.githubusercontent.com/36925935/37018305-2aa617bc-2114-11e8-9c35-0b16ab4e1262.png)

A zespół by wolał, żeby jednak domyślnym widokiem był list :) dlatego proszę o zmianę

**Comment by AgnieszkaZdanowicz** [comment]
Proszę o pomoc

**Comment by ad-m** [comment]
@rwa, zamierzasz zgłosić z tym PR?

**Comment by rwakulszowa** [comment]
#519

**Comment by ad-m** [comment]
Hmm…Nie połączyło. Mój błąd. Dziękuje za wiadomość!
