### ISSUE TITLE
Integracja edycji dokumentów online

### ISSUE THREAD

**Issue by ad-m** [watchdogpolska/poradnia#515]
- Microsoft Office365 by WOPI - http://wopi.readthedocs.io/en/latest/overview.html (wymaga subskrypcji Office 365 - zob. watchdogpolska/infra#16)
- OnlyOffice - https://api.onlyoffice.com/editors/open
- Zoho - https://www.zoho.com/officeapi/
- OpenOffice - https://www.collaboraoffice.com/code/
- Google Docs - brak? https://stackoverflow.com/questions/33502735/wopi-equivalent-for-google-docs

**Comment by rnickson** [comment]
Może Markdown z WYSIWYG zamiast pełnego edytora?
StackEdit.js - https://github.com/benweet/stackedit.js [[DEMO](https://stackedit.io/app#)]

Tutaj jest trochę dłuższa lista, ale nie wszystkie mają embed i WYSIWYG, a jedynie odsyłają do różnych poradników użycia Markdown:
https://github.com/mundimark/awesome-markdown-editors

**Comment by ad-m** [comment]
@rnickson , w poradni są wiadomości (obecnie w postaci tekstowej) i załączniki, które są pismami. Pisma są przygotowywane przez prawników. One mają specyficzny układ np.:

![5-skarga pdf-0](https://user-images.githubusercontent.com/3618479/39545191-b733f44c-4e50-11e8-83bb-8d7d95a50f5e.jpg)

Nie można z tego układu zrezygnować. Moim zdaniem nie da rady oprzeć tego na Markdown. 

Markdown można by wykorzystać do krótkich wiadomości, ale…zespół ceni prostotę, że nie musi niczego formatować i w wiadomościach nie chce żadnego formatowania.

**Comment by ad-m** [comment]
Może https://nextcloud.com/collaboraonline/ ? Teraz w kontenerze będzie to łatwo uruchomić...

**Comment by ad-m** [comment]
Wygląda na to, że interesuje nas protokół WOPI, abyśmy stali się "WOPI host", a następnie uruchomienie "WOPI client", którym może być m. in. LibreOffice Online.

Ogólne omówienie:
https://speakerdeck.com/kendy/integrating-libreoffice-online-via-wopi

Interesują nas cztery endpointy z perspektywy serwera. Przykładowa implementacja:
https://github.com/owncloud/richdocuments/blob/ca6e14aa0bff37e63253dcf56b92c9238ddc5728/appinfo/routes.php#L24-L27
https://github.com/owncloud/richdocuments/blob/ca6e14aa0bff37e63253dcf56b92c9238ddc5728/lib/Controller/DocumentController.php#L767-L953

Potrzebujemy także załadować ramkę z klientem "WOPI client". Przykładowa implementacja:
https://github.com/owncloud/richdocuments/blob/master/js/documents.js

**Comment by AgnieszkaZdanowicz** [comment]
Nad tym bym się zastanowiła. Bo w tej chwili jest tak, że ktoś wrzuca projekt pisma, Karolina musi je pobrać, dodać uwagi i odesłać, potem ktoś poprawia i znowu przesyła... Być może takie dokumenty online by pomogły. Ale z drugiej strony wszyscy mamy dostęp do GSuite (czy jak to się teraz nazywa) i każdy może sobie zrobić dokument w google docs i udostępnić Karolinie, żeby tam pracować nad ostateczną wersją pisma. No i pytanie, czy w wordzie jednak nie jest nam łatwiej ładnie wyedytować pisma niż w google docs albo innym narzędziu online. To bardziej zostawiam do przedyskutowania, bo sami byśmy pewnie nie wpadli na to, żeby w ogóle inaczej pracować nad projektami pism. Chciałam tu dodać Karolinę i poprosić o ocenę, ale nie mogę jej dodać.

**Comment by PiotrIw** [comment]
@AgnieszkaZdanowicz  - to spokojnie można zrobić dodając w załącznikach poniżej treści maila, obok plików opcję linków udostępniania dokumentów z google, analogicznie jak to się robi  w mailach google. Nie ma potrzeby pobierania etc.
Edycja dokumentów udostępnionych takim sposobem w Word'zie też jest możliwa, jednak wymaga więcej klikania i mimo wszystko zapisania wyedytowanego dokumentu lokalnie. Szczegóły do sprawdzenia i zaprojektowania.
@KarolaJ - proszę o opinię

**Comment by KarolaJ** [comment]
Takie link udostępniania dokumentów w Google będzie przydatny, ale rozumiem, że tylko my to widzimy jako zespół, a nie Klienci? Nie chcę, aby Klient widział wprowadzone poprawki i w ogóle pracę nad dokumentem w trakcie której często uczę Zespół, co i jak pisać. @PiotrIw @AgnieszkaZdanowicz

**Comment by PiotrIw** [comment]
@KarolaJ @AgnieszkaZdanowicz - oczywiście to by tylko było dostępne dla teamu SO, a przy pisaniu odpowiedzi można by zaznaczyć któryś z edytowanych dokumentów do wysłania jako złącznik.
Chociaż może w pierwszym kroku można dla bezpieczeństwa zrobić wysyłkę jako pobierz/sprawdź/dodaj załącznik żeby było pewne jaka wersja jest załączana

**Comment by AgnieszkaZdanowicz** [comment]
@KarolaJ ja się zastanawiam, czy rzeczywiście będziemy z tego korzystać? Na pewno wygodniej jest móc pracować na edytowalnym pliku, ale nie wiem, czy w dokumentach google się wygodnie edytuje (mam głównie doświadczenie z "excelem" googlowskim i on się na tyle różni od MS Office, że nie byłam w stanie się przestawić). Chyba po prostu nie potrafię sobie wyobrazić, jak by to miało wyglądać :)

**Comment by KarolaJ** [comment]
Agnieszko ja nie znam za bardzo Google w zakresie edycji, więc nie mogę na ten moment się wypowiedzieć, ale dość szybko się dostosowuję do technicznych zmian i innowacji. Jeżeli uważasz, że obecny zakres jest wystarczający to dla mnie też ok, pracuje się dobrze. Ostateczną decyzję zostawiam Tobie.

**Comment by PiotrIw** [comment]
@AgnieszkaZdanowicz to może przenieść wirtualne biuro fundacji z google na Office365 :) Tam excel online w zasadzie jest taki sam jak z desktopu, kosztuje tyle samo co google a wszyscy są bardziej przyzwyczajeni, mam doświadczenie bo migrowałem ...
@mrbojko co Ty na to?

**Comment by mrbojko** [comment]
@PiotrIw googla mamy w ramach sponsoringu dla ngo za darmo, Office calkiem konkretnie zeżre nam sponsoring z Microsoftu, wolę utrzymać go na magazyn i maszyny wirtualne. Zwłaszcza, że w google sky is the limit, a M$ sponsoring rozlicza się "kwotowo", czyli od liczby użytkowników.

**Comment by PiotrIw** [comment]
@mrbojko - wszystko jasne
@AgnieszkaZdanowicz @KarolaJ - w dyskusji zatoczyliśmy koło :) którą opcję wybieracie?:
- zostawiamy jak jest (załączniki do komunikatów dla teamu) i zamykamy issue
- dodć opcję linków do google docs?

**Comment by AgnieszkaZdanowicz** [comment]
@PiotrIw a czy to jest dużo roboty z tym dodaniem linków? Bo może dać to po prostu jako opcję i sobie zobaczymy, czy to dla nas przydatne, o ile to nie zajmie Ci zbyt wiele godzin

**Comment by PiotrIw** [comment]
@AgnieszkaZdanowicz ok 2 dni

**Comment by AgnieszkaZdanowicz** [comment]
no to sporo - to odpuszczamy
