### ISSUE TITLE
problem z załącznikami na poradni

### ISSUE THREAD

**Issue by AgnieszkaZdanowicz** [watchdogpolska/poradnia#516]
2 klientów zgłosiło ostatnio problemy z docieraniem do nich załączników:

https://porady.siecobywatelska.pl//sprawy/sprawa-2852/#letter-23571
https://porady.siecobywatelska.pl/sprawy/sprawa-2625/

Prosiłabym o sprawdzenie, czy problem nie jest szerszy.

**Comment by ad-m** [comment]
Odnośnie sprawy 2625:

- 5 marca 22:57 - prawnik sporządził list w systemie,
- 5 marca 22:57 - załącznik został zamieszczony na serwerze
- 6 marca 07:50 - @AgnieszkaZdanowicz edytowała (zatwierdziła?) list w systemie,

Odnośnie sprawy 2852:
- 8 marca 14:16 - prawnik sporządził list w systemie,
- 8 marca 14:16 - załącznik został zamieszczony na serwerze,
- 8 marca 15:13 - Szymon Osowski edytował (zatwierdził?) list.

Na kopiach wiadomości od użytkowników faktycznie brakuje załączników. 

@AgnieszkaZdanowicz , może nie działa wysyłanie załączników podczas zatwierdzania pism? Może przy edycji sygnaturki coś uszkodziłem.

**Comment by AgnieszkaZdanowicz** [comment]
To możliwe, bo potem jak dosyłaliśmy załączniki ja i Szymon bezpośrednio do klientów, to dochodziły bez problemu

**Comment by ad-m** [comment]
Tak, to była kwestia niedołączania wykazu załączników w listach innych niż bezpośrednie wysłanie. Naprawione w #517
