### ISSUE TITLE
Automatyczne oświeżenie przy nowym piśmie

### ISSUE THREAD

**Issue by ad-m** [watchdogpolska/poradnia#518]
https://github.com/fanout/pushpin
https://github.com/fanout/django-eventstream

**Comment by AgnieszkaZdanowicz** [comment]
@ad-m nie wiem, czy to aktualne?

**Comment by ad-m** [comment]
Aktualne, ale skoro nie jest to dla was dotkliwe to nie warto.

**Comment by AgnieszkaZdanowicz** [comment]
Nie bardzo wiem, o co dokładnie chodzi w tym issue, więc trudno mi określić, czy dotkliwe :)
