### ISSUE TITLE
przeszukiwanie spraw po przypisanych do prawnika - pojawiają się po 4 sprawy

### ISSUE THREAD

**Issue by AgnieszkaZdanowicz** [watchdogpolska/poradnia#520]
Na poradni jest taki problem:

Jak jestem w danej sprawie i klikam sobie w nazwisko prawnika_prawniczki, żeby zobaczyć, ile ma spraw przypisanych:

![image](https://user-images.githubusercontent.com/36925935/37448534-0a9072b4-2827-11e8-91eb-b1e237e73fa9.png)

Po czym wybieram opcję "przypisane sprawy":

![image](https://user-images.githubusercontent.com/36925935/37448570-28dca5c6-2827-11e8-964f-44c4ec0ddd7b.png)

I pojawiają mi się rzeczywiście sprawy przypisane, ale każda po 4 razy:

![image](https://user-images.githubusercontent.com/36925935/37448710-c5d517aa-2827-11e8-97a6-e2f2a8cabedf.png)

Może dałoby się to poprawić, żeby było widać każdą sprawę tylko raz?

**Comment by rwakulszowa** [comment]
Udało mi się częściowo zreprodukować problem:
- pojawia się tylko, gdy filtrowanie używa pola "Osoba przypisana"
- z jakiegoś powodu (zgaduję, że dawne API, które później uległo zmianie) w zapytaniu url parametr mapowany jest na "permission"
- koniec końców podejrzewam, że ta linia jest źródłem problemu: https://github.com/watchdogpolska/poradnia/blob/9d7b53fc5955b845022820297fd2a061ad2bce3b/poradnia/cases/filters.py#L28
  - nie jestem do końca pewien za co ona odpowiada, ale zakomentowanie wywołania metody `for_assign` zdaje się naprawiać błąd z duplikacją spraw
  - domyślam się jednak, że ta zmiana zepsułaby coś innego

**Comment by ad-m** [comment]
@rwakulszowa bazując wyłącznie na mojej wiedzy bez wykonywania kodu mogę wskazać, że parametr ```method``` ma za zadanie wpłynąć na filtrowanie poprzez wykorzystanie metody ```CaseQuerySet.for_assign``` ( https://github.com/watchdogpolska/poradnia/blob/9d7b53fc5955b845022820297fd2a061ad2bce3b/poradnia/cases/models.py#L27-30), która jest metodą do filtrowania według osób przypisanych do sprawy. W praktyce ma stwierdzać czy ktoś ma jakiekolwiek uprawnienie do sprawy. Zazwyczaj użytkownicy mają wiele uprawnień do jednej sprawy przez co na tym ekranie teraz występują wielokrotnie.

Przedstawiony problem wynika z ograniczeń Django, które źle znosi filtrowanie po relacji many-to-many, a na tym ekranie jest dużo filtrowania. Wiadomo, na niższym poziomie jest tam wtedy mnóstwo LEFT JOIN-ów  

Należy albo wprowadzić ```QuerySet.distinct``` bazujący na ```Case.id``` albo - co wydaje mi się lepszym rozwiązaniem - wprowadzić w ```CaseQuerySet.for_assign``` filtrowanie bazujące oprócz na nazwie użytkownika także na konkretnym uprawnieniu. W tym wypadku można wykorzystać uprawnienie ```can_view```, co – w mojej ocenie – może doprowadzić do tego, że złączenie będzie jednoznaczne, zatem pozycje nie będą powtórzone. W praktyce każdy przypisany do sprawy ma co najmniej uprawnienie ```can_view```.

**Comment by ad-m** [comment]
> z jakiegoś powodu (zgaduję, że dawne API, które później uległo zmianie) w zapytaniu url parametr mapowany jest na "permission"

Nie wiem skąd wątpliwości i sugestie o dawnym API, gdyż w mojej ocenie taka nazwa wynika z nazwy pola, gdzie pole filtrowania jest wykorzystane:

https://github.com/watchdogpolska/poradnia/blob/9d7b53fc5955b845022820297fd2a061ad2bce3b/poradnia/cases/filters.py#L36

"Osoba przypisana" oznacza, że osoba ma jakiekolwiek uprawnienie do sprawy. Proponuje zmienić na regułę, że osoba ma uprawnienie ```can_view``` do sprawy.

**Comment by AgnieszkaZdanowicz** [comment]
Teraz każda sprawa pojawia się 6 razy :)

**Comment by rwakulszowa** [comment]
PR: #521
