### ISSUE TITLE
Obsługa wiadomości e-mail wyłącznie z treścią HTML

### ISSUE THREAD

**Issue by ad-m** [watchdogpolska/poradnia#522]
# Zgłoszono:

>Szanowni,
>
>Czy da się coś zrobić, żeby w poprawny sposób wyświetlała się wiadomość w sprawie #2862?
>
>Z poważaniem,
>(…)

# Analiza:

Obecny problem wynika z sposobu skonstruowania klienta pocztowego. Otóż wiadomości mogą być wysyłane przez programy pocztowe:
- w postaci HTML,
- w postaci HTML i tekstowej (domyślnie programy pocztowe wyświetlają HTML),
- w postaci tekstowej.

W Poradni wyświetlamy wiadomości tekstowe tylko. Jeżeli nie ma postaci tekstowej to wyświetlamy postać HTML jako postać tekstową, co jest nieczytelne.

Wiadomości *.eml w sprawie zawierają wyłącznie kod HTML. Są zatem pełne znaczników HTML:
> poniewa&#380; wcze&#347;niej sie pomyli&#322;am i &#378;le napisa&#322;am je&#347;li

# Działanie:

- [ ] wprowadzić obsługę wiadomości HTML albo
- [ ] wprowadzić konwertowanie wiadomości HTML do txt

**Comment by rwakulszowa** [comment]
Mam pytanie odnośnie pola `.eml` w bazie. Jeśli dobrze rozumiem, jest ono opcjonalne (tj. pojawia się tylko dla emaili otrzymanych z zewnątrz) i zawiera ścieżkę do pliku .eml?

W takiej sytuacji prawidłowym działaniem będzie:
1. próba wyświetlenia pliku pod adresem `eml` (prawdopodobnie w oddzielnej iframe)
2. w przypadku jego braku, wyświetlenie formy tekstowej,

zgadza się?

**Comment by ad-m** [comment]
@rwakulszowa , myślę, że odwoływanie się stale do pliku ```eml```, który docelowo może być plikiem na zdalnym zasobie nie jest optymalnym rozwiązaniem. W mojej ocenie należy rozbudować Letter o pole html_content, a następnie wyświetlać html_content, jeżeli jest dostępny. Będzie dostępny, gdy procedurę importowania e-maili dostosuje się, aby wypełniała html_content.

Plik ```eml``` jest dostępny zawsze w przypadku listów, które pochodzą od użytkowników, którzy dostarczyli je e-mailem. E-maile mogą mieć warstwę tekstową, warstwę HTML, albo oba. Listy do systemu mogą być dostarczone także przez przeglądarkę i tam wystarczy postać tekstowa na razie.
