### ISSUE TITLE
Drobna ocena odpowiedzi na koniec sprawy

### ISSUE THREAD

**Issue by ad-m** [watchdogpolska/poradnia#537]
W powiadomieniach o listach można dodać małe odnośniki z oceną odpowiedzi:

![zaznaczenie_1483](https://user-images.githubusercontent.com/3618479/39117982-8673714e-46e8-11e8-81f3-37bbddb60b75.png)
![zaznaczenie_1484](https://user-images.githubusercontent.com/3618479/39118002-931dc480-46e8-11e8-9f40-df7e8bb169b2.png)

Docelowo można to ładnie spiąć z BI i widzieć więcej ewentualnych problemów.

**Comment by AgnieszkaZdanowicz** [comment]
@ad-m Nie zauważyłam tego wcześniej, ale to fajny pomysł! A to by się wysyłało, jak zamykam sprawę i powiadamiam klienta?

**Comment by AgnieszkaZdanowicz** [comment]
nadal uważam, że to fajny pomysł, więc zostawiam otwarte

**Comment by AgnieszkaZdanowicz** [comment]
tu mam o tyle wątpliwość, że raczej nie korzystamy z funkcji "powiadom klienta", jak zamykamy sprawę. Bo zamykamy je nie wtedy, jak są już ostatecznie skończone, ale też wtedy, kiedy odpowiedzieliśmy na dane pytanie i czekamy na reakcję klienta. Chodzi o to, żeby w sprawach "otwartych" (znaczy przypisanych lub moderowanych) pojawiały nam się tylko te sprawy, w których aktualnie musimy coś zrobić. Gdybyśmy wysyłali wiadomość do klientów, że zamknęliśmy ich sprawę, która wcale nie jest zakończona, to to by wzbudziło u nich pewnie niezrozumienie. A trudno też ocenić, kiedy sprawa jest ostatecznie zakończona. Mimo tych problemów, pomysł z ocenianiem udzielonych porad wydaje mi się fajny. Chciałam oznaczyć tu Karolinę, żeby oceniła, ale nie mogę jej dodać, bo mi github nie wyszukuje

**Comment by KarolaJ** [comment]
@AgnieszkaZdanowicz również uważam, że Klient nie powinien być informowany o zamknięciu sprawy, aby go nie niepokoić. A ocenę udzielonej porady myślę, że można zrobić automatycznie po każdym wysłanym liście, bo niemalże każdy list to kolejna/nowa porada.

**Comment by AgnieszkaZdanowicz** [comment]
@KarolaJ ale czasem dopytujemy klientów, czy coś wysłali albo prosimy, żeby dosłali (no przynajmniej ja to robię przy SK). To wtedy za każdym razem by dostawali ankietę? Chyba, że ta ocena byłaby jako stopka w mailu z treścią porady? @PiotrIw czy Ty to widzisz jakoś od strony UX?

**Comment by PiotrIw** [comment]
Podsumowując wątki powyżej i mailowe:

- Po udzieleniu porady i zakończeniu bieżącej pracy nad sprawą, zmieniamy jej status na np "kompletna" i wysyłamy maila z informacją o tym do klienta oraz z prośną o dokonanie oceny i linkiem do formularza prostej oceny
- sprawa przyjmuje tylko maile od osób już zaangażowanych a inne oznacza jako spam
- dodajemy możliwoość "wznowienia" porady czyli przywrócenia stanu aktywna

@KarolaJ @AgnieszkaZdanowicz  
- kto ma mieć uprawnienia do zmiany stanu sprawy na kompletna/wznowiona?
- co ma być na formularzu oceny?

**Comment by AgnieszkaZdanowicz** [comment]
@PiotrIw zmieniać stan sprawy niech mogą na pewno admini, ale też osoby, które mają przypisane uprawnienie "wsparcie++" (to jest w panelu admina w permission group"

Co do treści ankiety z oceną, to nie mamy tego przegadanego, a Karolina zniknęła teraz na kilka dni. Ja bym była za prostym formularzem "czy jest Pan/Pani zadowolony/zadowolona z udzielonej porady?" i odpowiedzi: tak/nie/nie mam zdania + pole na dodatkowe uwagi. Czy jest sens, żebyś wstępnie coś takiego przygotował i potem najwyżej treść zmienimy? Czy lepiej poczekać na Karolinę do przyszłego tygodnia?

Mam też pytanie - gdzie będą pojawiać się oceny i kto będzie mógł je zobaczyć?

Zastanawiam się, jak ten nowy status "kompletna" będzie się miał do statusu "zamknięta". Bo przy "zamknięta" też była koncepcja, że możemy wysłać powiadomienie do klienta, ale realnie z tego nie korzystamy. To może wyłączyć tam tę opcję wysyłania powiadomień? "zamknięta" może być w danym momencie, ale to co innego niż "kompletna"

**Comment by AgnieszkaZdanowicz** [comment]
@PiotrIw to wyjaśnię, że my obecnie "zamykamy" sprawę, jak wyślemy odpowiedź do klienta i chwilowo nie mamy w niej nic do zrobienia. Ale ten status nie oznacza, że ona jest już zakończona ostatecznie. Cel jest taki, żeby sprawy, w których czekamy na odpowiedź od klienta, nie były widoczne na liście spraw do zajęcia się, bo byłoby się trudno zorientować, co jest do zrobienia. Jak klient coś odpisze, to sprawa się "otwiera" albo my możemy to zrobić ręcznie. Tak więc to, o czym tu rozmawiamy, to jest jednak jeszcze inny status - w tej rozmowie chodzi o sprawy "ostatecznie zamknięte" :) Ale też się boję mnożenia opcji i im dłużej nad tym myślę, tym bardziej szukam jednak innego rozwiązania. Bo tu nam chodzi jednak o ankiety z ocenami, a nie o kolejny status do zaklikiwania :). Może lepszym rozwiązaniem byłoby jednak zrobienie mechanizmu do wysyłania ankiety raz na kwartał do klientów, którym udzieliliśmy porady w ciągu ostatnich 3 miesięcy? Wtedy też klienci, którzy mają dużo spraw, nie dostawaliby kilkunastu ankiet po każdej ze spraw, tylko jedną zbiorczą. Nie mam przekonania, że potrzebujemy oceny każdej sprawy osobno - chyba bardziej nam chodzi o ogólne odczucia ludzi, jak działa poradnia. Tylko wtedy ta ankieta mogłaby być odrobinę bardziej rozbudowana i zawierać pytania o czas odpowiedzi, jasność porady etc.

**Comment by KarolaJ** [comment]
Wracając do tego wątku to myślę, że trzeba pomyśleć jaki skutek ma mieć
taka ankieta dla SOWP, co ma ona nam dawać. Jeżeli ma to pomóc w
ewentualnej transformacji, reformie poradni (o czymś takim wspominał Szymon
i Marzena) to pewnie, jeśli nie to nie widzę sensu, bo my działamy darmowo
i nie mamy w zakresie poradni biznesowego nastawienia na satysfakcję
Klientów, która ma zwiększać zyski.

Jeśli to wprowadzić to jestem za rozwiązaniem Agnieszki, raz na kwartał.
Dobrym rozwiązaniem byłoby też wysyłać do Klientów, a nie do konkretnych
spraw, bo tak jak Agnieszka napisała jeden Klient ma czasem kilka lub
kilkanaście spraw i może by się Klienci wkurzali dostając tyle maili z
prośbą o ocenę.

*Pozdrawiam *
*Karolina Jankowska*


*Wspieraj działania Watchdoga!*
<https://siecobywatelska.pl/wspieraj-dzialania-watchdoga/>

*Sieć Obywatelska Watchdog Polska*
ul. Ursynowska 22/2 | 02-605 Warszawa
tel: +48 22 844 73 55

KRS: 0000181348
NIP: 526 284 28 72



czw., 15 cze 2023 o 08:37 AgnieszkaZdanowicz ***@***.***>
napisał(a):

**Comment by AgnieszkaZdanowicz** [comment]
Ja nie dam rady zastanowić się nad tematem przed urlopem, ale nie chcę go zupełnie porzucać, bo dla mnie jednak ten pomysł jest ważny. Dlatego zawieszam temat do października.
