### ISSUE TITLE
poprawki do rejestracji

### ISSUE THREAD

**Issue by ad-m** [watchdogpolska/poradnia#54]
Kasia zgłasza.

sorki, jeśli Cię zalewam.

 

1.       Tu brakuje przecinka: Masz konto? Jeśli tak, to zaloguj się.

2.       Są gwiazdki, ale nie jest wytłumaczone o co cho..

 

3.       Proponuję, albo zlikwidować gwiazdki i pod spodem napisać: Wszystkie pola należy obowiązkowo wypełnić. Albo napisać coś, co jest średnio logiczne: „pola oznaczone gwiazdką należy wypełnić obowiązkowo”

![image002](https://cloud.githubusercontent.com/assets/3618479/8635769/8fe55d00-2837-11e5-95d7-1c4900e5e5ca.jpg)

**Comment by ad-m** [comment]
W mojej ocenie należy dodać polę imię i nazwisko (nieobowiązkowe). To trochę rozwiąże ten problem.

**Comment by KatarzynaBatko** [comment]
Dobra :)

**Comment by ad-m** [comment]
Miło Cię widzieć w moich królestwie :-)

**Comment by ad-m** [comment]
![zaznaczenie_325](https://cloud.githubusercontent.com/assets/3618479/8637651/b47747ae-289c-11e5-91f0-30ad4131cda0.png)
Teraz nie wszystkie pola są obowiązkowe…

**Comment by KatarzynaBatko** [comment]
To tylko dodaj, że pola z gwiazadką są obowiązkowe :)

**Comment by ad-m** [comment]
![zaznaczenie_332](https://cloud.githubusercontent.com/assets/3618479/8639456/055eee9a-28db-11e5-9059-b8c824937fb8.png)
