### ISSUE TITLE
wyświetlanie wiadomości HTML na poradni 

### ISSUE THREAD

**Issue by AgnieszkaZdanowicz** [watchdogpolska/poradnia#544]
Na poradni niektóre (dotąd 2) wiadomości wyświetlają się w takim okienku:

![image](https://user-images.githubusercontent.com/36925935/40362939-4b1b6104-5dce-11e8-9e37-bac7026ddd71.png)

To chyba jest związane ze zmianą w odczytywaniu wiadomości HTML. Miałabym prośbę, żeby to okienko było szersze - najlepiej na całą szerokość strony

**Comment by ad-m** [comment]
@mik-laj , zrób chociaż #536 to zrobię to.

**Comment by rwakulszowa** [comment]
Na szybko możemy po prostu ustawić większe domyślne wartości.

Zdaje się że ustawienie szerokości na 100% nie wymaga zmian we frontendzie. Dopasowanie wysokości jest bardziej złożone.

**Comment by AgnieszkaZdanowicz** [comment]
Michał, który używa przeglądarki edge, nie widzi w ogóle tekstu w tym okienku, w którym wyświetla się wiadomość. Co można na to poradzić?

**Comment by ad-m** [comment]
@AgnieszkaZdanowicz , Microsoft Edge to niszowa przeglądarka. Mniej niż 5 % rynku. My natomiast wykorzystujemy ogólnoprzyjęty standard HTML5. Tylko Microsoft się do tego standardu nie stosuje w tym zakresie, co sam przyznaje na swojej stronie https://developer.microsoft.com/en-us/microsoft-edge/platform/status/iframesrcdocattribute/ . Potwierdzają to także inne źródła ( https://caniuse.com/#search=srcdoc ) dodając, że dla Polski niemal każdy (95%) wykorzystuje dostatecznie nowoczesną przeglądarkę.

Proponuje, aby Michał skontaktował się z dostawcą oprogramowania którego używa i wymusił na nim przestrzeganie standardów poprzez wydanie poprawionej wersji przeglądarki, albo…zmienił dostawcę. Z tego co wyczytałem istnieje szansa, że Microsoft w kolejnej wersji swojej przeglądarki naprawi ten błąd po ich stronie, więc nie widzę powodu do prac po naszej stronie.

**Comment by rwakulszowa** [comment]
Najłatwiejszym rozwiązaniem będzie uzycie innej przeglądarki (dowolny Firefox / Chrome).

Myślę jednak, że faktycznie powinniśmy wykrywać czy przeglądarka wspiera iframe / srcdoc i ewentualnie wyświetlać formę tekstową.

**Comment by AgnieszkaZdanowicz** [comment]
Tak myślałam, chciałam się upewnić - dzięki za szybkie odpowiedzi :)

**Comment by AgnieszkaZdanowicz** [comment]
Hej, prosiłabym Was o rozszerzenie tego okienka na 100 % szerokości, bo teraz bardzo dużo wiadomości przychodzi w takim okienku i czytanie tego jest bardzo trudne.

**Comment by ad-m** [comment]
@mik-laj trzeba pogonić.

pon., 28.05.2018, 11:10 użytkownik AgnieszkaZdanowicz <
notifications@github.com> napisał:

**Comment by mik-laj** [comment]
@ad-m  za to odpowiada ta linijka:
https://github.com/watchdogpolska/poradnia/blob/86b0faccdeaa196a3dc7e45c828454f2c48cc10d/poradnia/letters/templates/letters/_letter_list.html#L19

**Comment by ad-m** [comment]
Tak, napraw budowanie styli, bo wyłączyłeś z bootstrapa przeładowanie wysokości elementów w CSS. Nie możemy zbudować CSS. Na to jest zgłoszony błąd do którego jesteś przypisany.

**Comment by ad-m** [comment]
https://github.com/watchdogpolska/poradnia/issues/536

**Comment by rwakulszowa** [comment]
Dodałem commit który powinien tymczasowo ułatwić czytanie maili zanim dodamy porządne rozwiązanie.
#546

**Comment by ad-m** [comment]
Nie. Dziś wgram.

pt., 1.06.2018, 10:25 użytkownik AgnieszkaZdanowicz <
notifications@github.com> napisał:

**Comment by ad-m** [comment]
Działa. Ludzie korzystają.
