### ISSUE TITLE
Zapisywać długie listy w pamięci przeglądarki

### ISSUE THREAD

**Issue by ad-m** [watchdogpolska/poradnia#553]
https://gist.github.com/mik-laj/ef042b5aeea1c7793ed1ac0227d44c0c

Paula zgłaszała.

**Comment by mik-laj** [comment]
https://codepen.io/mik-laj/pen/dgbPaM?editors=0010 tutaj jeszcze raz napisałem kod. Wystarczy, że dorzucisz gdzieś ten kod JS, a potem do formularza, który chcesz, aby był zapisywany dodasz atrybut `data-form-save`, a w zawartości podasz unikalny klucz formularz np. `case-1`.

**Comment by ad-m** [comment]
@mik-laj , bardzo dziękuje!
