### ISSUE TITLE
wysyłanie maili do klientów z poradni

### ISSUE THREAD

**Issue by AgnieszkaZdanowicz** [watchdogpolska/poradnia#554]
Jeden z klientów (sprawa 3246) napisał tak:

_System wysyła 2x tą samą wiadomość z czego 2 ma tylko dopisek „Szymon Osowski (team) zaakceptował pismo:”, stan ten obniżać może rating wiadomości dla list spamowych RBL itp._

Przyznaję, że nie testowałam, co dostają klienci i myślałam, że dostają tyko jednego maila - tego z treścią porady. A my dostajemy 2 maile jako członkowie zespołu. Czy rzeczywiście klienci dostają też dwie wiadomości? I czy to obniża rating?

**Comment by ad-m** [comment]
Przyjrzę się temu dziś wieczorem.

**Comment by ad-m** [comment]
W https://github.com/watchdogpolska/poradnia/pull/575 poprawka.
