### ISSUE TITLE
Mail potwierdzający adres email jest po angielsku

### ISSUE THREAD

**Issue by kbiernat** [watchdogpolska/poradnia#558]
j.w.t.
Również po kliknięciu linku weryfikacyjnego komunikat jest po angielsku

Przeglądarka wysyła następujący nagłówek: `accept-language: pl-PL,pl;q=0.9,en-US;q=0.8,en;q=0.7`

Przeglądarka: Chrome 68

![potwierdzenie_link](https://user-images.githubusercontent.com/9462876/43994397-8d2b4bc8-9d9c-11e8-8660-284e541ac7dc.png)
![potwierdzenie_email](https://user-images.githubusercontent.com/9462876/43994398-8d4389ae-9d9c-11e8-9b4a-a637b18a94b9.png)

**Comment by ad-m** [comment]
Pull request jest tu: #594
