### ISSUE TITLE
poprawiona wersja w rejestracji nowej sprawy

### ISSUE THREAD

**Issue by ad-m** [watchdogpolska/poradnia#56]
Kasia zgłasza.

Proponuję krócej i mniej komplikacji. Ludzie nie myślą w taki sposób jak Ty. Jest w nich więcej chaosu.

Znów są gwiazdki, a wszystkie pola obowiązkowe.

 

Witamy w elektronicznym systemie poradnictwa Sieci Obywatelskiej Watchdog Polska. Tu możesz opisać swój problem.

Prosimy, podaj nam w poniższym formularzu informację jak przebiegała sytuacja i z jakim pytaniem się zwracasz. Załącz nam kopie pism (e-maile, skany, czytelne zdjęcia).

 

Poprawka do opisu „przedmiot”

Podaj nazwę instytucji i typ problemu np. „brak odpowiedzi”, „ochrona danych osobowych” itp.

 

Pod e-mai, trzeba poprawić:

Konto użytkownika zostanie utworzone automatycznie, dzięki czemu będziesz mieć dostęp do archiwum zawierającego wszystkie Twoje sprawy.

**Comment by ad-m** [comment]
Zmieniłem teksty. 

Myślę, że gwiazdki nie wprowadzają chaosu, choćby były na polach obowiązkowych. Przyjęta konwencja. Tłumaczy coś, bo w przypadku błędnie wypełnionego formularza możesz się dowiedzieć o co chodzi. Wprowadzanie obowiązkowych pól, ale bez gwiazdki może dezorientować, jeżeli absolutnie wszędzie indziej konwencje zachowywać.
![zaznaczenie_319](https://cloud.githubusercontent.com/assets/3618479/8637407/8df531b0-2890-11e5-9944-ac9181bda1c1.png)

Pozostawiam otwarte ze względu na dyskusje.

**Comment by KatarzynaBatko** [comment]
Ja tylko chciałam wytłumaczenia czym jest gwiazdka. A z drugiej strony może przesadzam. Nie bedę kruszyć kopii o to.
