### ISSUE TITLE
uwaga od użytkownika

### ISSUE THREAD

**Issue by KatarzynaBatko** [watchdogpolska/poradnia#562]
Cześć Chciałem zgłosić błąd działania Poradni, bo jak coś nowego się pojawia z Waszej strony, pismo, tekst, cokolwiek, to już nie otrzymuję maili na skrzynkę, że coś się pojawiło, stąd pewnie opóźnienia z mojej strony w odpisywaniu na pytania, itd.

Czy da się to naprawić bo to była super funkcja!

**Comment by ad-m** [comment]
Takie zachowanie jest oczekiwane. Jeżeli takie powiadomienia nie są wysyłane to jest to niepożądane działanie, które winno zostać wyeliminowane. Czy mógłbyś podać swój adres e-mail i wskazać o jakim piśmie nie dostałeś powiadomienia? Preferujemy świeże pismo (7 dni) dla których mamy sprawniejszy dostęp do logów. 

@kbiernat , weryfikowałeś to chyba ostatnio. Odczuwałeś jakieś problemy w tym zakresie?

**Comment by kbiernat** [comment]
być może ktoś z zespołu klikał 'odpowiedz dla zespołu' zamiast 'wszystkim'. Jak zobaczymy o którą konkretnie sprawę chodzi to można zbadać. Same logi z dziś sprawdziłem wyrywkowo, wiadomości wychodzą poprawnie.

**Comment by KatarzynaBatko** [comment]
napisałam do Marcina, który to zgłosił. Na razie nie odpisał, ale to pewnie proste do sprawdzenia po adresie  <redakcja@nowa-wies-kety.pl> lub infoskawina. Podejrzewam, że pisał z któregoś z tych dwóch. Ale jak nie chcesz tracić czasu na dochodzenie o co chodzi, to poczekajmy na info od  Marcina.

**Comment by KatarzynaBatko** [comment]
Chyba niepotrzebnie zawracałam Wam głowę. Bo jak się okazało, wpadło mu do spamu. Przy czym wcześniej nie wpadało.  A reszta zamieszania wynika z tego, że on nawet sprawdzał spam, ale nie na tym mailu. W poradni ma inny, niż ten którego najczęściej używa. Kwalifikacji spamu dokonał gmail.
Więc jedyne co być może powinno nas niepokoić, to ten spam. Gdyby nadal potrzeba było tych numerów spraw, to np. #3482 i #3491.

Pozdrawiam i dzięki. k

**Comment by kbiernat** [comment]
Mamy już issue na wpadanie maili do spamu. Jak widać muszę sie zając tematem prędzej niż później :)

**Comment by KatarzynaBatko** [comment]
Dzięki :)

**Comment by ad-m** [comment]
@HOWARDKNOPFLER, czy wciąż odnotowujesz problem?

**Comment by ad-m** [comment]
Brak reakcji użytkownika. Zamykam.

**Comment by HOWARDKNOPFLER** [comment]
Już jest dobrze. Ale pojawia się inny błąd.
Po wpisaniu nowego posta/wiadomości to zostaje na dłużej jej treść.
W sensie, gdy z tego wyjdę i wrócę, to aktywne jest okienko edycji tekstu z tekstem jak wcześniej już wpisanym, wiec żeby coś nowego napisać, muszę kasować poprzedni tekst w okienku i dopiero pisać coś nowego.
