### ISSUE TITLE
emaile z poradni - linki nie działają poprawnie

### ISSUE THREAD

**Issue by AgnieszkaZdanowicz** [watchdogpolska/poradnia#564]
Jak wpływa nowa sprawa na poradnię, to dostaję maila i w niej jest link, który teoretycznie prowadzi do tej sprawy na poradni. Tak było dotąd. A teraz ten link prowadzi do głównej strony na poradni. Przykład z dziś:

![image](https://user-images.githubusercontent.com/36925935/45740765-45ab4000-bbf6-11e8-9603-1254e5b9972b.png)

![image](https://user-images.githubusercontent.com/36925935/45740908-a175c900-bbf6-11e8-9ee8-b4fd0703e8c3.png)

I linki z powyższych maili kierują mnie tu:

![image](https://user-images.githubusercontent.com/36925935/45740819-66739580-bbf6-11e8-8326-5ae1c8e939ca.png)
  
Nie mogę sobie przypomnieć, czy tak jest przy każdej nowej sprawie, też nie we wszystkie linki klikam.
A może tak się dzieje, jak w między czasie (między otrzymaniem maila, a kliknięciem w link), co się w sprawie zmieniło np. została już do kogoś przypisana?

**Comment by AgnieszkaZdanowicz** [comment]
Jednak link działa źle również wtedy, kiedy nic się w sprawie nie zmieniło w między czasie. Teraz tak było ze sprawą 3656

**Comment by ad-m** [comment]
Bardzo dziwne! Wyjaśnię jutro wieczorem.

**Comment by AgnieszkaZdanowicz** [comment]
W sprawie 3657 link zadziałał poprawnie

**Comment by ad-m** [comment]
@AgnieszkaZdanowicz , czy jest to powtarzalne? Występuje dla konkretnych wiadomości?

**Comment by AgnieszkaZdanowicz** [comment]
Moim zdaniem tak się dzieje (przynajmniej u mnie) we wszystkich nowych
sprawach. Tak jak dziś ze sprawą 3736. Przyszedł mail, że jest nowa sprawa,
kliknęłam w link z wiadomości i przeniósł mnie na stronę główną poradni:

W systemie Poradnia została dodana nowa sprawa. Przejdź pod adres
http://poradnia.siecobywatelska.pl//sprawy/sprawa-3736/, aby się z nią
zapoznać.

Agnieszka Zdanowicz

 <http://siecobywatelska.pl/>

Sieć Obywatelska Watchdog Polska
ul. Ursynowska 22/2 | 02-605 Warszawa
KRS: 0000181348
tel: +48 22 844 73 55 <+48228447355> | fax: +48 22 207 24 09
www.siecobywatelska.pl | www.watchdogportal.pl | www.informacjapubliczna.org



czw., 4 paź 2018 o 02:29 Adam Dobrawy <notifications@github.com> napisał(a):

**Comment by ad-m** [comment]
OK, już wiem co jest :+1: Naprawie w weekend. 

Link jest do poradnia.siecobywatelska.pl, a ta domena cała przekierowuje do porady.siecobywatelska.pl. Link powinien być do porady.siecobywatelska.pl.

**Comment by ad-m** [comment]
Fixed via https://github.com/watchdogpolska/poradnia/commit/c5008fb590e9ca2653f01aa9b293549bcf51dac8 .
