### ISSUE TITLE
Nazwa strony pod logiem Watchdoga Polska

### ISSUE THREAD

**Issue by ad-m** [watchdogpolska/poradnia#57]
Kasia zgłasza.

> na stronie główna stronie głównej pod znaczkiem watchdoga jest wyraz "poradna", taki niby aktyny, ale nigzie nie prowadzi. Proponuję zlikwidowaćnej pod znaczkiem watchdoga jest wyraz "poradna", taki niby aktyny, ale nigzie nie prowadzi. Proponuję zlikwidować

**Comment by ad-m** [comment]
Ja jednak proponuje dodać link do strony głównej. Myślę, że warto gdzieś zachować nazwę strony. W innym wypadku będziemy mieli problem komunikacyjny, bo ludzie będą dowolnie nazywać, a my będziemy musieli zgadywać o co im chodzi. Jeżeli będzie jakakolwiek nazwa własna to w dominującym stopniu ludzie będą jej używać. 

Poprawiłem poprzez podlinkowanie do strony.

**Comment by KatarzynaBatko** [comment]
Jasne. Dwie uwagi. Co do strony głównej, to i tak wraca się na nią zawsze przez home. Może zatem raczej gdzieś podlinkować do strony sieci. Wymagałoby to jednak napisania nazwy Sieć Obywatelska Watchdog Polska.

Co do nazwy własnej, to z rozmowy z Szymonem wnioskuję, że problem jest właśnie w słowie poradnia, że niby brzmi jak "poradnia zdrowia". Ale że nie mam lepszego pomysłu, to proponuję napisać tam: Poradnia prawna Sieci Obywatelskiej Watchdog Polska www.siecobywatelska.pl. I na razie nie przenoś w takim razie na ten nowy adres. Pogadam z Szymonem. Jak z nim rozmawiałam to umknęła m nazwa "Klinika Uniwersyteckich Poradni Prawnych" i nie miałam do czego się odwołać. Bo zgadzam sie, że dobrze by była nazwa.

**Comment by ad-m** [comment]
Ja już przeniosłem na nowy adres  :angry: Proszę się zdecydować.

**Comment by KatarzynaBatko** [comment]
Skoro przeniosłeś, to nie ma o czym mówić. Twój argument o nazwie mnie zastanowił, ale w tej sytuacji nie ma co komplikowac i ustalać na nowo. To proponuję tam pod pieskiem: Porady prawne Sieci Obywatelskiej Watchdog Polska www.siecobywatelska.pl

**Comment by ad-m** [comment]
"Porady prawne Sieci Obywatelskiej Watchodg Polska" to bardzo długi tekst. Nie wiem czy nadaje się na tytuł. U mnie psuje menu. Już użytkownicy / użytkownicy to bardzo szeroki teskt. Sieć Obywatelska - Watchdog Polska jest zaznaczona w wielu miejscach innych miejscach. Niedługo dojdą dodatkowe dokumenty to opisujące.

Ewentualnie samo "Watchdog Polska"  :wink:

![zaznaczenie_333](https://cloud.githubusercontent.com/assets/3618479/8639477/a956a6aa-28db-11e5-8940-5ca7ec98bf7e.png)

Ewentualnie, Kamil, ustal z Kasią coś.

**Comment by KatarzynaBatko** [comment]
Może być J dznx

**Comment by ad-m** [comment]
Zatem musimy wybrać nazwę. Z tego względu zgłoszenie pozostawiam otwarte.

**Comment by ad-m** [comment]
Zmienić nazwę strony na "Poradnia".
