### ISSUE TITLE
poradnia nie łączy wątków

### ISSUE THREAD

**Issue by AgnieszkaZdanowicz** [watchdogpolska/poradnia#578]
Problem jest bardzo utrudniający pracę. Jak klienci odpowiadają na nasze maile, to poradnia te odpowiedzi kwalifikuje jako nowe sprawy, a nie jako kontynuację sprawy.  To powoduje chaos i wpływa na nasze statystyki. Potrzebujemy pomocy.

**Comment by ad-m** [comment]
Dziękuje za informacje o tym jak mocno jest to uciążliwe. Postaram się tym zająć pilnie.

**Comment by ad-m** [comment]
Problem znacząco ograniczony.

**Comment by AgnieszkaZdanowicz** [comment]
Bardzo serdecznie dziękuję! :)

Agnieszka Zdanowicz

Dyrektorka Zarządzająca

<http://siecobywatelska.pl/>

Sieć Obywatelska Watchdog Polska
ul. Ursynowska 22/2 | 02-605 Warszawa
KRS: 0000181348
tel: +48 22 844 73 55 <+48228447355> | fax: +48 22 207 24 09
www.siecobywatelska.pl | www.watchdogportal.pl | www.informacjapubliczna.org


pon., 5 lis 2018 o 18:54 Adam Dobrawy <notifications@github.com> napisał(a):

**Comment by AgnieszkaZdanowicz** [comment]
Adam, wciąż nie łączy wątków i ja się już gubię :/

**Comment by ad-m** [comment]
Odszukałem kilka wiadomości, które nie połączyło. Dodałem do automatycznych testów. Poprawiłem kod. Powinno być znacząco lepiej. Nie wymarzenie, ale na pełnego rozwiązania dziś nie wprowadzę, ale jak pojutrze przejrzę nowe sprawy to myślę, że doprowadzimy do stanu nie gorszego niż wcześniej. Aktualizacja wgrana.

**Comment by AgnieszkaZdanowicz** [comment]
teraz wygląda dobrze, dzięki :)
