### ISSUE TITLE
Stopka

### ISSUE THREAD

**Issue by ad-m** [watchdogpolska/poradnia#58]
Kasia zgłasza.

Ale nie „celem” a „w celu”

 

I brak informacji jak oni mają nas powiadomić. Strona nie ma stopki z adresem, ani tu nie jest podane. Może dorobimy stopkę wzorowaną  na głównej stronie, i przy okazji damy politykę prywatności? I chyba powinniśmy mieć powiadomienie o ciasteczkach na tej stronie?

 

Pozdr. k

**Comment by KatarzynaBatko** [comment]
Jednak ten opis ma więcej błędów, ponieważ teraz zarejestrowałam się jeszcze raz. Nie wiem czy widzisz obrazek, ale powinno być:

Wysłaliśmy do Ciebie wiadomość, która ma służyć upewnieniu się, że chcesz być  z nami w kontakcie. Kliknij w link, który otrzymasz na podany przez Ciebie adres e-mail, aby ukończyć rejestrację.

Powiadom nas, jeśli nie otrzymasz wiadomości w ciągu kilku minut. Kontakt do administratora: karol.bregula@siecobywatelska.pl.


![image](https://cloud.githubusercontent.com/assets/13284861/8636952/86f66f38-287b-11e5-89a2-443c30107593.png)

**Comment by ad-m** [comment]
> Ale nie „celem” a „w celu” 

Nie rozumiem.

> Może dorobimy stopkę wzorowaną na głównej stronie, i przy okazji damy politykę prywatności? I chyba powinniśmy mieć powiadomienie o ciasteczkach na tej stronie?

Myślę, że na stronie głównej stopka jest bardzo duża. Zabierze nam na wielu ekranach znaczną powierzchnie ekranu. Proponuje stopkę jak na http://ical2html.herokuapp.com/ :
 
![zaznaczenie_334](https://cloud.githubusercontent.com/assets/3618479/8639501/49b02aae-28dc-11e5-8cbc-d6a949561d3f.png)

**Comment by KatarzynaBatko** [comment]
Już gdzieś indziej napisałam Ci inny tekst calości. Więc zostawmy. Stopka, którą proponujesz, jest ok.

**Comment by ad-m** [comment]
- [ ] stopka
