### ISSUE TITLE
rejestr porad - nie działa zaznaczanie 

### ISSUE THREAD

**Issue by AgnieszkaZdanowicz** [watchdogpolska/poradnia#584]
Zaczęłyśmy z Paulą uzupełniać rejestr porad i chcemy przeklikać wszystkie porady z poradni, ale wydaje nam się, że nie zapisują się dane zaznaczone w polu "Zakresy tematyczne zapytania". Mam ogromną prośbę o sprawdzenie i naprawienie, bo bez tego w sumie nie możemy zacząć:

![image](https://user-images.githubusercontent.com/36925935/53076928-2d1abb00-34f1-11e9-87cc-33632eb4078d.png)

**Comment by ad-m** [comment]
Poprawka przygotowana.

**Comment by ad-m** [comment]
Uruchomiłem wdrażanie na produkcje, więc w krótkim czasie powinno się to (i inne zgłoszone jako naprawione) zostać naprawione.

**Comment by ad-m** [comment]
Dodam, że zaktualizowałem wiele bibliotek w ramach odkurzania, więc mogą być niespodziewane zmiany, których stałem się uniknąć. Jeszcze kilka pozostało, trudniejszych do aktualizacji, abyśmy byli na bieżąco.
