### ISSUE TITLE
rejestr porad - czy jedno pole może być wielokrotnego wyboru?

### ISSUE THREAD

**Issue by AgnieszkaZdanowicz** [watchdogpolska/poradnia#585]
Jak rejestrujemy poradę, to w polu "Problem z zakresu prawa do informacji" chciałybyśmy mieć opcję wielokrotnego wyboru . Czy jest to możliwe?

![image](https://user-images.githubusercontent.com/36925935/53077097-91d61580-34f1-11e9-991e-b14d223b08ee.png)

**Comment by ad-m** [comment]
Fix available in #596
