### ISSUE TITLE
rejestr porad - czy można dodać pole "siedziba instytucji"?

### ISSUE THREAD

**Issue by AgnieszkaZdanowicz** [watchdogpolska/poradnia#587]
Zastanawialiśmy się w zespole, jakie informacje jeszcze chcielibyśmy wyciągnąć z poradni i wyszło, że dobrze byłoby wiedzieć, na jakim obszarze są monitorowane instytucje. Dlatego prosiłabym o dodanie w rejestrze porad pola "siedziba instytucji" - będziemy tam wpisywać nazwę miasta/gminy. To chyba musi być pole do wpisywania krótkiego tekstu. Chyba, że mamy bazę z nazwami miast/gmin, to lepiej byłoby, gdybyśmy mogli wybierać tę nazwę z listy.

**Comment by ad-m** [comment]
Mamy bazę TERYT, która zawiera informacje o instytucjach - nazwach miast i gmin. Pole tekstowe nie ma problemu.

**Comment by AgnieszkaZdanowicz** [comment]
To jakby się dało zrobić pole takie jak w EOD, że zaczynamy wpisywać nazwę gminy, a ona się podpowiada z bazy, którą mam ,to byłoby super. A jak to duży problem, to wystarczy nowe pole tekstowe.

**Comment by ad-m** [comment]
Nie jest to duży kłopot. To użycie tego co już mamy w inny sposób.

**Comment by rwakulszowa** [comment]
@ad-m - mogę prosić o krótki opis problemu od technicznej strony? Czym jest baza Teryt i jak pobrać z niej dane do poradni?

**Comment by ad-m** [comment]
TERYT (w tym miejscu właściwie TERC) to baza danych jednostek samorządu terytorialnego opracowana przez MC.
Wprowadzenie teoretyczne: https://www.wikiwand.com/pl/TERYT
Implementacja wykorzystywana w Stowarzyszeniu: https://github.com/ad-m/django-teryt-tree/blob/master/teryt_tree/models.py#L55 (interesuje Cię model ```JednostkaAdministracyjna```)
Przykład wykorzystania: https://fedrowanie.siecobywatelska.pl/instytucje/ w polach ```Województwa```, ```Powiat```, ```Gmina```.

**Comment by AgnieszkaZdanowicz** [comment]
To chyba nie jest wprowadzone, a my byśmy chciały w przyszłym tygodniu zacząć tagować. Czy jest szansa dodania tego pola do przyszłego poniedziałku?

**Comment by AgnieszkaZdanowicz** [comment]
@ad-m Adamie, czy coś się uda zrobić w tej sprawie w tym tygodniu (np. w weekend?)

**Comment by AgnieszkaZdanowicz** [comment]
Tutaj, jak się wchodzi w poradę, to pojawia się opis:

![image](https://user-images.githubusercontent.com/36925935/61288169-d925b100-a7c6-11e9-8440-d8ba4329f839.png)

Ale jak się wejdzie w edytowanie porady, to już widać zaznaczoną gminę. Czy tutaj ona się powinna pojawiać?

I czy możliwe jest dodanie pola w filtrowaniu, żeby móc wyszukać po danej gminie?

**Comment by rwakulszowa** [comment]
Nie jestem do końca pewien, ale z tego co widzę w kodzie to pole `obszar` nie odnosi się to jednostki administracyjnej, ale do zakresu sprawy.

Co do filtrowania po gminach - w pewnym stopniu jest to już możliwe, choć dostęp jest nieco ukryty. Po wejściu w ścieżkę `/teryt/` (https://porady.siecobywatelska.pl/teryt/) widoczna jest lista województw, z której można przeklikać się do konkretnych gmin.
Jak wspomniałem, ta funkcjonalność została dodana w pewnym stopniu przy okazji i może pozostawiać wiele do życzenia - w razie znalezienia błędów / sugestii postaram się tym zająć.

**Comment by ad-m** [comment]
Ani tytuł porady, ani tytuł sprawy nie jest informacją ogólnodostępną i powinny być w obu przypadkach brane  pod uwagę uprawnienia użytkownika (zazwyczaj coś w stylu ```.for_user(self.request.user)```).

**Comment by ad-m** [comment]
@AgnieszkaZdanowicz , chcesz wyszukiwanie po gminie czy regionie? Różnica że w przypadku wyszukiwania po gminie jest to dopasowanie ścisłe, a w przypadku wyszukiwania po regionie dla województwa pokaże wszystkie gminy.

**Comment by AgnieszkaZdanowicz** [comment]
Wolałabym po gminie. Ale możemy też wchodzić przez ten teryt

**Comment by ad-m** [comment]
@AgnieszkaZdanowicz , mam wrażenie, że nie zrozumieliśmy się. Moje pytanie dotyczy chcesz przeszukiwanie "chcesz wyszukiwanie po gminie czy regionie", a nie czy ono będzie się odbywało poprzez TERYT, czy poprzez wykaz porad.

**Comment by ad-m** [comment]
Zaimplementowałem z wykorzystaniem wyszukiwania po regionie, ale obecnie pozwalam wybrać wyłącznie gminy.

**Comment by rwakulszowa** [comment]
@ad-m przepraszam, nie zauważyłem PR. Dziś / jutro postaram się przejrzeć.

**Comment by AgnieszkaZdanowicz** [comment]
Ok, takie wyszukiwanie, jak jest obecnie, jest dla mnie ok. Tylko, czy jest opcja, że tam, gdzie możemy filtrować porady, pojawi się pole do wyszukiwania po siedzibie? O tutaj:

![image](https://user-images.githubusercontent.com/36925935/63515877-1ed34900-c4ec-11e9-92f6-1cf6658857c1.png)

Czy szukać będzie można tylko poprzez wejście w ten link: https://porady.siecobywatelska.pl/teryt/?

**Comment by ad-m** [comment]
![obraz](https://user-images.githubusercontent.com/3618479/66613160-d15a8a80-ebc4-11e9-848b-4163e9ee2059.png)

**Comment by AgnieszkaZdanowicz** [comment]
Jest pięknie, dzięki! Pozwalam sobie zamknąć
