### ISSUE TITLE
Mail z potwierdzeniem rejestracji

### ISSUE THREAD

**Issue by KatarzynaBatko** [watchdogpolska/poradnia#59]
Jest literówka i ustalmy, że zwracamy się jako "my". Literów w tytule. Jest "Potwierdz" a powinno być "Potwierdź" oraz "Prosimy o potwierdzenie", a nie "Proszę"

![image](https://cloud.githubusercontent.com/assets/13284861/8636974/00f8c460-287d-11e5-8a1d-90611327e880.png)

**Comment by ad-m** [comment]
+ gender!
