### ISSUE TITLE
Po zarejestrowaniu sprawy

### ISSUE THREAD

**Issue by KatarzynaBatko** [watchdogpolska/poradnia#61]
Pojawia się napis, że sprawa zarejestrowana. Proponuję wyraźniej napisać:

Sprawa o tytule "...." została zarejestrowana.

Poza tym, czy w końcu ten "Przepływ pracy" będzie widoczny?

Czy po dodaniu osoby odpowiedzialnej za tę sprawę, idzie e-mail do osoby?

Nie jest jasne czym się różni w tym widoku wpis od listu. Tzreba może napisa "Wpis - to jest wiadomośc, którą już wysłałeś/-aś"

"List - tu możesz napisać kolejną wiadomość"

![image](https://cloud.githubusercontent.com/assets/13284861/8637018/c768ea7a-287e-11e5-9537-398c61db99bd.png)

**Comment by KatarzynaBatko** [comment]
![image](https://cloud.githubusercontent.com/assets/13284861/8637042/f2fe21e0-287f-11e5-820e-a09db54c1215.png)

**Comment by mik-laj** [comment]
<button type="button" class="btn btn-default" data-toggle="tooltip" data-placement="bottom" title="Tooltip on bottom">Tooltip on bottom</button>

**Comment by ad-m** [comment]
> Poza tym, czy w końcu ten "Przepływ pracy" będzie widoczny?

Tak (mogę zmienić), ale został zablokowany wykaz użytkowników, co oznacza, że klient może dowiedzieć się kto zajmuje się jego sprawą (i tak będą się podpisywać - Szymon mówił), ale nie ma dostępu do wykazu wszystkich, co kusiłoby do tego, aby klikać, aby to właśnie Szymon się sprawą zajmował. 

Wykaz użytkowników (a właściwie członków zespołu) jest dostępny tylko dla zespołu. 

Dla członków zespołu jest dostępnych trochę więcej informacji o sprawie…
![zaznaczenie_336](https://cloud.githubusercontent.com/assets/3618479/8639597/361d84f2-28df-11e5-9871-3e6d8a3a54a9.png)

> Sprawa o tytule "...." została zarejestrowana.

Done.

> Czy po dodaniu osoby odpowiedzialnej za tę sprawę, idzie e-mail do osoby?

Tak, konieczne jest opisanie treści tych wiadomości, ale każda aktualizacja uprawnień jest zgłaszana do osób zaangażowanych w sprawę.


> Nie jest jasne czym się różni w tym widoku wpis od listu. Tzreba może napisa "Wpis - to jest wiadomośc, którą już wysłałeś/-aś"

Skasowałem wpis. Już czytelne?
