### ISSUE TITLE
Sprawy o statusie "wolna sprawa"

### ISSUE THREAD

**Issue by KatarzynaBatko** [watchdogpolska/poradnia#62]
Proponuję dodać wyjaśnienie co to za status. 

Cz to będzie tak, że one się podzielą i będzie w tym widoku dla spraw, po zalogowaniu osobno pokazane będzie, które są wolne, ktore przypisane, a które zakończone?

A może w jednym widoku to będzie i trzeba po prostu zrobić opis mniej więcej taki:

Zgłoszona przez Ciebie sprawa otrzymuje najpierw status "wolna". To znaczy, że nie wiadomo jeszcze, która z udzielających porad osób Ci pomoże. Kiedy już wyznaczona zostanie ta osoba, porada zmieni status na "przypisana". A gdy już Ci pomożemy "zakończona".

Wszystkie zgłoszone przez Ciebie sprawy, możesz przeglądać w naszym systemie po zalogowaniu.

![image](https://cloud.githubusercontent.com/assets/13284861/8637046/1e851dbe-2880-11e5-9318-dfe3cd2092d0.png)

**Comment by ad-m** [comment]
Błędnie był link do "Sprawy o statusie wolna sprawa", bo link ten powinien być dostępny tylko dla członków upoważnionych.

Widok dla Szymona:
![zaznaczenie_320](https://cloud.githubusercontent.com/assets/3618479/8637433/cf5a5d1e-2891-11e5-9cb7-e1286fcba5e2.png)

Widok dla wolontariusza / klienta:
![zaznaczenie_321](https://cloud.githubusercontent.com/assets/3618479/8637437/f9c00f7c-2891-11e5-88e8-edfa052b3e4d.png)

Widok wykazu spraw dla klienta:
![zaznaczenie_322](https://cloud.githubusercontent.com/assets/3618479/8637442/07a9ac88-2892-11e5-9e4a-e4199cb67958.png)

Docelowo będę chciał wprowadzić mechanizm takiego filtrowania jak w rejestrze porad, bo teraz to filtrowanie jest słabo widoczne (por. #38):
![zaznaczenie_323](https://cloud.githubusercontent.com/assets/3618479/8637464/64e4ebe2-2892-11e5-8823-51562b4879ab.png)

**Comment by mik-laj** [comment]
`<button type="button" class="btn btn-default" data-toggle="tooltip" data-placement="bottom" title="Tooltip on bottom">Tooltip on bottom</button>`

**Comment by ad-m** [comment]
Tooltip wygląda szpetnie, @mik-laj .
![zaznaczenie_324](https://cloud.githubusercontent.com/assets/3618479/8637528/b354c9b6-2895-11e5-9585-9db08b3fcec3.png)

**Comment by mik-laj** [comment]
Naprawione. http://imgur.com/4NK9Wmw
