### ISSUE TITLE
grupowe pobieranie załączników

### ISSUE THREAD

**Issue by AgnieszkaZdanowicz** [watchdogpolska/poradnia#627]
Czy jest możliwość wprowadzenia takiego rozwiązania, żeby dało się jednym kliknięciem pobrać wszystkie załączniki wysłane przez klientów? Bo często dostajemy bardzo dużo załączników i to byłoby duże ułatwienie pracy.

**Comment by ad-m** [comment]
Tak, dodam dziś pierw dla prawników. Jak nie będzie to wywoływało problemów wydajnościowych - udostępnimy dla reszty.

**Comment by ad-m** [comment]
Dodane i wdrożone. Zobaczymy jak się zachowuje w tym zakresie Python, a jak nie będzie dość wydajnie to wykonamy mikroserwis w Python.
