### ISSUE TITLE
Sprawa

### ISSUE THREAD

**Issue by KatarzynaBatko** [watchdogpolska/poradnia#63]
A czy dałoby się napisać co to jst sprawa, np. na czerwonym/bordowym (może po gwiazdce na dole?)

Sprawa to Twoje złoszenie dotyczące konkretnego problemu.

Poza tym przydałby się regulamin poradnictwa do ściągnięcia z boku, z informacjami ile trzeba czekać, żeby ludzie kontaktowali się przez ten system itp. Spróbuję napisać i skonsultować z Szymonem.

Przypominam o adresie.

Jakaś informacja o możliwośći wparcia poradnictwa. Wyślę do Agi P. pytanie.

**Comment by ad-m** [comment]
> A czy dałoby się napisać co to jst sprawa, np. na czerwonym/bordowym (może po gwiazdce na dole?)
Nie rozumiem o jakim miejscu myślisz.

**Comment by KatarzynaBatko** [comment]
Chodzi mi o to, że człowiek wchodzi na stronę, i ma z boku sprawa napisane. Może nie wiedzieć o co chodzi. Ale trochę poprawiłam to w głównym tekście, więc na razie zostaw jak jest. Zobaczymy jak zadziała

Tak, wiem, pozostałe kwestie tylko byś może przygotował w sensie przemyślenia na nie miejca. Ja spróbuję je dziś do nich wypchnąć
