### ISSUE TITLE
Aktualizacja readme/getting_up

### ISSUE THREAD

**Issue by rwakulszowa** [watchdogpolska/poradnia#632]
Witam,
obecna instrukcja uruchomienia dockera zdaje się pomijać parę kroków. `docker-compose build` działa poprawnie, ale `docker-compose up` narzeka przy:
- kompilacji sass
- braku bazy danych "poradnia"

Próbowałem na świeżej maszynie Ubuntu 19 (czy wspierana jest jakaś inna wersja?)

**Comment by ad-m** [comment]
Brak jest automatycznych testów w tym obszarze, więc możliwe, że jakaś aktualizacja zależności, która nie była odpowiednio "pinned", albo zmiana w obrazie bazowym, który nie jest "pinned". Stan systemu na hoście nie powinien wpływać na środowisko w kontenerze.

Spojrzę na to w tym tygodniu.

**Comment by rwakulszowa** [comment]
Część zależności jest wywoływana ręcznie (apt-get install), więc podejrzewam że tam może być problem.
