### ISSUE TITLE
rejestr porad - automatyczne ułożenie porad

### ISSUE THREAD

**Issue by AgnieszkaZdanowicz** [watchdogpolska/poradnia#647]
Czy możliwe jest, żeby automatycznie porady układały się od najświeższej do najstarszej? Bo teraz jest na odwrót

![image](https://user-images.githubusercontent.com/36925935/59681085-57e0fb80-91d3-11e9-8c8a-8feead746518.png)

**Comment by ad-m** [comment]
Tak, jest to możliwe. Poprawka w ramach #648 przygotowana.

**Comment by AgnieszkaZdanowicz** [comment]
Teraz już są ułożone dobrze, ale po wejściu w rejestr porad jako pierwsza wyświetla się ostatnia strona :) czy mogłaby się pojawiać pierwsza?

**Comment by AgnieszkaZdanowicz** [comment]
Tutaj widzę, że coś się działo, ale opisany (przyznaję, że drobny) problem nadal występuje. To znaczy, jak się wchodzi w rejestr porad, to automatycznie wyświetla się ostatnia strona z poradami (obecnie 53), a chodziłoby o to, żeby było widać stronę nr 1:

![image](https://user-images.githubusercontent.com/36925935/63515347-f1d26680-c4ea-11e9-98bc-4e9f6dcd880b.png)

**Comment by AgnieszkaZdanowicz** [comment]
@ad-m  To zrobione, więc zamykam
