### ISSUE TITLE
rejestr porad - automatyczne uzupełnianie pola "radzący"

### ISSUE THREAD

**Issue by AgnieszkaZdanowicz** [watchdogpolska/poradnia#649]
W tej chwili, jak rejestrujemy nową poradę, to w polu "radzący" pojawia się imię i nazwisko osoby, która rejestruje poradę. Założenie było takie, że porady są telefoniczne raczej, a sprawy są mailowe. I że poradę rejestruje osoba, która jej udzieliła, stąd to automatyczne uzupełnienie. Ale ostatecznie rejestr będziemy inaczej wykorzystywać - do "otagowania" spraw. I będziemy to robić tak, że wchodzimy w daną sprawę i klikamy "utwórz nową poradę". I wtedy osobą radzącą będzie ta przypisana do sprawy - byłoby nam wygodniej, gdyby to pole się uzupełniało właśnie tą osobą przypisaną do sprawy. Ale nie wiem, co robić, kiedy jest kilka osób przypisanych...

**Comment by ad-m** [comment]
Jak często mamy wiele osób radzących?

**Comment by AgnieszkaZdanowicz** [comment]
ok 10% moim zdaniem

Agnieszka Zdanowicz

Dyrektorka Zarządzająca


Sieć Obywatelska Watchdog Polska
ul. Ursynowska 22/2 | 02-605 Warszawa
KRS: 0000181348
tel: +48 22 844 73 55 <+48228447355> | fax: +48 22 207 24 09
www.siecobywatelska.pl | www.watchdogportal.pl | www.informacjapubliczna.org


wt., 18 cze 2019 o 20:34 Adam Dobrawy <notifications@github.com> napisał(a):

**Comment by ad-m** [comment]
Zatem to margines. Wtedy można ręcznie.
