### ISSUE TITLE
wykaz spraw - oznaczanie, że sprawa jest dodana do rejestru porad

### ISSUE THREAD

**Issue by AgnieszkaZdanowicz** [watchdogpolska/poradnia#650]
Zastanawiam się, czy jak zaczniemy teraz masowo, a potem na bieżąco, wpisywać sprawy do rejestru porad, to nie byłoby nam wygodniej, żeby w wykazie spraw pojawiał się znacznik, że dana sprawa jest już "otagowana", czyli dodana do rejestru porad. Żebyśmy widzieli, co trzeba jeszcze zarejestrować. Mógłby się pojawiać np. fioletowy znaczek z napisem "tag" w tym miejscu, gdzie pojawiają się osoby przypisane do sprawy oraz terminy.

![image](https://user-images.githubusercontent.com/36925935/59753669-ebbed000-9284-11e9-8b73-8e915e222d15.png)

**Comment by ad-m** [comment]
Co sądzisz o tym? W ```poradnia/cases/templates/cases/case_filter.html``` należy dodać nową kolumnę na podstawie pola ```advice``` (zob. ```/poradnia/cases/templates/cases/case_detail.html``` na przykład użycia). Następnie należy zweryfikować z wykorzystaniem django-debug-toolbar czy liczba zapytań jest stała, czy dla każdego wiersza tabeli jest generowane nowe (nie powinno), a wtedy zaktualizować złączenia (```select_related```).

**Comment by AgnieszkaZdanowicz** [comment]
Nie wiem, czy w tym miejscu powinnam o tym napisać, czy osobno? Pytanie mam takie: czy będzie można filtrować sprawy tak, żeby zobaczyć tylko sprawy otagowane lub tylko nieotagowane?

**Comment by ad-m** [comment]
Myślę, że to musi być powiązane, więc warto tu.

**Comment by AgnieszkaZdanowicz** [comment]
Tutaj bardzo by nam ułatwiło pracę, żeby pojawiły się te znaczniki, która sprawa jest otagowana. Czy to trudna zmiana czy jest szansa, żeby ją wprowadzić w najbliższym czasie?

**Comment by ad-m** [comment]
@AgnieszkaZdanowicz , dziś będzie, bo poprawka jest nawet napisana. Nie wdrożyłem jej od razu, bo czekałem aż testy przejdą.
