### ISSUE TITLE
przeszukiwanie w rejestrze porad

### ISSUE THREAD

**Issue by AgnieszkaZdanowicz** [watchdogpolska/poradnia#652]
@ad-m Czy jest możliwość, żeby dało się przeszukiwać rejestr porad po treści komentarza albo pola "przedmiot"?

**Comment by ad-m** [comment]
#662

**Comment by AgnieszkaZdanowicz** [comment]
Tutaj widzę, że można przeszukiwać po "przedmiot" - chcę się upewnić, że po komentarzach nie będzie opcji przeszukiwania? Nie naciskam, tylko pytam, żeby wiedzieć, co ustalić z dziewczynami w tagowaniu.

**Comment by AgnieszkaZdanowicz** [comment]
Poradnia przestała wyszukiwać w rejestrze porad po przedmiocie :(

**Comment by ad-m** [comment]
Naprawione w  6cc0c3005404c799fe7e8fcc9e5279ac069fb162  .

**Comment by AgnieszkaZdanowicz** [comment]
A czy jest możliwość, żeby wyszukiwanie z tego pola było "niedokładne" (tak, jak jest w EOD przy wyszukiwaniu)? Tzn., żeby starczyło wpisać tylko jedno słowo albo nawet jego część i żeby wyszukało wszystkie porady, w przedmiocie których jest użyte dane słowo? Bo teraz trzeba wpisać dokładnie cały tekst z pola "przedmiot", a my sobie przyjęłyśmy taki sposób uzupełniania tego pola, że to wyszukiwanie nie zdaje egzaminu

**Comment by AgnieszkaZdanowicz** [comment]
@ad-m Pozwalam sobie zamknąć, bo moim zdaniem działa już tak, jak chciałyśmy. Mam nadzieję, że nie namieszam. Dzięki!
