### ISSUE TITLE
członek zespołu nie może edytować swoich pism

### ISSUE THREAD

**Issue by AgnieszkaZdanowicz** [watchdogpolska/poradnia#655]
Adamie, np. w tej sprawie: https://porady.siecobywatelska.pl/sprawy/sprawa-9015/ Michał ma zaznaczoną opcję "może zmieniać własne wpisy" , a w rzeczywistości nie może. Dotąd nie było takiego problemu. Czy weszła jakaś zmiana, która mogła to spowodować?

**Comment by ad-m** [comment]
Wyjaśnię to w ten weekend. Myślę, że jakaś aktualizacja.

**Comment by ad-m** [comment]
#661
