### ISSUE TITLE
Pierwsza strona

### ISSUE THREAD

**Issue by KatarzynaBatko** [watchdogpolska/poradnia#66]
mam wrażenie, że już gdzies to pisalam, ale może Ci nie wyslałam. Proponuję poprawki w tekście na pierwszej stronie. Chyba najłatwiej jak po postu całość wkleję.

A, pojawia się coś takiego jak "wykaz spraw" w tym tekście (Ty tak nazwałeś), a  z boku, na czerwonym tle jest samo "sprawy". Proponuję tam zmienić na "Wykaz spraw"

Pomagamy Ci skuetcznie korzystać z Twoich praw

Kim jesteśmy?

Sieć Obywatelska Watchdog Polska to niezależna, apolityczna i niedochodowa organizacja pożytku publicznego o charakterze organizacji strażniczej i think-do-thanku.

Od 12 lat działamy w Polsce na rzecz jawności życia publicznego, dobrego rządzenia i rozliczalności władz.

Stoimy na straży prawa do informacji. Postrzegamy je nie tylko jako warunek dobrego państwa, ale przede wszystkim jako jedno z praw człowieka, które chroni ludzką godność, daje wolność wyrażania opinii i bezpieczeństwo przed nadużyciami władzy.

Wzmacniamy w obywatelach poczucie, że mają prawo dowiadywać się, jak funkcjonują władze oraz instytucje publiczne, a także wpływać na podejmowane przez nie decyzje i sposób gospodarowania publicznym majątkiem (m. in. pieniędzmi z podatków). Uczymy, jak to zrobić skutecznie. W sytuacjach, gdy urzędy nie szanują praw obywateli, udzielamy pomocy prawnej.

Przez lata zdobyliśmy rzetelną wiedzę na temat dostępu do informacji publicznej, kontroli obywatelskiej oraz współdecydowania o sprawach publicznych. Udzielając porad prawnych, mieliśmy okazję poznać bliżej tysiące konkretnych spraw, w kilkuset uczestniczyliśmy na etapie postępowania sądowego (znaczną część wygrywając).

Pomoc prawna

Udzielamy ponad 1000 konsultacji prawnych rocznie. Aby jeszcze sprawniej pomagać, stworzyliśmy stronę, na której w tej chwili się znajdujesz.

Nie jesteśmy specjalistami w każdej dziedzinie. Pomagamy w tematach, które wiążą się z naszą misją, realizowanymi działaniami i celami statutowymi. Dzięki temu mamy pewność, że porada którą otrzymujesz opiera się na doświadczeniu i przemyślanej wiedzy.  

Nasze eksperckie obszary to dostęp do informacji publicznej, fundusz sołecki i wpływanie na decyzje rządzących. 

Aby zgłosić nam kwestię, która chcesz rozwiązać, zarejestruj się lub zaloguj i użyj formularza dla "nowej sprawy". Jeżeli chcesz odwołać się do wcześniejszej korespondencji z  nami, dotyczącej innych problemów - skorzystaj z „wykazu spraw”.

**Comment by ad-m** [comment]
@KatarzynaBatko , straciliśmy dostosowanie tekstu dla użytkownika zalogowanego / nie (por. [```poradnia/templates/pages/home.html wiersz 16```](https://github.com/watchdogpolska/poradnia.siecobywatelska.pl/commit/a383368b6477c5e90b0f2ad78afe9b4e82787646#diff-b3ef131a5c0595f0daab3997c0f9109aR13))

**Comment by KatarzynaBatko** [comment]
jasne. Przeróba ostatniego akapitu:

Aby zgłosić nam kwestię, którą chcesz rozwiązać, użyj formularza dla "nowej sprawy". Jeżeli chcesz odwołać się do wcześniejszej korespondencji z nami, dotyczącej innych problemów, skorzystaj z „wykazu spraw” dostępnego po zalogowaniu.

**Comment by ad-m** [comment]
Kasiu, musisz wybrać "reopen issues", jeżeli oczekujesz ode mnie jakiejś akcji…

W mojej ocenie powinniśmy dodać wykrywanie niezalogowania, bo to dezorientuje jak masz dalej dostępny link "zaloguj się" gdziekolwiek. Ja nie piszę dobrze tekstu. Proszę o przygotowanie.

**Comment by KatarzynaBatko** [comment]
Czekaj, czekaj. Bo ja nie wiem o co chodzi. To już wyjaśnie z Tobą na czacie.

**Comment by KatarzynaBatko** [comment]
Aby zgłosić nam problem, który chcesz rozwiązać, użyj formularza dla "nowej sprawy". Jeżeli chcesz odwołać się do wcześniejszej korespondencji z nami, dotyczącej innych problemów - skorzystaj z „wykazu spraw”.

**Comment by ad-m** [comment]
@mik-laj miał przeanalizował możliwość dodania grafik.

**Comment by ad-m** [comment]
Dodano obsługę zarządzania stroną główną. Opisałem sekcje i wprowadzenie układ wielokolumnowy w dokumentacji: https://github.com/watchdogpolska/poradnia/wiki/Strona-g%C5%82%C3%B3wna

**Comment by mik-laj** [comment]
http://codepen.io/mik-laj/pen/JdaXrg
Zrobiłem coś takiego nieswornego :-/
Liczę na opinie i sugestię.

Ponad pół tysiąca ikonek, które możemy użyć bez problemu jest tutaj: http://fortawesome.github.io/Font-Awesome/icons/ 
Wykorzystujemy je już w projekcie w różnych miejscach.

**Comment by ad-m** [comment]
Jaki stan? Kto na kogo czeka?

@mik-laj , masz wszystkie materiały potrzebne do pracy?
@KatarzynaBatko , miałaś szeroką wizję zmiany porządków treści na w/w podstronie. Nie została sporządzona, bo gdy zdobyliśmy kartkę to zajeliśmy się czymś innym. Możesz przedstawić ponownie? Pewnie pomogłoby to @mik-laj  pchnąć sprawę. Chyba że @mik-laj wie wszystko?

**Comment by KatarzynaBatko** [comment]
Przygotowałam opis, ale wysyam na maila, żebyście dostosowali, za dużo mnie to gmerania kosztuje,a  WY to szybko opanujecie

**Comment by mik-laj** [comment]
"Sieć Obywatelska Watchdog Polska to niezależna, apolityczna i niedochodowa organizacja pożytku publicznego o charakterze organizacji strażniczej i think-do-thanku." To zdanie mi się nie podoba. Jest zbyt mądre. Myśle, że należy sie "zidiocić". 

Zrobiłem pierwszą stronę, ale należy sprawdzić, czy wszędzie jest poprawnie wyświetlony formularz horyzontalny.

**Comment by ad-m** [comment]
- [ ] dodanie bloku "po" poprawnych treściach i odpowiednia edycja.

@mik-laj , aby edytować home najlepiej zmieniać ```/templates/pages/home.html````. ```django-tinycontent``` działa na bazie danych. W przeciwieństwie do ```django-constance```` nie wymaga rejestracji sekcji, a wystarczy użyć templatetagów (por. https://django-tinycontent.readthedocs.org/en/latest/templates.html ).
