### ISSUE TITLE
Zadania

### ISSUE THREAD

**Issue by ad-m** [watchdogpolska/poradnia#67]
Mam propozycje zmiany na przyszłość. 

Proponuje utworzyć nową strukturę tj. zadania.

Obiekt tego rodzaju dodawany byłby do sprawy przez zespół i umożliwiałby zaprezentowanie  zadania. Zadanie opisywałoby przez kogo zostało utworzone, przez kogo ma zostać wykonane i status wykonania. 

Podczas dodawania np. Szymon wybierałby wolontariusza, opisywał zadanie i termin. System upoważniałby wolontariusza dostępu do sprawy i powiadamiał wolontariusza. Wolontariusz mógłby dodać nowy dokument (na starych zasadach) i zaznaczyć zadanie jako wykonaną. O wykonaniu zadania Szymon otrzymałby powiadomienie.

Jednocześnie Szymon miałbym zestawienie zadań z określeniem ich wykonania.

Spójrz na to @KatarzynaBatko .

**Comment by KatarzynaBatko** [comment]
To fajne. Rozumiem, że do widoku wewnętrznego? I że możemy to dodać już po odpaleniu? Żeby teraz nie zarzymywać/

**Comment by ad-m** [comment]
Tak, zakładam, że dodalibyśmy to w przyszłości. Elementy byłyby widoczne tylko dla członków zespołu.

**Comment by ad-m** [comment]
Pozbawione sensu. Przerost formy nad treścią. Szymon i tak nie klika zbyt wiele, więc nie przygotuje zadań.

**Comment by ad-m** [comment]
Wniosek po dotychczasowym działaniu systemu.
