### ISSUE TITLE
rejestr porad - nie uzupełnia się automatycznie pole "sprawa"

### ISSUE THREAD

**Issue by AgnieszkaZdanowicz** [watchdogpolska/poradnia#683]
Dziś usiadłyśmy do tagowania i okazało się, że przestało się automatycznie uzupełniać pole "sprawa". A że wiele spraw nazywa się tak samo, a do tego wypełnianie tego pola z listy jest mocno problematyczne, to to bardzo utrudnia naszą pracę. Mam ogromną prośbę o szybką zmianę. Mam nadzieję, że to nie trudne, bo kiedyś się wypełniało automatycznie.

![image](https://user-images.githubusercontent.com/36925935/61218976-80491080-a713-11e9-9952-c3246062bfc9.png)

**Comment by AgnieszkaZdanowicz** [comment]
Nie napisałam, że to jest widok jak się dodaje nową poradę

**Comment by ad-m** [comment]
@koszany , kiedy możesz to wykonać (wraz z testami)? Prawdopodobnie w https://github.com/watchdogpolska/poradnia/pull/663/files zostało to uszkodzone.

**Comment by AgnieszkaZdanowicz** [comment]
Przepraszam, że naciskam, ale to mocno pilna sprawa, która nam bardzo utrudnia pracę - kiedy dacie radę na to spojrzeć?

**Comment by ad-m** [comment]
Rozwiązane.
