### ISSUE TITLE
wylogowanie - Płeć

### ISSUE THREAD

**Issue by KatarzynaBatko** [watchdogpolska/poradnia#69]
Czy jesteś pewien/pewna, że chcesz się wylogować?

**Comment by KatarzynaBatko** [comment]
Wylogowałeś/-aś się.

![image](https://cloud.githubusercontent.com/assets/13284861/8637408/952cf706-2890-11e5-845c-11c90adfab49.png)

**Comment by ad-m** [comment]
Heh, to pochodzi z biblioteki, którą tylko wykorzystujemy. Przekonam autorów :-) Ewentualnie będziemy mieć własne zmiany…
