### ISSUE TITLE
prośba o zmianę formatu daty pod wiadomościami przychodzącymi i wychodzącymi

### ISSUE THREAD

**Issue by AgnieszkaZdanowicz** [watchdogpolska/poradnia#721]
W tej chwili na poradni pod wiadomościami wysyłanymi z systemu i przychodzącymi jest tak, że widać, ile czasu temu wiadomość wyszła/przyszła:

![image](https://user-images.githubusercontent.com/36925935/63577831-8d1d1780-c58f-11e9-824d-e1df8f9665fe.png)

Żeby zobaczyć dokładną datę, trzeba najechać na pole "XXX godzin temu"
Wygodniej by nam było, gdyby zamiast tego pojawiała się od razu dokładna data otrzymania/wysłania wiadomości.

**Comment by bukowa** [comment]
Jaki to model? Cieżko z kodu wyczytać, przydałyby się opisy w stylu:

````python
class Letter(AbstractRecord):
"""
Za co odpowiada ten model.
"""
    STATUS = Choices(("staff", _("Staff")), ("done", _("Done")))
    GENRE = Choices("mail", "comment")
    genre = models.CharField(choices=GENRE, default=GENRE.comment, max_length=20)
    status = StatusField(db_index=True)
    status_changed = MonitorField(monitor="status")
    accept = MonitorField(
        monitor="status", when=["done"], verbose_name=_("Accepted on")
    )

**Comment by AgnieszkaZdanowicz** [comment]
Ja nie wiem. @ad-m?

**Comment by ad-m** [comment]
To jest model ```Letter```. W tym miejscu https://github.com/watchdogpolska/poradnia/blob/master/poradnia/letters/templates/letters/_letter_list.html#L40 .

**Comment by AgnieszkaZdanowicz** [comment]
aktualne

**Comment by efefre** [comment]
Zadanie do zamknięcia. Weszło w #903.
