### ISSUE TITLE
Brak autocomplete w liście porad

### ISSUE THREAD

**Issue by rwakulszowa** [watchdogpolska/poradnia#729]
Na stronie `/porady/`, po kliknięciu w dowolny przycisk wywołujący `autocomplete` (np. radzący), nie pojawiają się sugestie, a w konsoli pojawia się błąd:
```TypeError: yl.getForwards is not a function```
poprzedzony przez
```Select2: The language file for "./i18n/pl" could not be automatically loaded. A fallback will be used instead.``` przy ładowaniu strony.

Mowa o lokalnie postawionym serwerze, gałąź master.

**Comment by ad-m** [comment]
Prawdopodobnie problem z django-autocomplete-light. Wykorzystasz lokalnie zbudowaną wersje front-endu, czy tą z repozytorium?

**Comment by rwakulszowa** [comment]
Hm, w zasadzie nie wiem. Domyślam się, że tę z repozytorium, bo nie wywołuję żadnych dodatkowych komend do budowania frontu (tylko `docker-compose build` i `docker-compose up`).

**Comment by ad-m** [comment]
W takim wypadku wykorzystujesz gulpa ( https://github.com/watchdogpolska/poradnia/blob/master/docker-compose.yml#L20 ) i masz przebudowane pliki statyczne.

**Comment by rwakulszowa** [comment]
Rzeczywiście, problem pojawia się przy lokalnym budowaniu js.
Spróbuję się temu przyjrzeć.

**Comment by AgnieszkaZdanowicz** [comment]
Tu moim zdaniem już wszystko działa, więc zamykam
