### ISSUE TITLE
sprawy zamknięte nie otwierają się przy pisaniu nowej wiadomości przez klientów

### ISSUE THREAD

**Issue by AgnieszkaZdanowicz** [watchdogpolska/poradnia#749]
Jak zamykamy sprawę, a klient/ka potem coś pisze, to sprawa się powinna otwierać. Ale teraz się nie otwierają. Te, które wyłapałam:

https://porady.siecobywatelska.pl/sprawy/sprawa-9339/
https://porady.siecobywatelska.pl/sprawy/sprawa-8389/
https://porady.siecobywatelska.pl/sprawy/sprawa-8569/

Paula mówi, że u niej było 6 takich spraw.

Proszę o pomoc, dzięki!

**Comment by ad-m** [comment]
Wynika z #576, które jest spowodowane #740 . Optymalne rozwiązanie to zamknięcie #479 . Połowiczne rozwiązanie to korekta #576 , aby otwierało sprawy jak dawniej.

**Comment by ad-m** [comment]
Mam poprawkę. Wraz z najbliższą aktualizacją wdroże, gdyż przyszykowałem więcej zmian.

**Comment by ad-m** [comment]
Naprawione.

**Comment by AgnieszkaZdanowicz** [comment]
Dzięki, będziemy obserwować i jak potwierdzę, to zamknę

**Comment by AgnieszkaZdanowicz** [comment]
wygląda, że już się otwierają sprawy, ale Paula zwróciła uwagę, że nie dostaje wiadomości z poradni, jak klient coś odpisze. Ja teraz sprawdziłam, że dostaję powiadomienie, jak w wolnej sprawie napisze coś prawnik, ale już jak klient coś napisze, to nie dostaje maila. Piszę w tym wątku, bo jakoś mi się to wydaje powiązane, że jak tamto naprawiłeś, to tutaj coś się zwaliło, ale mogę założyć nowy wątek, jak wolisz.

**Comment by AgnieszkaZdanowicz** [comment]
Teraz jeszcze sprawdziłam, że problem z nieotwierającymi się sprawami naprawiłeś 15 dni temu, a ten problem nie trwa aż tyle - wydaje mi się, że jeszcze przed weekendem dostawałam powiadomienia. I widzimy też, że wiadomości na poradni od klientów z dziś są wszystkie z 5:28 - był zablokowany serwer?

**Comment by ad-m** [comment]
@AgnieszkaZdanowicz , przyjrzę się temu dlaczego powiadomienie e-mailowe nie jest wysyłane, gdy klient napisze e-mail i dodam stosowne testy. To wydaje się związane z zmianami przy importowani e-maili. Przypuszczam, że powiadomień brakuje tylko, gdy klient pisze przez e-mail, więc niektóre powiadomienia (te ze strony) masz.

**Comment by AgnieszkaZdanowicz** [comment]
@ad-m Paula mi zgłosiła w zeszłym tygodniu, że nadal nie dostaje większości maili z poradni, gdy klient coś pisze

**Comment by ad-m** [comment]
A mogę prosić o wskazanie konkretnego przypadku, gdy się to dzieje? Wówczas dodam test, a potem naprawię poradnię szybko.

Potrzebuje wskazania na moment wysłania wiadomości:
- Kto jest przypisany do sprawy i jakie ma uprawnienia, gdy nadchodzi e-mail?
- Kto pisze wiadomość w sprawie i jako jaki użytkownik ta wiadomość została zarejestrowana?

**Comment by AgnieszkaZdanowicz** [comment]
Jasne, poprosiłam Paulę o wyłapanie kolejnego przypadku. Tylko nie do końca rozumiem te punkty:

- _Kto pisze wiadomość w sprawie i jako jaki użytkownik ta wiadomość została zarejestrowana?_ - tu chodzi, o to, który klient napisał?

- _W jakiej postaci wiadomość jest rejestrowana w systemie?_ - chodzi o to, czy to jest treść wiadomości czy załącznik?

**Comment by ad-m** [comment]
> tu chodzi, o to, który klient napisał?
Jakiego klienta system wykrył. Jeżeli nie wykryjemy nadawcę to domyślnie zakładamy nowe konto użytkownika, a takie konto nie musi mieć uprawnień w sprawie. 
> W jakiej postaci wiadomość jest rejestrowana w systemie? - chodzi o to, czy to jest treść wiadomości czy załącznik?
Czy wiadomość dla zespołu, czy także dla klienta. Jeżeli wolontariusz pisze odpisuje, a nie ma prawa do pisania do klienta to wówczas sprawa jest dostępna tylko dla zespołu.

**Comment by ad-m** [comment]
Dziękuje. To wszystko. Teraz powinienem być w stanie to odtworzyć, a następnie dodać test, aby takie sytuacje nie były pomijane w przyszłości.

**Comment by ad-m** [comment]
Rozumiem skąd nieporozumienie. W https://github.com/watchdogpolska/poradnia/commit/9e396ad611a0167995df4446e76f9b51cc5bd390 zmiana została przygotowana, ale nie została wprowadzona na serwer.

**Comment by AgnieszkaZdanowicz** [comment]
To uff, że udało się wyjaśnić, bo Alina też narzekała, że nie dostała powiadomienia w sprawie, do której ją ostatnio przypisałam. Teraz już powinno być ok? Wydaje mi się, że widzę na poradni, że czeka jakaś poprawka do wgrania - zgadza się?

**Comment by ad-m** [comment]
Powinno być rozwiązane i nic nie oczekiwało.

pon., 3 lut 2020 o 14:47 AgnieszkaZdanowicz <notifications@github.com>
napisał(a):

**Comment by ad-m** [comment]
Mogę prosić o potwierdzenie?

**Comment by AgnieszkaZdanowicz** [comment]
dopiero napisałam wczoraj do dziewczyn, żeby mi potwierdziły. Daję im czas do jutra ;)

**Comment by AgnieszkaZdanowicz** [comment]
Paula dostała powiadomienie o wiadomości z poradni, ale tutaj klient zgłasza problem z tym temacie: https://porady.siecobywatelska.pl/sprawy/sprawa-3671/

**Comment by ad-m** [comment]
@AgnieszkaZdanowicz , jak zwykle problem nie leży po naszej stronie, a po stronie serwera pocztowego odbiorcy:

![image](https://user-images.githubusercontent.com/3618479/73802577-614cc180-47be-11ea-8292-3dab4b3e801e.png)

**Comment by AgnieszkaZdanowicz** [comment]
@ad-m dzięki, to zamykam wątek

**Comment by AgnieszkaZdanowicz** [comment]
@ad-m  Paula zgłosiła, że nie dostała znowu powiadomień:

Ostatnie są z 6.02 (na tym etapie docierały prawidłowo), ale 9.02 powinnam dostać wiadomości w tych sprawach: https://porady.siecobywatelska.pl/sprawy/sprawa-9527/, https://porady.siecobywatelska.pl/sprawy/sprawa-9449/. Jak na razie nie dostałam.

**Comment by ad-m** [comment]
W świetle problemu ujawnionego w https://github.com/watchdogpolska/feder/issues/694 spowodowanego zmianą wskazaną w https://github.com/watchdogpolska/infra/issues/358 (wprowadzoną 9 lutego) uprzejmie proszę czy wiadomości jednak dotarły.

**Comment by AgnieszkaZdanowicz** [comment]
Dotarły o 15:26

**Comment by AgnieszkaZdanowicz** [comment]
ostatnio nie zauważyliśmy problemów w tym zakresie, więc zamykam
