### ISSUE TITLE
prośba o dodanie możliwości formatowania tekstu wysyłanego do klientów

### ISSUE THREAD

**Issue by AgnieszkaZdanowicz** [watchdogpolska/poradnia#768]
Rozmawialiśmy dziś w biurze, że istnieje możliwość, żeby wprowadzić do poradni edytowanie treści wiadomości wysyłanych do klientów, znaczy o tu:

![image](https://user-images.githubusercontent.com/36925935/67573454-aa5d9600-f738-11e9-9c30-9dc2029c2f48.png)

To jeśli to jest prosta zmiana, to mamy prośbę o jej wprowadzenie.

**Comment by ad-m** [comment]
Edytowania znaczy się formatowania?

**Comment by AgnieszkaZdanowicz** [comment]
Tak, chodziło mi o formatowanie

**Comment by AgnieszkaZdanowicz** [comment]
aktualne

**Comment by marcin-wicha** [comment]
Chciałbym się tym zająć. Czy checie możliwość formatowania wprowadzić do wszystkich większych pól tekstowych czy tylko w przypadku Listów?

**Comment by ad-m** [comment]
Pole listów ma specyficzną logikę aktualnie. Wystarczające jest jeżeli będzie to ograniczone do pól tekstowych dotyczących listów.

**Comment by ad-m** [comment]
W jaki sposób chcesz do tego podejść? Bogaty edytor Markdown czy o czymś innym myślisz?

**Comment by marcin-wicha** [comment]
Myślałem o edytorze markdown. Dopiero co odpaliłem projekt na dockerze i się zapoznaję ze strukturą. Dotychczas działałem głównie z Reactem, więc pewnie trochę mi zejdzie na zorientowanie się w Django.

**Comment by ad-m** [comment]
Najważniejsza różnica jest taka, że tu wszystko server-side-rendered. Pierw musisz rozsądnie zbudować przepływ dla surowego pola tekstowego z Markdown, a na samym końcu dodać bogaty edytor. Podejście z Markdown mi się podoba, bo niskie ryzyko w zakresie bezpieczeństwa. Budowanie front-endu (Gulp) dawno nie było wykonywane i boje się w jakiej jest kondycji.

Kroki:
- składowanie danych w Markdown
- wyświetlanie treści w Markdown
- przesyłanie treści w Markdown (wysyłamy kopie wiadomości w e-mailu)
- bogaty edytor

**Comment by marcin-wicha** [comment]
@ad-m 
Mam pytanie - w jaki sposób mógłbym przetestować mejle? Widzę, że w konfiguracji deweloperskiej po prostu jest print do consoli.

Na forku poniżej mam już parsowanie MD w listach. Wyjście sanityzuję poprzez whitelistę dozwolonych tagów i ich atrybutów.
[Link do brancha](https://github.com/marcin-wicha/poradnia/tree/768-ADD-RICH-TEXT-EDITOR)

**Comment by ad-m** [comment]
@marcin-wicha , w zakresie e-maili wykorzystujemy standardowe mechanizmy e-maili, gdzie domyślnie piszemy do konsoli, ale możeszs ustawić SMTP i wysyłać je w świat. 
Zobacz na https://github.com/watchdogpolska/poradnia/blob/master/config/settings/common.py#L112-L118 i https://docs.djangoproject.com/en/3.1/ref/settings/#std:setting-EMAIL_BACKEND .

**Comment by AgnieszkaZdanowicz** [comment]
To ja tylko napiszę, że jakby udało się wprowadzić te zmianę, to cały zespół poradni byłby super szczęśliwy :)

**Comment by ad-m** [comment]
W #927 zmiana weszła w zakresie:

* składowanie danych w Markdown
* wyświetlanie treści w Markdown
* przesyłanie treści w Markdown (wysyłamy kopie wiadomości w e-mailu)

Ewentualnie pozostało:

* bogaty edytor

**Comment by AgnieszkaZdanowicz** [comment]
Czy to działa tak, że musimy się nauczyć znaków z markdown (to znaczy, że nie ma edytora powyżej pola do wpisywania tekstów, tak jak np. w github) i czy sposób wyedytowania tekstów widać dopiero po wysłaniu wiadomości?

**Comment by ad-m** [comment]
Obecnie tak, ale jak wprowadzimy bogaty edytor (kolejne kroki) to zniknie
konieczność znajomości znaczników. Staramy się iść małymi kroczkami, aby
zbierać doświadczenie.

pon., 26.10.2020, 09:49 użytkownik AgnieszkaZdanowicz <
notifications@github.com> napisał:

**Comment by AgnieszkaZdanowicz** [comment]
Jasne, dzięki! To ogromna zmiana i bardzo się z niej cieszymy - nauczymy się po prosty tych znaczników markdown.
Przepraszam, dopiero teraz przeczytałam maila od Ciebie w tej sprawie i już wszystko jest dla mnie jasne.

**Comment by AgnieszkaZdanowicz** [comment]
Wpisałam normalnie treść, a pokazuje się tak:

![image](https://user-images.githubusercontent.com/36925935/97167212-b4203c00-1786-11eb-8c26-4b29f32552e6.png)

@ad-m napisał: Wygląda na to, że obecna składnia Markdown nie jest kompatybilna z naszym separatorem sygnaturek i trzy minusy oddzielające treść od stopki są traktowane jako nagłówek. 

Adamie, przepraszam, ale nie rozumiem, co mam zrobić jeszcze - napisałeś: "zamieść tam kopie treści wiadomości z edycji (bez formatowania)."

**Comment by ad-m** [comment]
Mam na myśli zawartość pola poniżej:

![image](https://user-images.githubusercontent.com/3618479/97167561-50e2d980-1787-11eb-884e-ccc6413333e7.png)

Wówczas można przeanalizować dlaczego coś się wyświetla w sposób w jaki się wyświetla.

Oryginał wiadomości:

```
A  w którym miejscu zmieniam? Bo ja tylko wybieram Cię z listy

---
Agnieszka Zdanowicz

Dyrektorka Zarządzająca Sieci Obywatelskiej Watchdog Polska
```

**Comment by ad-m** [comment]
Agnieszka zaczyna się tłumaczyć klientom np. w sprawie https://porady.siecobywatelska.pl/sprawy/sprawa-10787/ z formatowania, gdy ona wykorzystuje stopkę. Myślę, ze wystarczy skasować `---`, chyba że jest propozycja innego seperatora.

**Comment by AgnieszkaZdanowicz** [comment]
Byłoby super - może być bez separatora. Bo większość moich wiadomości jest pisana wielką czcionką i to trochę niepoważnie wygląda.

**Comment by AgnieszkaZdanowicz** [comment]
zaplanowane do wprowadzenia rozwiązania zaproponowanego przez @PiotrIw - Piotrze, czy w związku z tym, że wdrażasz to po swojemu, ten issue możemy zamknąć czy dopiero po wdrożeniu jednak?

**Comment by PiotrIw** [comment]
rozwiązne (edytor WYSIWYG HTML) w wersji 1.1.5
