### ISSUE TITLE
Avatar na profilu użytkownika

### ISSUE THREAD

**Issue by ad-m** [watchdogpolska/poradnia#79]

**Comment by ad-m** [comment]
Należy użyć
```
{% load avatar_tags %}
<img src="{% avatar_url object.created_by %}" class="timeline-avatar">
```
Ewentualnie spójrz do dokumentacji http://django-avatar.readthedocs.org/en/latest/#template-tags-and-filter .

**Comment by mik-laj** [comment]
https://github.com/watchdogpolska/poradnia/commit/f0f1b948d709d3f764f5eb3ae33973edb96e5fb5
