### ISSUE TITLE
Tłumaczenie avatarów

### ISSUE THREAD

**Issue by KatarzynaBatko** [watchdogpolska/poradnia#81]
![image](https://cloud.githubusercontent.com/assets/13284861/8670618/cc077050-2a1e-11e5-987e-7908fa90d84e.png)

**Comment by ad-m** [comment]
"Choices"

**Comment by ad-m** [comment]
"Successfully updated your avatar."

**Comment by ad-m** [comment]
"Dostępne avatary"

**Comment by ad-m** [comment]
Należy sprawdzić czy nie dotyka to tylko produkcji, zatem zachowuje.

![poradnia_-_2015-07-19_14 30 59](https://cloud.githubusercontent.com/assets/3618479/8765875/e3bcd2c8-2e22-11e5-8506-3f18dd3b1d19.png)

**Comment by ad-m** [comment]
![poradnia_-_2015-07-19_15 16 06](https://cloud.githubusercontent.com/assets/3618479/8766028/2732d9b6-2e29-11e5-9506-b189826a847d.png)

**Comment by ad-m** [comment]
Zdecydowałem się zmodyfikować zewnętrzną bibliotekę. Dodatkowo zaczęła ona uwzględniać gender poprawki. See jezdez/django-avatar#108 . Do tego czasu powinniśmy się przełączyć na forka.

**Comment by ad-m** [comment]
![poradnia_-_2015-07-19_15 49 34](https://cloud.githubusercontent.com/assets/3618479/8766177/c8770cbc-2e2d-11e5-81ef-a6aad1c51870.png)

Zachowuje, aby przypilnować pull requests.

**Comment by ad-m** [comment]
Kod wcielono. Gender się roznosi. Należy poczekać na nowe wydanie i będize można zmienić requirements.txt. Do tego czasu zostaje jak jest.
