### ISSUE TITLE
od użytkowniczki na temat formularza do zgłaszania spraw

### ISSUE THREAD

**Issue by KatarzynaBatko** [watchdogpolska/poradnia#83]
- zamiast "zapisz zmiany" powinien byc przycisk "zglos sprawe", a najlepiej dwa: "zapisz zmiany" i "zglos sprawe"

**Comment by ad-m** [comment]
Powiązane z #85 .

**Comment by ad-m** [comment]
Załatwione na gałęzi ```refactor_form_letter```.
