### ISSUE TITLE
internal server error przy nadawaniu uprawnień i wpisywaniu terminów

### ISSUE THREAD

**Issue by AgnieszkaZdanowicz** [watchdogpolska/poradnia#834]
@ad-m dziś już 3 razy wyskoczył mi błąd:

![image](https://user-images.githubusercontent.com/36925935/74914931-9adb1a80-53c3-11ea-946b-b7a45ff7ee8f.png)

Przy nadawaniu dostępu do 2 spraw i raz przy dodawaniu terminu do sprawy. Jak odświeżę stronę, to akcja się wykonuje mimo komunikatu o błędzie

**Comment by ad-m** [comment]
Wyczerpanie miejsca na rootfs na serwerze app-prod.watchdog.internal z powodu nadmiaru logów z powodu ich stałego buforowania z powodu nie pełnego wyłączenia centralnego logowania. Wprowadzono ponownie serwer centralnego logowania, aby dane mogły spłynąć.

W każdym razie – problem naprawiony.
