### ISSUE TITLE
Errory

### ISSUE THREAD

**Issue by KatarzynaBatko** [watchdogpolska/poradnia#84]
![image](https://cloud.githubusercontent.com/assets/13284861/8692222/95789998-2acc-11e5-86cd-8cd9c685c69a.png)dy 

przy okazji: jak na portalu klikam na "wykaz spraw" to przy przekierowaniu wyskakuje ten sam blad

**Comment by ad-m** [comment]
Pani się "niepoprawnie" nazywała. Naprawione. :+1:

**Comment by ad-m** [comment]
PS. Wszystkie zgłoszenia są ogólnodostępne. Dopiero przekonuje GitHub do stworzenia przestrzeni dla intymnych zgłoszeń.
