### ISSUE TITLE
Zabezpieczenie "Zgłoś uwagę" przed spamem

### ISSUE THREAD

**Issue by ad-m** [watchdogpolska/poradnia#845]
Mamy formularz "Zgłoś uwagę" w Poradni. Umożliwia on elastyczne zgłaszanie problemów. Niestety, boty nauczyły się formularza i średnio dwa razy w tygodniu mamy jakiś spam przez ten formularz, co rozprasza i wprowadza niepotrzebny chaos.

Potrzebujemy jakiegoś prostego rozwiązania, które pozwoli zbudowa

Odpowiednie elementny aplikacji to:
- routing do widoku przetworzenia formularza: https://github.com/watchdogpolska/poradnia/blob/master/poradnia/tasty_feedback/urls.py#L7
- widok przetworzenia formularza: https://github.com/watchdogpolska/poradnia/blob/master/poradnia/tasty_feedback/views.py#L30-L36
- formularz: https://github.com/watchdogpolska/poradnia/blob/master/poradnia/tasty_feedback/forms.py#L12
- widget formularza: https://github.com/watchdogpolska/poradnia/blob/master/poradnia/tasty_feedback/templates/tasty_feedback/widget.html
- znacznik do wczytania widgetu formularza: https://github.com/watchdogpolska/poradnia/blob/master/poradnia/tasty_feedback/templatetags/tasty_feedback_tags.py
- użycie znaczników formularza: https://github.com/watchdogpolska/poradnia/blob/513616caef0f2efef90b2d4c1bd89ceb4a5f6fee/poradnia/templates/base.html#L113-L114

**Comment by ad-m** [comment]
Liczyłem poprzez https://github.com/watchdogpolska/poradnia/pull/856 że dodanie nowego pola wyeliminuje spam. Jednak pole jest zbyt głupie i boty wypełniają. Dzień po wdrożeniu już wypełniały poprawnie. Potrzebujemy czegoś sprytniejszego użyć.

**Comment by AgnieszkaZdanowicz** [comment]
@ad-m nie wiem, czy to aktualne?

**Comment by ad-m** [comment]
Tak, aktualne. Możesz zobaczyc na https://porady.siecobywatelska.pl/uwagi/ jakie uwagi dominują.

**Comment by AgnieszkaZdanowicz** [comment]
Wow, nigdy tego nie widziałam! Rzeczywiście dużo spamu

**Comment by AgnieszkaZdanowicz** [comment]
a jednak kiedyś Adam mi zwracał uwagę na zakładkę "uwagi"! o tym rozmawialiśmy, żeby jednak uwagi można było zgłosić dopiero po zalogowaniu. Jeśli ktoś chciałby zgłosić uwagę, bo ma problem z zalogowaniem, to będzie musiał najwyżej napisać na biuro@

**Comment by PiotrIw** [comment]
v1.1.3 - "Zgłoś uwagę" dostępne tylko dla zalogowanych więc boty nie będą wrzucać spamu
@AgnieszkaZdanowicz  problemy z logowaniem można zaadresować stosownym komunikatem na stronie logowania lub na https://porady.siecobywatelska.pl/konta/password/reset/
