### ISSUE TITLE
DatePicker odfruwa

### ISSUE THREAD

**Issue by ad-m** [watchdogpolska/poradnia#87]
Nie wiem z jakiego powodu, ale czasem odfruwa. Nie musimy używać tego. Potrzebujemy działającego.
![zaznaczenie_353](https://cloud.githubusercontent.com/assets/3618479/8766252/66bbe33c-2e30-11e5-9056-f2b64ce17e1f.png)

**Comment by mik-laj** [comment]
https://github.com/watchdogpolska/poradnia/commit/8035e7e2f20ac42e11fa4aeb618cd3d32619af07

**Comment by mik-laj** [comment]
https://github.com/watchdogpolska/poradnia/commit/8035e7e2f20ac42e11fa4aeb618cd3d32619af07
