### ISSUE TITLE
wyszukiwanie w rejestrze porad po gminach - czy może być opcja zaznaczenia kilku gmin na raz?

### ISSUE THREAD

**Issue by AgnieszkaZdanowicz** [watchdogpolska/poradnia#889]
Mamy "rejestr porad"na poradni:

![image](https://user-images.githubusercontent.com/36925935/87446253-57df4500-c5f9-11ea-8ae7-ee5f267e8f3d.png)

A w nim wyszukiwanie po gminie:

![image](https://user-images.githubusercontent.com/36925935/87446289-67f72480-c5f9-11ea-8a02-7c18d27ec4b9.png)

Ale teraz można wybrać tylko jedną gminę na raz. Czy byłaby opcja, żeby można było wybrać kilka gmin na raz i ich wszystkich dotyczył wynik wyszukiwania?

**Comment by rwakulszowa** [comment]
Myślę, że powinno się dać. Jest szansa, że będzie to wymagało trochę większych zmian w kodzie, ale postaram się tym zająć.

Rozumiem, że chcemy zachować obecną funkcjonalność umożliwiającą wyszukiwanie gmin po nazwie (tj., o ile się nie mylę, w tym momencie pole Gmina działa o tyle inaczej niż pole Radzący, że zawiera pole tekstowe do filtrowania opcji), a dodać tylko możliwość dodawania i usuwania wielu opcji.

Innymi słowy, po wyborze gminy Brzesko, gdzieś będziemy musieli dodać ikonkę z napisem "Brzesko", która da możliwość cofnięcia wyboru, jednocześnie nadal wyświetlając pole wyboru Gmina, umożliwiające dodawanie kolejnych gmin.

Swoją drogą - czy są jeszcze jakieś inne sugestieodnośnie tego folmularza? Zakładam, że istnieje od dość dawna i pewnie wiele razy ewoluował przez lata, ale skoro się za niego biorę, to pewnie mogę przy okazji wprowadzić więcej zmian.

**Comment by ad-m** [comment]
Django-autocomplete-light wspiera multichoice widget: https://django-autocomplete-light.readthedocs.io/en/master/

**Comment by AgnieszkaZdanowicz** [comment]
@rwakulszowa dzięki! pomyślimy w zespole, czy coś jeszcze chcielibyśmy zmienić.

A co do tego pomysłu z wyszukiwaniem kilku gmin na raz, to czy takie rozwiązanie, które zaproponowałeś, dałoby się wprowadzić dla innych pól wyszukiwania? Bo np. w polu "zakresy tematyczne..." możemy wyszukiwać po kilku polach i zaznaczamy je poprzez trzymanie ctrl, ale to nie jest super wygodne. Pomyślałam, że może sposób, który Ty zaproponowałeś, będzie wygodniejszy.

**Comment by ad-m** [comment]
Oczekiwanie Agnieszki prawdopodobnie da się zaspokoić z użyciem django-autocomplete-light. BTW. Integracje django-autocomplete-light wartoby testować w minimalnym zakresie, bo jakoś nie czuje się komfortowo podczas aktualizacji tej biblioteki.

**Comment by rwakulszowa** [comment]
### Drobna aktualizacja
Wszystko wskazuje na to, że problem powinien być w miarę łatwy do rozwiązania. Przepraszam, że dość długo to schodzi, ale wcześniej chcę zamknąć #741 żeby zminimalizować szansę, że przez przypadek coś przestanie działać. W każdym razie - rozwiązanie jest w drodze.

**Comment by AgnieszkaZdanowicz** [comment]
Dzięki, czekam spokojnie :)
