### ISSUE TITLE
Sortowanie wykazu użytkowników

### ISSUE THREAD

**Issue by ad-m** [watchdogpolska/poradnia#909]
Na https://porady.siecobywatelska.pl/uzytkownik/?is_staff=1&page= mamy wykaz użytkowników.

@AgnieszkaZdanowicz , czy potrzebujesz sortowania go po kolumnach tj. wolne, aktywne, zamknietę? Mam poczucie, że by to ułatwiło.

**Comment by AgnieszkaZdanowicz** [comment]
@ad-m dobry pomysł!

**Comment by ad-m** [comment]
Kod widoku na https://github.com/watchdogpolska/poradnia/blob/master/poradnia/users/views.py#L65
Na https://github.com/watchdogpolska/poradnia/blob/master/poradnia/cases/views/cases.py#L108 już mamy sortowanie.
 
@efefre , masz ochotę na to zagadnienie?

**Comment by efefre** [comment]
Ok. Mogę spróbować :) A jest też jakaś wersja demo tej aplikacji, żebym mogła zobaczyć o jaki widok chodzi (wykaz użytkowników)? Czy mam poszukać tego widoku lokalnie?

**Comment by efefre** [comment]
@ad-m  to do zamknięcia. Zrobione w #910

**Comment by ad-m** [comment]
Umknęło mi pytanie. Aplikacja nie ma środowiska testowego, ale widzę, że odnalazłaś widok (w menu bocznym "Wykaz użytkowników" w przypadku użycia odpowiednio uprzywilejowanego konta).

@mrbojko , uprzejmie proszę o wdrożenie na produkcje, a następnie zadbanie o informacje zwrotną od @AgnieszkaZdanowicz .
