### ISSUE TITLE
nie dochodzą maile na poradnię

### ISSUE THREAD

**Issue by AgnieszkaZdanowicz** [watchdogpolska/poradnia#917]
Wiem, że Paula zgłaszała poszczególne sprawy przez uwagi na poradni, ale problem się wydaje jednak szerszy. Bo teraz namierzyłam kolejną wiadomość, która nie dotarła - wysłana 5 paź 2020, 16:34. Pan napisał do mnie maila i jednocześnie na poradnię i nie mogę tej sprawy namierzyć na poradni. W ogóle podejrzanie mało nowych spraw spłynęło przez weekend (chociaż pojedyncze owszem)

@ad-m czy możesz dodać do tego repozytorium Marcina Bójko?

**Comment by ad-m** [comment]
@mrbojko , z jakiegoś powodu połączenie do serwera IMAP zawisło. Widać to było po wykonaniu:

```
docker logs --tail 1000 -t imap-to-webhook-porady
```
na helper. Od `2020-09-29T15:50:55.448510358Z` zawisło 57 wiadomości. Zrestartowałem, a na przyszłość w github.com/watchdogpolska/imap-to-webhook można wprowadzić jakiś timeout.

**Comment by ad-m** [comment]
Identyczna sytuacja na Fedrowaniu. Tam `1149` wiadomości.

**Comment by ad-m** [comment]
Czy można tam zamknąć?
