### ISSUE TITLE
Błąd przy budowaniu kontenera web - django-flatpages-tinymce

### ISSUE THREAD

**Issue by rwakulszowa** [watchdogpolska/poradnia#925]
https://github.com/watchdogpolska/poradnia/blob/45d9c2d647a901f139c3b20d196c7c387be26dc3/requirements/base.txt#L38

> Not found

Czy biblioteka jest do czegoś używana? Oryginalne repozytorium zdaje się być opuszczone. Czy możemy po prostu pozbyć się zależności (jeśli nie jest w praktyce używana) / zastąpić alternatywą?

**Comment by ad-m** [comment]
Ja usunąłęm wszystkie forki z swojego konta, bo miałem ponad 200. Użyłem jako zależności mojego repozytorium, bo mój PR z niezbędnymi poprawkami nie chciał wejść ( https://github.com/mjr27/django-flatpages-tinymce/pull/19/files ). 

Biblioteka jest używana do zapewnienia edycji stron statycznych, takich jak https://porady.siecobywatelska.pl/strony/regulamin-poradnictwa/ bez udziału osoby technicznej.

**Comment by rwakulszowa** [comment]
Zdaje się, że naprawione w #926 
Potwierdzam, że udało mi się zbudować poradnię z mastera.
