### ISSUE TITLE
Brak tematu w powiadomieniach

### ISSUE THREAD

**Issue by ad-m** [watchdogpolska/poradnia#930]
W przypadku odpowiedzi ze strony w sprawie brak jest tematu:

![image](https://user-images.githubusercontent.com/3618479/97129136-697ad180-173e-11eb-907d-748092dfda21.png)

W nagłówkach:
```
Subject: 
```
Innymi słowy pusta wartość tekstowa.

@AgnieszkaZdanowicz , możesz sprawnie wychwycić w jakim rodzaju powiadomień ten problem występuje?

**Comment by AgnieszkaZdanowicz** [comment]
Nie wiem, jak to zrobić sprawnie :( mogę Ci po prostu wypisać, które wiadomości dostałam bez tematu (a to jest jakaś nowość, prawda? Bo wcześniej tego nie zauważyłam)

Teraz dostałam maila ws. https://porady.siecobywatelska.pl/sprawy/sprawa-10861/ - pisany przez członka zespołu z rolą "obserwator?

**Comment by AgnieszkaZdanowicz** [comment]
A tutaj w wiadomości od "klienta/spamera": https://porady.siecobywatelska.pl/sprawy/sprawa-10946/#letter-47653 Pierwsza wiadomość w wątku.

**Comment by ad-m** [comment]
Potrzebowałem przykładów wiadomości, aby wiedzieć gdzie szukać. Źródło namierzone.

**Comment by AgnieszkaZdanowicz** [comment]
ok! :)

**Comment by AgnieszkaZdanowicz** [comment]
Donoszę, że już żadne powiadomienia z poradni nie mają tematu

![image](https://user-images.githubusercontent.com/36925935/97544376-cb9b3700-19c9-11eb-9a0b-cbb393eeaa51.png)

**Comment by AgnieszkaZdanowicz** [comment]
Znaczy żadne poza powiadomieniami o nowej sprawie

**Comment by ad-m** [comment]
W #931 jest przygotowana poprawka. Oczekuje na recenzje.

**Comment by ad-m** [comment]
@AgnieszkaZdanowicz , uprzejmie proszę o weryfikacje.

**Comment by AgnieszkaZdanowicz** [comment]
@ad-m wygląda, że wszystko już jest ok. dzięki!
