### ISSUE TITLE
sprawa otworzyła się sama z siebie

### ISSUE THREAD

**Issue by AgnieszkaZdanowicz** [watchdogpolska/poradnia#935]
Paula zgłasza, że ta sprawa sama zmieniła sobie status z "zamknięta" na "przypisana", chociaż nic nowego się w niej nie wydarzyło: https://porady.siecobywatelska.pl/sprawy/sprawa-10782/

**Comment by ad-m** [comment]
@mrbojko , jesteś w stanie przejrzeć login nginx / haproxy, aby to potwierdzić? Brzmi to bardzo dziwnie, ale Paula zamkneła już sprawę nadpisując informację z pola "ostatnia aktualizacja".

@AgnieszkaZdanowicz , jesteś w stanie zaokreślić okres czasowy za który należy przejrzeć dzienniki?

**Comment by AgnieszkaZdanowicz** [comment]
@ad-m Paula mi o tym napisała o 12:55 3.11.2020 r. Więc pewnie wtedy się to wydarzyło i to jest jedyna sprawa, którą nakryłyśmy na takim zachowaniu

**Comment by ad-m** [comment]
@AgnieszkaZdanowicz czy jesteś w stanie dostarczyć mi dodatkowe informacje, czy można zamknąć to zgłoszenie po dwóch latach?

**Comment by AgnieszkaZdanowicz** [comment]
nic podobnego się potem nie wydarzyło, więc zamykam
