### ISSUE TITLE
Literówka w tłumaczeniu ("zarejest(R)uj")

### ISSUE THREAD

**Issue by rwakulszowa** [watchdogpolska/poradnia#937]
![image](https://user-images.githubusercontent.com/10756296/98438743-8de68e80-20ec-11eb-998f-7c9d3b88b1e4.png)

Pisząc podstawowy test integracyjny dla #889 zauważyłem, że w słowie "Zarejestruj" brakuje litery "R". 

Wygląda na to, że problem jest w zależności [django-allauth](https://github.com/pennersr/django-allauth/blob/master/allauth/locale/pl/LC_MESSAGES/django.po#L639).

Postaram się poprawić u źródła.

**Comment by rwakulszowa** [comment]
pennersr/django-allauth#2708

**Comment by ad-m** [comment]
Dziękuje za zgłoszenie błędu. Błąd w pierwotnej bibliotece znajduje się od 7 lat i nikt nie zgłosił go dotąd. Jak wcielą zmianę i wydadzą nowe wydanie to przyjdzie do nas bot z PR-em.

**Comment by ad-m** [comment]
Bot w #1024 .

**Comment by AgnieszkaZdanowicz** [comment]
aktualne

**Comment by PiotrIw** [comment]
poprawione w v1.1.3
