### ISSUE TITLE
Kalendarz wydarzeń jest ograniczony do 2020 roku

### ISSUE THREAD

**Issue by rwakulszowa** [watchdogpolska/poradnia#942]
W ramach pracy nad #913 zauważyłem drobny problem z kalendarzem.

Formularz wyboru daty, używany m.in. przy tworzeniu wydarzeń, jest tworzony [w tym miejscu](https://github.com/watchdogpolska/poradnia/blob/master/poradnia/assets/js/project.js#L10). Maksymalna data jaką można w tym momencie określić to 31.12.2020.

Tak się pechowo składa, że poprawka wymaga aktualizacji frontendu, co do tej pory było dosć problematyczne. Co więcej, plik project.js nie jest obecnie kompatybilny z innymi zmianami we frontendzie: zmienił się sposób definiowania jQuery, przez co zmienna `$` nie jest zdefiniowana*. Najprawdopniej wystarczy owinąć moduł w anonimową funkcję przyjmującą `$` jako argument, analogicznie do pliku [formset](https://github.com/watchdogpolska/poradnia/blob/master/poradnia/assets/js/jquery.formset.js#L12).

W każdym razie, ze względu na problem z kalendarzem, prawdopodobnie będziemy chcieli zaktualizować frontend w najbliższych tygodniach.

*wykrywają to obecne testy e2e, choć w odrobinę zawoalowany sposób; postaram się rozszerzyć testy o użycie formularza wydarzeń

**Comment by ad-m** [comment]
Cudownie, że wyłapujesz błędy nim dotkną one ludzi.
