### ISSUE TITLE
Niewidoczna różnica między wierszami w kalendarzu 

### ISSUE THREAD

**Issue by ad-m** [watchdogpolska/poradnia#96]
Proponuje kolor ```#DDDDDD```.

Przed: ![zaznaczenie_354](https://cloud.githubusercontent.com/assets/3618479/8774207/f4efe652-2edb-11e5-97ef-307aac400e89.png)
Po: ![zaznaczenie_355](https://cloud.githubusercontent.com/assets/3618479/8774209/f8a29f92-2edb-11e5-9054-b75497e41047.png)

**Comment by mik-laj** [comment]
https://github.com/watchdogpolska/poradnia/commit/7e8f410ed170e00ab7dc7d486613bf245a9b5e40
