### ISSUE TITLE
sprawa rejestrowana z adresu poradni?

### ISSUE THREAD

**Issue by AgnieszkaZdanowicz** [watchdogpolska/poradnia#967]
Na poradnię spłynęły 22 maile, z których wynika, że ktoś zakładał sprawy z adresów z poradni tj. (na screenie 19 spraw z 22):

![image](https://user-images.githubusercontent.com/36925935/103520941-45431b80-4e78-11eb-8257-5e82307da4a8.png)

Spojrzałam, z jakich adresów z poradni mamy "klientów":

![image](https://user-images.githubusercontent.com/36925935/103521035-6572da80-4e78-11eb-9539-0998301c029d.png)

Nie wiem, jak to możliwe, że sprawa została założona z adresu, z którego piszemy przez poradnię?

**Comment by ad-m** [comment]
W przypadku spamu jest to możliwe, bo można podać dowolnego nadawcę w poczcie elektronicznej. Moglibyśmy od razu takie wiadomości filtrować...

Jeżeli dotyka to zwykłych ludzi to możemy mieć problem z identyfikowaniem nadawcy, a wówczas jest to usterka.

Z jaką sytuacją mamy doczynienia? Czy zagadnienie jest świeże, czy dotyczy danych archiwalnych?

**Comment by AgnieszkaZdanowicz** [comment]
Wszystkie te maile, o których piszę, wpłynęły 3.01, więc świeże

**Comment by ad-m** [comment]
Możliwe, że Zenbox od nowego roku coś zmienił u siebie. Muszę się temu przyjrzeć. Prawdopodobnie Fedrowanie jest także dotknięte problemem.

**Comment by ad-m** [comment]
Usunąłem wszystkich tych użytkowników. Nie mieli oni realnych spraw. Przyjmuje, że to spam, incydent i ewentualnie do uwzględnienia podczas #1015 .
