### ISSUE TITLE
Ostylowanie przycisku SingleButtonMixin

### ISSUE THREAD

**Issue by ad-m** [watchdogpolska/poradnia#98]
Przycisk z ````utitlities.forms.SingleButtonMixin``` powinien być wyśrodkowany.

**Comment by ad-m** [comment]
Dodatkowo fajnie, gdyby dla form-actions zmieniało się tło jak na getbootstrap.com:
![zaznaczenie_356](https://cloud.githubusercontent.com/assets/3618479/8774482/084ddca6-2edf-11e5-89f9-ab53f8f0ae3e.png)

**Comment by mik-laj** [comment]
https://github.com/watchdogpolska/poradnia/commit/9c064e67b68756f0b792cb311eee8771d48c790e
